@ GT Advance 3 - converted span
@ Region: file offset 0x021C94-0x022CB4 (VMA 0x08021C94-0x08022CB4).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080021C94, %function
sub_080021C94:
_080021C94:
	push	{r4, lr}
	adds	r4, r1, #0
	bl 0x08004B68
	movs	r1, #2
	ldrsh	r0, [r0, r1]
	cmp	r0, #15
	beq _080021CA8
	cmp	r0, #20
	bne _080021CB0
_080021CA8:
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #5
	b _080021CB6
_080021CB0:
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #6
_080021CB6:
	strh	r0, [r1, #0]
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080021CC0, %function
sub_080021CC0:
_080021CC0:
	bx	lr
	movs	r0, r0
	.type sub_080021CC4, %function
sub_080021CC4:
_080021CC4:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	sub	sp, #8
	adds	r7, r0, #0
	movs	r0, #51
	bl 0x0802B214
	ldr r5, _080021DAC
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r6, #1
	str	r6, [sp, #4]
	movs	r0, #0
	adds	r1, r5, #0
	movs	r2, #4
	movs	r3, #0
	bl 0x08007770
	movs	r0, #6
	str	r0, [r7, #80]
	str	r6, [r7, #92]
	str	r6, [r7, #104]
	movs	r0, #8
	adds	r0, r0, r7
	mov	r8, r0
	bl 0x0800DAB8
	ldr r4, _080021DB0
	adds	r0, r4, #0
	movs	r1, #1
	movs	r2, #0
	movs	r3, #3
	bl 0x08007614
	adds	r0, r4, #0
	movs	r1, #1
	movs	r2, #1
	movs	r3, #4
	bl 0x08007614
	adds	r0, r5, #0
	adds	r1, r7, #0
	bl 0x0800798C
	adds	r0, r7, #0
	bl 0x08007A58
	adds	r0, r5, #0
	movs	r1, #1
	movs	r2, #6
	bl 0x080075E8
	adds	r0, r5, #0
	movs	r1, #2
	movs	r2, #7
	bl 0x080075E8
	adds	r0, r5, #0
	movs	r1, #0
	movs	r2, #8
	bl 0x080075E8
	adds	r0, r5, #0
	movs	r1, #3
	movs	r2, #5
	bl 0x080075E8
	adds	r4, r7, #0
	adds	r4, #160
	str	r4, [r7, #120]
	mov	r2, r8
	str	r2, [r7, #124]
	movs	r0, #0
	str	r0, [r7, #8]
	strh	r6, [r7, #12]
	adds	r0, r7, #0
	adds	r0, #28
	movs	r2, #32
	negs	r2, r2
	movs	r1, #0
	bl 0x0800D77C
	adds	r0, r7, #0
	adds	r0, #20
	movs	r1, #0
	movs	r2, #160
	bl 0x0800D77C
	strh	r6, [r7, #16]
	movs	r0, #5
	strh	r0, [r7, #18]
	movs	r0, #2
	str	r0, [r4, #0]
	ldr r1, _080021DB4
	ldr r2, _080021DB8
	adds	r0, r1, r2
	ldrh	r2, [r0, #0]
	adds	r0, r7, #0
	adds	r0, #156
	strh	r2, [r0, #0]
	ldr r0, _080021DBC
	adds	r1, r1, r0
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	bl 0x08025D90
	adds	r1, r7, #0
	adds	r1, #158
	strh	r0, [r1, #0]
	add	sp, #8
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080021DAC: .4byte 0x08376500
_080021DB0: .4byte 0x082A798C
_080021DB4: .4byte 0x03001780
_080021DB8: .4byte 0x00000FF6
_080021DBC: .4byte 0x00000FF2
	.type sub_080021DC0, %function
sub_080021DC0:
_080021DC0:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	sub	sp, #4
	adds	r4, r0, #0
	lsls	r2, r2, #16
	lsrs	r5, r2, #16
	adds	r6, r4, #0
	adds	r6, #156
	ldrh	r0, [r6, #0]
	mov	r9, r0
	cmp	r5, #2
	bne _080021DEE
	movs	r0, #4
	bl 0x0802B368
	movs	r1, #10
	str	r1, [r4, #8]
	movs	r0, #0
	strh	r0, [r4, #12]
	str	r1, [r4, #40]
	str	r0, [r4, #36]
_080021DEE:
	cmp	r5, #1
	bne _080021E50
	movs	r0, #1
	bl 0x0802B368
	movs	r0, #0
	strh	r0, [r4, #12]
	adds	r0, r4, #0
	adds	r0, #116
	strh	r5, [r0, #0]
	ldr r2, _080021E3C
	ldr r1, _080021E40
	movs	r3, #0
	ldrsh	r0, [r6, r3]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldrh	r1, [r0, #0]
	ldr r3, _080021E44
	adds	r0, r2, r3
	strh	r1, [r0, #0]
	movs	r3, #0
	ldrsh	r1, [r0, r3]
	lsls	r1, r1, #1
	ldr r3, _080021E48
	adds	r0, r2, r3
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	lsls	r0, r0, #3
	adds	r1, r1, r0
	movs	r0, #253
	lsls	r0, r0, #4
	adds	r2, r2, r0
	adds	r1, r1, r2
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r0, #0
	bne _080021E4C
	strh	r5, [r4, #16]
	b _080021E50
_080021E3C: .4byte 0x03001780
_080021E40: .4byte 0x080CC120
_080021E44: .4byte 0x00000FF6
_080021E48: .4byte 0x00000FF2
_080021E4C:
	movs	r0, #6
	strh	r0, [r4, #16]
_080021E50:
	adds	r6, r4, #0
	adds	r6, #156
	cmp	r5, #64
	bne _080021E5E
	ldrh	r0, [r6, #0]
	subs	r0, #1
	strh	r0, [r6, #0]
_080021E5E:
	cmp	r5, #128
	bne _080021E68
	ldrh	r0, [r6, #0]
	adds	r0, #1
	strh	r0, [r6, #0]
_080021E68:
	ldr r2, _080021F0C
	movs	r3, #255
	lsls	r3, r3, #4
	adds	r0, r2, r3
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	adds	r4, #158
	cmp	r0, #0
	beq _080021EBE
	adds	r3, #2
	adds	r7, r2, r3
	ldrh	r0, [r7, #0]
	mov	r8, r0
	cmp	r5, #32
	bne _080021E9A
	movs	r0, #0
	strh	r0, [r7, #0]
	adds	r3, #4
	adds	r1, r2, r3
	strh	r0, [r1, #0]
	str	r2, [sp, #0]
	bl 0x08025D90
	strh	r0, [r4, #0]
	ldr	r2, [sp, #0]
_080021E9A:
	cmp	r5, #16
	bne _080021EB2
	movs	r1, #0
	movs	r0, #1
	strh	r0, [r7, #0]
	ldr r5, _080021F10
	adds	r0, r2, r5
	strh	r1, [r0, #0]
	movs	r0, #1
	bl 0x08025D90
	strh	r0, [r4, #0]
_080021EB2:
	ldrh	r7, [r7, #0]
	cmp	r8, r7
	beq _080021EBE
	movs	r0, #3
	bl 0x0802B368
_080021EBE:
	adds	r2, r6, #0
	movs	r1, #0
	ldrsh	r0, [r2, r1]
	cmp	r0, #0
	bge _080021ECC
	movs	r0, #0
	strh	r0, [r2, #0]
_080021ECC:
	movs	r3, #0
	ldrsh	r1, [r2, r3]
	ldrh	r3, [r4, #0]
	movs	r5, #0
	ldrsh	r0, [r4, r5]
	cmp	r1, r0
	ble _080021EDC
	strh	r3, [r2, #0]
_080021EDC:
	mov	r1, r9
	lsls	r0, r1, #16
	asrs	r4, r0, #16
	movs	r2, #0
	ldrsh	r0, [r6, r2]
	cmp	r4, r0
	beq _080021EFE
	movs	r0, #2
	bl 0x0802B368
	movs	r3, #0
	ldrsh	r0, [r6, r3]
	cmp	r4, r0
	beq _080021EFE
	movs	r0, #2
	bl 0x0802B368
_080021EFE:
	add	sp, #4
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080021F0C: .4byte 0x03001780
_080021F10: .4byte 0x00000FF6
	.type sub_080021F14, %function
sub_080021F14:
_080021F14:
	push	{r4, r5, lr}
	sub	sp, #16
	adds	r3, r0, #0
	adds	r4, r1, #0
	adds	r5, r2, #0
	ldr r1, _080021F40
	adds	r0, #156
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldrh	r1, [r0, #0]
	adds	r0, r3, #0
	adds	r0, #160
	ldr	r0, [r0, #0]
	cmp	r0, #1
	beq _080021F4C
	cmp	r0, #1
	bgt _080021F44
	cmp	r0, #0
	beq _080021F66
	b _080021F7E
_080021F40: .4byte 0x080CC098
_080021F44:
	cmp	r0, #2
	beq _080021F66
	cmp	r0, #3
	bne _080021F7E
_080021F4C:
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	str	r0, [sp, #8]
	str	r0, [sp, #12]
	adds	r0, r3, #0
	adds	r2, r4, #0
	adds	r3, r5, #0
	bl 0x08007B18
	b _080021F7E
_080021F66:
	movs	r0, #3
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	str	r0, [sp, #8]
	str	r0, [sp, #12]
	adds	r0, r3, #0
	adds	r2, r4, #0
	adds	r3, r5, #0
	bl 0x08007B18
_080021F7E:
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080021F88, %function
sub_080021F88:
_080021F88:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #16
	adds	r5, r0, #0
	movs	r7, #0
	movs	r6, #0
_080021F92:
	adds	r0, r5, #0
	adds	r0, #156
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	adds	r2, r0, #0
	cmp	r6, r1
	bne _080022018
	adds	r0, #4
	ldr	r0, [r0, #0]
	cmp	r0, #4
	bhi _080021FD6
	lsls	r0, r0, #2
	ldr r1, _080021FB4
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_080021FB4: .4byte 0x08021FB8
_080021FB8: .4byte 0x08021FD0
_080021FBC: .4byte 0x08021FD4
_080021FC0: .4byte 0x08021FD0
_080021FC4: .4byte 0x08021FD4
_080021FC8: .4byte 0x08021FCC
_080021FCC:
	movs	r7, #0
	b _080021FD6
_080021FD0:
	movs	r7, #1
	b _080021FD6
_080021FD4:
	movs	r7, #2
_080021FD6:
	ldr r1, _080022010
	movs	r3, #0
	ldrsh	r0, [r2, r3]
	lsls	r3, r0, #1
	adds	r3, r3, r0
	adds	r0, r3, r7
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldrh	r1, [r0, #0]
	ldr r4, _080022014
	adds	r3, r3, r7
	lsls	r3, r3, #3
	adds	r0, r3, r4
	ldr	r2, [r0, #0]
	adds	r4, #4
	adds	r3, r3, r4
	ldr	r3, [r3, #0]
	movs	r0, #6
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	str	r0, [sp, #8]
	str	r0, [sp, #12]
	adds	r0, r5, #0
	bl 0x08007B18
	b _080022046
	movs	r0, r0
_080022010: .4byte 0x080CC108
_080022014: .4byte 0x080CC0A8
_080022018:
	ldr r1, _080022054
	lsls	r3, r6, #1
	adds	r3, r3, r6
	lsls	r0, r3, #1
	adds	r0, r0, r1
	ldrh	r1, [r0, #0]
	ldr r4, _080022058
	lsls	r3, r3, #3
	adds	r0, r3, r4
	ldr	r2, [r0, #0]
	adds	r4, #4
	adds	r3, r3, r4
	ldr	r3, [r3, #0]
	movs	r0, #6
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	str	r0, [sp, #8]
	str	r0, [sp, #12]
	adds	r0, r5, #0
	bl 0x08007B18
_080022046:
	adds	r6, #1
	cmp	r6, #3
	ble _080021F92
	add	sp, #16
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080022054: .4byte 0x080CC108
_080022058: .4byte 0x080CC0A8
	.type sub_08002205C, %function
sub_08002205C:
_08002205C:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #16
	adds	r7, r0, #0
	adds	r0, #152
	movs	r1, #15
	bl 0x0800D97C
	ldr r1, _080022094
	movs	r2, #255
	lsls	r2, r2, #4
	adds	r0, r1, r2
	movs	r3, #0
	ldrsh	r5, [r0, r3]
	cmp	r5, #1
	bne _08002211C
	adds	r2, #2
	adds	r0, r1, r2
	movs	r3, #0
	ldrsh	r6, [r0, r3]
	cmp	r6, #0
	beq _080022098
	cmp	r6, #1
	beq _0800220DA
	b _08002211C
_080022094: .4byte 0x03001780
_080022098:
	movs	r4, #7
	str	r4, [sp, #0]
	str	r5, [sp, #4]
	str	r6, [sp, #8]
	str	r6, [sp, #12]
	adds	r0, r7, #0
	movs	r1, #14
	movs	r2, #8
	movs	r3, #32
	bl 0x08007B18
	movs	r0, #8
	str	r0, [sp, #0]
	str	r5, [sp, #4]
	str	r6, [sp, #8]
	str	r6, [sp, #12]
	adds	r0, r7, #0
	movs	r1, #6
	movs	r2, #64
	movs	r3, #34
	bl 0x08007B18
	str	r4, [sp, #0]
	str	r5, [sp, #4]
	str	r6, [sp, #8]
	str	r6, [sp, #12]
	adds	r0, r7, #0
	movs	r1, #11
	movs	r2, #72
	movs	r3, #32
	bl 0x08007B18
	b _08002211C
_0800220DA:
	movs	r5, #7
	str	r5, [sp, #0]
	str	r6, [sp, #4]
	movs	r4, #0
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	adds	r0, r7, #0
	movs	r1, #13
	movs	r2, #8
	movs	r3, #32
	bl 0x08007B18
	movs	r0, #8
	str	r0, [sp, #0]
	str	r6, [sp, #4]
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	adds	r0, r7, #0
	movs	r1, #12
	movs	r2, #64
	movs	r3, #34
	bl 0x08007B18
	str	r5, [sp, #0]
	str	r6, [sp, #4]
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	adds	r0, r7, #0
	movs	r1, #5
	movs	r2, #72
	movs	r3, #32
	bl 0x08007B18
_08002211C:
	movs	r5, #0
	movs	r0, #158
	adds	r0, r0, r7
	mov	r8, r0
	movs	r1, #156
	adds	r1, r1, r7
	mov	r9, r1
	movs	r2, #8
	adds	r2, r2, r7
	mov	sl, r2
	ldr r4, _08002219C
	ldr r6, _0800221A0
_080022134:
	ldr	r2, [r4, #0]
	ldr	r3, [r4, #4]
	mov	ip, r3
	mov	r1, r8
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r5, r0
	ble _08002215C
	ldrh	r1, [r6, #0]
	movs	r0, #5
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	str	r0, [sp, #8]
	str	r0, [sp, #12]
	adds	r0, r7, #0
	mov	r3, ip
	bl 0x08007B18
_08002215C:
	adds	r4, #8
	adds	r6, #2
	adds	r5, #1
	cmp	r5, #3
	ble _080022134
	ldr r2, _08002219C
	mov	r1, r9
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	lsls	r0, r0, #3
	adds	r1, r0, r2
	ldr	r1, [r1, #0]
	adds	r2, #4
	adds	r0, r0, r2
	ldr	r2, [r0, #0]
	adds	r0, r7, #0
	bl sub_080021F14
	adds	r0, r7, #0
	bl sub_080021F88
	mov	r0, sl
	bl 0x0800DBE8
	add	sp, #16
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08002219C: .4byte 0x080CC078
_0800221A0: .4byte 0x080CC0A0
	.type _0800221A4, %function
_0800221A4:
	push	{r4, r5, lr}
	adds	r5, r1, #0
	adds	r4, r3, #0
	subs	r0, #1
	cmp	r0, #11
	bhi _080022238
	lsls	r0, r0, #2
	ldr r1, _0800221BC
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_0800221BC: .4byte 0x080221C0
_0800221C0: .4byte 0x0802222A
_0800221C4: .4byte 0x080221F0
_0800221C8: .4byte 0x08022238
_0800221CC: .4byte 0x08022238
_0800221D0: .4byte 0x080221FA
_0800221D4: .4byte 0x08022214
_0800221D8: .4byte 0x0802220C
_0800221DC: .4byte 0x08022238
_0800221E0: .4byte 0x08022238
_0800221E4: .4byte 0x08022238
_0800221E8: .4byte 0x08022238
_0800221EC: .4byte 0x08022232
_0800221F0:
	adds	r0, r4, #0
	adds	r1, r5, #0
	bl sub_080021C94
	b _080022238
_0800221FA:
	adds	r0, r4, #0
	adds	r0, #8
	bl 0x0800D854
	adds	r0, r4, #0
	adds	r0, #112
	bl 0x0800D8E4
	b _080022238
_08002220C:
	adds	r0, r4, #0
	bl sub_08002205C
	b _080022238
_080022214:
	ldrh	r0, [r4, #12]
	cmp	r0, #0
	beq _080022238
	lsls	r1, r5, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r4, #0
	bl sub_080021DC0
	b _080022238
_08002222A:
	adds	r0, r4, #0
	bl sub_080021CC4
	b _080022238
_080022232:
	adds	r0, r4, #0
	bl sub_080021CC0
_080022238:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080022240:
	adds	r1, r0, #0
	ldrh	r0, [r1, #8]
	cmp	r0, #1
	beq _080022274
	cmp	r0, #1
	bgt _080022252
	cmp	r0, #0
	beq _08002225C
	b _08002227A
_080022252:
	cmp	r0, #2
	beq _08002227A
	cmp	r0, #3
	beq _080022264
	b _08002227A
_08002225C:
	movs	r0, #200
	strh	r0, [r1, #10]
	movs	r0, #3
	b _080022278
_080022264:
	ldrh	r0, [r1, #10]
	subs	r0, #1
	strh	r0, [r1, #10]
	lsls	r0, r0, #16
	cmp	r0, #0
	bgt _08002227A
	movs	r0, #1
	b _080022278
_080022274:
	strh	r0, [r1, #12]
	movs	r0, #2
_080022278:
	strh	r0, [r1, #8]
_08002227A:
	bx	lr
	.type sub_08002227C, %function
sub_08002227C:
_08002227C:
	bx	lr
	movs	r0, r0
	.type sub_080022280, %function
sub_080022280:
_080022280:
	push	{r4, r5, lr}
	adds	r4, r0, #0
	movs	r0, #67
	bl 0x0802B214
	ldr r5, _0800222CC
	adds	r0, r5, #0
	adds	r1, r4, #0
	bl 0x0800798C
	movs	r0, #19
	bl 0x0800572C
	str	r0, [r4, #20]
	movs	r0, #5
	str	r0, [r4, #24]
	adds	r0, r5, #0
	movs	r1, #0
	movs	r2, #3
	bl 0x080075E8
	ldr	r0, [r4, #4]
	ldr	r1, [r4, #24]
	ldr	r2, [r4, #20]
	bl 0x08007ABC
	ldr r0, _0800222D0
	ldr r1, _0800222D4
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #1
	beq _0800222EE
	cmp	r0, #1
	bgt _0800222D8
	cmp	r0, #0
	beq _0800222E2
	b _080022310
_0800222CC: .4byte 0x0837BBB0
_0800222D0: .4byte 0x03001780
_0800222D4: .4byte 0x00000FF6
_0800222D8:
	cmp	r0, #2
	beq _0800222FA
	cmp	r0, #3
	beq _080022306
	b _080022310
_0800222E2:
	movs	r0, #0
	adds	r1, r5, #0
	movs	r2, #2
	bl 0x08007664
	b _080022310
_0800222EE:
	movs	r0, #0
	adds	r1, r5, #0
	movs	r2, #3
	bl 0x08007664
	b _080022310
_0800222FA:
	movs	r0, #0
	adds	r1, r5, #0
	movs	r2, #1
	bl 0x08007664
	b _080022310
_080022306:
	movs	r0, #0
	adds	r1, r5, #0
	movs	r2, #4
	bl 0x08007664
_080022310:
	movs	r0, #0
	strh	r0, [r4, #8]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08002231C, %function
sub_08002231C:
_08002231C:
	bx	lr
	movs	r0, r0
	.type sub_080022320, %function
sub_080022320:
_080022320:
	push	{r4, lr}
	lsls	r4, r2, #16
	lsrs	r4, r4, #16
	bl 0x08004B68
	subs	r4, #1
	lsls	r4, r4, #16
	lsrs	r4, r4, #16
	cmp	r4, #1
	bhi _080022340
	movs	r0, #14
	bl 0x08004BFC
	movs	r0, #1
	bl 0x08004EC0
_080022340:
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080022348, %function
sub_080022348:
_080022348:
	bx	lr
	movs	r0, r0
	.type sub_08002234C, %function
sub_08002234C:
_08002234C:
	push	{r4, r5, lr}
	adds	r5, r1, #0
	adds	r4, r3, #0
	subs	r0, #1
	cmp	r0, #6
	bhi _0800223BA
	lsls	r0, r0, #2
	ldr r1, _080022364
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_080022364: .4byte 0x08022368
_080022368: .4byte 0x0802238E
_08002236C: .4byte 0x08022384
_080022370: .4byte 0x080223BA
_080022374: .4byte 0x080223BA
_080022378: .4byte 0x08022396
_08002237C: .4byte 0x080223AC
_080022380: .4byte 0x080223A4
_080022384:
	adds	r0, r4, #0
	adds	r1, r5, #0
	bl sub_08002227C
	b _0800223BA
_08002238E:
	adds	r0, r4, #0
	bl sub_080022280
	b _0800223BA
_080022396:
	adds	r0, r4, #0
	bl sub_08002231C
	adds	r0, r4, #0
	bl _080022240
	b _0800223BA
_0800223A4:
	adds	r0, r4, #0
	bl sub_080022348
	b _0800223BA
_0800223AC:
	lsls	r1, r5, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r4, #0
	bl sub_080022320
_0800223BA:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_0800223C0, %function
sub_0800223C0:
_0800223C0:
	push	{r4, lr}
	sub	sp, #8
	adds	r4, r0, #0
	ldr r1, _0800223EC
	mov	r0, sp
	movs	r2, #6
	bl 0x0802E0A4
	cmp	r4, #1
	ble _0800223D6
	movs	r4, #2
_0800223D6:
	cmp	r4, #0
	bgt _0800223DC
	movs	r4, #0
_0800223DC:
	lsls	r0, r4, #1
	add	r0, sp
	ldrh	r0, [r0, #0]
	add	sp, #8
	pop	{r4}
	pop	{r1}
	bx	r1
	movs	r0, r0
_0800223EC: .4byte 0x0805FC64
	.type sub_0800223F0, %function
sub_0800223F0:
_0800223F0:
	push	{r4, r5, r6, r7, lr}
	adds	r7, r0, #0
	movs	r6, #0
	movs	r4, #0
	adds	r5, r7, #0
	adds	r5, #186
_0800223FC:
	adds	r0, r4, #0
	bl 0x08026068
	cmp	r0, #1
	bne _08002240C
	strh	r4, [r5, #0]
	adds	r5, #2
	adds	r6, #1
_08002240C:
	adds	r4, #1
	cmp	r4, #2
	ble _0800223FC
	subs	r0, r6, #1
	adds	r1, r7, #0
	adds	r1, #184
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	cmp	r0, #0
	bgt _080022424
	movs	r0, #0
	strh	r0, [r1, #0]
_080022424:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08002242C, %function
sub_08002242C:
_08002242C:
	lsls	r1, r1, #1
	adds	r0, #186
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bx	lr
_080022438:
	movs	r1, #0
	cmp	r0, #95
	beq _080022448
	cmp	r0, #95
	ble _08002244E
	cmp	r0, #96
	beq _08002244C
	b _08002244E
_080022448:
	movs	r1, #1
	b _08002244E
_08002244C:
	movs	r1, #2
_08002244E:
	adds	r0, r1, #0
	bx	lr
	movs	r0, r0
	.type sub_080022454, %function
sub_080022454:
_080022454:
	push	{r4, lr}
	adds	r4, r1, #0
	bl 0x08004B68
	ldrh	r0, [r0, #2]
	cmp	r0, #44
	bne _08002246A
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #5
	b _080022470
_08002246A:
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #6
_080022470:
	strh	r0, [r1, #0]
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_080022478, %function
sub_080022478:
_080022478:
	bx	lr
	movs	r0, r0
	.type sub_08002247C, %function
sub_08002247C:
_08002247C:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #44
	adds	r7, r0, #0
	movs	r0, #51
	bl 0x0802B214
	ldr r0, _0800225B4
	mov	r8, r0
	ldr r0, _0800225B8
	add	r0, r8
	movs	r1, #0
	mov	r9, r1
	mov	r2, r9
	strh	r2, [r0, #0]
	ldr r5, _0800225BC
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r6, #1
	str	r6, [sp, #4]
	movs	r0, #0
	adds	r1, r5, #0
	movs	r2, #1
	movs	r3, #0
	bl 0x08007770
	movs	r3, #6
	str	r3, [r7, #80]
	movs	r0, #20
	str	r0, [r7, #92]
	str	r6, [r7, #104]
	movs	r4, #8
	adds	r4, r4, r7
	mov	sl, r4
	mov	r0, sl
	bl 0x0800DAB8
	ldr r4, _0800225C0
	adds	r0, r4, #0
	movs	r1, #1
	movs	r2, #0
	movs	r3, #4
	bl 0x08007614
	adds	r0, r4, #0
	movs	r1, #1
	movs	r2, #1
	movs	r3, #5
	bl 0x08007614
	adds	r0, r5, #0
	adds	r1, r7, #0
	bl 0x0800798C
	adds	r0, r7, #0
	bl 0x08007A58
	adds	r0, r5, #0
	movs	r1, #0
	movs	r2, #6
	bl 0x080075E8
	adds	r4, r7, #0
	adds	r4, #196
	str	r4, [r7, #120]
	mov	r5, sl
	str	r5, [r7, #124]
	mov	r0, r9
	str	r0, [r7, #8]
	strh	r6, [r7, #12]
	adds	r0, r7, #0
	adds	r0, #28
	movs	r2, #32
	negs	r2, r2
	movs	r1, #0
	bl 0x0800D77C
	adds	r0, r7, #0
	adds	r0, #20
	movs	r1, #0
	movs	r2, #160
	bl 0x0800D77C
	movs	r1, #6
	strh	r1, [r7, #16]
	movs	r0, #5
	strh	r0, [r7, #18]
	adds	r0, r7, #0
	bl sub_0800223F0
	movs	r0, #2
	str	r0, [r4, #0]
	ldr r0, _0800225C4
	add	r0, r8
	mov	r2, r9
	strh	r2, [r0, #0]
	ldr r3, _0800225C8
	add	r8, r3
	mov	r4, r8
	movs	r5, #0
	ldrsh	r0, [r4, r5]
	bl _080022438
	adds	r1, r7, #0
	adds	r1, #132
	strh	r0, [r1, #0]
	ldr r1, _0800225CC
	add	r0, sp, #8
	movs	r2, #6
	bl 0x0802E0A4
	add	r2, sp, #16
	adds	r1, r2, #0
	ldr r0, _0800225D0
	ldmia	r0!, {r3, r4, r5}
	stmia	r1!, {r3, r4, r5}
	ldmia	r0!, {r3, r4, r5}
	stmia	r1!, {r3, r4, r5}
	movs	r0, #0
	mov	r8, r0
	movs	r6, #0
	adds	r5, r7, #0
	adds	r5, #136
	movs	r3, #0
	mov	r9, r2
	adds	r4, r7, #0
	adds	r4, #144
_080022580:
	mov	r0, r8
	str	r3, [sp, #40]
	bl 0x08026068
	ldr	r3, [sp, #40]
	cmp	r0, #0
	beq _0800225DC
	ldr r0, _0800225D4
	adds	r0, r3, r0
	ldrh	r0, [r0, #0]
	strh	r0, [r5, #0]
	ldr r0, _0800225D8
	adds	r0, r3, r0
	ldrh	r0, [r0, #0]
	strh	r0, [r4, #0]
	adds	r2, r7, #0
	adds	r2, #152
	adds	r2, r2, r6
	mov	sl, r2
	mov	r2, r9
	ldr	r0, [r2, #0]
	ldr	r1, [r2, #4]
	mov	r2, sl
	str	r0, [r2, #0]
	str	r1, [r2, #4]
	b _0800225FC
_0800225B4: .4byte 0x03001780
_0800225B8: .4byte 0x00001078
_0800225BC: .4byte 0x0839CFE0
_0800225C0: .4byte 0x082A798C
_0800225C4: .4byte 0x00001076
_0800225C8: .4byte 0x00000FC2
_0800225CC: .4byte 0x0805FC64
_0800225D0: .4byte 0x0805FC6C
_0800225D4: .4byte 0x080CC140
_0800225D8: .4byte 0x080CC146
_0800225DC:
	movs	r0, #8
	strh	r0, [r5, #0]
	movs	r0, #9
	strh	r0, [r4, #0]
	adds	r0, r7, #0
	adds	r0, #152
	adds	r0, r0, r6
	movs	r1, #88
	str	r1, [r0, #0]
	adds	r1, r7, #0
	adds	r1, #156
	adds	r1, r1, r6
	add	r0, sp, #20
	adds	r0, r0, r6
	ldr	r0, [r0, #0]
	str	r0, [r1, #0]
_0800225FC:
	adds	r6, #8
	adds	r5, #2
	adds	r4, #2
	adds	r3, #2
	movs	r0, #8
	add	r9, r0
	movs	r1, #1
	add	r8, r1
	mov	r2, r8
	cmp	r2, #2
	ble _080022580
	add	sp, #44
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080022624, %function
sub_080022624:
_080022624:
	push	{r4, r5, r6, r7, lr}
	adds	r5, r0, #0
	lsls	r2, r2, #16
	lsrs	r6, r2, #16
	adds	r4, r5, #0
	adds	r4, #132
	ldrh	r7, [r4, #0]
	cmp	r6, #2
	bne _080022648
	movs	r0, #4
	bl 0x0802B368
	movs	r1, #10
	str	r1, [r5, #8]
	movs	r0, #0
	strh	r0, [r5, #12]
	str	r1, [r5, #40]
	str	r0, [r5, #36]
_080022648:
	cmp	r6, #1
	bne _08002268E
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	bl 0x08026068
	cmp	r0, #1
	bne _080022688
	movs	r2, #0
	ldrsh	r0, [r4, r2]
	bl sub_0800223C0
	ldr r1, _080022680
	ldr r3, _080022684
	adds	r1, r1, r3
	movs	r4, #0
	strh	r0, [r1, #0]
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r5, #0
	adds	r0, #196
	str	r6, [r0, #0]
	strh	r4, [r5, #12]
	subs	r0, #80
	strh	r6, [r0, #0]
	str	r6, [r5, #36]
	b _08002268E
_080022680: .4byte 0x03001780
_080022684: .4byte 0x00000FC2
_080022688:
	movs	r0, #10
	bl 0x0802B368
_08002268E:
	adds	r2, r5, #0
	adds	r2, #132
	cmp	r6, #64
	bne _08002269C
	ldrh	r0, [r2, #0]
	subs	r0, #1
	strh	r0, [r2, #0]
_08002269C:
	cmp	r6, #128
	bne _0800226A6
	ldrh	r0, [r2, #0]
	adds	r0, #1
	strh	r0, [r2, #0]
_0800226A6:
	adds	r1, r2, #0
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #0
	bge _0800226B4
	movs	r0, #0
	strh	r0, [r1, #0]
_0800226B4:
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #2
	ble _0800226C0
	movs	r0, #2
	strh	r0, [r1, #0]
_0800226C0:
	ldrh	r2, [r2, #0]
	cmp	r7, r2
	beq _0800226CC
	movs	r0, #2
	bl 0x0802B368
_0800226CC:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800226D4, %function
sub_0800226D4:
_0800226D4:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #16
	mov	r8, r0
	adds	r7, r1, #0
	adds	r6, r2, #0
	movs	r0, #1
	mov	sl, r0
	movs	r4, #0
	movs	r5, #0
	movs	r0, #29
	mov	r9, r0
_0800226F2:
	cmp	r6, #2
	beq _0800226FC
	cmp	r6, #3
	beq _080022718
	b _080022732
_0800226FC:
	movs	r0, #4
	str	r0, [sp, #0]
	mov	r0, sl
	str	r0, [sp, #4]
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	mov	r0, r8
	adds	r0, #44
	movs	r1, #7
	adds	r2, r5, #0
	adds	r3, r7, #0
	bl 0x08007B18
	b _080022732
_080022718:
	movs	r0, #5
	str	r0, [sp, #0]
	mov	r0, sl
	str	r0, [sp, #4]
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	mov	r0, r8
	adds	r0, #44
	movs	r1, #7
	adds	r2, r5, #0
	adds	r3, r7, #0
	bl 0x08007B18
_080022732:
	adds	r5, #8
	movs	r0, #1
	negs	r0, r0
	add	r9, r0
	mov	r0, r9
	cmp	r0, #0
	bge _0800226F2
	add	sp, #16
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.type sub_080022750, %function
sub_080022750:
_080022750:
	push	{r4, r5, lr}
	sub	sp, #16
	adds	r3, r0, #0
	adds	r4, r1, #0
	adds	r5, r2, #0
	adds	r0, #132
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	lsls	r1, r1, #1
	adds	r0, #4
	adds	r0, r0, r1
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	adds	r0, r3, #0
	adds	r0, #196
	ldr	r0, [r0, #0]
	cmp	r0, #1
	beq _080022786
	cmp	r0, #1
	bgt _08002277E
	cmp	r0, #0
	beq _0800227A0
	b _0800227B8
_08002277E:
	cmp	r0, #2
	beq _0800227A0
	cmp	r0, #3
	bne _0800227B8
_080022786:
	movs	r0, #5
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	str	r0, [sp, #8]
	str	r0, [sp, #12]
	adds	r0, r3, #0
	adds	r2, r4, #0
	adds	r3, r5, #0
	bl 0x08007B18
	b _0800227B8
_0800227A0:
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	str	r0, [sp, #8]
	str	r0, [sp, #12]
	adds	r0, r3, #0
	adds	r2, r4, #0
	adds	r3, r5, #0
	bl 0x08007B18
_0800227B8:
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_0800227C0, %function
sub_0800227C0:
_0800227C0:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	sub	sp, #24
	adds	r5, r0, #0
	adds	r0, #128
	movs	r1, #15
	bl 0x0800D97C
	movs	r4, #0
	movs	r0, #152
	adds	r0, r0, r5
	mov	r8, r0
	adds	r7, r5, #0
	adds	r7, #156
	movs	r6, #0
_0800227E0:
	lsls	r1, r4, #1
	adds	r0, r5, #0
	adds	r0, #144
	adds	r0, r0, r1
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	lsls	r3, r4, #3
	adds	r0, r5, #0
	adds	r0, #152
	adds	r0, r0, r3
	ldr	r2, [r0, #0]
	adds	r0, r5, #0
	adds	r0, #156
	adds	r0, r0, r3
	ldr	r3, [r0, #0]
	movs	r0, #6
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	str	r6, [sp, #8]
	str	r6, [sp, #12]
	adds	r0, r5, #0
	bl 0x08007B18
	adds	r4, #1
	cmp	r4, #3
	ble _0800227E0
	adds	r4, r5, #0
	adds	r4, #132
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	lsls	r0, r0, #3
	adds	r0, r7, r0
	ldr	r1, [r0, #0]
	adds	r0, r5, #0
	adds	r0, #196
	ldr	r2, [r0, #0]
	adds	r0, r5, #0
	bl sub_0800226D4
	movs	r2, #0
	ldrsh	r0, [r4, r2]
	lsls	r0, r0, #3
	mov	r2, r8
	adds	r1, r2, r0
	ldr	r1, [r1, #0]
	adds	r0, r7, r0
	ldr	r2, [r0, #0]
	adds	r0, r5, #0
	bl sub_080022750
	adds	r0, r5, #0
	adds	r0, #8
	bl 0x0800DBE8
	add	sp, #24
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08002285C, %function
sub_08002285C:
_08002285C:
	push	{r4, r5, lr}
	adds	r5, r1, #0
	adds	r4, r3, #0
	subs	r0, #1
	cmp	r0, #11
	bhi _0800228F0
	lsls	r0, r0, #2
	ldr r1, _080022874
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_080022874: .4byte 0x08022878
_080022878: .4byte 0x080228E2
_08002287C: .4byte 0x080228A8
_080022880: .4byte 0x080228F0
_080022884: .4byte 0x080228F0
_080022888: .4byte 0x080228B2
_08002288C: .4byte 0x080228CC
_080022890: .4byte 0x080228C4
_080022894: .4byte 0x080228F0
_080022898: .4byte 0x080228F0
_08002289C: .4byte 0x080228F0
_0800228A0: .4byte 0x080228F0
_0800228A4: .4byte 0x080228EA
_0800228A8:
	adds	r0, r4, #0
	adds	r1, r5, #0
	bl sub_080022454
	b _0800228F0
_0800228B2:
	adds	r0, r4, #0
	adds	r0, #8
	bl 0x0800D854
	adds	r0, r4, #0
	adds	r0, #112
	bl 0x0800D8E4
	b _0800228F0
_0800228C4:
	adds	r0, r4, #0
	bl sub_0800227C0
	b _0800228F0
_0800228CC:
	ldrh	r0, [r4, #12]
	cmp	r0, #0
	beq _0800228F0
	lsls	r1, r5, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r4, #0
	bl sub_080022624
	b _0800228F0
_0800228E2:
	adds	r0, r4, #0
	bl sub_08002247C
	b _0800228F0
_0800228EA:
	adds	r0, r4, #0
	bl sub_080022478
_0800228F0:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800228F8, %function
sub_0800228F8:
_0800228F8:
	push	{r4, lr}
	adds	r4, r1, #0
	bl 0x08004B68
	ldrh	r0, [r0, #2]
	cmp	r0, #15
	bne _08002290E
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #5
	b _080022914
_08002290E:
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #6
_080022914:
	strh	r0, [r1, #0]
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_08002291C, %function
sub_08002291C:
_08002291C:
	bx	lr
	movs	r0, r0
	.type sub_080022920, %function
sub_080022920:
_080022920:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #8
	adds	r7, r0, #0
	ldr r0, _0800229E8
	ldr r1, _0800229EC
	adds	r4, r0, r1
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	mov	r9, r0
	movs	r0, #51
	bl 0x0802B214
	movs	r5, #0
	strh	r5, [r4, #0]
	ldr r0, _0800229F0
	mov	r8, r0
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r1, #1
	mov	sl, r1
	str	r1, [sp, #4]
	movs	r0, #0
	mov	r1, r8
	movs	r2, #0
	movs	r3, #0
	bl 0x08007770
	movs	r0, #6
	str	r0, [r7, #80]
	movs	r0, #20
	str	r0, [r7, #92]
	mov	r1, sl
	str	r1, [r7, #104]
	adds	r6, r7, #0
	adds	r6, #8
	adds	r0, r6, #0
	bl 0x0800DAB8
	ldr r4, _0800229F4
	adds	r0, r4, #0
	movs	r1, #1
	movs	r2, #0
	movs	r3, #4
	bl 0x08007614
	adds	r0, r4, #0
	movs	r1, #1
	movs	r2, #1
	movs	r3, #5
	bl 0x08007614
	mov	r0, r8
	adds	r1, r7, #0
	bl 0x0800798C
	adds	r0, r7, #0
	bl 0x08007A58
	adds	r4, r7, #0
	adds	r4, #136
	str	r4, [r7, #120]
	str	r6, [r7, #124]
	str	r5, [r7, #8]
	mov	r0, sl
	strh	r0, [r7, #12]
	adds	r0, r7, #0
	adds	r0, #28
	movs	r2, #32
	negs	r2, r2
	movs	r1, #0
	bl 0x0800D77C
	adds	r0, r7, #0
	adds	r0, #20
	movs	r1, #0
	movs	r2, #160
	bl 0x0800D77C
	movs	r1, #6
	strh	r1, [r7, #16]
	movs	r0, #5
	strh	r0, [r7, #18]
	movs	r0, #2
	str	r0, [r4, #0]
	ldr r0, _0800229F8
	strh	r5, [r0, #0]
	mov	r1, r9
	cmp	r1, #1
	beq _0800229DE
	cmp	r1, #2
	beq _0800229FC
_0800229DE:
	adds	r0, r7, #0
	adds	r0, #132
	strh	r5, [r0, #0]
	b _080022A04
	movs	r0, r0
_0800229E8: .4byte 0x03001780
_0800229EC: .4byte 0x00001078
_0800229F0: .4byte 0x0839E9C0
_0800229F4: .4byte 0x082A798C
_0800229F8: .4byte 0x030027F6
_0800229FC:
	adds	r0, r7, #0
	adds	r0, #132
	mov	r1, sl
	strh	r1, [r0, #0]
_080022A04:
	add	sp, #8
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.type sub_080022A14, %function
sub_080022A14:
_080022A14:
	push	{r4, r5, r6, r7, lr}
	adds	r4, r0, #0
	lsls	r2, r2, #16
	lsrs	r5, r2, #16
	adds	r6, r4, #0
	adds	r6, #132
	ldrh	r7, [r6, #0]
	cmp	r5, #2
	bne _080022A38
	movs	r0, #4
	bl 0x0802B368
	movs	r1, #10
	str	r1, [r4, #8]
	movs	r0, #0
	strh	r0, [r4, #12]
	str	r1, [r4, #40]
	str	r0, [r4, #36]
_080022A38:
	cmp	r5, #1
	bne _080022A80
	movs	r1, #0
	ldrsh	r0, [r6, r1]
	cmp	r0, #0
	beq _080022A4A
	cmp	r0, #1
	beq _080022A5C
	b _080022A66
_080022A4A:
	ldr r0, _080022A54
	ldr r3, _080022A58
	adds	r0, r0, r3
	strh	r5, [r0, #0]
	b _080022A66
_080022A54: .4byte 0x03001780
_080022A58: .4byte 0x00001078
_080022A5C:
	ldr r0, _080022AC4
	ldr r1, _080022AC8
	adds	r0, r0, r1
	movs	r1, #2
	strh	r1, [r0, #0]
_080022A66:
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r4, #0
	adds	r0, #136
	movs	r1, #1
	str	r1, [r0, #0]
	movs	r0, #0
	strh	r0, [r4, #12]
	adds	r0, r4, #0
	adds	r0, #116
	strh	r1, [r0, #0]
	str	r1, [r4, #36]
_080022A80:
	adds	r2, r4, #0
	adds	r2, #132
	cmp	r5, #64
	bne _080022A8E
	ldrh	r0, [r2, #0]
	subs	r0, #1
	strh	r0, [r2, #0]
_080022A8E:
	cmp	r5, #128
	bne _080022A98
	ldrh	r0, [r2, #0]
	adds	r0, #1
	strh	r0, [r2, #0]
_080022A98:
	adds	r1, r2, #0
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #0
	bge _080022AA6
	movs	r0, #0
	strh	r0, [r1, #0]
_080022AA6:
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #1
	ble _080022AB2
	movs	r0, #1
	strh	r0, [r1, #0]
_080022AB2:
	ldrh	r2, [r2, #0]
	cmp	r7, r2
	beq _080022ABE
	movs	r0, #2
	bl 0x0802B368
_080022ABE:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080022AC4: .4byte 0x03001780
_080022AC8: .4byte 0x00001078
	.type sub_080022ACC, %function
sub_080022ACC:
_080022ACC:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #16
	mov	r8, r0
	adds	r7, r1, #0
	adds	r6, r2, #0
	movs	r0, #1
	mov	sl, r0
	movs	r4, #0
	movs	r5, #0
	movs	r0, #29
	mov	r9, r0
_080022AEA:
	cmp	r6, #2
	beq _080022AF4
	cmp	r6, #3
	beq _080022B10
	b _080022B2A
_080022AF4:
	movs	r0, #4
	str	r0, [sp, #0]
	mov	r0, sl
	str	r0, [sp, #4]
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	mov	r0, r8
	adds	r0, #44
	movs	r1, #7
	adds	r2, r5, #0
	adds	r3, r7, #0
	bl 0x08007B18
	b _080022B2A
_080022B10:
	movs	r0, #5
	str	r0, [sp, #0]
	mov	r0, sl
	str	r0, [sp, #4]
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	mov	r0, r8
	adds	r0, #44
	movs	r1, #7
	adds	r2, r5, #0
	adds	r3, r7, #0
	bl 0x08007B18
_080022B2A:
	adds	r5, #8
	movs	r0, #1
	negs	r0, r0
	add	r9, r0
	mov	r0, r9
	cmp	r0, #0
	bge _080022AEA
	add	sp, #16
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.type sub_080022B48, %function
sub_080022B48:
_080022B48:
	push	{r4, r5, lr}
	sub	sp, #16
	adds	r3, r0, #0
	adds	r4, r1, #0
	adds	r5, r2, #0
	ldr r1, _080022B74
	adds	r0, #132
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldrh	r1, [r0, #0]
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	cmp	r0, #1
	beq _080022B80
	cmp	r0, #1
	bgt _080022B78
	cmp	r0, #0
	beq _080022B9A
	b _080022BB2
_080022B74: .4byte 0x080CC168
_080022B78:
	cmp	r0, #2
	beq _080022B9A
	cmp	r0, #3
	bne _080022BB2
_080022B80:
	movs	r0, #5
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	str	r0, [sp, #8]
	str	r0, [sp, #12]
	adds	r0, r3, #0
	adds	r2, r4, #0
	adds	r3, r5, #0
	bl 0x08007B18
	b _080022BB2
_080022B9A:
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	str	r0, [sp, #8]
	str	r0, [sp, #12]
	adds	r0, r3, #0
	adds	r2, r4, #0
	adds	r3, r5, #0
	bl 0x08007B18
_080022BB2:
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080022BBC, %function
sub_080022BBC:
_080022BBC:
	push	{r4, r5, r6, lr}
	mov	r6, r8
	push	{r6}
	adds	r4, r0, #0
	adds	r0, #128
	movs	r1, #15
	bl 0x0800D97C
	ldr r5, _080022C14
	adds	r6, r4, #0
	adds	r6, #132
	movs	r1, #0
	ldrsh	r0, [r6, r1]
	lsls	r0, r0, #3
	adds	r1, r5, #4
	mov	r8, r1
	add	r0, r8
	ldr	r1, [r0, #0]
	adds	r0, r4, #0
	adds	r0, #136
	ldr	r2, [r0, #0]
	adds	r0, r4, #0
	bl sub_080022ACC
	movs	r1, #0
	ldrsh	r0, [r6, r1]
	lsls	r0, r0, #3
	adds	r5, r0, r5
	ldr	r1, [r5, #0]
	add	r0, r8
	ldr	r2, [r0, #0]
	adds	r0, r4, #0
	bl sub_080022B48
	adds	r4, #8
	adds	r0, r4, #0
	bl 0x0800DBE8
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080022C14: .4byte 0x080CC158
	.type _080022C18, %function
_080022C18:
	push	{r4, r5, lr}
	adds	r5, r1, #0
	adds	r4, r3, #0
	subs	r0, #1
	cmp	r0, #11
	bhi _080022CAC
	lsls	r0, r0, #2
	ldr r1, _080022C30
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_080022C30: .4byte 0x08022C34
_080022C34: .4byte 0x08022C9E
_080022C38: .4byte 0x08022C64
_080022C3C: .4byte 0x08022CAC
_080022C40: .4byte 0x08022CAC
_080022C44: .4byte 0x08022C6E
_080022C48: .4byte 0x08022C88
_080022C4C: .4byte 0x08022C80
_080022C50: .4byte 0x08022CAC
_080022C54: .4byte 0x08022CAC
_080022C58: .4byte 0x08022CAC
_080022C5C: .4byte 0x08022CAC
_080022C60: .4byte 0x08022CA6
_080022C64:
	adds	r0, r4, #0
	adds	r1, r5, #0
	bl sub_0800228F8
	b _080022CAC
_080022C6E:
	adds	r0, r4, #0
	adds	r0, #8
	bl 0x0800D854
	adds	r0, r4, #0
	adds	r0, #112
	bl 0x0800D8E4
	b _080022CAC
_080022C80:
	adds	r0, r4, #0
	bl sub_080022BBC
	b _080022CAC
_080022C88:
	ldrh	r0, [r4, #12]
	cmp	r0, #0
	beq _080022CAC
	lsls	r1, r5, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r4, #0
	bl sub_080022A14
	b _080022CAC
_080022C9E:
	adds	r0, r4, #0
	bl sub_080022920
	b _080022CAC
_080022CA6:
	adds	r0, r4, #0
	bl sub_08002291C
_080022CAC:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.hword 0x0000
