@ GT Advance 3 - converted span
@ Region: file offset 0x004B68-0x004B74 (VMA 0x08004B68-0x08004B74).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	ldr r0, _08004B70
	ldr	r0, [r0, #8]
	bx	lr
	movs	r0, r0
_08004B70: .4byte 0x03000198
