@ GT Advance 3 - converted span
@ Region: file offset 0x02DE96-0x02DE9C (VMA 0x0802DE96-0x0802DE9C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	movs	r0, r0
	.type sub_0802DE98, %function
sub_0802DE98:
_0802DE98:
	mov	pc, lr
	.hword 0x0000
code_2de96_end:
