@ GT Advance 3 - converted span
@ Region: file offset 0x004E6C-0x00572C (VMA 0x08004E6C-0x0800572C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08004E6C, %function
sub_08004E6C:
_08004E6C:
	push	{lr}
	bl 0x08004B68
	ldrh	r0, [r0, #8]
	pop	{r1}
	bx	r1
	.type sub_08004E78, %function
sub_08004E78:
_08004E78:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	ldr r0, _08004EA4
	ldr	r0, [r0, #8]
	ldrh	r4, [r0, #8]
	bl 0x08004B68
	strh	r5, [r0, #8]
	cmp	r4, #1
	bne _08004E9E
	cmp	r5, #0
	beq _08004E94
	cmp	r5, #2
	bne _08004E9E
_08004E94:
	movs	r0, #19
	movs	r1, #0
	movs	r2, #0
	bl 0x08004D4C
_08004E9E:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_08004EA4: .4byte 0x03000198
_08004EA8:
sub_08004EA8:
	push	{lr}
	ldr r1, _08004EBC
	ldr	r2, [r1, #8]
	movs	r1, #1
	strh	r1, [r2, #6]
	bl 0x08004E40
	pop	{r0}
	bx	r0
	movs	r0, r0
_08004EBC: .4byte 0x03000198
_08004EC0:
sub_08004EC0:
	push	{lr}
	ldr r1, _08004ED4
	ldr	r2, [r1, #8]
	movs	r1, #0
	strh	r1, [r2, #6]
	bl 0x08004E40
	pop	{r0}
	bx	r0
	movs	r0, r0
_08004ED4: .4byte 0x03000198
_08004ED8:
sub_08004ED8:
	push	{lr}
	ldr r1, _08004EEC
	ldr	r2, [r1, #8]
	movs	r1, #2
	strh	r1, [r2, #6]
	bl 0x08004E40
	pop	{r0}
	bx	r0
	movs	r0, r0
_08004EEC: .4byte 0x03000198
_08004EF0:
sub_08004EF0:
	ldr r1, _08004EF8
	ldr	r1, [r1, #8]
	str	r0, [r1, #92]
	bx	lr
_08004EF8: .4byte 0x03000198
	.type _08004EFC, %function
_08004EFC:
	push	{r4, lr}
	ldr r4, _08004F1C
	adds	r1, r4, #0
	adds	r1, #144
	ldr	r1, [r1, #0]
	cmp	r1, r0
	bcs _08004F10
	ldr r0, _08004F20
	bl 0x0800295C
_08004F10:
	adds	r0, r4, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	pop	{r4}
	pop	{r1}
	bx	r1
_08004F1C: .4byte 0x03000198
_08004F20: .4byte 0x0805BA70
_08004F24:
	ldr r1, _08004F30
	movs	r0, #1
	ldrh	r1, [r1, #8]
	ands	r0, r1
	bx	lr
	movs	r0, r0
_08004F30: .4byte 0x03000250
	.type _08004F34, %function
_08004F34:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	ldr r0, _08004F64
	ldr	r4, [r0, #0]
	bl _08004F24
	cmp	r0, #0
	bne _08004F5E
	cmp	r4, #0
	beq _08004F5E
_08004F48:
	ldr	r0, [r4, #0]
	ldr	r2, [r0, #0]
	cmp	r2, #0
	beq _08004F58
	adds	r0, r5, #0
	adds	r1, r4, #0
	bl 0x0802DDD0
_08004F58:
	ldr	r4, [r4, #4]
	cmp	r4, #0
	bne _08004F48
_08004F5E:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_08004F64: .4byte 0x03000250
	.type _08004F68, %function
_08004F68:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r8, r0
	lsls	r1, r1, #16
	lsrs	r7, r1, #16
	lsls	r2, r2, #16
	lsrs	r6, r2, #16
	ldr r0, _08004FAC
	ldr	r4, [r0, #0]
	bl _08004F24
	cmp	r0, #0
	bne _08004FA2
	cmp	r4, #0
	beq _08004FA2
_08004F88:
	ldr	r0, [r4, #0]
	ldr	r5, [r0, #4]
	cmp	r5, #0
	beq _08004F9C
	mov	r0, r8
	adds	r1, r4, #0
	adds	r2, r7, #0
	adds	r3, r6, #0
	bl 0x0802DDDC
_08004F9C:
	ldr	r4, [r4, #4]
	cmp	r4, #0
	bne _08004F88
_08004FA2:
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08004FAC: .4byte 0x03000250
	.type _08004FB0, %function
_08004FB0:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	ldr r0, _08004FE0
	ldr	r4, [r0, #0]
	bl _08004F24
	cmp	r0, #0
	bne _08004FDA
	cmp	r4, #0
	beq _08004FDA
_08004FC4:
	ldr	r0, [r4, #0]
	ldr	r2, [r0, #8]
	cmp	r2, #0
	beq _08004FD4
	adds	r0, r5, #0
	adds	r1, r4, #0
	bl 0x0802DDD0
_08004FD4:
	ldr	r4, [r4, #4]
	cmp	r4, #0
	bne _08004FC4
_08004FDA:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_08004FE0: .4byte 0x03000250
	.type _08004FE4, %function
_08004FE4:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	ldr r0, _08005014
	ldr	r4, [r0, #0]
	bl _08004F24
	cmp	r0, #0
	bne _0800500E
	cmp	r4, #0
	beq _0800500E
_08004FF8:
	ldr	r0, [r4, #0]
	ldr	r2, [r0, #12]
	cmp	r2, #0
	beq _08005008
	adds	r0, r5, #0
	adds	r1, r4, #0
	bl 0x0802DDD0
_08005008:
	ldr	r4, [r4, #4]
	cmp	r4, #0
	bne _08004FF8
_0800500E:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_08005014: .4byte 0x03000250
	.type _08005018, %function
_08005018:
	bx	lr
	movs	r0, r0
	.type sub_0800501C, %function
sub_0800501C:
_0800501C:
	push	{lr}
	sub	sp, #4
	movs	r0, #0
	str	r0, [sp, #0]
	ldr r1, _08005034
	ldr r2, _08005038
	mov	r0, sp
	bl 0x0802D974
	add	sp, #4
	pop	{r0}
	bx	r0
_08005034: .4byte 0x03000250
_08005038: .4byte 0x05000003
@ Entry label for the anonymous list-insert leaf at 0x0800503C. Same reason as
@ `_08004DEC` in code_4d4c.s: `_0800501C`'s 32-byte span ran through it. Zero
@ bytes emitted.
	.type _0800503C, %function
_0800503C:
	adds	r2, r0, #0
	movs	r0, #0
	str	r0, [r2, #4]
	str	r1, [r2, #0]
	ldr r1, _08005050
	ldr	r0, [r1, #0]
	cmp	r0, #0
	bne _08005054
	str	r2, [r1, #0]
	b _08005058
_08005050: .4byte 0x03000250
_08005054:
	ldr	r0, [r1, #4]
	str	r2, [r0, #4]
_08005058:
	str	r2, [r1, #4]
	bx	lr
	.type _0800505C, %function
_0800505C:
	ldr r0, _08005068
	movs	r1, #1
	ldrh	r2, [r0, #8]
	orrs	r1, r2
	strh	r1, [r0, #8]
	bx	lr
_08005068: .4byte 0x03000250
	.type _0800506C, %function
_0800506C:
	ldr r1, _08005078
	ldr r0, _0800507C
	ldrh	r2, [r1, #8]
	ands	r0, r2
	strh	r0, [r1, #8]
	bx	lr
_08005078: .4byte 0x03000250
_0800507C: .4byte 0x0000FFFE
	.type _08005080, %function
_08005080:
	push	{r4, r5, r6, lr}
	adds	r6, r0, #0
	adds	r5, r1, #0
	movs	r1, #12
	bl 0x080020B0
	adds	r4, r0, #0
	str	r5, [r4, #4]
	ldr	r1, [r5, #4]
	adds	r0, r6, #0
	bl 0x080020B0
	str	r0, [r4, #8]
	adds	r0, r4, #0
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
_080050A4:
	ldr r2, _080050B0
	lsls	r0, r0, #1
	adds	r2, #84
	adds	r0, r0, r2
	strh	r1, [r0, #0]
	bx	lr
_080050B0: .4byte 0x03000260
	.type _080050B4, %function
_080050B4:
	push	{lr}
	bl _080050A4
	pop	{r0}
	bx	r0
	movs	r0, r0
_080050C0:
	ldr r2, _080050CC
	lsls	r0, r0, #2
	adds	r2, #68
	adds	r0, r0, r2
	str	r1, [r0, #0]
	bx	lr
_080050CC: .4byte 0x03000260
	.type _080050D0, %function
_080050D0:
	ldr r2, _080050E4
	lsls	r0, r0, #1
	adds	r2, #84
	adds	r0, r0, r2
	ldrh	r2, [r0, #0]
	adds	r1, r2, r1
	strh	r1, [r0, #0]
	adds	r0, r2, #0
	bx	lr
	movs	r0, r0
_080050E4: .4byte 0x03000260
_080050E8:
	.type _080050E8, %function
sub_080050E8:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #48
	adds	r7, r0, #0
	mov	sl, r1
	add	r4, sp, #8
	ldr r1, _08005248
	adds	r0, r4, #0
	movs	r2, #12
	bl 0x0802E0A4
	add	r0, sp, #20
	mov	r8, r0
	ldr r1, _0800524C
	movs	r2, #8
	bl 0x0802E0A4
	add	r6, sp, #28
	ldr r1, _08005250
	adds	r0, r6, #0
	movs	r2, #8
	bl 0x0802E0A4
	add	r5, sp, #36
	ldr r1, _08005254
	adds	r0, r5, #0
	movs	r2, #8
	bl 0x0802E0A4
	movs	r0, #128
	lsls	r0, r0, #19
	ldrh	r0, [r0, #0]
	movs	r1, #64
	mov	r9, r1
	ldrh	r1, [r7, #0]
	lsls	r0, r1, #1
	adds	r4, r4, r0
	ldrh	r4, [r4, #0]
	mov	r0, r9
	orrs	r4, r0
	mov	r9, r4
	mov	r3, r8
	adds	r2, r7, #0
	movs	r4, #3
_08005146:
	ldrb	r0, [r2, #4]
	cmp	r0, #0
	beq _08005154
	ldrh	r1, [r3, #0]
	mov	r0, r9
	orrs	r1, r0
	mov	r9, r1
_08005154:
	adds	r3, #2
	adds	r2, #16
	subs	r4, #1
	cmp	r4, #0
	bge _08005146
	ldrh	r1, [r7, #2]
	mov	r8, r1
	ldrh	r0, [r7, #12]
	mov	ip, r0
	str	r6, [sp, #44]
	mov	r3, sp
	adds	r2, r7, #0
	movs	r4, #3
_0800516E:
	ldrb	r6, [r2, #9]
	lsls	r1, r6, #1
	adds	r1, r5, r1
	ldrb	r6, [r2, #8]
	lsls	r0, r6, #1
	ldr	r6, [sp, #44]
	adds	r0, r6, r0
	ldrh	r1, [r1, #0]
	ldrh	r0, [r0, #0]
	orrs	r1, r0
	movs	r0, #64
	orrs	r1, r0
	ldrb	r0, [r2, #7]
	cmp	r0, #0
	beq _08005190
	movs	r0, #128
	orrs	r1, r0
_08005190:
	ldrb	r6, [r2, #5]
	lsls	r0, r6, #2
	orrs	r1, r0
	ldrb	r6, [r2, #6]
	lsls	r0, r6, #8
	orrs	r1, r0
	strh	r1, [r3, #0]
	adds	r3, #2
	adds	r2, #16
	subs	r4, #1
	cmp	r4, #0
	bge _0800516E
	mov	r1, r8
	lsls	r0, r1, #16
	cmp	r0, #0
	beq _080051C0
	movs	r6, #128
	lsls	r6, r6, #5
	adds	r0, r6, #0
	mov	r1, r9
	orrs	r1, r0
	lsls	r0, r1, #16
	lsrs	r0, r0, #16
	mov	r9, r0
_080051C0:
	movs	r0, #0
	mov	r1, ip
	bl _080050A4
	ldrh	r1, [r7, #28]
	movs	r0, #1
	bl _080050A4
	ldrh	r1, [r7, #44]
	movs	r0, #2
	bl _080050A4
	ldrh	r1, [r7, #60]
	movs	r0, #3
	bl _080050A4
	ldr	r1, [r7, #16]
	movs	r0, #0
	bl _080050C0
	ldr	r1, [r7, #32]
	movs	r0, #1
	bl _080050C0
	ldr	r1, [r7, #48]
	movs	r0, #2
	bl _080050C0
	ldr	r1, [r7, #64]
	movs	r0, #3
	bl _080050C0
	mov	r6, sl
	cmp	r6, #0
	beq _0800522E
	ldr r1, _08005258
	mov	r0, sp
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #0]
	adds	r1, #2
	mov	r0, sp
	ldrh	r0, [r0, #2]
	strh	r0, [r1, #0]
	adds	r1, #2
	mov	r0, sp
	ldrh	r0, [r0, #4]
	strh	r0, [r1, #0]
	adds	r1, #2
	mov	r0, sp
	ldrh	r0, [r0, #6]
	strh	r0, [r1, #0]
	movs	r0, #128
	lsls	r0, r0, #19
	mov	r1, r9
	strh	r1, [r0, #0]
_0800522E:
	ldr r0, _0800525C
	adds	r1, r7, #0
	movs	r2, #68
	bl 0x0802E0A4
	add	sp, #48
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08005248: .4byte 0x0805BA80
_0800524C: .4byte 0x0805BA8C
_08005250: .4byte 0x0805BA94
_08005254: .4byte 0x0805BA9C
_08005258: .4byte 0x04000008
_0800525C: .4byte 0x03000260
	.type _08005260, %function
_08005260:
	push	{r4, lr}
	ldr r4, _08005294
	str	r1, [r4, #0]
	ldr r1, _08005298
	lsls	r0, r0, #4
	adds	r0, r0, r1
	ldrb	r0, [r0, #5]
	lsls	r0, r0, #14
	lsls	r2, r2, #5
	movs	r1, #192
	lsls	r1, r1, #19
	adds	r2, r2, r1
	adds	r0, r0, r2
	str	r0, [r4, #4]
	cmp	r3, #0
	bge _08005282
	adds	r3, #3
_08005282:
	asrs	r0, r3, #2
	movs	r1, #132
	lsls	r1, r1, #24
	orrs	r0, r1
	str	r0, [r4, #8]
	ldr	r0, [r4, #8]
	pop	{r4}
	pop	{r0}
	bx	r0
_08005294: .4byte 0x040000D4
_08005298: .4byte 0x03000260
	.type _0800529C, %function
_0800529C:
	push	{r4, r5, r6, r7, lr}
	adds	r4, r1, #0
	ldr	r6, [sp, #20]
	ldr	r7, [sp, #24]
	ldr r1, _080052E8
	lsls	r0, r0, #4
	adds	r0, r0, r1
	ldrb	r0, [r0, #6]
	lsls	r1, r0, #11
	adds	r0, r3, #0
	muls	r0, r6
	lsls	r0, r0, #1
	movs	r3, #192
	lsls	r3, r3, #19
	adds	r0, r0, r3
	adds	r1, r1, r0
	lsls	r2, r2, #1
	adds	r1, r1, r2
	cmp	r7, #0
	ble _080052E2
	ldr r3, _080052EC
	movs	r5, #128
	lsls	r5, r5, #24
	orrs	r5, r6
	lsls	r6, r6, #1
	adds	r2, r7, #0
_080052D0:
	str	r4, [r3, #0]
	str	r1, [r3, #4]
	str	r5, [r3, #8]
	ldr	r0, [r3, #8]
	adds	r4, r4, r6
	adds	r1, #64
	subs	r2, #1
	cmp	r2, #0
	bne _080052D0
_080052E2:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080052E8: .4byte 0x03000260
_080052EC: .4byte 0x040000D4
	.type _080052F0, %function
_080052F0:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #12
	mov	sl, r1
	ldr r4, _080053CC
	ldr r1, _080053D0
	lsls	r0, r0, #4
	adds	r0, r0, r1
	ldrb	r0, [r0, #6]
	lsls	r1, r0, #11
	ldr	r5, [sp, #44]
	adds	r0, r3, #0
	muls	r0, r5
	lsls	r0, r0, #1
	movs	r3, #192
	lsls	r3, r3, #19
	adds	r0, r0, r3
	adds	r1, r1, r0
	lsls	r2, r2, #1
	adds	r1, r1, r2
	mov	r8, r1
	str	r4, [sp, #0]
	movs	r2, #0
	ldr	r5, [sp, #48]
	cmp	r2, r5
	bge _0800538E
	ldr r6, _080053D4
	movs	r0, #128
	lsls	r0, r0, #24
	ldr	r1, [sp, #44]
	orrs	r1, r0
	str	r1, [sp, #4]
	ldr	r3, [sp, #44]
	lsls	r3, r3, #1
	str	r3, [sp, #8]
_0800533C:
	mov	r5, sl
	str	r5, [r6, #0]
	str	r4, [r6, #4]
	ldr	r0, [sp, #4]
	str	r0, [r6, #8]
	ldr	r0, [r6, #8]
	adds	r3, r4, #0
	adds	r7, r3, #0
	adds	r7, #64
	adds	r2, #1
	mov	ip, r2
	ldr	r1, [sp, #44]
	cmp	r1, #0
	ble _08005380
	movs	r2, #192
	lsls	r2, r2, #4
	mov	r9, r2
	adds	r4, r1, #0
	ldr	r0, [sp, #56]
	lsls	r5, r0, #12
_08005364:
	ldrh	r2, [r3, #0]
	ldr r1, _080053D8
	ands	r1, r2
	mov	r0, r9
	ands	r0, r2
	ldr	r2, [sp, #52]
	adds	r1, r1, r2
	orrs	r0, r5
	orrs	r0, r1
	strh	r0, [r3, #0]
	subs	r4, #1
	adds	r3, #2
	cmp	r4, #0
	bne _08005364
_08005380:
	ldr	r3, [sp, #8]
	add	sl, r3
	adds	r4, r7, #0
	mov	r2, ip
	ldr	r5, [sp, #48]
	cmp	r2, r5
	blt _0800533C
_0800538E:
	ldr	r0, [sp, #48]
	cmp	r0, #0
	ble _080053BA
	ldr r1, _080053D4
	movs	r3, #128
	lsls	r3, r3, #24
	ldr	r2, [sp, #44]
	orrs	r3, r2
	adds	r2, r0, #0
_080053A0:
	ldr	r5, [sp, #0]
	str	r5, [r1, #0]
	mov	r0, r8
	str	r0, [r1, #4]
	str	r3, [r1, #8]
	ldr	r0, [r1, #8]
	adds	r5, #64
	str	r5, [sp, #0]
	movs	r5, #64
	add	r8, r5
	subs	r2, #1
	cmp	r2, #0
	bne _080053A0
_080053BA:
	add	sp, #12
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080053CC: .4byte 0x02002000
_080053D0: .4byte 0x03000260
_080053D4: .4byte 0x040000D4
_080053D8: .4byte 0x000003FF
	.type sub_080053DC, %function
sub_080053DC:
_080053DC:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #24
	str	r0, [sp, #0]
	mov	sl, r1
	str	r2, [sp, #4]
	str	r3, [sp, #8]
	movs	r0, #0
	ldr	r1, [sp, #60]
	cmp	r0, r1
	bge _0800548E
	ldr	r7, [sp, #56]
	lsls	r7, r7, #1
	str	r7, [sp, #16]
_080053FE:
	mov	ip, sl
	movs	r1, #0
	mov	r8, r1
	adds	r7, r0, #1
	str	r7, [sp, #12]
	ldr	r1, [sp, #56]
	cmp	r8, r1
	bge _08005482
	ldr	r7, [sp, #8]
	adds	r0, r7, r0
	str	r0, [sp, #20]
	ldr	r1, [sp, #0]
	lsls	r0, r1, #2
	ldr r7, _08005440
	adds	r6, r0, r7
	ldr	r0, [sp, #20]
	lsls	r5, r0, #6
	ldr	r1, [sp, #4]
	lsls	r4, r1, #1
	movs	r7, #248
	lsls	r7, r7, #3
	adds	r3, r4, r7
_0800542A:
	ldr	r0, [sp, #4]
	add	r0, r8
	cmp	r0, #31
	bgt _08005444
	ldr	r0, [sp, #20]
	cmp	r0, #31
	bgt _0800544A
	ldr	r0, [r6, #0]
	adds	r0, r0, r4
	b _0800544E
	movs	r0, r0
_08005440: .4byte 0x030002A4
_08005444:
	ldr	r1, [sp, #20]
	cmp	r1, #31
	bgt _08005452
_0800544A:
	ldr	r0, [r6, #0]
	adds	r0, r0, r3
_0800544E:
	adds	r0, r0, r5
	mov	r9, r0
_08005452:
	mov	r7, ip
	ldrh	r1, [r7, #0]
	movs	r0, #2
	add	ip, r0
	ldr r2, _080054A0
	ands	r2, r1
	movs	r0, #192
	lsls	r0, r0, #4
	ands	r0, r1
	ldr	r1, [sp, #64]
	adds	r2, r2, r1
	ldr	r7, [sp, #68]
	lsls	r1, r7, #12
	orrs	r0, r1
	orrs	r0, r2
	mov	r1, r9
	strh	r0, [r1, #0]
	adds	r3, #2
	adds	r4, #2
	movs	r7, #1
	add	r8, r7
	ldr	r0, [sp, #56]
	cmp	r8, r0
	blt _0800542A
_08005482:
	ldr	r1, [sp, #16]
	add	sl, r1
	ldr	r0, [sp, #12]
	ldr	r7, [sp, #60]
	cmp	r0, r7
	blt _080053FE
_0800548E:
	add	sp, #24
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080054A0: .4byte 0x000003FF
	.type sub_080054A4, %function
sub_080054A4:
_080054A4:
	push	{r4, r5, r6, r7, lr}
	adds	r6, r1, #0
	adds	r5, r3, #0
	ldr	r7, [sp, #20]
	ldr r3, _080054F8
	lsls	r1, r0, #4
	adds	r1, r1, r3
	ldrb	r1, [r1, #6]
	lsls	r4, r1, #11
	movs	r1, #192
	lsls	r1, r1, #19
	adds	r4, r4, r1
	lsls	r0, r0, #2
	adds	r3, #68
	adds	r0, r0, r3
	ldr	r1, [r0, #0]
	lsls	r2, r2, #6
	adds	r4, r4, r2
	adds	r1, r1, r2
	cmp	r7, #0
	ble _080054F2
	ldr r3, _080054FC
	lsrs	r0, r5, #31
	adds	r0, r5, r0
	asrs	r5, r0, #1
	movs	r0, #132
	lsls	r0, r0, #24
	orrs	r5, r0
	adds	r2, r7, #0
_080054DE:
	str	r1, [r3, #0]
	adds	r0, r4, r6
	str	r0, [r3, #4]
	str	r5, [r3, #8]
	ldr	r0, [r3, #8]
	adds	r4, #64
	adds	r1, #64
	subs	r2, #1
	cmp	r2, #0
	bne _080054DE
_080054F2:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080054F8: .4byte 0x03000260
_080054FC: .4byte 0x040000D4
	.type sub_08005500, %function
sub_08005500:
_08005500:
	push	{r4, r5, r6, lr}
	sub	sp, #4
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r6, r2, #0
	movs	r0, #0
	str	r0, [sp, #0]
	ldr r2, _08005528
	mov	r0, sp
	adds	r1, r4, #0
	bl 0x0802D974
	str	r5, [r4, #8]
	strh	r6, [r4, #0]
	str	r5, [r4, #12]
	add	sp, #4
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08005528: .4byte 0x05000004
	.type sub_0800552C, %function
sub_0800552C:
_0800552C:
	push	{r4, r5, r6, lr}
	adds	r4, r0, #0
	adds	r5, r1, #0
	movs	r0, #2
	ldrsh	r1, [r4, r0]
	movs	r6, #0
	ldrsh	r0, [r4, r6]
	cmp	r1, r0
	bge _08005556
	ldr	r1, [r4, #12]
	movs	r0, #0
	strh	r0, [r1, #0]
	ldr	r0, [r4, #12]
	str	r5, [r0, #4]
	str	r2, [r0, #8]
	str	r3, [r0, #12]
	adds	r0, #16
	str	r0, [r4, #12]
	ldrh	r0, [r4, #2]
	adds	r0, #1
	strh	r0, [r4, #2]
_08005556:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	.type sub_0800555C, %function
sub_0800555C:
_0800555C:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #4
	adds	r5, r0, #0
	movs	r7, #0
	ldr	r4, [r5, #8]
	movs	r1, #2
	ldrsh	r0, [r5, r1]
	cmp	r7, r0
	bge _080055BA
	ldr r6, _0800558C
_08005570:
	ldrh	r0, [r4, #0]
	cmp	r0, #0
	bne _08005590
	ldr	r0, [r4, #4]
	ldr	r1, [r4, #8]
	ldr	r2, [r4, #12]
	lsls	r2, r2, #9
	lsrs	r2, r2, #11
	movs	r3, #128
	lsls	r3, r3, #19
	orrs	r2, r3
	bl 0x0802D974
	b _080055AE
_0800558C: .4byte 0x040000D4
_08005590:
	cmp	r0, #1
	beq _080055AE
	ldrh	r0, [r4, #2]
	str	r0, [sp, #0]
	mov	r0, sp
	str	r0, [r6, #0]
	ldr	r0, [r4, #8]
	str	r0, [r6, #4]
	ldr	r0, [r4, #12]
	lsrs	r0, r0, #2
	movs	r1, #133
	lsls	r1, r1, #24
	orrs	r0, r1
	str	r0, [r6, #8]
	ldr	r0, [r6, #8]
_080055AE:
	adds	r7, #1
	adds	r4, #16
	movs	r1, #2
	ldrsh	r0, [r5, r1]
	cmp	r7, r0
	blt _08005570
_080055BA:
	movs	r0, #0
	strh	r0, [r5, #2]
	ldr	r0, [r5, #8]
	str	r0, [r5, #12]
	add	sp, #4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080055CC:
	movs	r1, #0
	strh	r1, [r0, #2]
	ldr	r1, [r0, #8]
	str	r1, [r0, #12]
	bx	lr
	movs	r0, r0
	.type sub_080055D8, %function
sub_080055D8:
_080055D8:
	push	{lr}
	adds	r3, r0, #0
	adds	r2, r1, #0
	ldr r0, _080055F0
	adds	r1, r3, #0
	bl sub_08005500
	movs	r0, #0
	bl _080056B8
	pop	{r0}
	bx	r0
_080055F0: .4byte 0x030002C0
_080055F4:
sub_080055F4:
	push	{lr}
	ldr r0, _08005600
	bl _080055CC
	pop	{r0}
	bx	r0
_08005600: .4byte 0x030002C0
_08005604:
sub_08005604:
	push	{lr}
	ldr r0, _08005610
	bl sub_0800555C
	pop	{r0}
	bx	r0
_08005610: .4byte 0x030002C0
_08005614:
sub_08005614:
	push	{r4, r5, lr}
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r3, r2, #0
	ldr r1, _08005648
	adds	r0, r1, #0
	adds	r0, #100
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r0, #0
	bne _08005650
	ldr r2, _0800564C
	str	r4, [r2, #0]
	str	r5, [r2, #4]
	adds	r0, r3, #0
	cmp	r3, #0
	bge _08005638
	adds	r0, r3, #3
_08005638:
	asrs	r0, r0, #2
	movs	r1, #132
	lsls	r1, r1, #24
	orrs	r0, r1
	str	r0, [r2, #8]
	ldr	r0, [r2, #8]
	b _0800565C
	movs	r0, r0
_08005648: .4byte 0x03000260
_0800564C: .4byte 0x040000D4
_08005650:
	adds	r0, r1, #0
	adds	r0, #96
	adds	r1, r4, #0
	adds	r2, r5, #0
	bl sub_0800552C
_0800565C:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08005664, %function
sub_08005664:
_08005664:
	push	{r4, lr}
	sub	sp, #4
	adds	r4, r0, #0
	adds	r3, r1, #0
	ldr r1, _0800569C
	adds	r0, r1, #0
	adds	r0, #100
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r0, #0
	bne _080056A4
	str	r0, [sp, #0]
	ldr r2, _080056A0
	mov	r0, sp
	str	r0, [r2, #0]
	str	r4, [r2, #4]
	adds	r0, r3, #0
	cmp	r3, #0
	bge _0800568C
	adds	r0, r3, #3
_0800568C:
	asrs	r0, r0, #2
	movs	r1, #133
	lsls	r1, r1, #24
	orrs	r0, r1
	str	r0, [r2, #8]
	ldr	r0, [r2, #8]
	b _080056B0
	movs	r0, r0
_0800569C: .4byte 0x03000260
_080056A0: .4byte 0x040000D4
_080056A4:
	adds	r0, r1, #0
	adds	r0, #96
	movs	r1, #0
	adds	r2, r4, #0
	bl sub_0800552C
_080056B0:
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
_080056B8:
	ldr r1, _080056C0
	adds	r1, #100
	strh	r0, [r1, #0]
	bx	lr
_080056C0: .4byte 0x03000260
	.type sub_080056C4, %function
sub_080056C4:
_080056C4:
	ldr r1, _080056D8
	lsls	r0, r0, #4
	adds	r0, r0, r1
	ldrb	r0, [r0, #5]
	lsls	r0, r0, #14
	movs	r1, #192
	lsls	r1, r1, #19
	adds	r0, r0, r1
	bx	lr
	movs	r0, r0
_080056D8: .4byte 0x03000260
	.type sub_080056DC, %function
sub_080056DC:
_080056DC:
	ldr r1, _080056F0
	lsls	r0, r0, #4
	adds	r0, r0, r1
	ldrb	r0, [r0, #6]
	lsls	r0, r0, #11
	movs	r1, #192
	lsls	r1, r1, #19
	adds	r0, r0, r1
	bx	lr
	movs	r0, r0
_080056F0: .4byte 0x03000260
@ A FUNCTION ENTRY with no label of its own, the same conversion
@ artifact as the four 0x080240xx leaves: the code starts 4 bytes after
@ its own pool word and the listing emitted only the data label. Five asm
@ files branch to 0x080056F4 by bare numeric `bl 0x080056F4` and nm lists
@ only an *ABS* relocation anchor, so nothing could resolve the name and
@ 0x08018260 read 'no closure label'. Verified against the ROM: it is
@ `lsls r1,r1,#4 / adds r0,r0,r1 / strb r2,[r0,#4] / bx lr`, a complete leaf.
_080056F4:
	lsls	r1, r1, #4
	adds	r0, r0, r1
	strb	r2, [r0, #4]
	bx	lr
	.type sub_080056FC, %function
sub_080056FC:
_080056FC:
	push	{r4, lr}
	sub	sp, #4
	movs	r0, #0
	str	r0, [sp, #0]
	ldr r4, _08005724
	ldr r2, _08005728
	mov	r0, sp
	adds	r1, r4, #0
	bl 0x0802D974
	movs	r0, #128
	lsls	r0, r0, #3
	strh	r0, [r4, #2]
	adds	r4, #68
	movs	r0, #16
	strh	r0, [r4, #0]
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
_08005724: .4byte 0x030002D8
_08005728: .4byte 0x05000012

@ End of region 0x0800572C. The last function here ends exactly at 0x0800572C, where
@ the next region file's prologue begins, so this anchor is the precise
@ end marker -- not a bounded-region guess. Without it the last body in
@ this file has no end marker to fall back on and the promotion screen
@ refuses it. Emits no bytes; the following file supplies the address.
code_4e6c_end:
