@ GT Advance 3 - converted span
@ Region: file offset 0x004B50-0x004B68 (VMA 0x08004B50-0x08004B68).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08004B50, %function
sub_08004B50:
_08004B50:
	push	{lr}
	ldr r1, _08004B64
	ldr	r0, [r1, #8]
	ldr	r1, [r1, #4]
	bl 0x0802DDCC
	bl 0x08004AA4
	pop	{r0}
	bx	r0
_08004B64: .4byte 0x03000198

@ End of region 0x08004B50-0x08004B68. This file's declared region is only 24
@ bytes and nothing follows it inside the file, so the splice has no textual
@ end anchor to bound a replacement of sub_08004B50 and the promotion screen
@ refuses the body ("no end marker in code_4b50.s and no code_4b50_end:"). The
@ span ends exactly at the region boundary -- the pool word above is the last
@ byte -- so this anchor is the precise end marker, not a bounded-region guess.
@ It emits no bytes, so the reference ROM hash is unchanged, but it is NOT
@ hash-neutral: docs/data/independent_slice.json and
@ docs/data/code_data_ownership.json pin this file's SHA-256 and size, so
@ `make independent-slice` and `make ownership-map` must run in the same change.
code_4b50_end:
