@ GT Advance 3 - converted span
@ Region: file offset 0x0241C8-0x02446C (VMA 0x080241C8-0x0802446C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_0800241C8, %function
sub_0800241C8:
_0800241C8:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #8
	movs	r7, #0
	ldr r0, _080024240
	mov	r8, r0
	movs	r1, #255
	lsls	r1, r1, #4
	add	r1, r8
	mov	sl, r1
_0800241E2:
	movs	r5, #0
	lsls	r2, r7, #3
	mov	r9, r2
	adds	r0, r7, #1
	str	r0, [sp, #0]
_0800241EC:
	adds	r0, r7, #0
	adds	r1, r5, #0
	bl 0x08025D64
	lsls	r2, r5, #1
	mov	r1, r9
	adds	r3, r2, r1
	ldr r6, _080024244
	add	r6, r8
	adds	r1, r3, r6
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	str	r2, [sp, #4]
	cmp	r0, #11
	bne _0800242A4
	ldr r0, _080024248
	add	r0, r8
	adds	r0, r3, r0
	movs	r3, #1
	strh	r3, [r0, #0]
	adds	r0, r5, #1
	ldr r1, _08002424C
	add	r1, r8
	strh	r0, [r1, #0]
	adds	r4, r0, #0
	cmp	r7, #0
	bne _080024274
	mov	r2, sl
	movs	r0, #0
	ldrsh	r2, [r2, r0]
	cmp	r2, #0
	bne _080024254
	lsls	r0, r4, #16
	asrs	r0, r0, #16
	ldr r2, _080024250
	adds	r6, r6, r2
	cmp	r0, #3
	ble _0800242B4
	movs	r0, #3
	strh	r0, [r1, #0]
	b _0800242B4
_080024240: .4byte 0x03001780
_080024244: .4byte 0x00000FFA
_080024248: .4byte 0x0000101A
_08002424C: .4byte 0x00000FF6
_080024250: .4byte 0xFFFFF006
_080024254:
	lsls	r0, r4, #16
	asrs	r0, r0, #16
	ldr r2, _08002426C
	adds	r6, r6, r2
	cmp	r0, #3
	ble _0800242B4
	strh	r7, [r1, #0]
	ldr r0, _080024270
	add	r0, r8
	strh	r3, [r0, #0]
	b _0800242B4
	movs	r0, r0
_08002426C: .4byte 0xFFFFF006
_080024270: .4byte 0x00000FF2
_080024274:
	mov	r0, sl
	ldrh	r0, [r0, #0]
	cmp	r0, #1
	bne _080024288
	lsls	r0, r4, #16
	asrs	r0, r0, #16
	cmp	r0, #3
	ble _080024288
	movs	r0, #3
	strh	r0, [r1, #0]
_080024288:
	movs	r1, #1
	mov	r2, sl
	strh	r1, [r2, #0]
	ldr r0, _08002429C
	add	r0, r8
	strh	r1, [r0, #0]
	ldr r1, _0800242A0
	adds	r6, r0, r1
	b _0800242B4
	movs	r0, r0
_08002429C: .4byte 0x00000FF2
_0800242A0: .4byte 0xFFFFF00E
_0800242A4:
	ldr r0, _0800242D4
	add	r0, r8
	adds	r0, r3, r0
	movs	r2, #0
	strh	r2, [r0, #0]
	ldr r0, _0800242D8
	adds	r6, r6, r0
	adds	r4, r5, #1
_0800242B4:
	ldr	r2, [sp, #4]
	add	r2, r9
	ldr r1, _0800242DC
	adds	r0, r6, r1
	adds	r0, r2, r0
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #2
	ble _0800242E4
	ldr r1, _0800242E0
	adds	r0, r6, r1
	adds	r0, r2, r0
	movs	r1, #1
	strh	r1, [r0, #0]
	b _0800242EE
	movs	r0, r0
_0800242D4: .4byte 0x0000101A
_0800242D8: .4byte 0xFFFFF006
_0800242DC: .4byte 0x00000FFA
_0800242E0: .4byte 0x0000102A
_0800242E4:
	ldr r1, _080024334
	adds	r0, r6, r1
	adds	r0, r2, r0
	movs	r2, #0
	strh	r2, [r0, #0]
_0800242EE:
	adds	r0, r7, #0
	adds	r1, r5, #0
	bl 0x0800A9A0
	adds	r2, r0, #0
	adds	r0, r7, #0
	adds	r1, r5, #0
	bl sub_08002714
	adds	r0, r7, #0
	adds	r1, r5, #0
	bl 0x0800A9E0
	adds	r2, r0, #0
	adds	r0, r7, #0
	adds	r1, r5, #0
	bl sub_080026DC
	adds	r5, r4, #0
	cmp	r5, #3
	bgt _08002431A
	b _0800241EC
_08002431A:
	ldr	r7, [sp, #0]
	cmp	r7, #1
	bgt _080024322
	b _0800241E2
_080024322:
	add	sp, #8
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080024334: .4byte 0x0000102A
	.type sub_080024338, %function
sub_080024338:
_080024338:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	bl 0x08025B3C
	bl 0x08025B88
	movs	r5, #0
_080024348:
	movs	r4, #0
	adds	r6, r5, #1
_08002434C:
	movs	r0, #0
	adds	r1, r5, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl 0x08025C84
	movs	r0, #1
	adds	r1, r5, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl 0x08025C84
	adds	r4, #1
	cmp	r4, #10
	ble _08002434C
	adds	r5, r6, #0
	cmp	r5, #3
	ble _080024348
	ldr r4, _08002445C
	ldr r0, _080024460
	adds	r5, r4, r0
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	bl 0x08025D90
	ldr r2, _080024464
	adds	r1, r4, r2
	strh	r0, [r1, #0]
	movs	r2, #0
	ldrsh	r0, [r5, r2]
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	bl 0x08025D64
	ldr r1, _080024468
	adds	r4, r4, r1
	strh	r0, [r4, #0]
	bl sub_0800241C8
	movs	r0, #1
	bl 0x08025F78
	movs	r0, #3
	bl 0x08025F78
	movs	r0, #6
	bl 0x08025F78
	movs	r0, #7
	bl 0x08025F78
	movs	r0, #8
	bl 0x08025F78
	movs	r0, #10
	bl 0x08025F78
	movs	r0, #15
	bl 0x08025F78
	movs	r0, #16
	bl 0x08025F78
	movs	r0, #24
	bl 0x08025F78
	movs	r0, #25
	bl 0x08025F78
	movs	r0, #32
	bl 0x08025F78
	movs	r0, #34
	bl 0x08025F78
	movs	r0, #35
	bl 0x08025F78
	movs	r0, #41
	bl 0x08025F78
	movs	r0, #57
	bl 0x08025F78
	movs	r0, #63
	bl 0x08025F78
	movs	r0, #65
	bl 0x08025F78
	movs	r0, #67
	bl 0x08025F78
	movs	r0, #68
	bl 0x08025F78
	movs	r0, #72
	bl 0x08025F78
	movs	r4, #0
_080024414:
	adds	r0, r4, #0
	movs	r1, #0
	bl 0x08025DBC
	adds	r4, #1
	cmp	r4, #31
	ble _080024414
	movs	r7, #0
_080024424:
	movs	r5, #0
	adds	r2, r7, #1
	mov	r8, r2
_08002442A:
	movs	r4, #0
	adds	r6, r5, #1
_08002442E:
	adds	r0, r7, #0
	adds	r1, r5, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl 0x08025E70
	adds	r4, #1
	cmp	r4, #2
	ble _08002442E
	adds	r5, r6, #0
	cmp	r5, #3
	ble _08002442A
	mov	r7, r8
	cmp	r7, #1
	ble _080024424
	movs	r0, #0
	bl 0x08025FF0
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08002445C: .4byte 0x03001780
_080024460: .4byte 0x00000FF2
_080024464: .4byte 0x00000FF6
_080024468: .4byte 0x0000103A
