@ GT Advance 3 - converted span
@ Region: file offset 0x024144-0x024150 (VMA 0x08024144-0x08024150).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	ldr r0, _08002414C
	ldr	r0, [r0, #0]
	bx	lr
	movs	r0, r0
_08002414C: .4byte 0x03000610
