@ GT Advance 3 - converted span
@ Region: file offset 0x024048-0x0240D0 (VMA 0x08024048-0x080240D0).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080024048, %function
sub_080024048:
_080024048:
	push	{r4, r5, lr}
	ldr r3, _080024064
	ldr	r2, [r3, #0]
	lsls	r1, r2, #3
	adds	r1, r1, r3
	ldr	r4, [r1, #4]
	ldr	r5, [r1, #8]
	adds	r2, #1
	str	r2, [r3, #0]
	str	r4, [r0, #0]
	str	r5, [r0, #4]
	pop	{r4, r5}
	pop	{r2}
	bx	r2
_080024064: .4byte 0x030005B0
@ 0x08024068 — a real 8-instruction leaf the span generator emitted but never
@ named, because nothing in the C referenced it by address. It is the target
@ of `bl 0x08024068` from 0x0801E204 (see asm/code_1e1e0.s) and from the menu
@ record bodies, which is why both call sites were refused by promotion_screen
@ with "no closure label at 0x08024068". Reads the 0x030005B0 block counter,
@ scales it by 8 into the block array, and returns the block's +4/+8 words.
@ Labels only: no bytes change.
	.type _08024068, %function
_08024068:
Sub_08024068:
	ldr r0, _080024078
	ldr	r1, [r0, #0]
	lsls	r1, r1, #3
	adds	r1, r1, r0
	ldr	r0, [r1, #4]
	ldr	r1, [r1, #8]
	bx	lr
	movs	r0, r0
_080024078: .4byte 0x030005B0
	.type _08002407C, %function
_08002407C:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #8
	adds	r3, r0, #0
	adds	r5, r2, #0
	ldr r6, _0800240C0
	str	r3, [r6, #4]
	str	r1, [r6, #8]
	movs	r7, #0
	str	r7, [sp, #0]
	adds	r0, r5, #0
	cmp	r5, #0
	bge _080024096
	adds	r0, r5, #3
_080024096:
	lsls	r0, r0, #9
	lsrs	r4, r0, #11
	movs	r0, #160
	lsls	r0, r0, #19
	orrs	r4, r0
	mov	r0, sp
	adds	r1, r3, #0
	adds	r2, r4, #0
	bl 0x0802D974
	str	r7, [sp, #4]
	add	r0, sp, #4
	ldr	r1, [r6, #8]
	adds	r2, r4, #0
	bl 0x0802D974
	add	sp, #8
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800240C0: .4byte 0x03000610
@ A FUNCTION ENTRY, and the only label it lacks. The `.4byte` above is this
@ leaf's own POOL WORD, not the body: the code begins 4 bytes after it and
@ falls straight through with no label of its own. The converted listing
@ emitted the data label and dropped the entry, so the screen found no
@ closure owner and refused the body as 'no closure owner'. (deleted: asm/ghost2.s)
@ does carry these four labels, but it is an ORPHAN -- nothing includes it,
@ and adding it to the closure would double-define the region. Confirmed as
@ code, not data, by disassembling baserom.gba at this VMA.
_080240C4:
	ldr r0, _0800240CC
	ldr	r0, [r0, #4]
	bx	lr
	movs	r0, r0
_0800240CC: .4byte 0x03000610

@ End-of-region anchor for the splicer. This file declares exactly one
@ `@ Region:` (0x08024048-0x080240d0) and has no `.include`; the promoted body at
@ 0x080240C4 ends on 0x080240d0, exactly that boundary. Unambiguous, so the anchor is
@ safe. Without it the body is refused as 'no end marker'.
code_24048_end:
