@ GT Advance 3 - converted span
@ Region: file offset 0x004CF0-0x004D4C (VMA 0x08004CF0-0x08004D4C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08004CF0, %function
sub_08004CF0:
	ldr r2, _08004D0C
	adds	r1, r2, #0
	adds	r1, #112
	ldrh	r0, [r1, #0]
	cmp	r0, #0
	beq _08004D00
	subs	r0, #1
	strh	r0, [r1, #0]
_08004D00:
	adds	r0, r2, #0
	adds	r0, #116
	ldrh	r1, [r1, #0]
	adds	r0, r1, r0
	ldrb	r0, [r0, #0]
	bx	lr
_08004D0C: .4byte 0x03000198
	.type _08004D10, %function
_08004D10:
	movs	r1, #0
	strh	r1, [r0, #4]
	bx	lr
	movs	r0, r0
	.type _08004D18, %function
_08004D18:
	movs	r1, #64
	ldrh	r0, [r0, #4]
	ands	r1, r0
	cmp	r1, #0
	bne _08004D26
	movs	r0, #1
	b _08004D28
_08004D26:
	movs	r0, #0
_08004D28:
	bx	lr
	movs	r0, r0
	.type _08004D2C, %function
_08004D2C:
	adds	r2, r0, #0
	cmp	r1, #0
	beq _08004D3A
	movs	r0, #64
	ldrh	r1, [r2, #4]
	orrs	r0, r1
	b _08004D40
_08004D3A:
	ldr r0, _08004D44
	ldrh	r1, [r2, #4]
	ands	r0, r1
_08004D40:
	strh	r0, [r2, #4]
	bx	lr
_08004D44: .4byte 0x0000FFBF
	.type _08004D48, %function
_08004D48:
	ldrh	r0, [r0, #6]
	bx	lr

@ Byte-neutral end anchor for the splicer. This file declares exactly one
@ `@ Region:` (0x004CF0-0x004D4C) and has no `.include`; the body at
@ 0x08004D48 ends on 0x004D4C, exactly that boundary, so the anchor is safe.
@ Without it the body is refused as 'no end marker in code_4cf0.s'.
code_4cf0_end:
