@ GT Advance 3 - converted span
@ Region: file offset 0x024F34-0x024F4C (VMA 0x08024F34-0x08024F4C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	movs	r1, #0
	strb	r1, [r0, #0]
	strb	r1, [r0, #1]
	strb	r1, [r0, #2]
	strb	r1, [r0, #3]
	strb	r1, [r0, #4]
	strb	r1, [r0, #5]
	strb	r1, [r0, #6]
	strb	r1, [r0, #7]
	strb	r1, [r0, #8]
	strb	r1, [r0, #9]
	bx	lr
