@ GT Advance 3 - converted span
@ Region: file offset 0x024FC4-0x024FE8 (VMA 0x08024FC4-0x08024FE8).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080024FC4, %function
sub_080024FC4:
_080024FC4:
	push	{r4, lr}
	ldr r4, _080024FE4
	lsls	r2, r2, #2
	movs	r3, #44
	muls	r1, r3
	adds	r2, r2, r1
	movs	r1, #176
	muls	r0, r1
	adds	r2, r2, r0
	adds	r2, r2, r4
	movs	r1, #0
	ldrsh	r0, [r2, r1]
	pop	{r4}
	pop	{r1}
	bx	r1
	movs	r0, r0
_080024FE4: .4byte 0x080CCD8C
code_24fc4_end:
