@ GT Advance 3 - converted span
@ Region: file offset 0x02DF6A-0x02DF6C (VMA 0x0802DF6A-0x0802DF6C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.hword 0x0000
