@ GT Advance 3 - converted span
@ Region: file offset 0x004B74-0x004B9C (VMA 0x08004B74-0x08004B9C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.


@ Entry marker for the 0x08004B74 slice entry. The `.type` for this VMA lives
@ in passthrough.inc, so tools/promotion_screen.py:pick_marker finds no
@ UNIQUE start marker inside this region file and the body is unstageable.
@ A second `.type` for the same symbol is byte-neutral: `.type` emits nothing.
.type sub_08004B74, %function
	ldrh	r0, [r0, #4]
	lsrs	r1, r0, #2
	movs	r0, #1
	bics	r0, r1
	bx	lr
	movs	r0, r0
	.type sub_08004B80, %function
sub_08004B80:
_08004B80:
	ldr r1, _08004B8C
	ldrh	r2, [r0, #4]
	ands	r1, r2
	strh	r1, [r0, #4]
	bx	lr
	movs	r0, r0
_08004B8C: .4byte 0x0000FFFB
	.type sub_08004B90, %function
sub_08004B90:
_08004B90:
	movs	r1, #4
	ldrh	r2, [r0, #4]
	orrs	r1, r2
	strh	r1, [r0, #4]
	bx	lr
	.hword 0x0000
code_4b74_end:
