@ GT Advance 3 - converted span
@ Region: file offset 0x0263E0-0x026F30 (VMA 0x080263E0-0x08026F30).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_0800263E0, %function
sub_0800263E0:
_0800263E0:
	push	{r4, r5, lr}
	adds	r4, r0, #0
	lsls	r5, r1, #5
	ldr r0, _0800264A8
	adds	r1, r5, r0
	adds	r0, r4, #0
	movs	r2, #48
	bl 0x0802D970
	adds	r0, r4, #0
	adds	r0, #192
	ldr r2, _0800264AC
	adds	r1, r5, r2
	movs	r2, #48
	bl 0x0802D970
	movs	r1, #192
	lsls	r1, r1, #1
	adds	r0, r4, r1
	ldr r2, _0800264B0
	adds	r1, r5, r2
	movs	r2, #48
	bl 0x0802D970
	movs	r1, #144
	lsls	r1, r1, #2
	adds	r0, r4, r1
	ldr r2, _0800264B4
	adds	r1, r5, r2
	movs	r2, #48
	bl 0x0802D970
	movs	r1, #192
	lsls	r1, r1, #2
	adds	r0, r4, r1
	ldr r2, _0800264B8
	adds	r1, r5, r2
	movs	r2, #48
	bl 0x0802D970
	movs	r1, #240
	lsls	r1, r1, #2
	adds	r0, r4, r1
	ldr r2, _0800264BC
	adds	r1, r5, r2
	movs	r2, #48
	bl 0x0802D970
	movs	r1, #144
	lsls	r1, r1, #3
	adds	r0, r4, r1
	ldr r2, _0800264C0
	adds	r1, r5, r2
	movs	r2, #48
	bl 0x0802D970
	movs	r1, #168
	lsls	r1, r1, #3
	adds	r0, r4, r1
	ldr r2, _0800264C4
	adds	r1, r5, r2
	movs	r2, #48
	bl 0x0802D970
	movs	r1, #192
	lsls	r1, r1, #3
	adds	r0, r4, r1
	ldr r2, _0800264C8
	adds	r1, r5, r2
	movs	r2, #48
	bl 0x0802D970
	movs	r1, #216
	lsls	r1, r1, #3
	adds	r0, r4, r1
	ldr r2, _0800264CC
	adds	r1, r5, r2
	movs	r2, #48
	bl 0x0802D970
	movs	r1, #240
	lsls	r1, r1, #3
	adds	r0, r4, r1
	ldr r2, _0800264D0
	adds	r1, r5, r2
	movs	r2, #48
	bl 0x0802D970
	movs	r1, #132
	lsls	r1, r1, #4
	adds	r0, r4, r1
	ldr r2, _0800264D4
	adds	r1, r5, r2
	movs	r2, #48
	bl 0x0802D970
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800264A8: .4byte 0x06010120
_0800264AC: .4byte 0x06010220
_0800264B0: .4byte 0x06010320
_0800264B4: .4byte 0x06010420
_0800264B8: .4byte 0x06010520
_0800264BC: .4byte 0x06010620
_0800264C0: .4byte 0x06010920
_0800264C4: .4byte 0x06010A20
_0800264C8: .4byte 0x06010B20
_0800264CC: .4byte 0x06010C20
_0800264D0: .4byte 0x06010D20
_0800264D4: .4byte 0x06010E20
	.type sub_0800264D8, %function
sub_0800264D8:
_0800264D8:
	push	{r4, r5, r6, lr}
	adds	r6, r0, #0
	adds	r4, r1, #0
	ldr r0, _080026518
	ldr	r1, [r6, #0]
	bl 0x08007498
	adds	r5, r0, #0
	bl 0x0800748C
	ldr r1, _08002651C
	ands	r4, r1
	ldr	r0, [r0, #0]
	asrs	r4, r0
	adds	r0, r5, #0
	movs	r1, #0
	bl 0x08007498
	bl 0x0800748C
	adds	r0, r0, r4
	movs	r1, #127
	ldrb	r0, [r0, #0]
	ands	r1, r0
	lsls	r2, r1, #3
	adds	r2, r2, r1
	lsls	r2, r2, #8
	ldr	r0, [r6, #4]
	adds	r0, r0, r2
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
_080026518: .4byte 0x087999D8
_08002651C: .4byte 0x00000FFF
	.type sub_080026520, %function
sub_080026520:
_080026520:
	push	{r4, lr}
	adds	r4, r1, #0
	ldr r2, _080026548
	ldr r1, _08002654C
	lsls	r0, r0, #2
	adds	r0, r0, r1
	ldr	r1, [r0, #0]
	adds	r0, r2, #0
	bl 0x08007498
	movs	r1, #2
	bl 0x08007498
	bl 0x0800748C
	lsls	r4, r4, #5
	adds	r0, r0, r4
	pop	{r4}
	pop	{r1}
	bx	r1
_080026548: .4byte 0x083D7BE8
_08002654C: .4byte 0x080CC1E4
	.type _080026550, %function
_080026550:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #4
	adds	r3, r0, #0
	adds	r5, r1, #0
	adds	r7, r2, #0
	ldr	r0, [r7, #44]
	mov	sl, r0
	ldrb	r1, [r7, #4]
	mov	r9, r1
	ldr	r0, [r7, #24]
	ldrh	r6, [r7, #24]
	adds	r0, #64
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	str	r0, [sp, #0]
	ldr r0, _080026660
	ldr	r1, [r3, #0]
	bl 0x08007498
	adds	r4, r0, #0
	bl 0x0800748C
	ldr r1, _080026664
	ands	r5, r1
	ldr	r0, [r0, #0]
	asrs	r5, r0
	adds	r0, r4, #0
	movs	r1, #0
	bl 0x08007498
	bl 0x0800748C
	adds	r1, r0, #0
	ldr r0, _080026668
	ldr r2, _08002666C
	adds	r0, r0, r2
	ldrb	r0, [r0, #0]
	movs	r3, #128
	lsls	r3, r3, #3
	mov	r8, r3
	cmp	r0, #0
	beq _0800265B2
	movs	r0, #128
	lsls	r0, r0, #4
	mov	r8, r0
_0800265B2:
	adds	r1, r1, r5
	movs	r0, #128
	ldrb	r1, [r1, #0]
	ands	r0, r1
	cmp	r0, #0
	beq _0800265D0
	ldr	r0, [r7, #20]
	bl 0x08002C84
	ldr	r0, [r7, #24]
	ldrh	r1, [r7, #24]
	str	r1, [sp, #0]
	adds	r0, #64
	lsls	r0, r0, #16
	lsrs	r6, r0, #16
_0800265D0:
	bl 0x08002BFC
	adds	r2, r0, #0
	mov	r0, r9
	mov	r3, sl
	ldrh	r3, [r3, #8]
	orrs	r0, r3
	strh	r0, [r2, #0]
	ldr	r1, [r7, #0]
	mov	r0, sl
	ldrh	r0, [r0, #0]
	subs	r1, r1, r0
	ldr r3, _080026670
	adds	r5, r3, #0
	ands	r1, r5
	ldr	r0, [r7, #20]
	lsls	r0, r0, #9
	movs	r3, #192
	lsls	r3, r3, #8
	adds	r4, r3, #0
	orrs	r0, r4
	orrs	r1, r0
	strh	r1, [r2, #2]
	mov	r0, r8
	orrs	r6, r0
	ldrh	r1, [r7, #28]
	orrs	r6, r1
	strh	r6, [r2, #4]
	movs	r3, #0
	strh	r3, [r2, #12]
	ldr	r0, [r7, #8]
	adds	r1, r2, #0
	bl 0x08002C34
	bl 0x08002BFC
	adds	r2, r0, #0
	mov	r0, sl
	ldrh	r1, [r0, #8]
	mov	r0, r9
	orrs	r1, r0
	strh	r1, [r2, #0]
	ldr	r1, [r7, #0]
	mov	r3, sl
	ldrh	r3, [r3, #2]
	subs	r1, r1, r3
	ands	r1, r5
	ldr	r0, [r7, #20]
	lsls	r0, r0, #9
	orrs	r0, r4
	orrs	r1, r0
	strh	r1, [r2, #2]
	mov	r0, r8
	ldr	r1, [sp, #0]
	orrs	r0, r1
	ldrh	r3, [r7, #28]
	orrs	r3, r0
	strh	r3, [r2, #4]
	movs	r0, #0
	strh	r0, [r2, #12]
	ldr	r0, [r7, #8]
	adds	r1, r2, #0
	bl 0x08002C34
	add	sp, #4
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080026660: .4byte 0x087999D8
_080026664: .4byte 0x00000FFF
_080026668: .4byte 0x03001780
_08002666C: .4byte 0x000010BC
_080026670: .4byte 0x000001FF
	.type sub_080026674, %function
sub_080026674:
_080026674:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #16
	adds	r4, r0, #0
	adds	r6, r1, #0
	str	r2, [sp, #0]
	str	r3, [sp, #4]
	ldr	r1, [sp, #48]
	movs	r0, #0
	mov	r8, r0
	movs	r2, #0
	str	r2, [sp, #8]
	lsls	r0, r1, #16
	lsrs	r7, r0, #16
	adds	r1, #64
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	mov	sl, r1
	mov	r5, sl
	ldr r0, _0800267E8
	ldr	r1, [r4, #0]
	bl 0x08007498
	adds	r4, r0, #0
	bl 0x0800748C
	adds	r1, r0, #0
	ldr r0, _0800267EC
	ldr r2, _0800267F0
	adds	r0, r0, r2
	ldrb	r0, [r0, #0]
	movs	r2, #128
	lsls	r2, r2, #3
	str	r2, [sp, #12]
	cmp	r0, #0
	beq _0800266C8
	movs	r0, #128
	lsls	r0, r0, #4
	str	r0, [sp, #12]
_0800266C8:
	ldr r0, _0800267F4
	ands	r6, r0
	ldr	r0, [r1, #0]
	asrs	r6, r0
	adds	r0, r4, #0
	movs	r1, #0
	bl 0x08007498
	bl 0x0800748C
	adds	r0, r0, r6
	movs	r1, #128
	ldrb	r0, [r0, #0]
	ands	r1, r0
	cmp	r1, #0
	beq _0800266F2
	ldr	r0, [sp, #64]
	bl 0x08002C84
	mov	sl, r7
	adds	r7, r5, #0
_0800266F2:
	ldr	r0, [sp, #60]
	cmp	r0, #0
	bge _0800266FA
	adds	r0, #15
_0800266FA:
	lsls	r0, r0, #12
	lsrs	r4, r0, #16
	asrs	r0, r0, #16
	bl 0x08005B5C
	cmp	r0, #4
	bgt _08002670A
	movs	r4, #0
_08002670A:
	lsls	r0, r4, #16
	asrs	r6, r0, #16
	cmp	r6, #0
	beq _080026748
	ldr	r0, [sp, #64]
	adds	r1, r6, #0
	bl 0x08002C74
	negs	r0, r6
	movs	r1, #10
	bl 0x0802D978
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	mov	r8, r0
	adds	r0, r6, #0
	movs	r1, #10
	bl 0x0802D978
	adds	r4, r0, #0
	adds	r0, r6, #0
	movs	r1, #5
	bl 0x0802D978
	movs	r1, #2
	bl 0x0802D97C
	adds	r4, r4, r0
	lsls	r4, r4, #16
	lsrs	r4, r4, #16
	str	r4, [sp, #8]
_080026748:
	bl 0x08002BFC
	adds	r1, r0, #0
	movs	r4, #128
	lsls	r4, r4, #1
	mov	r2, r8
	lsls	r0, r2, #16
	asrs	r0, r0, #16
	ldr	r2, [sp, #4]
	subs	r0, r2, r0
	movs	r2, #255
	mov	r8, r2
	mov	r2, r8
	ands	r0, r2
	orrs	r0, r4
	movs	r2, #0
	mov	r9, r2
	strh	r0, [r1, #0]
	ldr	r0, [sp, #0]
	subs	r0, #56
	ldr r2, _0800267F8
	adds	r6, r2, #0
	ands	r0, r6
	movs	r2, #192
	lsls	r2, r2, #8
	orrs	r0, r2
	ldr	r2, [sp, #64]
	lsls	r5, r2, #9
	orrs	r0, r5
	strh	r0, [r1, #2]
	ldr	r0, [sp, #52]
	orrs	r7, r0
	ldr	r2, [sp, #12]
	orrs	r7, r2
	strh	r7, [r1, #4]
	mov	r0, r9
	strh	r0, [r1, #12]
	ldr	r0, [sp, #56]
	bl 0x08002C34
	bl 0x08002BFC
	adds	r1, r0, #0
	ldr	r2, [sp, #8]
	lsls	r0, r2, #16
	asrs	r0, r0, #16
	ldr	r2, [sp, #4]
	subs	r0, r2, r0
	mov	r2, r8
	ands	r0, r2
	orrs	r4, r0
	strh	r4, [r1, #0]
	ldr	r0, [sp, #0]
	subs	r0, #8
	ands	r0, r6
	movs	r2, #192
	lsls	r2, r2, #8
	orrs	r0, r2
	orrs	r0, r5
	strh	r0, [r1, #2]
	mov	r0, sl
	ldr	r2, [sp, #52]
	orrs	r0, r2
	ldr	r2, [sp, #12]
	orrs	r2, r0
	strh	r2, [r1, #4]
	mov	r2, r9
	strh	r2, [r1, #12]
	ldr	r0, [sp, #56]
	bl 0x08002C34
	add	sp, #16
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800267E8: .4byte 0x087999D8
_0800267EC: .4byte 0x03001780
_0800267F0: .4byte 0x000010BC
_0800267F4: .4byte 0x00000FFF
_0800267F8: .4byte 0x000001FF
	.type sub_0800267FC, %function
sub_0800267FC:
_0800267FC:
	push	{r4, r5, r6, lr}
	adds	r6, r1, #0
	ldr r1, _080026850
	adds	r2, r0, r1
	movs	r1, #0
	ldrsb	r1, [r2, r1]
	movs	r0, #1
	negs	r0, r0
	cmp	r1, r0
	beq _080026860
	ldr r0, _080026854
	bl 0x08007498
	bl 0x0800748C
	adds	r5, r0, #0
	ldr r0, _080026858
	movs	r1, #6
	bl 0x08007498
	adds	r4, r0, #0
	bl 0x0800748C
	ldr r1, _08002685C
	ands	r6, r1
	ldr	r0, [r0, #0]
	asrs	r6, r0
	adds	r0, r4, #0
	movs	r1, #0
	bl 0x08007498
	bl 0x0800748C
	adds	r0, r0, r6
	movs	r1, #127
	ldrb	r0, [r0, #0]
	ands	r1, r0
	lsls	r1, r1, #10
	adds	r5, r5, r1
	adds	r0, r5, #0
	b _080026862
	movs	r0, r0
_080026850: .4byte 0x080CDA74
_080026854: .4byte 0x0879A304
_080026858: .4byte 0x087999D8
_08002685C: .4byte 0x00000FFF
_080026860:
	movs	r0, #0
_080026862:
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	.type sub_080026868, %function
sub_080026868:
_080026868:
	push	{lr}
	lsls	r1, r1, #5
	ldr r2, _08002687C
	adds	r1, r1, r2
	movs	r2, #128
	lsls	r2, r2, #1
	bl 0x0802D970
	pop	{r0}
	bx	r0
_08002687C: .4byte 0x06010000
	.type sub_08026880, %function
sub_08026880:
_08026880:
	push	{lr}
	ldr r0, _080026894
	movs	r1, #3
	bl 0x08007498
	bl 0x0800748C
	pop	{r1}
	bx	r1
	movs	r0, r0
_080026894: .4byte 0x0879A304
	.type sub_080026898, %function
sub_080026898:
_080026898:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #4
	adds	r5, r2, #0
	mov	r8, r3
	ldr	r0, [sp, #48]
	ldr	r7, [sp, #52]
	movs	r1, #0
	mov	sl, r1
	movs	r2, #192
	lsls	r2, r2, #8
	mov	r9, r2
	negs	r4, r0
	orrs	r4, r0
	asrs	r4, r4, #31
	movs	r0, #128
	lsls	r0, r0, #3
	ands	r4, r0
	bl 0x08002BFC
	adds	r1, r0, #0
	movs	r0, #255
	mov	r2, r8
	ands	r2, r0
	orrs	r4, r2
	strh	r4, [r1, #0]
	adds	r0, r5, #0
	subs	r0, #56
	ldr r2, _080026934
	mov	r8, r2
	mov	r2, r8
	ands	r0, r2
	mov	r2, r9
	orrs	r0, r2
	strh	r0, [r1, #2]
	ldr	r0, [sp, #40]
	lsls	r6, r0, #12
	ldr	r0, [sp, #36]
	orrs	r0, r6
	lsls	r7, r7, #10
	orrs	r0, r7
	strh	r0, [r1, #4]
	mov	r2, sl
	strh	r2, [r1, #12]
	ldr	r0, [sp, #44]
	bl 0x08002C34
	bl 0x08002BFC
	adds	r1, r0, #0
	strh	r4, [r1, #0]
	subs	r5, #8
	mov	r0, r8
	ands	r5, r0
	mov	r2, r9
	orrs	r5, r2
	strh	r5, [r1, #2]
	ldr	r0, [sp, #36]
	adds	r0, #64
	orrs	r0, r6
	orrs	r0, r7
	strh	r0, [r1, #4]
	mov	r0, sl
	strh	r0, [r1, #12]
	ldr	r0, [sp, #44]
	bl 0x08002C34
	add	sp, #4
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080026934: .4byte 0x000001FF
	.type sub_080026938, %function
sub_080026938:
_080026938:
	push	{lr}
	ldr	r0, [r0, #8]
_08002693C:
	ldr	r0, [r0, #92]
	bl 0x080262A4
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080026948, %function
sub_080026948:
_080026948:
	push	{r4, r5, r6, lr}
	mov	r6, r8
	push	{r6}
	ldr r0, _0800269A4
	bl 0x08004E0C
	mov	r8, r0
	ldr	r4, [r0, #8]
_080026958:
	movs	r5, #0
	strb	r5, [r4, #18]
	movs	r0, #160
	bl 0x08005758
	movs	r6, #0
	strh	r0, [r4, #0]
	ldrh	r0, [r4, #0]
	movs	r1, #160
	bl 0x080057A4
	movs	r0, #1
	bl 0x08005790
	strh	r0, [r4, #2]
	strh	r5, [r4, #10]
	movs	r0, #1
	strb	r0, [r4, #16]
	strb	r6, [r4, #17]
	adds	r0, r4, #0
	adds	r0, #20
	ldr r1, _0800269A8
	bl 0x0802620C
	bl 0x08026220
	movs	r0, #0
	movs	r1, #0
	bl 0x08026230
	str	r0, [r4, #92]
	mov	r0, r8
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
_0800269A4: .4byte 0x080CDAD8
_0800269A8: .4byte 0x0202AC00
	.type _0800269AC, %function
_0800269AC:
	push	{r4, r5, r6, lr}
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6}
	adds	r5, r0, #0
	lsls	r5, r5, #16
	lsrs	r5, r5, #16
	ldr r0, _080026A18
	bl 0x08004E0C
	mov	r9, r0
	ldr	r4, [r0, #8]
	movs	r6, #0
	strb	r6, [r4, #18]
	movs	r0, #160
	bl 0x08005758
	movs	r1, #0
	mov	r8, r1
	strh	r0, [r4, #0]
	ldrh	r0, [r4, #0]
	movs	r1, #160
	bl 0x080057A4
	movs	r0, #1
	bl 0x08005790
	strh	r0, [r4, #2]
	strh	r6, [r4, #10]
	movs	r0, #1
	strb	r0, [r4, #16]
	mov	r1, r8
	strb	r1, [r4, #17]
	strh	r5, [r4, #8]
	strb	r0, [r4, #18]
	adds	r0, r4, #0
	adds	r0, #20
	ldr r1, _080026A1C
	bl 0x0802620C
	bl 0x08026220
	movs	r0, #0
	movs	r1, #0
	bl 0x08026230
	str	r0, [r4, #92]
	mov	r0, r9
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
_080026A18: .4byte 0x080CDAD8
_080026A1C: .4byte 0x0202AC00
_080026A20:
sub_080026A20:
	ldr	r3, [r0, #8]
	strh	r1, [r3, #4]
	ldr	r0, [r0, #8]
	strh	r2, [r0, #6]
	bx	lr
	movs	r0, r0
	.type sub_080026A2C, %function
sub_080026A2C:
_080026A2C:
	push	{r4, lr}
	ldr	r4, [r0, #8]
	ldr r3, _080026A48
	ldrh	r3, [r3, #12]
	lsls	r3, r3, #16
	asrs	r3, r3, #19
	subs	r1, r1, r3
	strh	r1, [r4, #4]
	ldr	r0, [r0, #8]
	strh	r2, [r0, #6]
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080026A48: .4byte 0x030035C0
	.type sub_080026A4C, %function
sub_080026A4C:
_080026A4C:
_08026A4C:
	ldr	r3, [r0, #8]
	strh	r1, [r3, #10]
	ldr	r0, [r0, #8]
	strh	r2, [r0, #12]
	bx	lr
	movs	r0, r0
	.type sub_080026A58, %function
sub_080026A58:
_080026A58:
_08026A58:
	ldr	r0, [r0, #8]
	strb	r1, [r0, #16]
	bx	lr
	movs	r0, r0
	.type sub_080026A60, %function
sub_080026A60:
_080026A60:
_08026A60:
	ldr	r0, [r0, #8]
	strb	r1, [r0, #17]
	bx	lr
	movs	r0, r0
_080026A68:
	adds	r1, r0, #0
	ldrb	r0, [r1, #18]
	cmp	r0, #0
	bne _080026A76
	ldrh	r0, [r1, #8]
	adds	r0, #64
	strh	r0, [r1, #8]
_080026A76:
	bx	lr
	.type sub_080026A78, %function
sub_080026A78:
_080026A78:
	push	{r4, r5, lr}
	sub	sp, #20
	adds	r5, r0, #0
	ldrb	r0, [r5, #16]
	cmp	r0, #0
	beq _080026AAA
	ldr	r0, [r5, #92]
	movs	r2, #8
	ldrsh	r1, [r5, r2]
	movs	r3, #4
	ldrsh	r2, [r5, r3]
	movs	r4, #6
	ldrsh	r3, [r5, r4]
	ldrh	r4, [r5, #0]
	str	r4, [sp, #0]
	ldrh	r4, [r5, #2]
	str	r4, [sp, #4]
	movs	r4, #2
	str	r4, [sp, #8]
	ldrb	r4, [r5, #17]
	str	r4, [sp, #12]
	movs	r4, #1
	str	r4, [sp, #16]
	bl sub_080026898
_080026AAA:
	add	sp, #20
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080026AB4, %function
sub_080026AB4:
_080026AB4:
	push	{r4, r5, r6, lr}
	adds	r6, r0, #0
	movs	r0, #8
	ldrsh	r1, [r6, r0]
	cmp	r1, #0
	bge _080026AC2
	adds	r1, #255
_080026AC2:
	asrs	r1, r1, #8
	lsls	r1, r1, #7
	ldr	r0, [r6, #92]
	bl sub_0800264D8
	adds	r5, r0, #0
	movs	r1, #10
	ldrsh	r0, [r6, r1]
	movs	r2, #12
	ldrsh	r1, [r6, r2]
	bl sub_080026520
	adds	r4, r0, #0
	ldrh	r1, [r6, #0]
	adds	r0, r5, #0
	bl sub_0800263E0
	ldrh	r6, [r6, #2]
	lsls	r1, r6, #5
	ldr r0, _080026AFC
	adds	r1, r1, r0
	adds	r0, r4, #0
	movs	r2, #8
	bl 0x0802D970
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080026AFC: .4byte 0x05000200
	.type _080026B00, %function
_080026B00:
	push	{lr}
	cmp	r0, #7
	beq _080026B1E
	cmp	r0, #7
	bhi _080026B10
	cmp	r0, #5
	beq _080026B16
	b _080026B2C
_080026B10:
	cmp	r0, #8
	beq _080026B26
	b _080026B2C
_080026B16:
	adds	r0, r3, #0
	bl _080026A68
	b _080026B2C
_080026B1E:
	adds	r0, r3, #0
	bl sub_080026A78
	b _080026B2C
_080026B26:
	adds	r0, r3, #0
	bl sub_080026AB4
_080026B2C:
	pop	{r0}
	bx	r0
	.type sub_080026B30, %function
sub_080026B30:
_080026B30:
	push	{r4, lr}
	sub	sp, #4
	adds	r1, r0, #0
	ldr r4, _080026B78
	str	r1, [r4, #0]
	movs	r0, #0
	str	r0, [sp, #0]
	ldr r2, _080026B7C
	mov	r0, sp
	bl 0x0802D974
	movs	r0, #12
	bl 0x080261B0
	ldr	r1, [r4, #0]
	strh	r0, [r1, #4]
	movs	r0, #12
	bl 0x080261F8
	ldr	r1, [r4, #0]
	strh	r0, [r1, #8]
	movs	r0, #13
	bl 0x080261B0
	ldr	r1, [r4, #0]
	strh	r0, [r1, #6]
	movs	r0, #13
	bl 0x080261F8
	ldr	r1, [r4, #0]
	strh	r0, [r1, #10]
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080026B78: .4byte 0x03001674
_080026B7C: .4byte 0x0500000F
	.type _080026B80, %function
_080026B80:
	push	{r4, r5, r6, lr}
	adds	r4, r0, #0
	cmp	r4, #8
	bne _080026BA0
	ldr r0, _080026B9C
	ldr	r1, [r0, #0]
	movs	r2, #0
	movs	r0, #1
	strh	r0, [r1, #2]
	strh	r2, [r1, #30]
	strh	r2, [r1, #12]
	strh	r2, [r1, #50]
	strh	r2, [r1, #32]
	b _080026C6C
_080026B9C: .4byte 0x03001674
_080026BA0:
	ldr r2, _080026C74
	ldr	r5, [r2, #0]
	movs	r0, #0
	strh	r0, [r5, #2]
	movs	r0, #0
	ldrsh	r1, [r5, r0]
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #2
	adds	r1, r5, r0
	movs	r3, #30
	ldrsh	r0, [r1, r3]
	adds	r6, r2, #0
	cmp	r0, #0
	beq _080026BD0
	movs	r0, #12
	strh	r0, [r1, #12]
	movs	r1, #0
	movs	r2, #0
	ldrsh	r0, [r5, r2]
	cmp	r0, #0
	bne _080026BCE
	movs	r1, #1
_080026BCE:
	strh	r1, [r5, #0]
_080026BD0:
	ldr	r3, [r6, #0]
	movs	r0, #0
	ldrsh	r1, [r3, r0]
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #2
	adds	r0, r3, r0
	movs	r1, #1
	strh	r1, [r0, #30]
	movs	r2, #0
	ldrsh	r1, [r3, r2]
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #2
	adds	r0, r3, r0
	movs	r1, #120
	strh	r1, [r0, #12]
	movs	r0, #0
	ldrsh	r1, [r3, r0]
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #2
	adds	r0, r3, r0
	strh	r4, [r0, #18]
	movs	r0, #0
	ldrsh	r2, [r3, r0]
	lsls	r1, r2, #2
	adds	r1, r1, r2
	lsls	r1, r1, #2
	adds	r1, r3, r1
	lsls	r2, r2, #1
	adds	r0, r3, #4
	adds	r0, r0, r2
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #20]
	movs	r0, #0
	ldrsh	r2, [r3, r0]
	lsls	r1, r2, #2
	adds	r1, r1, r2
	lsls	r1, r1, #2
	adds	r1, r3, r1
	lsls	r2, r2, #1
	adds	r0, r3, #0
	adds	r0, #8
	adds	r0, r0, r2
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #22]
	ldr r5, _080026C78
	ldr r0, _080026C7C
	lsls	r4, r4, #2
	adds	r0, r4, r0
	ldr	r1, [r0, #0]
	movs	r0, #0
	ldrsh	r2, [r3, r0]
	lsls	r0, r2, #2
	adds	r0, r0, r2
_080026C40:
	lsls	r0, r0, #2
	adds	r3, r3, r0
	movs	r0, #20
	ldrsh	r2, [r3, r0]
	adds	r0, r5, #0
	bl 0x08007538
	ldr r0, _080026C80
	adds	r4, r4, r0
	ldr	r1, [r4, #0]
	ldr	r2, [r6, #0]
	movs	r0, #0
	ldrsh	r3, [r2, r0]
	lsls	r0, r3, #2
	adds	r0, r0, r3
	lsls	r0, r0, #2
	adds	r2, r2, r0
	movs	r3, #22
	ldrsh	r2, [r2, r3]
	adds	r0, r5, #0
	bl 0x080075E8
_080026C6C:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080026C74: .4byte 0x03001674
_080026C78: .4byte 0x083A2100
_080026C7C: .4byte 0x080CDAE0
_080026C80: .4byte 0x080CDB2C
	.type sub_080026C84, %function
sub_080026C84:
_080026C84:
	push	{r4, r5, lr}
	sub	sp, #16
	ldr	r5, [sp, #28]
	lsls	r2, r2, #16
	asrs	r2, r2, #16
	lsls	r3, r3, #16
	asrs	r3, r3, #16
	movs	r4, #0
	str	r4, [sp, #0]
	movs	r4, #2
	str	r4, [sp, #4]
	adds	r4, #254
	str	r4, [sp, #8]
	str	r5, [sp, #12]
	bl 0x08003004
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_080026CAC, %function
sub_080026CAC:
_080026CAC:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #12
	mov	r9, r0
	adds	r7, r1, #0
	adds	r5, r2, #0
	adds	r4, r3, #0
	lsls	r4, r4, #16
	lsrs	r4, r4, #16
	ldr r6, _080026D44
	lsls	r5, r5, #16
	asrs	r5, r5, #16
	adds	r0, r6, #0
	movs	r1, #23
	adds	r2, r5, #0
	bl 0x08007538
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	adds	r0, r6, #0
	movs	r1, #9
_080026CDC:
	adds	r2, r4, #0
	bl 0x080075E8
	movs	r0, #0
	mov	r8, r0
	str	r0, [sp, #0]
	movs	r1, #6
	mov	sl, r1
	str	r1, [sp, #4]
	movs	r6, #1
	str	r6, [sp, #8]
	mov	r0, r9
	adds	r1, r7, #0
	adds	r2, r5, #0
	adds	r3, r4, #0
	bl 0x08002DB8
	mov	r0, r9
	adds	r0, #32
	adds	r2, r5, #0
	adds	r2, #8
	mov	r1, r8
	str	r1, [sp, #0]
	mov	r1, sl
	str	r1, [sp, #4]
	str	r6, [sp, #8]
	adds	r1, r7, #0
	adds	r3, r4, #0
	bl 0x08002DB8
	movs	r0, #64
	add	r9, r0
	adds	r5, #16
	mov	r1, r8
	str	r1, [sp, #0]
	movs	r0, #8
	str	r0, [sp, #4]
	str	r6, [sp, #8]
	mov	r0, r9
	adds	r1, r7, #0
	adds	r2, r5, #0
	adds	r3, r4, #0
	bl 0x08002DB8
	add	sp, #12
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080026D44: .4byte 0x083A2100
	.type _080026D48, %function
_080026D48:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #4
	ldr r6, _080026D70
	ldr	r3, [r6, #0]
	movs	r1, #2
	ldrsh	r0, [r3, r1]
	cmp	r0, #0
	beq _080026D74
	movs	r4, #4
	ldrsh	r2, [r3, r4]
	movs	r5, #8
	ldrsh	r3, [r3, r5]
	movs	r0, #84
	movs	r1, #28
	bl sub_080026CAC
	ldr	r1, [r6, #0]
	movs	r0, #0
	strh	r0, [r1, #2]
	b _080026F20
_080026D70: .4byte 0x03001674
_080026D74:
	movs	r7, #30
	ldrsh	r0, [r3, r7]
	cmp	r0, #0
	bne _080026D7E
	b _080026EA0
_080026D7E:
	movs	r1, #50
	ldrsh	r0, [r3, r1]
	cmp	r0, #0
	bne _080026D88
	b _080026EA0
_080026D88:
	movs	r2, #0
	ldrsh	r0, [r3, r2]
	movs	r1, #0
	cmp	r0, #0
	bne _080026D94
	movs	r1, #20
_080026D94:
	adds	r0, r3, r1
	movs	r4, #12
	ldrsh	r0, [r0, r4]
	cmp	r0, #0
	ble _080026E72
	movs	r5, #0
	ldrsh	r0, [r3, r5]
	lsls	r1, r0, #2
	adds	r1, r1, r0
	lsls	r1, r1, #2
	adds	r1, r3, r1
	ldrh	r0, [r1, #12]
	subs	r0, #1
	strh	r0, [r1, #12]
	movs	r7, #0
	ldrsh	r0, [r3, r7]
	movs	r1, #0
	cmp	r0, #0
	bne _080026DBC
	movs	r1, #20
_080026DBC:
	adds	r2, r3, r1
	movs	r1, #0
	cmp	r0, #0
	bne _080026DC6
	movs	r1, #20
_080026DC6:
	adds	r0, r3, r1
	ldrh	r0, [r0, #12]
	subs	r0, #1
	strh	r0, [r2, #12]
	movs	r0, #0
	ldrsh	r1, [r3, r0]
	movs	r0, #0
	cmp	r1, #0
	bne _080026DDA
	movs	r0, #20
_080026DDA:
	adds	r0, r3, r0
	movs	r2, #12
	ldrsh	r0, [r0, r2]
	adds	r5, r0, #0
	adds	r5, #12
	movs	r0, #0
	cmp	r1, #0
	bne _080026DEC
	movs	r0, #20
_080026DEC:
	adds	r0, r3, r0
	movs	r4, #20
	ldrsh	r2, [r0, r4]
	movs	r0, #0
	cmp	r1, #0
	bne _080026DFA
	movs	r0, #20
_080026DFA:
	adds	r0, r3, r0
	movs	r7, #22
	ldrsh	r4, [r0, r7]
	movs	r0, #0
	cmp	r1, #0
	bne _080026E08
	movs	r0, #20
_080026E08:
	adds	r0, r3, r0
	movs	r3, #12
	ldrsh	r1, [r0, r3]
	movs	r0, #12
	subs	r0, r0, r1
	lsls	r0, r0, #4
	movs	r7, #128
	lsls	r7, r7, #1
	adds	r0, r0, r7
	str	r0, [sp, #0]
	movs	r0, #104
	adds	r1, r5, #0
	adds	r3, r4, #0
	bl sub_080026C84
	ldr	r2, [r6, #0]
	movs	r4, #0
	ldrsh	r3, [r2, r4]
	movs	r0, #0
	cmp	r3, #0
	bne _080026E34
	movs	r0, #20
_080026E34:
	adds	r0, r2, r0
	movs	r5, #12
	ldrsh	r0, [r0, r5]
	adds	r6, r0, #0
	adds	r6, #24
	movs	r0, #0
	ldrsh	r1, [r2, r0]
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #2
	adds	r0, r2, r0
	movs	r1, #20
	ldrsh	r4, [r0, r1]
	movs	r1, #22
	ldrsh	r5, [r0, r1]
	movs	r0, #0
	cmp	r3, #0
	bne _080026E5A
	movs	r0, #20
_080026E5A:
	adds	r0, r2, r0
	movs	r2, #12
	ldrsh	r0, [r0, r2]
	lsls	r0, r0, #4
	adds	r0, r0, r7
	str	r0, [sp, #0]
	movs	r0, #104
	adds	r1, r6, #0
	adds	r2, r4, #0
	adds	r3, r5, #0
	bl sub_080026C84
_080026E72:
	ldr r0, _080026E9C
	ldr	r1, [r0, #0]
	movs	r4, #0
	ldrsh	r3, [r1, r4]
	movs	r0, #0
	cmp	r3, #0
	bne _080026E82
	movs	r0, #20
_080026E82:
	adds	r0, r1, r0
	movs	r5, #12
	ldrsh	r2, [r0, r5]
	cmp	r2, #0
	bne _080026F20
	movs	r0, #0
	cmp	r3, #0
	bne _080026E94
	movs	r0, #20
_080026E94:
	adds	r0, r1, r0
	strh	r2, [r0, #30]
	b _080026F20
	movs	r0, r0
_080026E9C: .4byte 0x03001674
_080026EA0:
	ldr r4, _080026F28
	ldr	r2, [r4, #0]
	movs	r7, #0
	ldrsh	r0, [r2, r7]
	lsls	r1, r0, #2
	adds	r1, r1, r0
	lsls	r1, r1, #2
	adds	r1, r2, r1
	ldrh	r3, [r1, #12]
	movs	r5, #12
	ldrsh	r0, [r1, r5]
	cmp	r0, #0
	ble _080026F06
	subs	r0, r3, #1
	strh	r0, [r1, #12]
	movs	r7, #0
	ldrsh	r1, [r2, r7]
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #2
	adds	r1, r2, r0
	movs	r2, #12
	ldrsh	r0, [r1, r2]
	cmp	r0, #80
	ble _080026EE2
	movs	r1, #10
	bl 0x0802D978
	movs	r1, #2
	bl 0x0802D97C
	cmp	r0, #0
	beq _080026F06
_080026EE2:
	ldr	r1, [r4, #0]
	movs	r4, #0
	ldrsh	r2, [r1, r4]
	lsls	r0, r2, #2
	adds	r0, r0, r2
	lsls	r0, r0, #2
	adds	r1, r1, r0
	movs	r5, #20
	ldrsh	r2, [r1, r5]
	movs	r7, #22
	ldrsh	r3, [r1, r7]
	movs	r0, #128
	lsls	r0, r0, #1
	str	r0, [sp, #0]
	movs	r0, #104
	movs	r1, #24
	bl sub_080026C84
_080026F06:
	ldr r0, _080026F28
	ldr	r2, [r0, #0]
	movs	r0, #0
	ldrsh	r1, [r2, r0]
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #2
	adds	r2, r2, r0
	movs	r1, #12
	ldrsh	r0, [r2, r1]
	cmp	r0, #0
	bne _080026F20
	strh	r0, [r2, #30]
_080026F20:
	add	sp, #4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080026F28: .4byte 0x03001674
	bx	lr
	.hword 0x0000
