@ GT Advance 3 - converted span
@ Region: file offset 0x0026F8-0x002730 (VMA 0x080026F8-0x08002730).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type _080026F8, %function
_080026F8:
	ldr r2, _0800270C
	lsls	r1, r1, #1
	lsls	r0, r0, #3
	adds	r1, r1, r0
	ldr r0, _08002710
	adds	r2, r2, r0
	adds	r1, r1, r2
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	bx	lr
_0800270C: .4byte 0x03001780
_08002710: .4byte 0x0000108C
	.type sub_08002714, %function
sub_08002714:
_08002714:
	ldr r3, _08002728
	lsls	r1, r1, #1
	lsls	r0, r0, #3
	adds	r1, r1, r0
	ldr r0, _0800272C
	adds	r3, r3, r0
	adds	r1, r1, r3
	strh	r2, [r1, #0]
	bx	lr
	movs	r0, r0
_08002728: .4byte 0x03001780
_0800272C: .4byte 0x0000109C

code_26f8_end:
