@ GT Advance 3 - converted span
@ Region: file offset 0x002694-0x0026F8 (VMA 0x08002694-0x080026F8).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08002694, %function
sub_08002694:
_08002694:
	push	{r4, lr}
	sub	sp, #4
	movs	r0, #0
	str	r0, [sp, #0]
	ldr r4, _080026CC
	ldr r2, _080026D0
	mov	r0, sp
	adds	r1, r4, #0
	bl 0x0802D974
	movs	r0, #188
	lsls	r0, r0, #3
	adds	r4, r4, r0
	movs	r0, #1
	strh	r0, [r4, #0]
	ldr r0, _080026D4
	ldr r1, _080026D8
	movs	r2, #160
	lsls	r2, r2, #4
	bl 0x0802407C
	bl 0x08024568
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080026CC: .4byte 0x03001780
_080026D0: .4byte 0x0500078D
_080026D4: .4byte 0x0203D600
_080026D8: .4byte 0x0203CC00
	.type sub_080026DC, %function
sub_080026DC:
_080026DC:
	ldr r3, _080026F0
	lsls	r1, r1, #1
	lsls	r0, r0, #3
	adds	r1, r1, r0
	ldr r0, _080026F4
	adds	r3, r3, r0
	adds	r1, r1, r3
	strh	r2, [r1, #0]
	bx	lr
	movs	r0, r0
_080026F0: .4byte 0x03001780
_080026F4: .4byte 0x0000108C

code_2694_end:
