@ GT Advance 3 - converted span
@ Region: file offset 0x004D4C-0x004E6C (VMA 0x08004D4C-0x08004E6C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08004D4C, %function
sub_08004D4C:
_08004D4C:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	adds	r6, r0, #0
	adds	r7, r1, #0
	mov	r8, r2
	ldr r5, _08004DC4
	ldr	r0, [r5, #8]
	ldr	r1, [r0, #76]
	cmp	r1, #0
	beq _08004D70
	ldr	r0, [r1, #0]
	ldr	r3, [r1, #4]
	ldr	r4, [r0, #0]
	adds	r0, r6, #0
	adds	r1, r7, #0
	bl 0x0802DDD8
_08004D70:
	ldr	r0, [r5, #8]
	ldr	r1, [r0, #80]
	ldr	r3, [r0, #84]
	ldr	r4, [r1, #4]
	adds	r0, r6, #0
	adds	r1, r7, #0
	mov	r2, r8
	bl 0x0802DDD8
	ldr	r0, [r5, #8]
	ldr	r5, [r0, #88]
	cmp	r5, #0
	beq _08004DA0
_08004D8A:
	ldr	r0, [r5, #4]
	ldr	r3, [r5, #8]
	ldr	r4, [r0, #0]
	adds	r0, r6, #0
	adds	r1, r7, #0
	mov	r2, r8
	bl 0x0802DDD8
	ldr	r5, [r5, #0]
	cmp	r5, #0
	bne _08004D8A
_08004DA0:
	ldr r0, _08004DC4
	ldr	r0, [r0, #8]
	ldr	r1, [r0, #92]
	cmp	r1, #0
	beq _08004DBA
	ldr	r0, [r1, #4]
	ldr	r3, [r1, #8]
	ldr	r4, [r0, #0]
	adds	r0, r6, #0
	adds	r1, r7, #0
	mov	r2, r8
	bl 0x0802DDD8
_08004DBA:
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08004DC4: .4byte 0x03000198
	.type sub_08004DC8, %function
sub_08004DC8:
_08004DC8:
	push	{r4, r5, lr}
	adds	r4, r0, #0
	movs	r0, #12
	bl 0x080049AC
	adds	r5, r0, #0
	str	r4, [r5, #4]
	ldr	r0, [r4, #4]
	cmp	r0, #0
	beq _08004DE2
	bl 0x080049AC
	str	r0, [r5, #8]
_08004DE2:
	adds	r0, r5, #0
	pop	{r4, r5}
	pop	{r1}
	bx	r1
	movs	r0, r0
@ Entry label for the anonymous leaf at 0x08004DEC. The inventory admits a bare
@ label only on `.type %function` or an inbound `bl`; without it this body is
@ invisible, so `_08004DC8`'s span ran through it and its 36-byte body could
@ never score above PARTIAL. Zero bytes emitted.
	.type _08004DEC, %function
_08004DEC:
	str	r1, [r0, #4]
	str	r2, [r0, #8]
	bx	lr
	movs	r0, r0
	.type sub_08004DF4, %function
sub_08004DF4:
_08004DF4:
	push	{r4, lr}
	adds	r4, r0, #0
	bl 0x08004B68
	ldr	r1, [r0, #88]
	str	r1, [r4, #0]
	str	r4, [r0, #88]
	adds	r0, r4, #0
	pop	{r4}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_08004E0C, %function
sub_08004E0C:
_08004E0C:
	push	{lr}
	bl sub_08004DC8
	bl sub_08004DF4
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_08004E1C, %function
sub_08004E1C:
_08004E1C:
	push	{r4, lr}
	adds	r4, r0, #0
	movs	r0, #1
	bl 0x08004E78
	ldr r0, _08004E3C
	ldr	r0, [r0, #8]
	strh	r4, [r0, #10]
	movs	r0, #13
	adds	r1, r4, #0
	movs	r2, #0
	bl sub_08004D4C
	pop	{r4}
	pop	{r0}
	bx	r0
_08004E3C: .4byte 0x03000198
	.type _08004E40, %function
_08004E40:
	push	{r4, r5, lr}
	adds	r4, r0, #0
	movs	r0, #2
	bl 0x08004E78
	ldr r5, _08004E68
	ldr	r0, [r5, #8]
	strh	r4, [r0, #10]
	movs	r0, #14
	adds	r1, r4, #0
	movs	r2, #0
	bl sub_08004D4C
	ldr	r0, [r5, #8]
	bl 0x08004B90
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08004E68: .4byte 0x03000198
code_4d4c_end:
