@ GT Advance 3 - converted span
@ Region: file offset 0x0240D0-0x024138 (VMA 0x080240D0-0x08024138).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

@ 0x080240D0's entry marker, moved here from asm/passthrough.inc (zero bytes).
@ It must sit in the file that also spells the span's END (`_080240DC:`): with
@ the marker in the aggregator, the splicer's end marker lived in a different
@ file and 0x080240d0 could not be bounded -- "no end marker in passthrough.inc
@ and no passthrough_end: to fall back on". The spelling is unchanged, so
@ `asm/saveblock.s: bl sub_080240D0` still resolves and the `.type` line that
@ was deleted with it was never what made 0x080240d0 a known start.
@ No `.type` line here on purpose: `pick_marker` prefers it, and splicing
@ 0x080240d0 would then delete the marker 0x080240dc's own entry needs.
sub_080240D0:
	ldr r0, _0800240D8
	ldr	r0, [r0, #8]
	bx	lr
	movs	r0, r0
_0800240D8: .4byte 0x03000610
@ Function entry: leaf whose pool word (`_0800240E8`) sits directly above it,
@ with no label of its own -- same shape as _080240EC and _080240F8 below, and
@ no `bl` to 0x080240DC anywhere in the closure, so `.type %function` is the
@ only thing that admits it. Without it, _080240D0's span ran through this
@ whole body and it could never score EXACT. Zero bytes emitted.
	.type _080240DC, %function
_080240DC:
	ldr r0, _0800240E8
	ldr	r1, [r0, #4]
	movs	r0, #0
	strh	r0, [r1, #0]
	bx	lr
	movs	r0, r0
_0800240E8: .4byte 0x03000610
@ A FUNCTION ENTRY, and the only label it lacks. The `.4byte` above is this
@ leaf's own POOL WORD, not the body: the code begins 4 bytes after it and
@ falls straight through with no label of its own. The converted listing
@ emitted the data label and dropped the entry, so the screen found no
@ closure owner and refused the body as 'no closure owner'. (deleted: asm/ghost2.s)
@ does carry these four labels, but it is an ORPHAN -- nothing includes it,
@ and adding it to the closure would double-define the region. Confirmed as
@ code, not data, by disassembling baserom.gba at this VMA.
_080240EC:
	ldr r1, _0800240F4
	ldr	r1, [r1, #4]
	str	r0, [r1, #8]
	bx	lr
_0800240F4: .4byte 0x03000610
@ A FUNCTION ENTRY, and the only label it lacks. The `.4byte` above is this
@ leaf's own POOL WORD, not the body: the code begins 4 bytes after it and
@ falls straight through with no label of its own. The converted listing
@ emitted the data label and dropped the entry, so the screen found no
@ closure owner and refused the body as 'no closure owner'. (deleted: asm/ghost2.s)
@ does carry these four labels, but it is an ORPHAN -- nothing includes it,
@ and adding it to the closure would double-define the region. Confirmed as
@ code, not data, by disassembling baserom.gba at this VMA.
_080240F8:
	ldr r1, _080024100
	ldr	r1, [r1, #4]
	str	r0, [r1, #4]
	bx	lr
_080024100: .4byte 0x03000610
@ Function entry: another leaf whose pool word (`_080024100`) sits directly
@ above it, with no label of its own. Labelled so the body at 0x080240F8 has a
@ textual end marker for its span; without one the splicer cannot bound the
@ replacement and refuses it.
_08024104:
	ldr r1, _08002410C
	ldr	r1, [r1, #4]
	strh	r0, [r1, #2]
	bx	lr
_08002410C: .4byte 0x03000610
_08024110:
	push	{r4, lr}
	ldr r1, _080024128
	ldr	r1, [r1, #4]
	adds	r1, #16
	ldmia	r0!, {r2, r3, r4}
	stmia	r1!, {r2, r3, r4}
	ldr	r0, [r0, #0]
	str	r0, [r1, #0]
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080024128: .4byte 0x03000610
@ A FUNCTION ENTRY, and the only label it lacks. The `.4byte` above is this
@ leaf's own POOL WORD, not the body: the code begins 4 bytes after it and
@ falls straight through with no label of its own. The converted listing
@ emitted the data label and dropped the entry, so the screen found no
@ closure owner and refused the body as 'no closure owner'. (deleted: asm/ghost2.s)
@ does carry these four labels, but it is an ORPHAN -- nothing includes it,
@ and adding it to the closure would double-define the region. Confirmed as
@ code, not data, by disassembling baserom.gba at this VMA.
_0802412C:
	ldr r1, _080024134
	movs	r0, #0
	str	r0, [r1, #0]
	bx	lr
_080024134: .4byte 0x03000610

@ End-of-region anchor for the splicer. This file declares exactly one
@ `@ Region:` (0x080240d0-0x08024138) and has no `.include`; the promoted body at
@ 0x0802412C ends on 0x08024138, exactly that boundary. Unambiguous, so the anchor is
@ safe. Without it the body is refused as 'no end marker'.
code_240d0_end:
