@ GT Advance 3 - converted span
@ Region: file offset 0x022D20-0x0235F4 (VMA 0x08022D20-0x080235F4).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080022D20, %function
sub_080022D20:
_080022D20:
	bx	lr
	movs	r0, r0
	.type sub_080022D24, %function
sub_080022D24:
_080022D24:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	adds	r4, r1, #0
	adds	r1, r2, #0
	adds	r0, r4, #0
	bl 0x08025C60
	ldr	r0, [r5, #12]
	ldr	r1, [r4, #24]
	ldr	r2, [r4, #20]
	bl 0x08007ABC
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080022D44, %function
sub_080022D44:
_080022D44:
	push	{r4, r5, lr}
	sub	sp, #20
	adds	r0, #8
	ldr	r4, [r1, #20]
	ldr	r5, [r1, #24]
	ldr	r3, [r1, #4]
	ldr	r1, [r1, #8]
	adds	r2, r2, r1
	str	r2, [sp, #0]
	movs	r1, #6
	str	r1, [sp, #4]
	movs	r1, #1
	str	r1, [sp, #8]
	movs	r1, #0
	str	r1, [sp, #12]
	str	r1, [sp, #16]
	adds	r1, r4, #0
	adds	r2, r5, #0
	bl 0x08007C68
	add	sp, #20
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_080022D74, %function
sub_080022D74:
_080022D74:
	push	{r4, lr}
	adds	r3, r0, #0
	adds	r4, r1, #0
	ldr	r1, [r3, #0]
	ldr	r0, [r4, #0]
	cmp	r1, r0
	bne _080022DA0
	ldr	r0, [r3, #8]
	ldr r2, _080022D9C
	ands	r0, r2
	ldr	r1, [r4, #8]
	ands	r1, r2
	cmp	r0, r1
	bne _080022DA0
	ldrh	r3, [r3, #4]
	ldrh	r4, [r4, #4]
	cmp	r3, r4
	bne _080022DA0
	movs	r0, #1
	b _080022DA2
_080022D9C: .4byte 0x00FFFFFF
_080022DA0:
	movs	r0, #0
_080022DA2:
	pop	{r4}
	pop	{r1}
	bx	r1
	.type sub_080022DA8, %function
sub_080022DA8:
_080022DA8:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #428
	adds	r1, r0, #0
	adds	r1, #152
	ldr	r1, [r1, #0]
	str	r1, [sp, #340]
	adds	r0, #148
	ldr	r0, [r0, #0]
	str	r0, [sp, #344]
	movs	r0, #0
	str	r0, [sp, #336]
	mov	r1, sp
	adds	r1, #60
	str	r1, [sp, #380]
	mov	r2, sp
	adds	r2, #120
	str	r2, [sp, #384]
	mov	r3, sp
	adds	r3, #132
	str	r3, [sp, #388]
	mov	r4, sp
	adds	r4, #156
	str	r4, [sp, #396]
	mov	r5, sp
	adds	r5, #216
	str	r5, [sp, #376]
	mov	r6, sp
	adds	r6, #144
	str	r6, [sp, #392]
_080022DEA:
	ldr	r7, [sp, #336]
	lsls	r7, r7, #3
	str	r7, [sp, #372]
	ldr	r0, [sp, #336]
	adds	r0, #1
	str	r0, [sp, #404]
	ldr	r3, [sp, #380]
	mov	r2, sp
	movs	r4, #4
_080022DFC:
	adds	r1, r2, #0
	ldr	r0, [sp, #340]
	ldmia	r0!, {r5, r6, r7}
	stmia	r1!, {r5, r6, r7}
	adds	r1, r3, #0
	ldr	r0, [sp, #344]
	ldmia	r0!, {r5, r6, r7}
	stmia	r1!, {r5, r6, r7}
	ldr	r0, [sp, #340]
	adds	r0, #12
	str	r0, [sp, #340]
	ldr	r1, [sp, #344]
	adds	r1, #12
	str	r1, [sp, #344]
	adds	r3, #12
	adds	r2, #12
	subs	r4, #1
	cmp	r4, #0
	bge _080022DFC
	ldr	r1, [sp, #384]
	ldmia	r0!, {r2, r3, r4}
	stmia	r1!, {r2, r3, r4}
	ldr	r1, [sp, #388]
	ldr	r0, [sp, #344]
	ldmia	r0!, {r5, r6, r7}
	stmia	r1!, {r5, r6, r7}
	ldr	r0, [sp, #340]
	adds	r0, #12
	str	r0, [sp, #340]
	ldr	r1, [sp, #344]
	adds	r1, #12
	str	r1, [sp, #344]
	mov	r8, sp
	ldr	r2, [sp, #376]
	mov	r9, r2
	ldr	r3, [sp, #380]
	ldr	r2, [sp, #396]
	movs	r5, #4
_080022E48:
	adds	r1, r2, #0
	adds	r0, r3, #0
	ldmia	r0!, {r4, r6, r7}
	stmia	r1!, {r4, r6, r7}
	mov	r1, r9
	mov	r0, r8
	ldmia	r0!, {r4, r6, r7}
	stmia	r1!, {r4, r6, r7}
	movs	r0, #12
	add	r8, r0
	add	r9, r0
	adds	r3, #12
	adds	r2, #12
	subs	r5, #1
	cmp	r5, #0
	bge _080022E48
	ldr	r1, [sp, #336]
	cmp	r1, #31
	ble _080022E70
	b _080022F90
_080022E70:
	movs	r2, #0
	mov	r8, r2
_080022E74:
	mov	r3, r8
	lsls	r0, r3, #1
	mov	r6, r8
	adds	r6, #1
	add	r0, r8
	lsls	r7, r0, #2
	ldr	r4, [sp, #376]
	movs	r5, #4
_080022E84:
	ldr	r1, [sp, #396]
	adds	r0, r1, r7
	adds	r1, r4, #0
	bl sub_080022D74
	lsls	r0, r0, #24
	cmp	r0, #0
	beq _080022E98
	ldr r0, _080022F8C
	str	r0, [r4, #0]
_080022E98:
	adds	r4, #12
	subs	r5, #1
	cmp	r5, #0
	bge _080022E84
	mov	r8, r6
	cmp	r6, #4
	ble _080022E74
	movs	r7, #0
	movs	r2, #0
	str	r2, [sp, #348]
	mov	r8, r2
	ldr	r3, [sp, #120]
	str	r3, [sp, #400]
	ldr	r4, [sp, #376]
	mov	r9, r4
	movs	r5, #0
	str	r5, [sp, #420]
	movs	r6, #138
	lsls	r6, r6, #1
	add	r6, sp
	str	r6, [sp, #424]
	str	r4, [sp, #356]
	movs	r0, #138
	lsls	r0, r0, #1
	add	r0, sp
	str	r0, [sp, #416]
	mov	ip, r5
_080022ECE:
	mov	r1, r9
	ldr	r0, [r1, #0]
	ldr r2, _080022F8C
	cmp	r0, r2
	beq _080022F48
	ldr	r5, [sp, #348]
	cmp	r5, #4
	bgt _080022F28
	ldr	r3, [sp, #396]
	str	r3, [sp, #352]
	ldr	r4, [sp, #356]
	ldr	r6, [sp, #420]
	adds	r4, r4, r6
	mov	sl, r4
	ldr	r4, [sp, #416]
	add	r4, ip
_080022EEE:
	lsls	r0, r5, #1
	adds	r0, r0, r5
	lsls	r0, r0, #2
	ldr	r1, [sp, #352]
	adds	r2, r1, r0
	ldr	r1, [r2, #0]
	mov	r3, sl
	ldr	r0, [r3, #0]
	adds	r3, r5, #1
	cmp	r1, r0
	bhi _080022F22
	adds	r1, r4, #0
	adds	r0, r2, #0
	ldmia	r0!, {r2, r5, r6}
	stmia	r1!, {r2, r5, r6}
	adds	r4, #12
	ldr	r5, [sp, #424]
	adds	r5, #12
	str	r5, [sp, #424]
	movs	r6, #12
	add	ip, r6
	adds	r7, #1
	str	r3, [sp, #348]
	cmp	r7, #4
	ble _080022F22
	b _0800230A4
_080022F22:
	adds	r5, r3, #0
	cmp	r5, #4
	ble _080022EEE
_080022F28:
	cmp	r7, #4
	ble _080022F2E
	b _0800230A4
_080022F2E:
	ldr	r1, [sp, #424]
	mov	r0, r9
	ldmia	r0!, {r2, r3, r4}
	stmia	r1!, {r2, r3, r4}
	ldr	r5, [sp, #424]
	adds	r5, #12
	str	r5, [sp, #424]
	movs	r6, #12
	add	ip, r6
	adds	r7, #1
	cmp	r7, #4
	ble _080022F48
	b _0800230A4
_080022F48:
	movs	r0, #12
	add	r9, r0
	ldr	r1, [sp, #420]
	adds	r1, #12
	str	r1, [sp, #420]
	movs	r2, #1
	add	r8, r2
	mov	r3, r8
	cmp	r3, #4
	ble _080022ECE
	cmp	r7, #4
	ble _080022F62
	b _0800230A4
_080022F62:
	add	r0, sp, #276
	lsls	r1, r7, #1
	adds	r1, r1, r7
	lsls	r1, r1, #2
	adds	r3, r0, r1
	ldr	r4, [sp, #348]
	lsls	r0, r4, #1
	adds	r0, r0, r4
	lsls	r0, r0, #2
	ldr	r5, [sp, #396]
	adds	r2, r0, r5
_080022F78:
	adds	r1, r3, #0
	adds	r0, r2, #0
	ldmia	r0!, {r4, r5, r6}
	stmia	r1!, {r4, r5, r6}
	adds	r2, #12
	adds	r3, #12
	adds	r7, #1
	cmp	r7, #4
	ble _080022F78
	b _0800230A4
_080022F8C: .4byte 0x001BA61D
_080022F90:
	movs	r6, #0
	mov	r8, r6
_080022F94:
	mov	r7, r8
	lsls	r0, r7, #1
	mov	r6, r8
	adds	r6, #1
	add	r0, r8
	lsls	r7, r0, #2
	ldr	r4, [sp, #376]
	movs	r5, #4
_080022FA4:
	ldr	r1, [sp, #396]
	adds	r0, r1, r7
	adds	r1, r4, #0
	bl sub_080022D74
	lsls	r0, r0, #24
	cmp	r0, #0
	beq _080022FB8
	ldr r0, _0800230B8
	str	r0, [r4, #0]
_080022FB8:
	adds	r4, #12
	subs	r5, #1
	cmp	r5, #0
	bge _080022FA4
	mov	r8, r6
	cmp	r6, #4
	ble _080022F94
	movs	r7, #0
	movs	r2, #0
	str	r2, [sp, #360]
	mov	r8, r2
	ldr	r3, [sp, #120]
	str	r3, [sp, #400]
	ldr	r4, [sp, #376]
	mov	ip, r4
	movs	r5, #0
	str	r5, [sp, #412]
	movs	r6, #138
	lsls	r6, r6, #1
	add	r6, sp
	str	r6, [sp, #424]
	mov	r0, ip
	str	r0, [sp, #368]
	movs	r1, #138
	lsls	r1, r1, #1
	add	r1, sp
	str	r1, [sp, #408]
	mov	r9, r5
_080022FF0:
	mov	r2, ip
	ldr	r0, [r2, #0]
	ldr r3, _0800230B8
	cmp	r0, r3
	beq _080023064
	ldr	r5, [sp, #360]
	cmp	r5, #4
	bgt _080023048
	ldr	r4, [sp, #396]
	str	r4, [sp, #364]
	ldr	r6, [sp, #368]
	ldr	r0, [sp, #412]
	adds	r6, r6, r0
	mov	sl, r6
	ldr	r4, [sp, #408]
	add	r4, r9
_080023010:
	lsls	r0, r5, #1
	adds	r0, r0, r5
	lsls	r0, r0, #2
	ldr	r1, [sp, #364]
	adds	r2, r1, r0
	ldr	r1, [r2, #0]
	mov	r3, sl
	ldr	r0, [r3, #0]
	adds	r3, r5, #1
	cmp	r1, r0
	bcc _080023042
	adds	r1, r4, #0
	adds	r0, r2, #0
	ldmia	r0!, {r2, r5, r6}
	stmia	r1!, {r2, r5, r6}
	adds	r4, #12
	ldr	r5, [sp, #424]
	adds	r5, #12
	str	r5, [sp, #424]
	movs	r6, #12
	add	r9, r6
	adds	r7, #1
	str	r3, [sp, #360]
	cmp	r7, #4
	bgt _0800230A4
_080023042:
	adds	r5, r3, #0
	cmp	r5, #4
	ble _080023010
_080023048:
	cmp	r7, #4
	bgt _0800230A4
	ldr	r1, [sp, #424]
	mov	r0, ip
	ldmia	r0!, {r2, r3, r4}
	stmia	r1!, {r2, r3, r4}
	ldr	r5, [sp, #424]
	adds	r5, #12
	str	r5, [sp, #424]
	movs	r6, #12
	add	r9, r6
	adds	r7, #1
	cmp	r7, #4
	bgt _0800230A4
_080023064:
	movs	r0, #12
	add	ip, r0
	ldr	r1, [sp, #412]
	adds	r1, #12
	str	r1, [sp, #412]
	movs	r2, #1
	add	r8, r2
	mov	r3, r8
	cmp	r3, #4
	ble _080022FF0
	cmp	r7, #4
	bgt _0800230A4
	add	r0, sp, #276
	lsls	r1, r7, #1
	adds	r1, r1, r7
	lsls	r1, r1, #2
	adds	r3, r0, r1
	ldr	r4, [sp, #360]
	lsls	r0, r4, #1
	adds	r0, r0, r4
	lsls	r0, r0, #2
	ldr	r5, [sp, #396]
	adds	r2, r0, r5
_080023092:
	adds	r1, r3, #0
	adds	r0, r2, #0
	ldmia	r0!, {r4, r5, r6}
	stmia	r1!, {r4, r5, r6}
	adds	r2, #12
	adds	r3, #12
	adds	r7, #1
	cmp	r7, #4
	ble _080023092
_0800230A4:
	ldr	r6, [sp, #388]
	ldr	r0, [r6, #0]
	ldr	r7, [sp, #400]
	cmp	r7, r0
	bhi _0800230BC
	ldr	r1, [sp, #392]
	ldr	r0, [sp, #384]
	ldmia	r0!, {r2, r3, r4}
	stmia	r1!, {r2, r3, r4}
	b _0800230C4
_0800230B8: .4byte 0x000003E7
_0800230BC:
	ldr	r1, [sp, #392]
	ldr	r0, [sp, #388]
	ldmia	r0!, {r5, r6, r7}
	stmia	r1!, {r5, r6, r7}
_0800230C4:
	add	r3, sp, #276
	ldr	r2, [sp, #380]
	movs	r5, #4
_0800230CA:
	adds	r1, r2, #0
	adds	r0, r3, #0
	ldmia	r0!, {r4, r6, r7}
	stmia	r1!, {r4, r6, r7}
	adds	r3, #12
	adds	r2, #12
	subs	r5, #1
	cmp	r5, #0
	bge _0800230CA
	ldr	r1, [sp, #384]
	ldr	r0, [sp, #392]
	ldmia	r0!, {r2, r3, r4}
	stmia	r1!, {r2, r3, r4}
	ldr r1, _08002313C
	ldr	r5, [sp, #372]
	ldr	r6, [sp, #336]
	adds	r0, r5, r6
	lsls	r0, r0, #3
	adds	r2, r0, r1
	movs	r3, #0
	movs	r4, #4
_0800230F4:
	ldr r7, _080023140
	adds	r1, r2, r7
	ldr	r5, [sp, #380]
	adds	r0, r5, r3
	ldmia	r0!, {r5, r6, r7}
	stmia	r1!, {r5, r6, r7}
	adds	r2, #12
	adds	r3, #12
	subs	r4, #1
	cmp	r4, #0
	bge _0800230F4
	ldr	r6, [sp, #372]
	ldr	r7, [sp, #336]
	adds	r1, r6, r7
	lsls	r1, r1, #3
	ldr r0, _08002313C
	adds	r1, r1, r0
	movs	r2, #196
	lsls	r2, r2, #3
	adds	r1, r1, r2
	ldr	r0, [sp, #392]
	ldmia	r0!, {r3, r4, r5}
	stmia	r1!, {r3, r4, r5}
	ldr	r6, [sp, #404]
	str	r6, [sp, #336]
	cmp	r6, #34
	bgt _08002312C
	b _080022DEA
_08002312C:
	add	sp, #428
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08002313C: .4byte 0x03001780
_080023140: .4byte 0x000005E4
	.type sub_08023144, %function
sub_08023144:
_08023144:
	bx	lr
	movs	r0, r0
	.type sub_080023148, %function
sub_080023148:
_080023148:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	sub	sp, #4
	adds	r5, r0, #0
	movs	r7, #0
	ldr r0, _0800231A8
	mov	r9, r0
_08002315A:
	lsls	r3, r7, #3
	adds	r1, r7, #1
	mov	r8, r1
	adds	r0, r3, r7
	lsls	r0, r0, #3
	movs	r6, #4
	mov	r1, r9
	adds	r4, r1, r0
_08002316A:
	adds	r0, r4, #0
	adds	r1, r5, #0
	ldr r2, _0800231AC
	str	r3, [sp, #0]
	bl 0x0802D974
	adds	r5, #12
	adds	r4, #12
	subs	r6, #1
	ldr	r3, [sp, #0]
	cmp	r6, #0
	bge _08002316A
	adds	r0, r3, r7
	lsls	r0, r0, #3
	ldr r1, _0800231B0
	adds	r0, r0, r1
	adds	r1, r5, #0
	ldr r2, _0800231AC
	bl 0x0802D974
	adds	r5, #12
	mov	r7, r8
	cmp	r7, #34
	ble _08002315A
	add	sp, #4
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_0800231A8: .4byte 0x03001D64
_0800231AC: .4byte 0x04000003
_0800231B0: .4byte 0x03001DA0
	.type sub_0800231B4, %function
sub_0800231B4:
_0800231B4:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	sub	sp, #4
	adds	r5, r0, #0
	movs	r7, #0
	ldr r0, _080023214
	mov	r9, r0
_0800231C6:
	lsls	r3, r7, #3
	adds	r1, r7, #1
	mov	r8, r1
	adds	r0, r3, r7
	lsls	r0, r0, #3
	movs	r6, #4
	mov	r1, r9
	adds	r4, r1, r0
_0800231D6:
	adds	r0, r5, #0
	adds	r1, r4, #0
	ldr r2, _080023218
	str	r3, [sp, #0]
	bl 0x0802D974
	adds	r5, #12
	adds	r4, #12
	subs	r6, #1
	ldr	r3, [sp, #0]
	cmp	r6, #0
	bge _0800231D6
	adds	r1, r3, r7
	lsls	r1, r1, #3
	ldr r0, _08002321C
	adds	r1, r1, r0
	adds	r0, r5, #0
	ldr r2, _080023218
	bl 0x0802D974
	adds	r5, #12
	mov	r7, r8
	cmp	r7, #34
	ble _0800231C6
	add	sp, #4
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080023214: .4byte 0x03001D64
_080023218: .4byte 0x04000003
_08002321C: .4byte 0x03001DA0
	.type _080023220, %function
_080023220:
	push	{r4, r5, lr}
	sub	sp, #8
	adds	r4, r0, #0
	adds	r0, #156
	movs	r1, #0
	ldrsh	r5, [r0, r1]
	cmp	r5, #0
	bne _08002328E
	ldr r1, _08002326C
	str	r5, [sp, #0]
	movs	r0, #3
	str	r0, [sp, #4]
	movs	r0, #1
	movs	r2, #3
	movs	r3, #0
	bl 0x08007770
	adds	r1, r4, #0
	adds	r1, #176
	adds	r0, r4, #0
	movs	r2, #5
	bl sub_080022D24
	ldr r0, _080023270
	ldr r1, _080023274
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _080023278
	movs	r0, #1
	movs	r1, #1
	bl 0x08002618
	adds	r1, r4, #0
	adds	r1, #144
	movs	r0, #1
	strh	r0, [r1, #0]
	b _080023286
_08002326C: .4byte 0x082B7410
_080023270: .4byte 0x03001780
_080023274: .4byte 0x000010C3
_080023278:
	movs	r0, #1
	movs	r1, #0
	bl 0x08002618
	adds	r0, r4, #0
	adds	r0, #144
	strh	r5, [r0, #0]
_080023286:
	adds	r1, r4, #0
	adds	r1, #156
	movs	r0, #1
	strh	r0, [r1, #0]
_08002328E:
	add	sp, #8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080023298, %function
sub_080023298:
_080023298:
	push	{r4, r5, r6, lr}
	sub	sp, #8
	adds	r6, r0, #0
	adds	r0, #158
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #14
	bls _0800232AA
	b _0800235E8
_0800232AA:
	lsls	r0, r0, #2
	ldr r1, _0800232B4
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
_0800232B4: .4byte 0x080232B8
_0800232B8: .4byte 0x080232F4
_0800232BC: .4byte 0x08023336
_0800232C0: .4byte 0x08023384
_0800232C4: .4byte 0x08023444
_0800232C8: .4byte 0x08023460
_0800232CC: .4byte 0x08023478
_0800232D0: .4byte 0x080234A4
_0800232D4: .4byte 0x080234CA
_0800232D8: .4byte 0x080234F0
_0800232DC: .4byte 0x080235E8
_0800232E0: .4byte 0x08023596
_0800232E4: .4byte 0x080235B2
_0800232E8: .4byte 0x080235E8
_0800232EC: .4byte 0x08023528
_0800232F0: .4byte 0x0802355C
_0800232F4:
	ldr r1, _080023380
	movs	r4, #0
	str	r4, [sp, #0]
	movs	r0, #3
	str	r0, [sp, #4]
	movs	r0, #1
	movs	r2, #1
	movs	r3, #0
	bl 0x08007770
	movs	r0, #1
	movs	r1, #1
	bl 0x08002618
	adds	r0, r6, #0
	adds	r0, #144
	movs	r5, #1
	strh	r5, [r0, #0]
	adds	r0, #20
	strh	r4, [r0, #0]
	adds	r0, #2
	strh	r4, [r0, #0]
	subs	r0, #4
	strh	r4, [r0, #0]
	adds	r1, r6, #0
	adds	r1, #176
	adds	r0, r6, #0
	movs	r2, #8
	bl sub_080022D24
	adds	r0, r6, #0
	adds	r0, #158
	strh	r5, [r0, #0]
_080023336:
	movs	r0, #0
	movs	r1, #5
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #1
	bne _08002335A
	adds	r1, r6, #0
	adds	r1, #176
	adds	r0, r6, #0
	movs	r2, #5
	bl sub_080022D24
	adds	r1, r6, #0
	adds	r1, #158
	movs	r0, #2
	strh	r0, [r1, #0]
_08002335A:
	movs	r0, #0
	movs	r1, #5
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r4, r0, #16
	cmp	r4, #2
	beq _08002336C
	b _0800235E8
_08002336C:
	adds	r1, r6, #0
	adds	r1, #176
	adds	r0, r6, #0
	movs	r2, #5
	bl sub_080022D24
	adds	r0, r6, #0
	adds	r0, #158
	strh	r4, [r0, #0]
	b _0800235E8
_080023380: .4byte 0x082B7410
_080023384:
	ldr r0, _0800233B0
	ldr r1, _0800233B4
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _0800233C4
	movs	r0, #1
	movs	r1, #4
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r2, r0, #16
	cmp	r2, #3
	beq _0800233B8
	cmp	r2, #4
	beq _0800233A6
	b _0800235E8
_0800233A6:
	adds	r0, r6, #0
	adds	r0, #158
	strh	r2, [r0, #0]
	b _0800235E8
	movs	r0, r0
_0800233B0: .4byte 0x03001780
_0800233B4: .4byte 0x000010C3
_0800233B8:
	adds	r0, r6, #0
	adds	r0, #158
	strh	r2, [r0, #0]
	adds	r1, r6, #0
	adds	r1, #176
	b _08002343A
_0800233C4:
	adds	r0, r6, #0
	adds	r0, #164
	adds	r4, r0, #0
	ldrh	r0, [r4, #0]
	cmp	r0, #1
	bne _0800233EA
	movs	r0, #1
	movs	r1, #5
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #1
	bne _0800233EA
	adds	r1, r6, #0
	adds	r1, #158
	movs	r0, #4
	strh	r0, [r1, #0]
	b _0800235E8
_0800233EA:
	ldrh	r1, [r4, #0]
	cmp	r1, #2
	bne _080023416
	movs	r0, #1
	movs	r1, #5
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #2
	beq _080023430
	ldrh	r0, [r4, #0]
	cmp	r0, #2
	bne _080023416
	movs	r0, #1
	movs	r1, #5
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #1
	beq _080023430
_080023416:
	ldrh	r4, [r4, #0]
	cmp	r4, #1
	beq _08002341E
	b _0800235E8
_08002341E:
	movs	r0, #1
	movs	r1, #5
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #2
	beq _080023430
	b _0800235E8
_080023430:
	adds	r1, r6, #0
	adds	r1, #158
	movs	r0, #3
	strh	r0, [r1, #0]
	adds	r1, #18
_08002343A:
	adds	r0, r6, #0
	movs	r2, #16
	bl sub_080022D24
	b _0800235E8
_080023444:
	ldr r0, _080023458
	ldr r1, _08002345C
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	beq _080023452
	b _0800235CC
_080023452:
	movs	r0, #0
	b _0800235CE
	movs	r0, r0
_080023458: .4byte 0x03001780
_08002345C: .4byte 0x000010C3
_080023460:
	ldr r0, _080023470
	ldr r1, _080023474
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne _08002346E
	b _08002358C
_08002346E:
	b _080023578
_080023470: .4byte 0x03001780
_080023474: .4byte 0x000010C3
_080023478:
	adds	r1, r6, #0
	adds	r1, #240
	movs	r0, #0
	str	r0, [r1, #0]
	subs	r1, #64
	adds	r0, r6, #0
	movs	r2, #7
	bl sub_080022D24
	adds	r0, r6, #0
	adds	r0, #148
	ldr	r0, [r0, #0]
	ldr r1, _0800234A0
	bl 0x0800226C
	adds	r1, r6, #0
	adds	r1, #158
	movs	r0, #7
	strh	r0, [r1, #0]
	b _0800235E8
_0800234A0: .4byte 0x000009D8
_0800234A4:
	adds	r1, r6, #0
	adds	r1, #240
	movs	r0, #0
	str	r0, [r1, #0]
	subs	r1, #64
	adds	r0, r6, #0
	movs	r2, #6
	bl sub_080022D24
	adds	r0, r6, #0
	adds	r0, #152
	ldr	r0, [r0, #0]
	bl 0x08002298
	adds	r1, r6, #0
	adds	r1, #158
	movs	r0, #8
	strh	r0, [r1, #0]
	b _0800235E8
_0800234CA:
	bl 0x080022C0
	adds	r1, r0, #0
	cmp	r1, #1
	beq _0800234D6
	b _0800235E8
_0800234D6:
	adds	r0, r6, #0
	adds	r0, #240
	str	r1, [r0, #0]
	subs	r0, #94
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #0
	beq _08002350A
	adds	r1, r6, #0
	adds	r1, #158
	movs	r0, #10
	strh	r0, [r1, #0]
	b _0800235E8
_0800234F0:
	bl 0x080022C0
	adds	r1, r0, #0
	cmp	r1, #1
	bne _0800235E8
	adds	r0, r6, #0
	adds	r0, #240
	str	r1, [r0, #0]
	subs	r0, #94
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #0
	bne _080023514
_08002350A:
	adds	r1, r6, #0
	adds	r1, #158
	movs	r0, #13
	strh	r0, [r1, #0]
	b _0800235E8
_080023514:
	adds	r1, r6, #0
	adds	r1, #158
	movs	r0, #10
	strh	r0, [r1, #0]
	adds	r0, r6, #0
	adds	r0, #152
	ldr	r0, [r0, #0]
	bl sub_0800231B4
	b _0800235E8
_080023528:
	ldr r0, _080023554
	ldr r1, _080023558
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne _080023544
	adds	r0, r6, #0
	bl sub_080022DA8
	adds	r0, r6, #0
	adds	r0, #148
	ldr	r0, [r0, #0]
	bl sub_080023148
_080023544:
	adds	r1, r6, #0
	adds	r1, #146
	movs	r0, #1
	strh	r0, [r1, #0]
	adds	r1, #12
	movs	r0, #14
	strh	r0, [r1, #0]
	b _0800235E8
_080023554: .4byte 0x03001780
_080023558: .4byte 0x000010C3
_08002355C:
	movs	r0, #1
	movs	r1, #4
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #14
	bne _0800235E8
	ldr r0, _080023584
	ldr r1, _080023588
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne _08002358C
_080023578:
	adds	r1, r6, #0
	adds	r1, #158
	movs	r0, #5
	strh	r0, [r1, #0]
	b _0800235E8
	movs	r0, r0
_080023584: .4byte 0x03001780
_080023588: .4byte 0x000010C3
_08002358C:
	adds	r1, r6, #0
	adds	r1, #158
	movs	r0, #6
	strh	r0, [r1, #0]
	b _0800235E8
_080023596:
	adds	r1, r6, #0
	adds	r1, #176
	adds	r0, r6, #0
	movs	r2, #10
	bl sub_080022D24
	adds	r1, r6, #0
	adds	r1, #146
	movs	r0, #0
	strh	r0, [r1, #0]
	adds	r1, #12
	movs	r0, #11
	strh	r0, [r1, #0]
	b _0800235E8
_0800235B2:
	ldr r0, _0800235C4
	ldr r1, _0800235C8
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne _0800235CC
	movs	r0, #0
	b _0800235CE
	movs	r0, r0
_0800235C4: .4byte 0x03001780
_0800235C8: .4byte 0x000010C3
_0800235CC:
	movs	r0, #1
_0800235CE:
	movs	r1, #6
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #1
	bne _0800235E8
	adds	r0, r6, #0
	adds	r0, #142
	movs	r1, #0
	strh	r1, [r0, #0]
	adds	r0, #14
	strh	r1, [r0, #0]
_0800235E8:
	add	sp, #8
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	.type sub_080235F0, %function
sub_080235F0:
_080235F0:
	bx	lr
	.hword 0x0000
code_22d20_end:
