@ GT Advance 3 - converted span
@ Region: file offset 0x002A68-0x002A80 (VMA 0x08002A68-0x08002A80).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08002A68, %function
sub_08002A68:
_08002A68:
	push	{r4, lr}
	movs	r4, #0
_08002A6C:
	adds	r0, r4, #0
	movs	r1, #0
	bl 0x08002A3C
	adds	r4, #1
	cmp	r4, #0
	ble _08002A6C
	pop	{r4}
	pop	{r0}
	bx	r0

@ Region end 0x002A80. The _08002A68 span runs to here exactly and this
@ file has no.include, so the marker bounds it truthfully.
code_2a68_end:
