@ GT Advance 3 - converted span
@ Region: file offset 0x023A34-0x023BD4 (VMA 0x08023A34-0x08023BD4).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080023A34, %function
sub_080023A34:
_080023A34:
	push	{r4, r5, r6, r7, lr}
	adds	r5, r0, #0
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r4, r2, #16
	adds	r6, r5, #0
	adds	r6, #140
	ldr r0, _080023A84
	ldr r2, _080023A88
	adds	r7, r0, r2
	ldrb	r0, [r7, #0]
	cmp	r0, #1
	bne _080023A72
	movs	r0, #0
	bl 0x08002158
	movs	r0, #1
	adds	r1, r4, #0
	bl 0x08002158
	ldrh	r1, [r6, #0]
	movs	r0, #2
	bl 0x08002158
	adds	r0, r5, #0
	adds	r0, #232
	ldrb	r1, [r0, #0]
	movs	r0, #3
	bl 0x08002158
_080023A72:
	ldrb	r0, [r7, #0]
	cmp	r0, #0
	bne _080023A8C
	movs	r0, #1
	movs	r1, #0
	bl 0x08002178
	movs	r0, #1
	b _080023A96
_080023A84: .4byte 0x03001780
_080023A88: .4byte 0x000010C3
_080023A8C:
	movs	r0, #0
	movs	r1, #0
	bl 0x08002178
	movs	r0, #0
_080023A96:
	movs	r1, #1
	bl 0x08002178
	adds	r4, r0, #0
	cmp	r4, #2
	bne _080023ADE
	adds	r0, r5, #0
	adds	r0, #142
	movs	r4, #0
	strh	r4, [r0, #0]
	ldr r0, _080023AC8
	ldr r1, _080023ACC
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _080023AD0
	movs	r0, #1
	movs	r1, #1
	bl 0x08002618
	adds	r1, r5, #0
	adds	r1, #144
	movs	r0, #1
	strh	r0, [r1, #0]
	b _080023ADE
_080023AC8: .4byte 0x03001780
_080023ACC: .4byte 0x000010C3
_080023AD0:
	movs	r0, #1
	movs	r1, #0
	bl 0x08002618
	adds	r0, r5, #0
	adds	r0, #144
	strh	r4, [r0, #0]
_080023ADE:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.type sub_080023AE4, %function
sub_080023AE4:
_080023AE4:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #16
	mov	r8, r0
	adds	r7, r1, #0
	adds	r6, r2, #0
	movs	r5, #1
	movs	r0, #0
	mov	sl, r0
	movs	r4, #0
	movs	r0, #29
	mov	r9, r0
_080023B02:
	cmp	r6, #2
	beq _080023B0C
	cmp	r6, #3
_080023B08: .4byte 0xE01AD00E
_080023B0C:
	movs	r0, #4
	str	r0, [sp, #0]
	str	r5, [sp, #4]
	str	r5, [sp, #8]
	mov	r0, sl
	str	r0, [sp, #12]
	mov	r0, r8
	adds	r0, #52
	movs	r1, #7
	adds	r2, r4, #0
	adds	r3, r7, #0
	bl 0x08007B18
	b _080023B42
_080023B28:
	movs	r0, #5
	str	r0, [sp, #0]
	str	r5, [sp, #4]
	str	r5, [sp, #8]
	mov	r0, sl
	str	r0, [sp, #12]
	mov	r0, r8
	adds	r0, #52
	movs	r1, #7
	adds	r2, r4, #0
	adds	r3, r7, #0
	bl 0x08007B18
_080023B42:
	adds	r4, #8
	movs	r0, #1
	negs	r0, r0
	add	r9, r0
	mov	r0, r9
	cmp	r0, #0
	bge _080023B02
	add	sp, #16
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.type sub_080023B60, %function
sub_080023B60:
_080023B60:
	push	{r4, r5, lr}
	sub	sp, #16
	adds	r3, r0, #0
	adds	r4, r1, #0
	adds	r5, r2, #0
	ldr r1, _080023B8C
	adds	r0, #140
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldrh	r1, [r0, #0]
	adds	r0, r3, #0
	adds	r0, #168
	ldr	r0, [r0, #0]
	cmp	r0, #1
	beq _080023B98
	cmp	r0, #1
	bgt _080023B90
	cmp	r0, #0
	beq _080023BB2
	b _080023BCA
_080023B8C: .4byte 0x080CC190
_080023B90:
	cmp	r0, #2
	beq _080023BB2
	cmp	r0, #3
	bne _080023BCA
_080023B98:
	movs	r0, #5
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	str	r0, [sp, #8]
	movs	r0, #0
	str	r0, [sp, #12]
	adds	r0, r3, #0
	adds	r2, r4, #0
	adds	r3, r5, #0
	bl 0x08007B18
	b _080023BCA
_080023BB2:
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	str	r0, [sp, #8]
	movs	r0, #0
	str	r0, [sp, #12]
	adds	r0, r3, #0
	adds	r2, r4, #0
	adds	r3, r5, #0
	bl 0x08007B18
_080023BCA:
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.hword 0x0000

code_23a34_end:
