@ GT Advance 3 - converted span
@ Region: file offset 0x024150-0x02417C (VMA 0x08024150-0x0802417C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

_080024150:
	movs	r1, #0
	strh	r1, [r0, #0]
	bx	lr
	movs	r0, r0
@ The `.type sub_080024158, %function` line that stood here is GONE, and that
@ is the point: 0x08024150's promoted entry ends its splice at `sub_080024158:`,
@ and `replace_body` deletes everything up to that line EXCLUSIVE -- so it took
@ the `.type` line with it and 0x08024158's own start marker vanished, failing
@ the next splice as "ambiguous source markers". The bare label survives, and it
@ is what `pick_marker` now returns. 0x08024158 is still a known start through
@ `asm/race_scene.s: bl 0x08024158`, which is what the `.type` line only
@ duplicated. Zero bytes emitted.
sub_080024158:
_080024158:
	push	{r4, lr}
	ldr r4, _080024178
	ldr	r1, [r4, #4]
	ldr	r0, [r4, #8]
	str	r0, [r4, #4]
	str	r1, [r4, #8]
	bl _080024150
	ldr	r1, [r4, #8]
	movs	r0, #1
	strh	r0, [r1, #0]
	bl 0x08024138
	pop	{r4}
	pop	{r0}
	bx	r0
_080024178: .4byte 0x03000610

@ End-of-region anchor for the splicer. This file declares exactly one
@ `@ Region:` (0x08024150-0x0802417C) and has no `.include`, and the promoted
@ body at 0x08024158 ends on 0x0802417C, exactly that boundary -- so the anchor
@ is unambiguous and the screen's `end_vma != region end` refusal cannot fire.
@ Without it the body is refused as 'no end marker' and the span, which really
@ does end inside this file, is unstageable. Emits no bytes; `make` stays
@ byte-identical, but `make independent-slice` and `make ownership-map` must be
@ re-run because they pin per-source SHA-256.
code_24150_end:
