@ GT Advance 3 - converted span
@ Region: file offset 0x023BD4-0x023D4C (VMA 0x08023BD4-0x08023D4C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080023BD4, %function
sub_080023BD4:
_080023BD4:
	push	{r4, r5, r6, r7, lr}
	adds	r7, r0, #0
	adds	r0, #136
	movs	r1, #15
	bl 0x0800D97C
	ldr r4, _080023C48
	adds	r5, r7, #0
	adds	r5, #140
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	lsls	r0, r0, #3
	adds	r6, r4, #4
	adds	r0, r0, r6
	ldr	r1, [r0, #0]
	adds	r0, r7, #0
	adds	r0, #168
	ldr	r2, [r0, #0]
	adds	r0, r7, #0
	bl 0x08023AE4
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	lsls	r0, r0, #3
	adds	r4, r0, r4
	ldr	r1, [r4, #0]
	adds	r0, r0, r6
	ldr	r2, [r0, #0]
	adds	r0, r7, #0
	bl 0x08023B60
	adds	r0, r7, #0
	adds	r0, #16
	bl 0x0800DBE8
	ldr r0, _080023C4C
	ldr r1, _080023C50
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _080023C3C
	adds	r0, r7, #0
	adds	r0, #144
	ldrh	r0, [r0, #0]
	cmp	r0, #1
	bne _080023C3C
	adds	r1, r7, #0
	adds	r1, #176
	adds	r0, r7, #0
	movs	r2, #48
	bl 0x08022D44
_080023C3C:
	adds	r0, r7, #0
	bl 0x08023E78
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080023C48: .4byte 0x080CC178
_080023C4C: .4byte 0x03001780
_080023C50: .4byte 0x000010C3
	.type sub_080023C54, %function
sub_080023C54:
_080023C54:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #32
	mov	r9, r0
	adds	r7, r1, #0
	ldr r1, _080023D3C
	add	r0, sp, #20
	movs	r2, #4
	bl 0x0802E0A4
	add	r6, sp, #24
	ldr r1, _080023D40
	adds	r0, r6, #0
	movs	r2, #4
	bl 0x0802E0A4
	cmp	r7, #2
	bne _080023C80
	movs	r7, #0
_080023C80:
	ldr r0, _080023D44
	ldr	r0, [r0, #0]
	cmp	r7, r0
	bne _080023CA2
	ldr r0, _080023D48
	ldr	r0, [r0, #0]
	mov	r5, r9
	adds	r5, #212
	mov	r1, r9
	adds	r1, #224
	str	r1, [sp, #28]
	subs	r1, #16
	movs	r2, #220
	add	r2, r9
	mov	sl, r2
	cmp	r0, #0
	bne _080023CE4
_080023CA2:
	mov	r5, r9
	adds	r5, #212
	lsls	r1, r7, #1
	mov	r0, sp
	adds	r0, r0, r1
	adds	r0, #20
	ldrh	r0, [r0, #0]
	str	r0, [r5, #0]
	mov	r4, r9
	adds	r4, #224
	adds	r1, r6, r1
	ldrh	r0, [r1, #0]
	str	r0, [r4, #0]
	mov	r3, r9
	ldr	r0, [r3, #12]
	ldr	r1, [r5, #0]
	movs	r2, #208
	add	r2, r9
	mov	r8, r2
	ldr	r2, [r2, #0]
	bl 0x08007ABC
	mov	r3, r9
	ldr	r0, [r3, #12]
	ldr	r1, [r4, #0]
	mov	r6, r9
	adds	r6, #220
	ldr	r2, [r6, #0]
	bl 0x08007ABC
	str	r4, [sp, #28]
	mov	r1, r8
	mov	sl, r6
_080023CE4:
	movs	r0, #8
	add	r9, r0
	ldr	r1, [r1, #0]
	ldr	r2, [r5, #0]
	movs	r3, #96
	mov	r8, r3
	str	r3, [sp, #0]
	movs	r6, #6
	str	r6, [sp, #4]
	movs	r5, #1
	str	r5, [sp, #8]
	movs	r4, #0
	str	r4, [sp, #12]
	str	r4, [sp, #16]
	mov	r0, r9
	movs	r3, #168
	bl 0x08007BFC
	mov	r0, sl
	ldr	r1, [r0, #0]
	ldr	r3, [sp, #28]
	ldr	r2, [r3, #0]
	mov	r0, r8
	str	r0, [sp, #0]
	str	r6, [sp, #4]
	str	r5, [sp, #8]
	str	r4, [sp, #12]
	str	r4, [sp, #16]
	mov	r0, r9
	movs	r3, #40
	bl 0x08007BFC
	ldr r0, _080023D44
	str	r7, [r0, #0]
	ldr r0, _080023D48
	str	r5, [r0, #0]
	add	sp, #32
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080023D3C: .4byte 0x0805FC84
_080023D40: .4byte 0x0805FC88
_080023D44: .4byte 0x030005AC
_080023D48: .4byte 0x080CC198
