@ GT Advance 3 - converted span
@ Region: file offset 0x026180-0x0261B0 (VMA 0x08026180-0x080261B0).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080026180, %function
sub_080026180:
_080026180:
	push	{r4, r5, lr}
	adds	r4, r0, #0
	adds	r0, r1, #0
	lsls	r4, r4, #16
	lsrs	r4, r4, #16
	lsls	r0, r0, #16
	lsrs	r5, r0, #16
	asrs	r0, r0, #16
	bl 0x08005758
	ldr r1, _0800261AC
	lsls	r4, r4, #16
	asrs	r4, r4, #13
	adds	r4, r4, r1
	strh	r0, [r4, #0]
	strh	r5, [r4, #2]
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	pop	{r4, r5}
	pop	{r1}
	bx	r1
	movs	r0, r0
_0800261AC: .4byte 0x030015F0

@ Byte-neutral end label for the promoted _080026180 span (0x08026180-0x080261B0).
@ The body runs to end-of-region, so the splice needs an explicit terminator;
@ a bare label emits no bytes and leaves the executable region identical.
code_26180_end:
