@ GT Advance 3 - converted span
@ Region: file offset 0x004B9C-0x004CC4 (VMA 0x08004B9C-0x08004CC4).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

@ Region-start marker. `passthrough.inc` names this address with `sub_08004B9C`,
@ but `owners` prefers a `.s` over a `.inc`, so without a label here the
@ screen resolves the byte owner as `passthrough.inc` -- which names only region
@ starts and therefore can never yield this span's end marker (`_08004BAC:`,
@ line below). A bare label emits zero bytes.
_08004B9C:
	ldr r0, _08004BA8
	ldr	r1, [r0, #8]
	movs	r0, #1
	ldrh	r1, [r1, #4]
	ands	r0, r1
	bx	lr
_08004BA8: .4byte 0x03000198
_08004BAC:
	movs	r1, #1
	ldrh	r2, [r0, #4]
	orrs	r1, r2
	strh	r1, [r0, #4]
	bx	lr
	movs	r0, r0
	.type sub_08004BB8, %function
sub_08004BB8:
_08004BB8:
	push	{lr}
	movs	r1, #0
	strh	r1, [r0, #6]
	bl _08004BAC
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08004BC8, %function
sub_08004BC8:
_08004BC8:
	push	{lr}
	movs	r1, #1
	strh	r1, [r0, #6]
	bl _08004BAC
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08004BD8, %function
sub_08004BD8:
_08004BD8:
	push	{lr}
	bl 0x08004B68
	movs	r1, #2
	strh	r1, [r0, #6]
	bl _08004BAC
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08004BEC, %function
sub_08004BEC:
_08004BEC:
	adds	r1, r0, #0
	movs	r0, #2
	ldrh	r1, [r1, #4]
	ands	r0, r1
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	bx	lr
	movs	r0, r0
	.type sub_08004BFC, %function
sub_08004BFC:
_08004BFC:
	push	{r4, lr}
	adds	r4, r0, #0
	bl 0x08004B68
	str	r4, [r0, #44]
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_08004C0C, %function
sub_08004C0C:
_08004C0C:
	push	{lr}
	bl 0x08004B68
	ldr	r0, [r0, #44]
	pop	{r1}
	bx	r1
	.type sub_08004C18, %function
sub_08004C18:
_08004C18:
	push	{r4, r5, lr}
	adds	r4, r0, #0
	adds	r5, r1, #0
	bl 0x08004B68
	lsls	r4, r4, #2
	adds	r0, #44
	adds	r0, r0, r4
	str	r5, [r0, #0]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_08004C30, %function
sub_08004C30:
_08004C30:
	push	{r4, lr}
	adds	r4, r0, #0
	bl 0x08004B68
	lsls	r4, r4, #2
	adds	r0, #44
	adds	r0, r0, r4
	ldr	r0, [r0, #0]
	pop	{r4}
	pop	{r1}
	bx	r1
	movs	r0, r0
@ Entry label for the anonymous leaf at 0x08004C48 (see code_4d4c.s:91). It is
@ `_08004C30`'s successor; without it `_08004C30`'s span swallowed it plus the
@ two more leaves that follow. Zero bytes emitted.
	.type _08004C48, %function
_08004C48:
	lsls	r1, r1, #16
	ldr r3, _08004C5C
	ldr	r3, [r3, #12]
	lsrs	r1, r1, #15
	lsls	r0, r0, #3
	adds	r0, r0, r3
	adds	r1, r1, r0
	strh	r2, [r1, #0]
	bx	lr
	movs	r0, r0
_08004C5C: .4byte 0x03000198
@ Anonymous grid halfword getter (zero bytes emitted by the label).
	.type _08004C60, %function
_08004C60:
	lsls	r1, r1, #16
	ldr r2, _08004C74
	ldr	r2, [r2, #12]
	lsrs	r1, r1, #15
	lsls	r0, r0, #3
	adds	r0, r0, r2
	adds	r1, r1, r0
	ldrh	r0, [r1, #0]
	bx	lr
	movs	r0, r0
_08004C74: .4byte 0x03000198
@ Anonymous manager word store (+0x94) (zero bytes emitted by the label).
	.type _08004C78, %function
_08004C78:
	ldr r1, _08004C80
	adds	r1, #148
	str	r0, [r1, #0]
	bx	lr
_08004C80: .4byte 0x03000198
	.type _08004C84, %function
_08004C84:
	push	{r4, lr}
	lsls	r0, r0, #16
	ldr r3, _08004CA4
	ldr	r2, [r3, #8]
	movs	r4, #0
	ldrsh	r2, [r2, r4]
	ldr	r3, [r3, #12]
	lsrs	r0, r0, #15
	lsls	r2, r2, #3
	adds	r2, r2, r3
	adds	r0, r0, r2
	strh	r1, [r0, #0]
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08004CA4: .4byte 0x03000198
_08004CA8:
sub_08004CA8:
	lsls	r0, r0, #16
	ldr r2, _08004CC0
	ldr	r1, [r2, #8]
	movs	r3, #0
	ldrsh	r1, [r1, r3]
	ldr	r2, [r2, #12]
	lsrs	r0, r0, #15
	lsls	r1, r1, #3
	adds	r1, r1, r2
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	bx	lr
_08004CC0: .4byte 0x03000198
@ End-of-region anchor for the splicer: this file declares exactly one
@ `@ Region:` (0x004B9C-0x004CC4) and no `.include`, and the body at
@ 0x08004ca8 is 28 bytes, so it ends on 0x08004cc4 -- exactly that boundary,
@ which is where the trailing pool word `_08004CC0` (4 bytes) already sits.
@ Without it promotion_screen refuses the body with "no end marker in
@ code_4b9c.s", even though the body is byte-exact at 28/28.
code_4b9c_end:
