@ GT Advance 3 - converted span
@ Region: file offset 0x0258A8-0x0258B8 (VMA 0x080258A8-0x080258B8).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.thumb
	.type sub_080258A8, %function
sub_080258A8:
_080258A8:
	ldr r1, _0800258B4
	lsls	r0, r0, #1
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bx	lr
_0800258B4: .4byte 0x080CD7D0

code_258a8_end:
