@ GT Advance 3 - converted span
@ Region: file offset 0x0235F4-0x023628 (VMA 0x080235F4-0x08023628).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_0800235F4, %function
sub_0800235F4:
_0800235F4:
	push	{lr}
	adds	r1, r0, #0
	adds	r1, #142
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	cmp	r1, #1
	beq _080023618
	cmp	r1, #1
	bgt _08002360C
	cmp	r1, #0
	beq _080023612
	b _080023622
_08002360C:
	cmp	r1, #2
	beq _08002361E
	b _080023622
_080023612:
	bl 0x08023220
	b _080023622
_080023618:
	bl 0x08023298
	b _080023622
_08002361E:
	bl sub_080235F0
_080023622:
	pop	{r0}
	bx	r0
	.hword 0x0000
code_235f4_end:
