@ GT Advance 3 - converted span
@ Region: file offset 0x02381C-0x023958 (VMA 0x0802381C-0x08023958).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08002381C, %function
sub_08002381C:
_08002381C:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	adds	r5, r0, #0
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r6, r2, #16
	adds	r4, r5, #0
	adds	r4, #140
	ldrh	r0, [r4, #0]
	mov	r8, r0
	ldr r0, _080023880
	ldr r2, _080023884
	adds	r7, r0, r2
	ldrb	r0, [r7, #0]
	cmp	r0, #1
	bne _08002385A
	movs	r0, #0
	bl 0x08002158
	movs	r0, #1
	adds	r1, r6, #0
	bl 0x08002158
	adds	r0, r5, #0
	adds	r0, #162
	ldrh	r1, [r0, #0]
	movs	r0, #6
	bl 0x08002158
_08002385A:
	ldrh	r1, [r4, #0]
	movs	r0, #2
	bl 0x08002158
	adds	r0, r5, #0
	adds	r0, #232
	ldrb	r1, [r0, #0]
	movs	r0, #3
	bl 0x08002158
	ldrb	r0, [r7, #0]
	cmp	r0, #0
	bne _080023888
	movs	r0, #1
	movs	r1, #0
	bl 0x08002178
	movs	r0, #1
	b _080023892
_080023880: .4byte 0x03001780
_080023884: .4byte 0x000010C3
_080023888:
	movs	r0, #0
	movs	r1, #0
	bl 0x08002178
	movs	r0, #0
_080023892:
	movs	r1, #1
	bl 0x08002178
	adds	r6, r0, #0
	cmp	r6, #2
	bne _0800238BE
	movs	r0, #4
	bl 0x0802B368
	movs	r0, #10
	str	r0, [r5, #16]
	movs	r4, #0
	strh	r4, [r5, #20]
	str	r0, [r5, #48]
	str	r4, [r5, #44]
	movs	r0, #1
	movs	r1, #0
	bl 0x08002618
	adds	r0, r5, #0
	adds	r0, #144
	strh	r4, [r0, #0]
_0800238BE:
	adds	r7, r5, #0
	adds	r7, #140
	cmp	r6, #1
	bne _080023914
	movs	r1, #0
	ldrsh	r4, [r7, r1]
	cmp	r4, #1
	beq _080023902
	cmp	r4, #1
	bgt _080023914
	cmp	r4, #0
	bne _080023914
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r5, #0
	adds	r0, #168
	str	r6, [r0, #0]
	strh	r4, [r5, #20]
	subs	r0, #44
	strh	r6, [r0, #0]
	str	r6, [r5, #44]
	movs	r0, #1
	movs	r1, #0
	bl 0x08002618
	adds	r0, r5, #0
	adds	r0, #144
	strh	r4, [r0, #0]
	movs	r2, #0
	ldrsh	r0, [r7, r2]
	bl 0x08004BFC
	b _080023914
_080023902:
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r5, #0
	adds	r0, #142
	movs	r1, #0
	strh	r6, [r0, #0]
	adds	r0, #16
	strh	r1, [r0, #0]
_080023914:
	cmp	r6, #64
	bne _08002391E
	ldrh	r0, [r7, #0]
	subs	r0, #1
	strh	r0, [r7, #0]
_08002391E:
	cmp	r6, #128
	bne _080023928
	ldrh	r0, [r7, #0]
	adds	r0, #1
	strh	r0, [r7, #0]
_080023928:
	adds	r1, r7, #0
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r0, #0
	bge _080023936
	movs	r0, #0
	strh	r0, [r1, #0]
_080023936:
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r0, #1
	ble _080023942
	movs	r0, #1
	strh	r0, [r1, #0]
_080023942:
	ldrh	r7, [r7, #0]
	cmp	r8, r7
	beq _08002394E
	movs	r0, #2
	bl 0x0802B368
_08002394E:
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
