@ GT Advance 3 - converted span
@ Region: file offset 0x004AF4-0x004B50 (VMA 0x08004AF4-0x08004B50).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08004AF4, %function
sub_08004AF4:
_08004AF4:
	push	{r4, r5, lr}
	sub	sp, #4
	adds	r5, r0, #0
	ldrh	r1, [r5, #2]
	lsls	r0, r1, #3
	cmp	r0, #0
	beq _08004B18
	movs	r0, #0
	str	r0, [sp, #0]
	ldr	r1, [r5, #12]
	ldrh	r0, [r5, #2]
	lsls	r2, r0, #1
	movs	r0, #160
	lsls	r0, r0, #19
	orrs	r2, r0
	mov	r0, sp
	bl 0x0802D974
_08004B18:
	ldr r4, _08004B48
	ldr	r0, [r5, #8]
	str	r0, [r4, #0]
	ldr	r0, [r5, #4]
	str	r0, [r4, #4]
	ldr	r0, [r5, #12]
	str	r0, [r4, #12]
	bl 0x08004CC4
	movs	r0, #0
	str	r0, [sp, #0]
	adds	r4, #148
	ldr r2, _08004B4C
	mov	r0, sp
	adds	r1, r4, #0
	bl 0x0802D974
	ldrh	r0, [r5, #0]
	bl 0x08004AA4
	add	sp, #4
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_08004B48: .4byte 0x03000198
_08004B4C: .4byte 0x05000008

@ Byte-neutral end anchor for the splicer. This file declares exactly one
@ `@ Region:` (0x004AF4-0x004B50) and has no `.include`; the body at
@ 0x08004AF4 runs to 0x004B50, exactly that boundary, so the anchor is safe.
@ Without it the body is refused as 'no end marker in code_4af4.s'.
code_4af4_end:
