@ GT Advance 3 - converted span
@ Region: file offset 0x024138-0x024144 (VMA 0x08024138-0x08024144).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	ldr r1, _080024140
	movs	r0, #1
	str	r0, [r1, #0]
	bx	lr
_080024140: .4byte 0x03000610
