@ GT Advance 3 - converted span
@ Region: file offset 0x025264-0x0254E8 (VMA 0x08025264-0x080254E8).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080025264, %function
sub_080025264:
_080025264:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #216
	adds	r4, r0, #0
	lsls	r4, r4, #16
	lsrs	r4, r4, #16
	mov	r0, sp
	movs	r1, #0
	movs	r2, #196
	bl 0x0802E104
	add	r5, sp, #196
	adds	r0, r5, #0
	movs	r1, #0
	movs	r2, #16
	bl 0x0802E104
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	adds	r0, r4, #0
	bl 0x08024E54
	adds	r6, r0, #0
	movs	r7, #0
	ldrh	r1, [r6, #0]
	movs	r2, #0
	ldrsh	r0, [r6, r2]
	movs	r2, #1
	negs	r2, r2
	cmp	r0, r2
	beq _0800252FA
	adds	r4, r2, #0
_0800252AA:
	lsls	r0, r1, #16
	asrs	r0, r0, #16
	cmp	r0, #86
	beq _0800252EE
	cmp	r0, #56
	beq _0800252EE
	cmp	r0, #55
	beq _0800252EE
	cmp	r0, #31
	beq _0800252EE
	cmp	r0, #14
	beq _0800252EE
	cmp	r0, #98
	beq _0800252EE
	cmp	r0, #54
	beq _0800252EE
	movs	r3, #0
	ldrsh	r0, [r6, r3]
	bl 0x080022E4
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, r4
	beq _0800252EE
	lsls	r0, r7, #16
	asrs	r0, r0, #16
	lsls	r1, r0, #1
	mov	r3, sp
	adds	r2, r3, r1
	ldrh	r1, [r6, #0]
	strh	r1, [r2, #0]
	adds	r0, #1
	lsls	r0, r0, #16
	lsrs	r7, r0, #16
_0800252EE:
	adds	r6, #2
	ldrh	r1, [r6, #0]
	movs	r2, #0
	ldrsh	r0, [r6, r2]
	cmp	r0, r4
	bne _0800252AA
_0800252FA:
	lsls	r4, r7, #16
	lsrs	r2, r4, #16
	asrs	r0, r4, #16
	ldr r1, _080025420
	ldr r3, _080025424
	adds	r1, r1, r3
	movs	r6, #0
	ldrsh	r1, [r1, r6]
	subs	r1, #1
	cmp	r0, r1
	bge _08002533E
	lsls	r0, r2, #16
	asrs	r0, r0, #16
	mov	r8, r0
	adds	r6, r1, #0
_080025318:
	asrs	r4, r4, #16
	lsls	r0, r4, #1
	mov	r1, sp
	adds	r5, r1, r0
	adds	r0, r4, #0
	mov	r1, r8
	bl 0x0802DE9C
	lsls	r0, r0, #1
	add	r0, sp
	ldrh	r0, [r0, #0]
	strh	r0, [r5, #0]
	adds	r4, #1
	lsls	r4, r4, #16
	lsrs	r7, r4, #16
	lsls	r4, r7, #16
	asrs	r0, r4, #16
	cmp	r0, r6
	blt _080025318
_08002533E:
	movs	r6, #0
	lsls	r0, r7, #16
	asrs	r1, r0, #16
	cmp	r6, r1
	bge _08002537C
	adds	r5, r1, #0
_08002534A:
	bl 0x08008014
	bl 0x08005B5C
	adds	r1, r5, #0
	bl 0x0802DE9C
	lsls	r2, r6, #16
	asrs	r2, r2, #16
	lsls	r1, r2, #1
	mov	r4, sp
	adds	r3, r4, r1
	ldrh	r4, [r3, #0]
	lsls	r0, r0, #1
	mov	r6, sp
	adds	r1, r6, r0
	ldrh	r0, [r1, #0]
	strh	r0, [r3, #0]
	strh	r4, [r1, #0]
	adds	r2, #1
	lsls	r2, r2, #16
	lsrs	r6, r2, #16
	asrs	r2, r2, #16
	cmp	r2, r5
	blt _08002534A
_08002537C:
	mov	r0, sp
	ldrh	r0, [r0, #0]
	add	r1, sp, #196
	strh	r0, [r1, #0]
	movs	r6, #1
	ldr r1, _080025420
	ldr r2, _080025424
	adds	r0, r1, r2
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	subs	r0, #1
	cmp	r6, r0
	bge _080025464
_080025396:
	movs	r4, #0
	mov	sl, r4
	lsls	r0, r6, #16
	asrs	r1, r0, #16
	str	r0, [sp, #212]
	cmp	sl, r1
	bge _080025436
	mov	r9, r1
	lsls	r0, r1, #1
	add	r0, sp
	mov	r8, r0
_0800253AC:
	mov	r6, r8
	movs	r1, #0
	ldrsh	r0, [r6, r1]
	bl 0x08025518
	adds	r6, r0, #0
	mov	r2, r8
	movs	r3, #0
	ldrsh	r0, [r2, r3]
	bl 0x08025530
	lsls	r6, r6, #24
	asrs	r6, r6, #24
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	adds	r6, r6, r0
	mov	r4, sl
	lsls	r0, r4, #16
	asrs	r7, r0, #16
	lsls	r5, r7, #1
	add	r5, sp
	adds	r5, #196
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	bl 0x08025518
	adds	r4, r0, #0
	movs	r2, #0
	ldrsh	r0, [r5, r2]
	bl 0x08025530
	lsls	r4, r4, #24
	asrs	r4, r4, #24
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	adds	r4, r4, r0
	cmp	r6, r4
	bge _080025428
	ldr	r1, [sp, #212]
	asrs	r0, r1, #16
	cmp	r0, r7
	ble _080025436
	add	r3, sp, #196
	adds	r5, r7, #0
_080025404:
	asrs	r1, r1, #16
	lsls	r2, r1, #1
	adds	r2, r3, r2
	subs	r1, #1
	lsls	r0, r1, #1
	adds	r0, r3, r0
	ldrh	r0, [r0, #0]
	strh	r0, [r2, #0]
	lsls	r1, r1, #16
	asrs	r0, r1, #16
	cmp	r0, r5
	bgt _080025404
	b _080025436
	movs	r0, r0
_080025420: .4byte 0x03001780
_080025424: .4byte 0x000010CA
_080025428:
	adds	r0, r7, #1
	lsls	r0, r0, #16
	lsrs	r3, r0, #16
	mov	sl, r3
	asrs	r0, r0, #16
	cmp	r0, r9
	blt _0800253AC
_080025436:
	mov	r4, sl
	lsls	r2, r4, #16
	asrs	r2, r2, #15
	add	r2, sp
	adds	r2, #196
	ldr	r6, [sp, #212]
	asrs	r1, r6, #16
	lsls	r0, r1, #1
	add	r0, sp
	ldrh	r0, [r0, #0]
	strh	r0, [r2, #0]
	adds	r1, #1
	lsls	r1, r1, #16
	lsrs	r6, r1, #16
	asrs	r1, r1, #16
	ldr r0, _0800254D8
	ldr r2, _0800254DC
	adds	r0, r0, r2
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	subs	r0, #1
	cmp	r1, r0
	blt _080025396
_080025464:
	movs	r6, #1
	ldr r4, _0800254D8
	ldr r0, _0800254DC
	adds	r1, r4, r0
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r6, r0
	bge _0800254C6
	adds	r7, r4, #0
	mov	r9, r1
_080025478:
	lsls	r5, r6, #16
	asrs	r5, r5, #16
	lsls	r6, r5, #1
	ldr r3, _0800254E0
	adds	r1, r7, r3
	adds	r1, r6, r1
	subs	r4, r5, #1
	lsls	r4, r4, #1
	add	r4, sp
	adds	r4, #196
	ldrh	r0, [r4, #0]
	strh	r0, [r1, #0]
	bl 0x08008014
	bl 0x08005B5C
	mov	r8, r0
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	bl 0x080254E8
	adds	r1, r0, #0
	lsls	r1, r1, #24
	asrs	r1, r1, #24
	mov	r0, r8
	bl 0x0802D97C
	ldr r2, _0800254E4
	adds	r1, r7, r2
	adds	r6, r6, r1
	strh	r0, [r6, #0]
	adds	r5, #1
	lsls	r5, r5, #16
	lsrs	r6, r5, #16
	mov	r3, r9
	ldrh	r3, [r3, #0]
	lsls	r0, r3, #16
	cmp	r5, r0
	blt _080025478
_0800254C6:
	add	sp, #216
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800254D8: .4byte 0x03001780
_0800254DC: .4byte 0x000010CA
_0800254E0: .4byte 0x00001DD4
_0800254E4: .4byte 0x00001DE4
