@ GT Advance 3 - converted span
@ Region: file offset 0x02446C-0x024568 (VMA 0x0802446C-0x08024568).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08002446C, %function
sub_08002446C:
_08002446C:
	push	{r4, r5, r6, lr}
	ldr r4, _080024548
	ldr r0, _08002454C
	adds	r2, r4, r0
	movs	r1, #0
	movs	r0, #8
	strh	r0, [r2, #0]
	ldr r2, _080024550
	adds	r0, r4, r2
	movs	r2, #1
	strb	r2, [r0, #0]
	movs	r3, #188
	lsls	r3, r3, #3
	adds	r0, r4, r3
	strh	r2, [r0, #0]
	movs	r2, #255
	lsls	r2, r2, #4
	adds	r0, r4, r2
	strh	r1, [r0, #0]
	ldr r3, _080024554
	adds	r0, r4, r3
	strh	r1, [r0, #0]
	adds	r2, #6
	adds	r0, r4, r2
	strh	r1, [r0, #0]
	adds	r3, #72
	adds	r0, r4, r3
	strh	r1, [r0, #0]
	ldr r0, _080024558
	adds	r2, r4, r0
	movs	r0, #16
	strh	r0, [r2, #0]
	ldr r2, _08002455C
	adds	r0, r4, r2
	strh	r1, [r0, #0]
	adds	r3, #32
	adds	r0, r4, r3
	strh	r1, [r0, #0]
	adds	r2, #30
	adds	r0, r4, r2
	strh	r1, [r0, #0]
	adds	r3, #2
	adds	r0, r4, r3
	strh	r1, [r0, #0]
	movs	r0, #0
	bl 0x0800274C
	movs	r1, #0
	movs	r0, #9
	ldr r2, _080024560
	adds	r4, r4, r2
_0800244D2:
	strh	r1, [r4, #0]
	subs	r4, #2
	subs	r0, #1
	cmp	r0, #0
	bge _0800244D2
	movs	r1, #0
	ldr r0, _080024548
	movs	r3, #0
	movs	r2, #253
	lsls	r2, r2, #4
	adds	r4, r0, r2
_0800244E8:
	lsls	r0, r1, #3
	adds	r2, r1, #1
	movs	r1, #3
	adds	r0, r0, r4
	adds	r0, #6
_0800244F2:
	strh	r3, [r0, #0]
	subs	r0, #2
	subs	r1, #1
	cmp	r1, #0
	bge _0800244F2
	adds	r1, r2, #0
	cmp	r1, #1
	ble _0800244E8
	ldr r5, _080024564
	movs	r4, #97
_080024506:
	adds	r0, r5, #0
	bl 0x08024F34
	adds	r5, #12
	subs	r4, #1
	cmp	r4, #0
	bge _080024506
	movs	r5, #0
_080024516:
	movs	r4, #0
	adds	r6, r5, #1
_08002451A:
	adds	r0, r5, #0
	adds	r1, r4, #0
	movs	r2, #0
	bl sub_08002714
	adds	r0, r5, #0
	adds	r1, r4, #0
	movs	r2, #0
	bl sub_080026DC
	adds	r4, #1
	cmp	r4, #3
	ble _08002451A
	adds	r5, r6, #0
	cmp	r5, #1
	ble _080024516
	bl 0x0802417C
	bl 0x08024338
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
_080024548: .4byte 0x03001780
_08002454C: .4byte 0x00000574
_080024550: .4byte 0x000010BF
_080024554: .4byte 0x00000FF2
_080024558: .4byte 0x00000576
_08002455C: .4byte 0x00001058
_080024560: .4byte 0x00001072
_080024564: .4byte 0x030017B0
