@ GT Advance 3 - converted span
@ Region: file offset 0x004A2C-0x004AF4 (VMA 0x08004A2C-0x08004AF4).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08004A2C, %function
sub_08004A2C:
_08004A2C:
	push	{lr}
	ldr r2, _08004A44
	adds	r3, r2, #0
	adds	r3, #132
	str	r0, [r3, #0]
	adds	r2, #140
	str	r1, [r2, #0]
	bl 0x08004A0C
	pop	{r0}
	bx	r0
	movs	r0, r0
_08004A44: .4byte 0x03000198
	.type sub_08004A48, %function
sub_08004A48:
_08004A48:
	push	{r4, r5, r6, lr}
	sub	sp, #4
	adds	r6, r0, #0
	adds	r4, r1, #0
	ldr r5, _08004A9C
	movs	r0, #0
	str	r0, [sp, #0]
	ldr r2, _08004AA0
	mov	r0, sp
	adds	r1, r5, #0
	bl 0x0802D974
	strh	r4, [r5, #0]
	adds	r1, r5, #0
	adds	r1, #98
	ldrh	r0, [r1, #0]
	strh	r0, [r5, #2]
	strh	r4, [r1, #0]
	str	r6, [r5, #80]
	ldr	r0, [r6, #8]
	bl 0x080049AC
	str	r0, [r5, #84]
	ldr	r0, [r6, #0]
	cmp	r0, #0
	beq _08004A92
	movs	r0, #8
	bl 0x080049AC
	str	r0, [r5, #76]
	ldr	r1, [r6, #0]
	str	r1, [r0, #0]
	ldr	r0, [r1, #4]
	bl 0x080049AC
	ldr	r1, [r5, #76]
	str	r0, [r1, #4]
_08004A92:
	adds	r0, r5, #0
	add	sp, #4
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
_08004A9C: .4byte 0x030001A8
_08004AA0: .4byte 0x05000018
	.type sub_08004AA4, %function
sub_08004AA4:
_08004AA4:
	push	{r4, r5, lr}
	sub	sp, #4
	adds	r5, r0, #0
	bl 0x08004A0C
	ldr r4, _08004AE8
	ldr	r1, [r4, #0]
	lsls	r0, r5, #2
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	adds	r1, r5, #0
	bl sub_08004A48
	str	r0, [r4, #8]
	adds	r4, #148
	adds	r2, r0, #0
	adds	r2, #12
	movs	r1, #7
_08004AC8:
	ldmia	r4!, {r0}
	stmia	r2!, {r0}
	subs	r1, #1
	cmp	r1, #0
	bge _08004AC8
	movs	r0, #0
	str	r0, [sp, #0]
	ldr r1, _08004AEC
	ldr r2, _08004AF0
	mov	r0, sp
	bl 0x0802D974
	add	sp, #4
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_08004AE8: .4byte 0x03000198
_08004AEC: .4byte 0x0300022C
_08004AF0: .4byte 0x05000008

@ End-of-region anchor for the splicer. This file declares exactly one
@ `@ Region:` (0x08004a2c-0x08004af4) and has no `.include`; the promoted body at
@ 0x08004AA4 ends on 0x08004af4, exactly that boundary, so the anchor is safe.
@ Without it the body is refused as 'no end marker in asm/code_4a2c.s'.
code_4a2c_end:
