@ GT Advance 3 - converted span
@ Region: file offset 0x000FA0-0x0015F4 (VMA 0x08000FA0-0x080015F4).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	mov	sl, r0
	cmp	r1, #15
	bls _08000FAE
	subs	r0, r1, #1
	mov	r1, sl
	strb	r0, [r1, #0]
	b _08001360
_08000FAE:
	adds	r1, r6, #0
	adds	r1, #72
	ldrb	r0, [r1, #0]
	cmp	r0, #0
	beq _08000FD8
	movs	r0, #0
	strb	r0, [r1, #0]
	ldr r0, _08000FD4
	ldrh	r0, [r0, #0]
	movs	r4, #252
	ands	r4, r0
	cmp	r4, #8
	beq _08000FD8
	adds	r0, r6, #0
	bl 0x08000F48
	movs	r0, #8
	eors	r0, r4
	b _08001362
_08000FD4: .4byte 0x04000128
_08000FD8:
	ldrb	r2, [r6, #24]
	cmp	r2, #223
	bls _0800102A
	adds	r0, r6, #0
	bl sub_080014B4
	adds	r4, r0, #0
	cmp	r4, #0
	beq _08000FEC
	b _08001362
_08000FEC:
	adds	r0, r6, #0
	adds	r0, #75
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne _08001008
	ldrb	r0, [r6, #24]
	cmp	r0, #225
	bls _08001008
	adds	r0, r6, #0
	bl _080014A4
	cmp	r0, #0
	bne _08001008
	b _08001350
_08001008:
	adds	r0, r6, #0
	bl _080014A4
	cmp	r0, #0
	beq _08001014
	b _08001360
_08001014:
	ldrh	r0, [r6, #22]
	cmp	r0, #0
	bne _08001024
	adds	r0, r6, #0
	bl 0x08000F48
	movs	r0, #113
	b _08001362
_08001024:
	subs	r0, #1
	strh	r0, [r6, #22]
	b _08001360
_0800102A:
	ldrb	r0, [r6, #24]
	cmp	r0, #2
	bne _08001032
	b _08001168
_08001032:
	cmp	r0, #2
	bgt _08001040
	cmp	r0, #0
	beq _0800104E
	cmp	r0, #1
	beq _0800110C
	b _080012A4
_08001040:
	cmp	r0, #208
	bne _08001046
	b _080011B4
_08001046:
	cmp	r0, #209
	bne _0800104C
	b _08001250
_0800104C:
	b _080012A4
_0800104E:
	movs	r5, #14
	movs	r4, #3
	ldr r0, _08001094
	ldrh	r0, [r0, #6]
	adds	r1, r0, #0
	ldr r0, _08001098
	ldrb	r2, [r6, #30]
	adds	r7, r2, #0
	cmp	r1, r0
	bne _08001076
	adds	r3, r1, #0
	ldr r1, _0800109C
_08001066:
	asrs	r5, r5, #1
	subs	r1, #2
	subs	r4, #1
	cmp	r4, #0
	beq _08001076
	ldrh	r0, [r1, #0]
	cmp	r0, r3
	beq _08001066
_08001076:
	movs	r0, #14
	ands	r5, r0
	strb	r5, [r6, #29]
	movs	r4, #3
	ldr r0, _08001094
	ldrh	r0, [r0, #6]
	adds	r3, r0, #0
	asrs	r0, r2, #3
	movs	r1, #1
	ands	r0, r1
	cmp	r0, #0
	beq _080010A4
	ldr r0, _080010A0
	b _080010CA
	movs	r0, r0
_08001094: .4byte 0x04000120
_08001098: .4byte 0x0000FFFF
_0800109C: .4byte 0x04000126
_080010A0: .4byte 0x00007208
_080010A4:
	subs	r4, #1
	cmp	r4, #0
	beq _080010D0
	lsls	r0, r4, #1
	ldr r1, _080010F8
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	adds	r3, r0, #0
	adds	r0, r2, #0
	asrs	r0, r4
	movs	r1, #1
	ands	r0, r1
	cmp	r0, #0
	beq _080010A4
	adds	r0, r1, #0
	lsls	r0, r4
	movs	r1, #228
	lsls	r1, r1, #7
	orrs	r0, r1
_080010CA:
	cmp	r3, r0
	beq _080010A4
	movs	r5, #0
_080010D0:
	adds	r0, r5, #0
	ands	r0, r7
	strb	r0, [r6, #30]
	cmp	r5, #0
	bne _080010E0
	movs	r0, #15
	mov	r2, sl
	strb	r0, [r2, #0]
_080010E0:
	mov	r1, sl
	ldrb	r0, [r1, #0]
	cmp	r0, #0
	bne _080010FC
	ldrb	r2, [r6, #29]
	ldrb	r0, [r6, #30]
	cmp	r2, r0
	beq _08001102
	adds	r0, r6, #0
	bl sub_080013BC
	b _0800110C
_080010F8: .4byte 0x04000120
_080010FC:
	subs	r0, #1
	mov	r1, sl
	strb	r0, [r1, #0]
_08001102:
	movs	r2, #196
	lsls	r2, r2, #7
	adds	r0, r2, #0
	ldrb	r1, [r6, #30]
	b _0800120C
_0800110C:
	adds	r1, r6, #0
	adds	r1, #73
	movs	r0, #0
	strb	r0, [r1, #0]
	movs	r4, #3
	adds	r7, r1, #0
	ldr r5, _08001160
_0800111A:
	lsls	r0, r4, #1
	ldr r2, _08001164
	adds	r0, r0, r2
	ldrh	r0, [r0, #0]
	adds	r3, r0, #0
	asrs	r0, r3, #8
	subs	r2, r4, #1
	cmp	r0, #114
	bne _08001144
	lsls	r0, r2, #1
	adds	r0, r0, r5
	strh	r3, [r0, #0]
	movs	r0, #255
	ands	r3, r0
	movs	r0, #1
	lsls	r0, r4
	cmp	r3, r0
	bne _08001144
	ldrb	r0, [r1, #0]
	orrs	r3, r0
	strb	r3, [r1, #0]
_08001144:
	adds	r4, r2, #0
	cmp	r4, #0
	bne _0800111A
	ldrb	r1, [r6, #29]
	ldrb	r2, [r7, #0]
	cmp	r1, r2
	bne _08001102
	movs	r0, #2
	strb	r0, [r6, #24]
	movs	r1, #194
	lsls	r1, r1, #7
	adds	r0, r1, #0
	ldrb	r1, [r7, #0]
	b _0800120C
_08001160: .4byte 0x03000000
_08001164: .4byte 0x04000120
_08001168:
	movs	r4, #3
	adds	r7, r6, #0
	adds	r7, #73
	adds	r5, r7, #0
	movs	r2, #1
	mov	ip, r2
	ldr r0, _080011AC
	mov	r9, r0
	ldr r1, _080011B0
	mov	r8, r1
_0800117C:
	ldrb	r3, [r5, #0]
	adds	r0, r3, #0
	asrs	r0, r4
	mov	r2, ip
	ands	r0, r2
	subs	r2, r4, #1
	cmp	r0, #0
	beq _080011A4
	lsls	r0, r4, #1
	add	r0, r8
	ldrh	r1, [r0, #0]
	lsls	r0, r2, #1
	add	r0, r9
	ldrh	r0, [r0, #0]
	cmp	r1, r0
	beq _080011A4
	mov	r0, ip
	lsls	r0, r4
	eors	r3, r0
	strb	r3, [r5, #0]
_080011A4:
	adds	r4, r2, #0
	cmp	r4, #0
	bne _0800117C
	b _08001308
_080011AC: .4byte 0x03000000
_080011B0: .4byte 0x04000120
_080011B4:
	movs	r5, #1
	movs	r4, #3
	adds	r7, r6, #0
	adds	r7, #73
	movs	r0, #25
	adds	r0, r0, r6
	mov	ip, r0
	ldr r1, _08001218
	mov	r8, r1
_080011C6:
	lsls	r0, r4, #1
	ldr r2, _0800121C
	adds	r0, r0, r2
	ldrh	r0, [r0, #0]
	adds	r3, r0, #0
	subs	r2, r4, #1
	mov	r1, ip
	adds	r0, r1, r2
	strb	r3, [r0, #0]
	ldrb	r1, [r7, #0]
	asrs	r1, r4
	movs	r0, #1
	ands	r1, r0
	cmp	r1, #0
	beq _080011FA
	asrs	r0, r3, #8
	subs	r0, #114
	cmp	r0, #1
	bls _080011EE
	b _08001356
_080011EE:
	lsls	r0, r2, #1
	add	r0, r8
	ldrh	r0, [r0, #0]
	cmp	r3, r0
	bne _080011FA
	movs	r5, #0
_080011FA:
	adds	r4, r2, #0
	cmp	r4, #0
	bne _080011C6
	cmp	r5, #0
	bne _08001220
	movs	r2, #198
	lsls	r2, r2, #7
	adds	r0, r2, #0
	ldrb	r1, [r6, #28]
_0800120C:
	orrs	r1, r0
	adds	r0, r6, #0
	bl sub_08001370
	b _08001362
	movs	r0, r0
_08001218: .4byte 0x03000000
_0800121C: .4byte 0x04000120
_08001220:
	movs	r0, #209
	strb	r0, [r6, #24]
	movs	r5, #17
	movs	r4, #3
	mov	r0, ip
	adds	r0, #2
_0800122C:
	ldrb	r1, [r0, #0]
	adds	r5, r1, r5
	subs	r0, #1
	subs	r4, #1
	cmp	r4, #0
	bne _0800122C
	strb	r5, [r6, #20]
	movs	r0, #255
	ands	r5, r0
	movs	r2, #200
	lsls	r2, r2, #7
	adds	r0, r2, #0
	orrs	r5, r0
	adds	r0, r6, #0
	adds	r1, r5, #0
	bl sub_08001370
	b _08001362
_08001250:
	movs	r4, #3
	adds	r7, r6, #0
	adds	r7, #73
	ldrb	r1, [r7, #0]
	ldr r2, _08001290
	movs	r5, #1
_0800125C:
	ldrh	r0, [r2, #0]
	adds	r3, r0, #0
	adds	r0, r1, #0
	asrs	r0, r4
	ands	r0, r5
	cmp	r0, #0
	beq _08001270
	asrs	r0, r3, #8
	cmp	r0, #115
	bne _08001356
_08001270:
	subs	r2, #2
	subs	r4, #1
	cmp	r4, #0
	bne _0800125C
	adds	r0, r6, #0
	bl 0x0802D98C
	adds	r4, r0, #0
	cmp	r4, #0
	bne _08001294
	movs	r0, #224
	strb	r0, [r6, #24]
	adds	r0, #176
	strh	r0, [r6, #22]
	b _08001360
	movs	r0, r0
_08001290: .4byte 0x04000126
_08001294:
	adds	r0, r6, #0
	bl 0x08000F48
	movs	r0, #30
	mov	r1, sl
	strb	r0, [r1, #0]
	movs	r0, #112
	b _08001362
_080012A4:
	movs	r4, #3
	adds	r7, r6, #0
	adds	r7, #73
	mov	ip, r7
	movs	r2, #1
	mov	r8, r2
_080012B0:
	mov	r0, ip
	ldrb	r5, [r0, #0]
	adds	r0, r5, #0
	asrs	r0, r4
	mov	r1, r8
	ands	r0, r1
	cmp	r0, #0
	beq _080012EA
	lsls	r0, r4, #1
	ldr r2, _08001304
	adds	r0, r0, r2
	ldrh	r0, [r0, #0]
	adds	r3, r0, #0
	asrs	r2, r3, #8
	ldrb	r0, [r6, #24]
	lsrs	r1, r0, #1
	movs	r0, #98
	subs	r0, r0, r1
	mov	r1, r8
	lsls	r1, r4
	cmp	r2, r0
	bne _080012E4
	movs	r0, #255
	ands	r3, r0
	cmp	r3, r1
	beq _080012EA
_080012E4:
	eors	r5, r1
	mov	r1, ip
	strb	r5, [r1, #0]
_080012EA:
	subs	r4, #1
	cmp	r4, #0
	bne _080012B0
	ldrb	r2, [r6, #24]
	cmp	r2, #196
	bne _08001308
	movs	r0, #14
	ldrb	r7, [r7, #0]
	ands	r0, r7
	strb	r0, [r6, #30]
	strb	r4, [r6, #24]
	b _08001102
	movs	r0, r0
_08001304: .4byte 0x04000120
_08001308:
	ldrb	r0, [r7, #0]
	cmp	r0, #0
	bne _08001318
	adds	r0, r6, #0
	bl 0x08000F48
	movs	r0, #80
	b _08001362
_08001318:
	ldrb	r0, [r6, #24]
	adds	r0, #2
	strb	r0, [r6, #24]
	lsls	r0, r0, #24
	lsrs	r0, r0, #24
	cmp	r0, #196
	bne _08001328
	b _08001102
_08001328:
	ldr	r0, [r6, #40]
	ldrb	r1, [r6, #24]
	adds	r0, r1, r0
	subs	r1, r0, #3
	ldrb	r1, [r1, #0]
	lsls	r1, r1, #8
	subs	r0, #4
	ldrb	r0, [r0, #0]
	orrs	r1, r0
	adds	r0, r6, #0
	bl sub_08001370
	adds	r4, r0, #0
	cmp	r4, #0
	bne _08001362
	adds	r0, r6, #0
	adds	r0, #75
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne _08001360
_08001350:
	bl sub_080015B8
	b _08000FAE
_08001356:
	adds	r0, r6, #0
	bl 0x08000F48
	movs	r0, #96
	b _08001362
_08001360:
	movs	r0, #0
_08001362:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	.type sub_08001370, %function
sub_08001370:
_08001370:
	push	{r4, lr}
	adds	r2, r0, #0
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	ldr r3, _0800139C
	ldrh	r0, [r3, #0]
	movs	r4, #140
	ands	r4, r0
	cmp	r4, #8
	bne _080013A8
	ldr r0, _080013A0
	strh	r1, [r0, #0]
	ldr r1, _080013A4
	adds	r0, r1, #0
	strh	r0, [r3, #0]
	adds	r1, r2, #0
	adds	r1, #72
	movs	r0, #1
	strb	r0, [r1, #0]
	movs	r0, #0
	b _080013B4
	movs	r0, r0
_0800139C: .4byte 0x04000128
_080013A0: .4byte 0x0400012A
_080013A4: .4byte 0x00002083
_080013A8:
	adds	r0, r2, #0
	bl 0x08000F48
	movs	r0, #8
	eors	r4, r0
	adds	r0, r4, #0
_080013B4:
	pop	{r4}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_080013BC, %function
sub_080013BC:
_080013BC:
	push	{lr}
	adds	r1, r0, #0
	ldrb	r0, [r1, #24]
	cmp	r0, #0
	beq _080013CE
	adds	r0, r1, #0
	bl 0x08000F48
	b _080013DA
_080013CE:
	adds	r2, r1, #0
	adds	r2, #74
	strb	r0, [r2, #0]
	strb	r0, [r1, #30]
	movs	r0, #1
	strb	r0, [r1, #24]
_080013DA:
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080013E0, %function
sub_080013E0:
_080013E0:
	push	{r4, r5, r6, r7, lr}
	adds	r5, r0, #0
	adds	r6, r1, #0
	ldr	r0, [sp, #20]
	lsls	r3, r3, #24
	lsrs	r3, r3, #24
	lsls	r0, r0, #24
	lsrs	r7, r0, #24
	ldrb	r0, [r5, #24]
	cmp	r0, #0
	bne _0800141A
	ldrb	r0, [r5, #30]
	cmp	r0, #0
	beq _0800141A
	adds	r0, r5, #0
	adds	r0, #74
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _0800141A
	str	r6, [r5, #32]
	adds	r2, #15
	movs	r0, #16
	negs	r0, r0
	ands	r2, r0
	subs	r0, #240
	adds	r1, r2, r0
	ldr r0, _08001424
	cmp	r1, r0
	bls _08001428
_0800141A:
	adds	r0, r5, #0
	bl 0x08000F48
	b _0800149C
	movs	r0, r0
_08001424: .4byte 0x0003FF00
_08001428:
	adds	r0, r6, r2
	str	r0, [r5, #36]
	lsls	r1, r7, #24
	movs	r2, #128
	lsls	r2, r2, #19
	adds	r0, r1, r2
	asrs	r0, r0, #24
	adds	r2, r1, #0
	cmp	r0, #8
	bhi _08001488
	lsls	r0, r0, #2
	ldr r1, _08001448
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_08001448: .4byte 0x0800144C
_0800144C: .4byte 0x08001470
_08001450: .4byte 0x08001470
_08001454: .4byte 0x08001470
_08001458: .4byte 0x08001470
_0800145C: .4byte 0x0800147A
_08001460: .4byte 0x08001480
_08001464: .4byte 0x08001480
_08001468: .4byte 0x08001480
_0800146C: .4byte 0x08001480
_08001470:
	lsls	r4, r3, #3
	asrs	r1, r2, #24
	movs	r0, #3
	subs	r0, r0, r1
	b _08001486
_0800147A:
	movs	r0, #56
	adds	r4, r3, #0
	b _08001486
_08001480:
	lsls	r4, r3, #3
	asrs	r0, r2, #24
	subs	r0, #1
_08001486:
	orrs	r4, r0
_08001488:
	movs	r0, #63
	ands	r4, r0
	lsls	r0, r4, #1
	movs	r2, #127
	negs	r2, r2
	adds	r1, r2, #0
	orrs	r0, r1
	strb	r0, [r5, #28]
	movs	r0, #208
	strb	r0, [r5, #24]
_0800149C:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080014A4:
	ldrb	r0, [r0, #24]
	cmp	r0, #233
	beq _080014AE
	movs	r0, #0
	b _080014B0
_080014AE:
	movs	r0, #1
_080014B0:
	bx	lr
	movs	r0, r0
	.type sub_080014B4, %function
sub_080014B4:
_080014B4:
	push	{r4, r5, r6, lr}
	adds	r3, r0, #0
	ldrb	r0, [r3, #24]
	cmp	r0, #224
	beq _080014D0
	cmp	r0, #224
	blt _080014E0
	cmp	r0, #232
	bgt _080014E0
	cmp	r0, #231
	blt _080014E0
	movs	r4, #3
	ldrb	r5, [r3, #30]
	b _08001540
_080014D0:
	movs	r1, #0
	movs	r0, #225
	strb	r0, [r3, #24]
	str	r1, [r3, #4]
	movs	r0, #128
	lsls	r0, r0, #13
	str	r0, [r3, #0]
	b _08001532
_080014E0:
	movs	r4, #3
	ldrb	r5, [r3, #30]
	movs	r6, #1
	ldr r1, _0800153C
_080014E8:
	ldrh	r0, [r1, #0]
	adds	r2, r0, #0
	adds	r0, r5, #0
	asrs	r0, r4
	ands	r0, r6
	cmp	r0, #0
	beq _080014FC
	ldr	r0, [r3, #4]
	cmp	r2, r0
	bne _080014D0
_080014FC:
	subs	r1, #2
	subs	r4, #1
	cmp	r4, #0
	bne _080014E8
	ldrb	r0, [r3, #24]
	adds	r0, #1
	strb	r0, [r3, #24]
	ldr	r1, [r3, #0]
	ldrh	r0, [r3, #0]
	str	r0, [r3, #4]
	cmp	r1, #0
	bne _0800152A
	ldr	r0, [r3, #40]
	adds	r1, r0, #0
	adds	r1, #172
	adds	r0, #173
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #8
	ldrb	r1, [r1, #0]
	orrs	r0, r1
	str	r0, [r3, #4]
	lsls	r0, r0, #5
	str	r0, [r3, #0]
_0800152A:
	ldr	r0, [r3, #0]
	lsrs	r0, r0, #5
	str	r0, [r3, #0]
_08001530:
	ldrh	r1, [r3, #0]
_08001532:
	adds	r0, r3, #0
	bl sub_08001370
	b _08001598
	movs	r0, r0
_0800153C: .4byte 0x04000126
_08001540:
	lsls	r0, r4, #1
	ldr r1, _08001588
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	adds	r2, r0, #0
	adds	r0, r5, #0
	asrs	r0, r4
	movs	r1, #1
	ands	r0, r1
	cmp	r0, #0
	beq _0800155C
	ldr	r0, [r3, #4]
	cmp	r2, r0
	bne _0800158C
_0800155C:
	subs	r4, #1
	cmp	r4, #0
	bne _08001540
	ldrb	r0, [r3, #24]
	adds	r0, #1
	strb	r0, [r3, #24]
	lsls	r0, r0, #24
	lsrs	r0, r0, #24
	cmp	r0, #233
	beq _08001596
	ldr	r0, [r3, #40]
	adds	r1, r0, #0
	adds	r1, #174
	adds	r0, #175
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #8
	ldrb	r1, [r1, #0]
	orrs	r0, r1
	str	r0, [r3, #0]
	str	r0, [r3, #4]
	b _08001530
	movs	r0, r0
_08001588: .4byte 0x04000120
_0800158C:
	adds	r0, r3, #0
	bl 0x08000F48
	movs	r0, #113
	b _08001598
_08001596:
	movs	r0, #0
_08001598:
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type _080015A0, %function
_080015A0:
	mov	r2, pc
	lsrs	r2, r2, #24
	movs	r1, #12
	cmp	r2, #2
	beq _080015B2
	movs	r1, #13
	cmp	r2, #8
	beq _080015B2
	movs	r1, #4
_080015B2:
	subs	r0, r0, r1
	bgt _080015B2
	bx	lr
	.type sub_080015B8, %function
sub_080015B8:
_080015B8:
	push	{r4, r5, lr}
	movs	r2, #0
	ldr r3, _080015EC
	ldrh	r1, [r3, #0]
	movs	r0, #128
	ands	r0, r1
	cmp	r0, #0
	beq _080015DC
	ldr r5, _080015F0
	movs	r4, #128
_080015CC:
	adds	r2, #1
	cmp	r2, r5
	bgt _080015DC
	ldrh	r1, [r3, #0]
	adds	r0, r4, #0
	ands	r0, r1
	cmp	r0, #0
	bne _080015CC
_080015DC:
	movs	r0, #150
	lsls	r0, r0, #2
	bl _080015A0
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080015EC: .4byte 0x04000128
_080015F0: .4byte 0x0000795C
