@ GT Advance 3 - converted span
@ Region: file offset 0x023E7C-0x023ED0 (VMA 0x08023E7C-0x08023ED0).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080023E7C, %function
sub_080023E7C:
_080023E7C:
	push	{r4, lr}
	adds	r4, r0, #0
	ldr r0, _080023EB8
	ldr r1, _080023EBC
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	cmp	r0, #3
	bne _080023EC8
	adds	r0, r4, #0
	adds	r0, #240
	ldr	r0, [r0, #0]
	cmp	r0, #1
	bne _080023EC8
	bl 0x08002140
	cmp	r0, #2
	beq _080023EC0
	adds	r1, r4, #0
	adds	r1, #236
	ldr	r0, [r1, #0]
	adds	r0, #1
	str	r0, [r1, #0]
	cmp	r0, #180
	ble _080023EC8
	movs	r0, #21
	movs	r1, #0
	movs	r2, #0
	bl 0x08004D4C
	b _080023EC8
_080023EB8: .4byte 0x03001780
_080023EBC: .4byte 0x00000FBC
_080023EC0:
	adds	r1, r4, #0
	adds	r1, #236
	movs	r0, #0
	str	r0, [r1, #0]
_080023EC8:
	pop	{r4}
	pop	{r0}
	bx	r0
	.hword 0x0000
