@ GT Advance 3 - converted span
@ Region: file offset 0x005988-0x0059F0 (VMA 0x08005988-0x080059F0).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08005988, %function
sub_08005988:
_08005988:
	push	{r4, r5, r6, lr}
	adds	r6, r1, #0
	lsls	r0, r0, #24
	lsrs	r0, r0, #21
	ldr r1, _080059DC
	adds	r4, r0, r1
	ldr r0, _080059E0
	ldr	r0, [r0, #0]
	ldr	r0, [r0, #4]
	cmp	r0, #2
	bgt _080059B0
	cmp	r0, #1
_080059A0: .4byte 0x6820DB06
	movs	r1, #128
	lsls	r1, r1, #18
	ldr	r2, [r4, #4]
	adds	r2, #4
	bl 0x08005884
_080059B0:
	ldr r5, _080059E4
	ldr	r1, [r4, #4]
	adds	r0, r5, #0
	bl 0x08005860
	movs	r1, #128
	lsls	r1, r1, #18
	ldr	r1, [r1, #0]
	cmp	r0, r1
	bne _080059E8
	ldr	r2, [r4, #4]
	lsrs	r0, r2, #31
	adds	r2, r2, r0
	lsls	r2, r2, #10
	lsrs	r2, r2, #11
	adds	r0, r5, #0
	adds	r1, r6, #0
	bl 0x0802D974
	movs	r0, #1
	b _080059EA
	movs	r0, r0
_080059DC: .4byte 0x0300032C
_080059E0: .4byte 0x030003AC
_080059E4: .4byte 0x02000004
_080059E8:
	movs	r0, #0
_080059EA:
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
