@ GT Advance 3 - converted span
@ Region: file offset 0x023D4C-0x023E0C (VMA 0x08023D4C-0x08023E0C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080023D4C, %function
sub_080023D4C:
_080023D4C:
	push	{r4, r5, r6, r7, lr}
	adds	r7, r0, #0
	adds	r0, #136
	movs	r1, #15
	bl 0x0800D97C
	ldr r4, _080023E04
	adds	r5, r7, #0
	adds	r5, #140
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	lsls	r0, r0, #3
	adds	r6, r4, #4
	adds	r0, r0, r6
	ldr	r1, [r0, #0]
	adds	r0, r7, #0
	adds	r0, #168
	ldr	r2, [r0, #0]
	adds	r0, r7, #0
	bl 0x08023AE4
	movs	r2, #0
	ldrsh	r0, [r5, r2]
	lsls	r0, r0, #3
	adds	r4, r0, r4
	ldr	r1, [r4, #0]
	adds	r0, r0, r6
	ldr	r2, [r0, #0]
	adds	r0, r7, #0
	bl 0x08023B60
	adds	r0, r7, #0
	adds	r0, #16
	bl 0x0800DBE8
	adds	r0, r7, #0
	adds	r0, #144
	ldrh	r0, [r0, #0]
	cmp	r0, #1
	bne _080023DE8
	adds	r4, r7, #0
	adds	r4, #158
	ldrh	r0, [r4, #0]
	cmp	r0, #1
	bne _080023DB4
	adds	r0, r7, #0
	adds	r0, #166
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	adds	r0, r7, #0
	bl 0x08023C54
_080023DB4:
	adds	r1, r7, #0
	adds	r1, #176
	adds	r0, r7, #0
	movs	r2, #64
	bl 0x08022D44
	ldrh	r0, [r4, #0]
	subs	r0, #5
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #3
	bhi _080023DE8
	bl 0x080022CC
	movs	r1, #100
	muls	r0, r1
	cmp	r0, #0
	bge _080023DDC
	ldr r2, _080023E08
	adds	r0, r0, r2
_080023DDC:
	asrs	r2, r0, #12
	subs	r2, r1, r2
	movs	r0, #128
	movs	r1, #96
	bl 0x08003978
_080023DE8:
	adds	r0, r7, #0
	adds	r0, #158
	ldrh	r0, [r0, #0]
	cmp	r0, #12
	bne _080023DF8
	adds	r0, r7, #0
	bl sub_08023144
_080023DF8:
	adds	r0, r7, #0
	bl 0x08023E78
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080023E04: .4byte 0x080CC178
_080023E08: .4byte 0x00000FFF
