@ GT Advance 3 - converted span
@ Region: file offset 0x022CB4-0x022D20 (VMA 0x08022CB4-0x08022D20).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080022CB4, %function
sub_080022CB4:
_080022CB4:
	push	{r4, r5, lr}
	adds	r4, r1, #0
	adds	r1, #88
	movs	r2, #0
	strb	r2, [r1, #0]
	adds	r5, r0, #0
	adds	r5, #144
	strh	r2, [r5, #0]
	ldr r0, _080022CF4
	ldr r1, _080022CF8
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _080022CDE
	adds	r0, r4, #0
	movs	r1, #1
	movs	r2, #1
	bl 0x080056F4
	movs	r0, #1
	strh	r0, [r5, #0]
_080022CDE:
	bl 0x08004B68
	movs	r1, #2
	ldrsh	r0, [r0, r1]
	cmp	r0, #35
	beq _080022D02
	cmp	r0, #35
	bgt _080022CFC
	cmp	r0, #15
	beq _080022D02
	b _080022D12
_080022CF4: .4byte 0x03001780
_080022CF8: .4byte 0x000010C3
_080022CFC:
	cmp	r0, #40
	beq _080022D0A
	b _080022D12
_080022D02:
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #5
	b _080022D18
_080022D0A:
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #1
	b _080022D18
_080022D12:
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #6
_080022D18:
	strh	r0, [r1, #0]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
code_22cb4_end:
