@ GT Advance 3 - converted span
@ Region: file offset 0x00CE2C-0x00CE70 (VMA 0x0800CE2C-0x0800CE70).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_0800CE2C, %function
sub_0800CE2C:
_0800CE2C:
	push	{lr}
	cmp	r0, #2
	beq _0800CE46
	cmp	r0, #2
	bhi _0800CE3C
	cmp	r0, #1
	beq _0800CE66
	b _0800CE6C
_0800CE3C:
	cmp	r0, #6
	beq _0800CE56
	cmp	r0, #7
	beq _0800CE4E
	b _0800CE6C
_0800CE46:
	adds	r0, r3, #0
	bl 0x0800CCC8
	b _0800CE6C
_0800CE4E:
	adds	r0, r3, #0
	bl 0x0800CDEC
	b _0800CE6C
_0800CE56:
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r3, #0
	bl 0x0800CD48
	b _0800CE6C
_0800CE66:
	adds	r0, r3, #0
	bl 0x0800CCEC
_0800CE6C:
	pop	{r0}
	bx	r0
code_ce2c_end:
