@ GT Advance 3 - converted span
@ Region: file offset 0x005B3C-0x005F2C (VMA 0x08005B3C-0x08005F2C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

@ Region-start marker. `passthrough.inc` names this address with `sub_08005B3C`,
@ but `owners` prefers a `.s` over a `.inc`, so without a label here the
@ screen resolves the byte owner as `passthrough.inc` -- which names only region
@ starts and can never yield this span's end marker (`sub_08005B4C:`, below),
@ and 0x08005B4C-0x08005B5B would be absorbed into 0x08005B3C's span. A bare
@ label emits zero bytes.
_08005B3C:
	ldr r0, _08005B48
	ldr	r0, [r0, #0]
	movs	r1, #34
	ldrsh	r0, [r0, r1]
	bx	lr
	movs	r0, r0
_08005B48: .4byte 0x030003D4
	.type sub_08005B4C, %function
sub_08005B4C:
_08005B4C:
	ldr r1, _08005B58
	ldr	r1, [r1, #0]
	lsls	r0, r0, #2
	adds	r1, r1, r0
	ldrh	r0, [r1, #18]
	bx	lr
_08005B58: .4byte 0x030003D4
_08005B5C:
	cmp	r0, #0
	bge _08005B62
	negs	r0, r0
_08005B62:
	bx	lr
@ 0x08005B64 / 0x08005B7C / 0x08005B8C are three real leaf entries the
@ inventory never saw: each is 4-byte aligned, opens with its own `cmp` or
@ sign-extend pair, and closes with its own `bx lr` (0x08005B78 / 0x08005B8A
@ / 0x08005BA4). Nothing in asm/ `bl`s the latter two and none had a `.type`,
@ so `_08005B5C`'s span ran on to `_08005BA8` -- 8 correct bytes reported as
@ 8/76. 0x08005B64 was worse: garage_26f50.s DOES `bl 0x08005B64`, but
@ `asm_vmas` only keeps a VMA when it has a label AND (typed or bl-called),
@ and the label was absent. Labels and `.type` emit zero bytes; the 2-byte
@ `movs r0, r0` at 0x08005B7A is the inter-function align pad that makes
@ 0x08005B7C 4-byte aligned.
	.type sub_08005B64, %function
sub_08005B64:
_08005B64:
	cmp	r0, #0
	bge _08005B6E
	movs	r0, #1
	negs	r0, r0
	b _08005B78
_08005B6E:
	cmp	r0, #0
	bgt _08005B76
	movs	r0, #0
	b _08005B78
_08005B76:
	movs	r0, #1
_08005B78:
	bx	lr
	movs	r0, r0
	.type _08005B7C, %function
_08005B7C:
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #0
	bge _08005B8A
	negs	r0, r0
	lsls	r0, r0, #16
	asrs	r0, r0, #16
_08005B8A:
	bx	lr
	.type _08005B8C, %function
_08005B8C:
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #0
	bge _08005B9A
	movs	r0, #1
	negs	r0, r0
	b _08005BA4
_08005B9A:
	cmp	r0, #0
	bgt _08005BA2
	movs	r0, #0
	b _08005BA4
_08005BA2:
	movs	r0, #1
_08005BA4:
	bx	lr
	movs	r0, r0
	.type sub_08005BA8, %function
sub_08005BA8:
_08005BA8:
	push	{r4, r5, r6, lr}
	ldr r3, _08005BE4
	ldr r2, _08005BE8
	ands	r2, r1
	adds	r3, r2, r3
	movs	r1, #0
	ldrsh	r6, [r3, r1]
	ldr r1, _08005BEC
	adds	r2, r2, r1
	movs	r1, #0
	ldrsh	r5, [r2, r1]
	ldr	r4, [r0, #0]
	adds	r3, r4, #0
	muls	r3, r6
	ldr	r2, [r0, #4]
	adds	r1, r2, #0
	muls	r1, r5
	subs	r3, r3, r1
	asrs	r3, r3, #12
	adds	r1, r4, #0
	muls	r1, r5
	muls	r2, r6
	adds	r1, r1, r2
	asrs	r1, r1, #12
	str	r1, [r0, #4]
	str	r3, [r0, #0]
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08005BE4: .4byte 0x0805BAF0
_08005BE8: .4byte 0x00000FFE
_08005BEC: .4byte 0x0805CAF0
.type _08005BF0, %function
_08005BF0:
	push	{r4, r5, r6, lr}
	ldr r3, _08005C30
	ldr r2, _08005C34
	ands	r2, r1
	adds	r3, r2, r3
	movs	r1, #0
	ldrsh	r6, [r3, r1]
	ldr r1, _08005C38
	adds	r2, r2, r1
	movs	r1, #0
	ldrsh	r5, [r2, r1]
	movs	r1, #0
	ldrsh	r4, [r0, r1]
	adds	r3, r4, #0
	muls	r3, r6
	movs	r1, #2
	ldrsh	r2, [r0, r1]
	adds	r1, r2, #0
	muls	r1, r5
	subs	r3, r3, r1
	lsrs	r3, r3, #12
	adds	r1, r4, #0
	muls	r1, r5
	muls	r2, r6
	adds	r1, r1, r2
	asrs	r1, r1, #12
	strh	r1, [r0, #2]
	strh	r3, [r0, #0]
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08005C30: .4byte 0x0805BAF0
_08005C34: .4byte 0x00000FFE
_08005C38: .4byte 0x0805CAF0
.type _08005C3C, %function
_08005C3C:
	push	{r4, lr}
	ldr	r3, [r1, #0]
	str	r3, [r0, #0]
	ldr	r4, [r1, #4]
	str	r4, [r0, #4]
	ldr	r1, [r2, #0]
	subs	r1, r1, r3
	str	r1, [r0, #8]
	ldr	r1, [r2, #4]
	subs	r1, r1, r4
	str	r1, [r0, #12]
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_08005C58, %function
sub_08005C58:
_08005C58:
	push	{r4, r5, r6, lr}
	adds	r6, r0, #0
	adds	r4, r1, #0
	ldr r0, _08005C88
	ands	r6, r0
	adds	r5, r6, #0
	ands	r4, r0
	subs	r0, r5, r4
	bl _08005B5C
	adds	r1, r0, #0
	movs	r0, #128
	lsls	r0, r0, #4
	cmp	r1, r0
	ble _08005C96
	cmp	r5, r4
	ble _08005C8C
	subs	r0, r4, r5
	movs	r2, #128
	lsls	r2, r2, #5
	adds	r1, r0, r2
	movs	r0, #1
	b _08005CA0
	movs	r0, r0
_08005C88: .4byte 0x00000FFF
_08005C8C:
	subs	r0, r5, r4
	movs	r2, #128
	lsls	r2, r2, #5
	adds	r1, r0, r2
	b _08005C9C
_08005C96:
	movs	r0, #1
	cmp	r5, r4
	ble _08005CA0
_08005C9C:
	movs	r0, #1
	negs	r0, r0
_08005CA0:
	lsls	r0, r0, #1
	muls	r0, r1
	adds	r0, r6, r0
	ldr r1, _08005CB0
	ands	r0, r1
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
_08005CB0: .4byte 0x00000FFF
	.type sub_08005CB4, %function
sub_08005CB4:
_08005CB4:
	push	{r4, r5, r6, lr}
	adds	r6, r0, #0
	ldr	r3, [r6, #0]
	cmp	r3, #0
	bne _08005CC4
	ldr	r0, [r6, #4]
	cmp	r0, #0
	beq _08005D6A
_08005CC4:
	cmp	r3, #0
	bge _08005CCC
	negs	r1, r3
	b _08005CCE
_08005CCC:
	adds	r1, r3, #0
_08005CCE:
	ldr	r5, [r6, #4]
	cmp	r5, #0
	bge _08005CD8
	negs	r2, r5
	b _08005CDA
_08005CD8:
	adds	r2, r5, #0
_08005CDA:
	cmp	r1, r2
	ble _08005D20
	cmp	r1, #0
	beq _08005D6A
	ldr r4, _08005D04
	lsls	r0, r2, #7
	bl 0x0802DE04
	lsls	r0, r0, #1
	adds	r0, r0, r4
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	ldr	r0, [r6, #0]
	cmp	r0, #0
	bge _08005D0E
	cmp	r5, #0
	bge _08005D08
	movs	r2, #192
	lsls	r2, r2, #4
	adds	r0, r1, r2
	b _08005D64
_08005D04: .4byte 0x0805DAF0
_08005D08:
	movs	r2, #192
	lsls	r2, r2, #4
	b _08005D60
_08005D0E:
	cmp	r5, #0
	bge _08005D18
	movs	r2, #128
	lsls	r2, r2, #3
	b _08005D60
_08005D18:
	movs	r2, #128
	lsls	r2, r2, #3
	adds	r0, r1, r2
	b _08005D64
_08005D20:
	cmp	r2, #0
	beq _08005D6A
	ldr r4, _08005D48
	lsls	r0, r1, #7
	adds	r1, r2, #0
	bl 0x0802DE04
	lsls	r0, r0, #1
	adds	r0, r0, r4
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	ldr	r0, [r6, #0]
	cmp	r0, #0
	bge _08005D54
	cmp	r5, #0
	bge _08005D4C
	movs	r2, #128
	lsls	r2, r2, #5
	b _08005D60
	movs	r0, r0
_08005D48: .4byte 0x0805DAF0
_08005D4C:
	movs	r2, #128
	lsls	r2, r2, #4
	adds	r0, r1, r2
	b _08005D64
_08005D54:
	cmp	r5, #0
	bge _08005D5C
	adds	r0, r1, #0
	b _08005D6C
_08005D5C:
	movs	r2, #128
	lsls	r2, r2, #4
_08005D60:
	adds	r0, r2, #0
	subs	r0, r0, r1
_08005D64:
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	b _08005D6C
_08005D6A:
	movs	r0, #0
_08005D6C:
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_08005D74, %function
sub_08005D74:
_08005D74:
	push	{lr}
	movs	r3, #0
	str	r3, [r0, #0]
	negs	r1, r1
	str	r1, [r0, #4]
	lsls	r1, r2, #16
	asrs	r1, r1, #16
	bl sub_08005BA8
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08005D8C, %function
sub_08005D8C:
_08005D8C:
	push	{r4, lr}
	ldr	r3, [r2, #0]
	ldr	r4, [r1, #0]
	subs	r3, r3, r4
	str	r3, [r0, #0]
	ldr	r2, [r2, #4]
	ldr	r1, [r1, #4]
	subs	r2, r2, r1
	str	r2, [r0, #4]
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_08005DA4, %function
sub_08005DA4:
_08005DA4:
	push	{r4, lr}
	ldr	r4, [r1, #12]
	str	r4, [r0, #0]
	ldr	r3, [r1, #8]
	negs	r3, r3
	str	r3, [r0, #4]
	ldr	r2, [r1, #0]
	muls	r2, r4
	ldr	r1, [r1, #4]
	muls	r1, r3
	adds	r2, r2, r1
	str	r2, [r0, #8]
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08005DC4, %function
sub_08005DC4:
_08005DC4:
	push	{r4, lr}
	ldr	r3, [r2, #4]
	ldr	r4, [r1, #4]
	subs	r3, r3, r4
	str	r3, [r0, #0]
	ldr	r1, [r1, #0]
	ldr	r2, [r2, #0]
	subs	r2, r1, r2
	str	r2, [r0, #4]
	muls	r1, r3
	muls	r2, r4
	adds	r1, r1, r2
	str	r1, [r0, #8]
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_08005DE4, %function
sub_08005DE4:
_08005DE4:
	push	{r4, r5, lr}
	movs	r3, #2
	ldrsh	r4, [r2, r3]
	movs	r5, #2
	ldrsh	r3, [r1, r5]
	subs	r4, r4, r3
	str	r4, [r0, #0]
	movs	r5, #0
	ldrsh	r3, [r1, r5]
	movs	r5, #0
	ldrsh	r2, [r2, r5]
	subs	r3, r3, r2
	str	r3, [r0, #4]
	movs	r5, #0
	ldrsh	r2, [r1, r5]
	muls	r2, r4
	movs	r4, #2
	ldrsh	r1, [r1, r4]
	muls	r1, r3
	adds	r2, r2, r1
	str	r2, [r0, #8]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_08005E14, %function
sub_08005E14:
_08005E14:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	sl, r0
	adds	r3, r1, #0
	ldr	r0, [r3, #0]
	mov	r9, r0
	ldr	r4, [r2, #4]
	mov	r1, r9
	muls	r1, r4
	ldr	r7, [r3, #4]
	ldr	r0, [r2, #0]
	mov	r8, r0
	mov	r0, r8
	muls	r0, r7
	subs	r6, r1, r0
	cmp	r6, #0
	beq _08005E6C
	ldr	r5, [r3, #8]
	adds	r0, r4, #0
	muls	r0, r5
	ldr	r4, [r2, #8]
	adds	r1, r7, #0
	muls	r1, r4
	subs	r0, r0, r1
	adds	r1, r6, #0
	bl 0x0802DE04
	mov	r1, sl
	str	r0, [r1, #0]
	mov	r0, r9
	muls	r0, r4
	mov	r1, r8
	muls	r1, r5
	subs	r0, r0, r1
	adds	r1, r6, #0
	bl 0x0802DE04
	mov	r1, sl
	str	r0, [r1, #4]
	movs	r0, #1
	b _08005E6E
_08005E6C:
	movs	r0, #0
_08005E6E:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	.type sub_08005E7C, %function
sub_08005E7C:
_08005E7C:
	push	{r4, r5, r6, lr}
	mov	r6, r8
	push	{r6}
	sub	sp, #28
	adds	r6, r0, #0
	mov	r8, r1
	adds	r4, r2, #0
	ldr	r0, [r1, #0]
	str	r0, [sp, #0]
	ldr	r0, [r1, #4]
	str	r0, [sp, #4]
	ldr	r0, [r4, #0]
	str	r0, [sp, #8]
	ldr	r0, [r4, #4]
	str	r0, [sp, #12]
	add	r5, sp, #16
	adds	r0, r5, #0
	mov	r1, sp
	bl sub_08005DA4
	adds	r0, r6, #0
	adds	r1, r4, #0
	adds	r2, r5, #0
	bl sub_08005E14
	ldr	r2, [r6, #0]
	mov	r1, r8
	ldr	r0, [r1, #0]
	subs	r2, r2, r0
	str	r2, [r6, #0]
	ldr	r1, [r6, #4]
	mov	r3, r8
	ldr	r0, [r3, #4]
	subs	r1, r1, r0
	str	r1, [r6, #4]
	adds	r0, r2, #0
	muls	r0, r2
	adds	r2, r1, #0
	muls	r2, r1
	adds	r1, r2, #0
	adds	r0, r0, r1
	add	sp, #28
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_08005EDC, %function
sub_08005EDC:
_08005EDC:
	push	{r4, r5, r6, lr}
	sub	sp, #40
	adds	r6, r0, #0
	adds	r4, r2, #0
	ldr	r0, [r1, #0]
	str	r0, [sp, #0]
	ldr	r0, [r1, #4]
	str	r0, [sp, #4]
	ldr	r0, [r4, #4]
	str	r0, [sp, #8]
	ldr	r0, [r4, #0]
	negs	r0, r0
	str	r0, [sp, #12]
	add	r5, sp, #28
	adds	r0, r5, #0
	mov	r1, sp
	bl sub_08005DA4
	ldr	r1, [r4, #0]
	str	r1, [sp, #0]
	ldr	r0, [r4, #4]
	str	r0, [sp, #4]
	str	r1, [sp, #8]
	str	r0, [sp, #12]
	add	r4, sp, #16
	adds	r0, r4, #0
	mov	r1, sp
	bl sub_08005DA4
	adds	r0, r6, #0
	adds	r1, r5, #0
	adds	r2, r4, #0
	bl sub_08005E14
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	add	sp, #40
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
