@ GT Advance 3 - converted span
@ Region: file offset 0x024F4C-0x024F74 (VMA 0x08024F4C-0x08024F74).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080024F4C, %function
sub_080024F4C:
_080024F4C:
	push	{r4, lr}
	ldr r4, _080024F70
	lsls	r2, r2, #3
	movs	r3, #88
	muls	r1, r3
	adds	r2, r2, r1
	lsls	r1, r0, #1
	adds	r1, r1, r0
	lsls	r1, r1, #2
	subs	r1, r1, r0
	lsls	r1, r1, #5
	adds	r2, r2, r1
	adds	r2, r2, r4
	movs	r1, #0
	ldrsh	r0, [r2, r1]
	pop	{r4}
	pop	{r1}
	bx	r1
_080024F70: .4byte 0x080CCACC
code_24f4c_end:
