@ GT Advance 3 - converted span
@ Region: file offset 0x002730-0x00279C (VMA 0x08002730-0x0800279C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08002730, %function
sub_08002730:
_08002730:
	ldr r2, _08002744
	lsls	r1, r1, #1
	lsls	r0, r0, #3
	adds	r1, r1, r0
	ldr r0, _08002748
	adds	r2, r2, r0
	adds	r1, r1, r2
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	bx	lr
_08002744: .4byte 0x03001780
_08002748: .4byte 0x0000109C
	.type sub_0800274C, %function
sub_0800274C:
_0800274C:
	push	{lr}
	adds	r1, r0, #0
	cmp	r1, #0
	bne _08002764
	ldr r0, _0800275C
	ldr r2, _08002760
	adds	r0, r0, r2
	b _0800276C
_0800275C: .4byte 0x03001780
_08002760: .4byte 0x00001056
_08002764:
	ldr r0, _08002778
	ldr r1, _0800277C
	adds	r0, r0, r1
	movs	r1, #1
_0800276C:
	strh	r1, [r0, #0]
	movs	r0, #0
	bl 0x0800279C
	pop	{r0}
	bx	r0
_08002778: .4byte 0x03001780
_0800277C: .4byte 0x00001056
@ 0x08002780 — `GridFlagTest_2780`: this body had NO `.type` and NO label, so
@ `tools/coverage.py` never saw it as an entry (hence no row in the corpus
@ report), `promotion_screen` could not consider it, and the preceding body's
@ span swallowed it. `span_audit` missed it too: `code_2730_end:` is a bare
@ label, not a function entry, so it does not terminate the span.
@ It is the callee of `_0800EBD8` (src/menus.c), which measured EXACT 212/212
@ but could not stage: `Screen.resolve('sub_08002780')` returned "no closure
@ label at 0x08002780", and the C definition in src/numeric_leaves.c cannot
@ satisfy that -- the slice link splices only promoted bodies.
@ Byte-neutral: `.type` emits nothing and the labels introduce no bytes.
	.type sub_08002780, %function
sub_08002780:
_08002780:
	ldr r0, _08002794
	ldr r1, _08002798
	adds	r0, r0, r1
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	negs	r0, r1
	orrs	r0, r1
	lsrs	r0, r0, #31
	bx	lr
	movs	r0, r0
_08002794: .4byte 0x03001780
_08002798: .4byte 0x00001056

code_2730_end:
