@ GT Advance 3 - converted span
@ Region: file offset 0x025930-0x025CF4 (VMA 0x08025930-0x08025CF4).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080025930, %function
sub_080025930:
_080025930:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #4
	movs	r7, #0
	movs	r0, #0
	mov	sl, r0
	ldr r1, _0800259B0
	movs	r2, #0
	adds	r0, r1, #0
	adds	r0, #124
_08002594A:
	str	r2, [r0, #0]
	subs	r0, #4
	cmp	r0, r1
	bge _08002594A
	movs	r1, #0
	mov	r8, r1
_080025956:
	movs	r6, #0
	movs	r2, #1
	add	r2, r8
	mov	r9, r2
	movs	r3, #0
_080025960:
	movs	r5, #3
	ldr r4, _0800259B4
	adds	r0, r3, r4
	adds	r4, r0, #0
	adds	r4, #72
_08002596A:
	movs	r0, #0
	adds	r1, r6, #0
	adds	r2, r5, #0
	str	r3, [sp, #0]
	bl 0x08025CF4
	ldr	r3, [sp, #0]
	cmp	r0, #0
	ble _08002599C
	movs	r0, #0
	adds	r1, r6, #0
	adds	r2, r5, #0
	bl 0x08025CF4
	ldr	r3, [sp, #0]
	cmp	r0, #3
	bgt _08002599C
	ldr r1, _0800259B8
	mov	r2, r8
	lsls	r0, r2, #1
	adds	r2, r0, r1
	ldrh	r0, [r4, #0]
	ldrh	r1, [r2, #0]
	cmp	r0, r1
	beq _0800259BC
_08002599C:
	adds	r4, #24
	adds	r5, #1
	cmp	r5, #10
	ble _08002596A
_0800259A4:
	mov	r2, sl
	cmp	r2, #1
	bne _0800259D4
	movs	r3, #0
	mov	sl, r3
	b _0800259E0
_0800259B0: .4byte 0x0203F9B0
_0800259B4: .4byte 0x0805FCAC
_0800259B8: .4byte 0x080600CC
_0800259BC:
	ldr r0, _0800259D0
	lsls	r1, r7, #2
	adds	r1, r1, r0
	movs	r4, #0
	ldrsh	r0, [r2, r4]
	str	r0, [r1, #0]
	adds	r7, #1
	movs	r0, #1
	mov	sl, r0
	b _0800259A4
_0800259D0: .4byte 0x0203F9B0
_0800259D4:
	movs	r1, #132
	lsls	r1, r1, #1
	adds	r3, r3, r1
	adds	r6, #1
	cmp	r6, #3
	ble _080025960
_0800259E0:
	mov	r8, r9
	mov	r2, r8
	cmp	r2, #31
	ble _080025956
	movs	r6, #0
	ldr r1, _080025A1C
	ldr r3, _080025A20
	mov	r9, r3
	movs	r4, #72
	add	r4, r9
	mov	r8, r4
	movs	r5, #0
	lsls	r0, r7, #2
	adds	r4, r0, r1
_0800259FC:
	movs	r0, #0
	adds	r1, r6, #0
	bl 0x08025D64
	adds	r1, r0, #0
	subs	r0, r1, #3
	cmp	r0, #7
	bhi _080025A24
	lsls	r0, r1, #1
	adds	r0, r0, r1
	lsls	r0, r0, #3
	adds	r0, r0, r5
	add	r0, r9
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	b _080025A38
_080025A1C: .4byte 0x0203F9B0
_080025A20: .4byte 0x0805FCAC
_080025A24:
	cmp	r1, #2
	bgt _080025A3C
	movs	r0, #0
	bl 0x08025D90
	cmp	r0, r6
	bne _080025A3C
	mov	r2, r8
	movs	r3, #0
	ldrsh	r0, [r2, r3]
_080025A38:
	stmia	r4!, {r0}
	adds	r7, #1
_080025A3C:
	movs	r0, #132
	lsls	r0, r0, #1
	add	r8, r0
	adds	r5, r5, r0
	adds	r6, #1
	cmp	r6, #3
	ble _0800259FC
	ldr r2, _080025A74
	subs	r0, r7, #1
	str	r0, [r2, #0]
	cmp	r0, #0
	bgt _080025A64
	ldr r1, _080025A78
	ldr r0, _080025A7C
	adds	r0, #72
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	str	r0, [r1, #0]
	movs	r0, #0
	str	r0, [r2, #0]
_080025A64:
	add	sp, #4
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080025A74: .4byte 0x0203FA40
_080025A78: .4byte 0x0203F9B0
_080025A7C: .4byte 0x0805FCAC
	.type sub_08025A80, %function
sub_08025A80:
_08025A80:
	ldr r0, _080025A88
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bx	lr
_080025A88: .4byte 0x0203FA40
	.type sub_08025A8C, %function
sub_08025A8C:
_08025A8C:
	ldr r1, _080025A98
	lsls	r0, r0, #2
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bx	lr
_080025A98: .4byte 0x0203F9B0
	.type sub_08025A9C, %function
sub_08025A9C:
_08025A9C:
	adds	r3, r0, #0
	movs	r1, #0
	ldr r2, _080025AB0
_080025AA2:
	ldr	r0, [r2, #0]
	cmp	r3, r0
	bne _080025AB4
	lsls	r0, r1, #16
	asrs	r0, r0, #16
	b _080025ABE
	movs	r0, r0
_080025AB0: .4byte 0x0203F9B0
_080025AB4:
	adds	r2, #4
	adds	r1, #1
	cmp	r1, #31
	ble _080025AA2
	movs	r0, #0
_080025ABE:
	bx	lr
	.type sub_080025AC0, %function
sub_080025AC0:
_080025AC0:
	push	{r4, r5, r6, r7, lr}
	movs	r6, #0
	movs	r4, #0
	ldr r5, _080025AF0
	ldr r7, _080025AF4
_080025ACA:
	adds	r0, r4, #0
	bl 0x08026004
	cmp	r0, #1
	bne _080025ADC
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	stmia	r7!, {r0}
	adds	r6, #1
_080025ADC:
	adds	r5, #8
	adds	r4, #1
	cmp	r4, #2
	ble _080025ACA
	ldr r1, _080025AF8
	subs	r0, r6, #1
	str	r0, [r1, #0]
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080025AF0: .4byte 0x0806010C
_080025AF4: .4byte 0x0203FA30
_080025AF8: .4byte 0x0203FA3C
	.type sub_08025AFC, %function
sub_08025AFC:
_08025AFC:
	ldr r0, _080025B04
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bx	lr
_080025B04: .4byte 0x0203FA3C
	.type sub_08025B08, %function
sub_08025B08:
_08025B08:
	ldr r1, _080025B14
	lsls	r0, r0, #2
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bx	lr
_080025B14: .4byte 0x0203FA30
	.type sub_08025B18, %function
sub_08025B18:
_08025B18:
	adds	r3, r0, #0
	movs	r1, #0
	ldr r2, _080025B2C
_080025B1E:
	ldr	r0, [r2, #0]
	cmp	r3, r0
	bne _080025B30
	lsls	r0, r1, #16
	asrs	r0, r0, #16
	b _080025B3A
	movs	r0, r0
_080025B2C: .4byte 0x0203FA30
_080025B30:
	adds	r2, #4
	adds	r1, #1
	cmp	r1, #2
	ble _080025B1E
	movs	r0, #0
_080025B3A:
	bx	lr
	.type sub_080025B3C, %function
sub_080025B3C:
_080025B3C:
	push	{r4, r5, r6, lr}
	ldr r4, _080025B78
	add	sp, r4
	ldr r1, _080025B7C
	movs	r2, #144
	lsls	r2, r2, #4
	mov	r0, sp
	bl 0x0802E0A4
	ldr r0, _080025B80
	mov	r4, sp
	ldr r1, _080025B84
	adds	r6, r0, r1
	movs	r5, #31
_080025B58:
	adds	r0, r6, #0
	adds	r1, r4, #0
	movs	r2, #72
	bl 0x0802E0A4
	adds	r4, #72
	adds	r6, #72
	subs	r5, #1
	cmp	r5, #0
	bge _080025B58
	movs	r3, #144
	lsls	r3, r3, #4
	add	sp, r3
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
_080025B78: .4byte 0xFFFFF700
_080025B7C: .4byte 0x08060370
_080025B80: .4byte 0x03001780
_080025B84: .4byte 0x000005E4
	.type sub_080025B88, %function
sub_080025B88:
_080025B88:
	push	{r4, r5, r6, lr}
	sub	sp, #216
	ldr r1, _080025BBC
	mov	r0, sp
	movs	r2, #216
	bl 0x0802E0A4
	ldr r0, _080025BC0
	mov	r4, sp
	ldr r1, _080025BC4
	adds	r6, r0, r1
	movs	r5, #2
_080025BA0:
	adds	r0, r6, #0
	adds	r1, r4, #0
	movs	r2, #72
	bl 0x0802E0A4
	adds	r4, #72
	adds	r6, #72
	subs	r5, #1
	cmp	r5, #0
	bge _080025BA0
	add	sp, #216
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
_080025BBC: .4byte 0x08060C70
_080025BC0: .4byte 0x03001780
_080025BC4: .4byte 0x00000EE4
	.type sub_080025BC8, %function
sub_080025BC8:
_080025BC8:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	adds	r4, r1, #0
	movs	r0, #84
	bl 0x0800572C
	str	r0, [r5, #0]
	ldr r1, _080025BEC
	lsls	r0, r4, #2
	adds	r0, r0, r4
	lsls	r0, r0, #2
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	str	r0, [r5, #4]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_080025BEC: .4byte 0x080CD830
	.type sub_08025BF0, %function
sub_08025BF0:
_08025BF0:
	ldr r3, _080025C04
	lsls	r2, r1, #2
	adds	r2, r2, r1
	lsls	r2, r2, #2
	adds	r2, r2, r3
	movs	r3, #0
	ldrsh	r1, [r2, r3]
	str	r1, [r0, #4]
	bx	lr
	movs	r0, r0
_080025C04: .4byte 0x080CD830
	.type sub_08025C08, %function
sub_08025C08:
_08025C08:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	adds	r4, r1, #0
	movs	r0, #182
	bl 0x0800572C
	str	r0, [r5, #0]
	ldr r1, _080025C2C
	lsls	r0, r4, #2
	adds	r0, r0, r4
	lsls	r0, r0, #2
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	str	r0, [r5, #4]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_080025C2C: .4byte 0x080CD830
	.type sub_08025C30, %function
sub_08025C30:
_08025C30:
	push	{r4, r5, lr}
	adds	r4, r0, #0
	adds	r5, r1, #0
	movs	r0, #182
	bl 0x0800572C
	str	r0, [r4, #20]
	ldr r1, _080025C5C
	lsls	r0, r5, #2
	adds	r0, r0, r5
	lsls	r0, r0, #2
	adds	r0, r0, r1
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	str	r1, [r4, #24]
	ldmia	r0!, {r1, r2, r3}
_080025C50:
	stmia	r4!, {r1, r2, r3}
	ldmia	r0!, {r1, r3}
	stmia	r4!, {r1, r3}
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_080025C5C: .4byte 0x080CD830
	.type sub_080025C60, %function
sub_080025C60:
_080025C60:
	push	{r4, lr}
	ldr r3, _080025C80
	lsls	r2, r1, #2
	adds	r2, r2, r1
_080025C68:
	lsls	r2, r2, #2
	adds	r2, r2, r3
	movs	r3, #0
	ldrsh	r1, [r2, r3]
	str	r1, [r0, #24]
	ldmia	r2!, {r1, r3, r4}
	stmia	r0!, {r1, r3, r4}
	ldmia	r2!, {r1, r4}
	stmia	r0!, {r1, r4}
	pop	{r4}
	pop	{r0}
	bx	r0
_080025C80: .4byte 0x080CD830
	.type sub_08025C84, %function
sub_08025C84:
_08025C84:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #4
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r6, r2, #0
	adds	r7, r3, #0
_080025C90:
	ldr r1, _080025CEC
	mov	r0, sp
	movs	r2, #4
	bl 0x0802E0A4
	movs	r0, #44
	muls	r0, r4
	movs	r1, #11
	muls	r1, r5
	adds	r0, r0, r1
	adds	r4, r0, r6
	movs	r0, #3
	ands	r7, r0
	adds	r0, r4, #0
	movs	r1, #4
	bl 0x0802D97C
	adds	r1, r0, #0
	ldr r2, _080025CF0
	adds	r0, r4, #0
	cmp	r4, #0
	bge _080025CBE
	adds	r0, r4, #3
_080025CBE:
	asrs	r0, r0, #2
_080025CC0:
	adds	r5, r0, r2
	mov	r2, sp
	adds	r0, r2, r1
	ldrb	r1, [r5, #0]
	ldrb	r0, [r0, #0]
	bics	r1, r0
	adds	r0, r1, #0
	strb	r0, [r5, #0]
	adds	r0, r4, #0
	movs	r1, #4
	bl 0x0802D97C
	lsls	r0, r0, #1
	lsls	r7, r0
	ldrb	r2, [r5, #0]
	orrs	r7, r2
	strb	r7, [r5, #0]
	add	sp, #4
_080025CE4:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080025CEC: .4byte 0x08060D48
_080025CF0: .4byte 0x03001780

@ Byte-neutral end label for the promoted _080025C84 span (0x08025C84-0x08025CF4).
@ The body runs to end-of-region, so the splice needs an explicit terminator;
@ a bare label emits no bytes and leaves the executable region identical.
code_25930_end:
