@ GT Advance 3 - converted span
@ Region: file offset 0x023628-0x02381C (VMA 0x08023628-0x0802381C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080023628, %function
sub_080023628:
_080023628:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #36
	adds	r7, r0, #0
	movs	r0, #51
	bl 0x0802B214
	ldr r0, _0800237F8
	mov	r8, r0
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r6, #1
	str	r6, [sp, #4]
	movs	r0, #0
	mov	r1, r8
	movs	r2, #0
	movs	r3, #0
	bl 0x08007770
	ldr r5, _0800237FC
	movs	r1, #0
	str	r1, [sp, #0]
	movs	r0, #3
	str	r0, [sp, #4]
	movs	r0, #1
	adds	r1, r5, #0
	movs	r2, #3
	movs	r3, #0
	bl 0x08007770
	movs	r2, #6
	str	r2, [r7, #88]
	movs	r0, #21
	mov	r9, r0
	str	r0, [r7, #100]
	str	r6, [r7, #112]
	movs	r1, #16
	adds	r1, r1, r7
	mov	sl, r1
	mov	r0, sl
	bl 0x0800DAB8
	ldr r4, _080023800
	adds	r0, r4, #0
	movs	r1, #1
	movs	r2, #0
	movs	r3, #4
	bl 0x08007614
	adds	r0, r4, #0
	movs	r1, #1
	movs	r2, #1
	movs	r3, #5
	bl 0x08007614
	mov	r0, r8
	adds	r1, r7, #0
	bl 0x0800798C
	adds	r0, r7, #0
	bl 0x08007A58
	adds	r1, r7, #0
	adds	r1, #8
	adds	r0, r5, #0
	bl 0x0800798C
	adds	r0, r5, #0
	movs	r1, #0
	movs	r2, #6
	bl 0x080075E8
	adds	r4, r7, #0
	adds	r4, #196
	adds	r0, r4, #0
	movs	r1, #5
	bl 0x08025BC8
	ldr	r0, [r7, #12]
	adds	r1, r7, #0
	adds	r1, #200
	ldr	r1, [r1, #0]
	ldr	r2, [r4, #0]
	bl 0x08007ABC
	movs	r0, #8
	bl 0x0800572C
	adds	r2, r7, #0
	adds	r2, #208
	str	r0, [r2, #0]
	adds	r1, r7, #0
	adds	r1, #212
	movs	r0, #22
	str	r0, [r1, #0]
	ldr	r0, [r7, #12]
	ldr	r2, [r2, #0]
	movs	r1, #22
	bl 0x08007ABC
	movs	r0, #8
	bl 0x0800572C
	adds	r1, r7, #0
	adds	r1, #220
	str	r0, [r1, #0]
	adds	r0, r7, #0
	adds	r0, #224
	mov	r2, r9
	str	r2, [r0, #0]
	ldr	r0, [r7, #12]
	ldr	r2, [r1, #0]
	movs	r1, #21
	bl 0x08007ABC
	adds	r0, r7, #0
	adds	r0, #128
	subs	r4, #28
	str	r4, [r0, #0]
	adds	r0, #4
	mov	r1, sl
	str	r1, [r0, #0]
	movs	r2, #0
	str	r2, [r7, #16]
	strh	r6, [r7, #20]
	subs	r0, #96
	subs	r2, #32
	movs	r1, #0
	bl 0x0800D77C
	adds	r0, r7, #0
	adds	r0, #28
	movs	r1, #0
	movs	r2, #160
	bl 0x0800D77C
	movs	r0, #6
	strh	r0, [r7, #24]
	movs	r0, #5
	strh	r0, [r7, #26]
	adds	r2, r7, #0
	adds	r2, #148
	ldr r0, _080023804
	str	r0, [r2, #0]
	adds	r1, r7, #0
	adds	r1, #152
	ldr r0, _080023808
	str	r0, [r1, #0]
	ldr	r6, [r2, #0]
	movs	r3, #0
	str	r4, [sp, #28]
	movs	r1, #142
	adds	r1, r1, r7
	mov	sl, r1
	adds	r2, #8
	str	r2, [sp, #16]
	adds	r0, r7, #0
	adds	r0, #158
	str	r0, [sp, #20]
	adds	r1, r7, #0
	adds	r1, #160
	str	r1, [sp, #24]
	subs	r2, #10
	str	r2, [sp, #8]
	adds	r7, #240
	str	r7, [sp, #12]
	ldr r0, _08002380C
	mov	r9, r0
_08002377E:
	lsls	r7, r3, #3
	adds	r1, r3, #1
	mov	r8, r1
	adds	r0, r7, r3
	lsls	r0, r0, #3
	movs	r4, #4
	mov	r2, r9
	adds	r5, r2, r0
_08002378E:
	adds	r0, r5, #0
	adds	r1, r6, #0
	ldr r2, _080023810
	str	r3, [sp, #32]
	bl 0x0802D974
	adds	r6, #12
	adds	r5, #12
	subs	r4, #1
	ldr	r3, [sp, #32]
	cmp	r4, #0
	bge _08002378E
	adds	r0, r7, r3
	lsls	r0, r0, #3
	ldr r1, _080023814
	adds	r0, r0, r1
	adds	r1, r6, #0
	ldr r2, _080023810
	bl 0x0802D974
	adds	r6, #12
	mov	r3, r8
	cmp	r3, #34
	ble _08002377E
	movs	r1, #0
	movs	r0, #2
	ldr	r2, [sp, #28]
	str	r0, [r2, #0]
	mov	r0, sl
	strh	r1, [r0, #0]
	ldr	r2, [sp, #16]
	strh	r1, [r2, #0]
	ldr	r0, [sp, #20]
	strh	r1, [r0, #0]
	ldr	r2, [sp, #24]
	strh	r1, [r2, #0]
	ldr	r0, [sp, #8]
	strh	r1, [r0, #0]
	ldr r0, _080023818
	bl 0x08002124
	movs	r0, #1
	ldr	r1, [sp, #12]
	str	r0, [r1, #0]
	add	sp, #36
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800237F8: .4byte 0x0839F5FC
_0800237FC: .4byte 0x082B7410
_080023800: .4byte 0x082A798C
_080023804: .4byte 0x02024EC0
_080023808: .4byte 0x02020000
_08002380C: .4byte 0x03001D64
_080023810: .4byte 0x04000003
_080023814: .4byte 0x03001DA0
_080023818: .4byte 0x0000138D
