@ GT Advance 3 - converted span
@ Region: file offset 0x00C668-0x00C7F4 (VMA 0x0800C668-0x0800C7F4).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_0800C668, %function
sub_0800C668:
_0800C668:
	push	{lr}
	adds	r2, r0, #0
	subs	r0, r1, #1
	cmp	r0, #7
	bhi _0800C6C2
	lsls	r0, r0, #2
	ldr r1, _0800C67C
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
_0800C67C: .4byte 0x0800C680
_0800C680: .4byte 0x0800C6A0
_0800C684: .4byte 0x0800C6A0
_0800C688: .4byte 0x0800C6A8
_0800C68C: .4byte 0x0800C6A8
_0800C690: .4byte 0x0800C6B8
_0800C694: .4byte 0x0800C6B8
_0800C698: .4byte 0x0800C6B8
_0800C69C: .4byte 0x0800C6B8
_0800C6A0:
	ldr r1, _0800C6A4
	b _0800C6AA
_0800C6A4: .4byte 0x000025E4
_0800C6A8:
	ldr r1, _0800C6B4
_0800C6AA:
	adds	r0, r2, r1
	ldr	r0, [r0, #0]
	bl 0x08004EF0
	b _0800C6C2
_0800C6B4: .4byte 0x000025E8
_0800C6B8:
	ldr r1, _0800C6C8
	adds	r0, r2, r1
	ldr	r0, [r0, #0]
	bl 0x08004EF0
_0800C6C2:
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800C6C8: .4byte 0x000025EC
	.type sub_0800C6CC, %function
sub_0800C6CC:
_0800C6CC:
	push	{lr}
	adds	r2, r0, #0
	subs	r0, r1, #1
	cmp	r0, #7
	bhi _0800C726
	lsls	r0, r0, #2
	ldr r1, _0800C6E0
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
_0800C6E0: .4byte 0x0800C6E4
_0800C6E4: .4byte 0x0800C704
_0800C6E8: .4byte 0x0800C704
_0800C6EC: .4byte 0x0800C70C
_0800C6F0: .4byte 0x0800C70C
_0800C6F4: .4byte 0x0800C71C
_0800C6F8: .4byte 0x0800C71C
_0800C6FC: .4byte 0x0800C71C
_0800C700: .4byte 0x0800C71C
_0800C704:
	ldr r1, _0800C708
	b _0800C70E
_0800C708: .4byte 0x000025E4
_0800C70C:
	ldr r1, _0800C718
_0800C70E:
	adds	r0, r2, r1
	ldr	r0, [r0, #0]
	bl 0x08004EF0
	b _0800C726
_0800C718: .4byte 0x000025E8
_0800C71C:
	ldr r1, _0800C72C
	adds	r0, r2, r1
	ldr	r0, [r0, #0]
	bl 0x08004EF0
_0800C726:
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800C72C: .4byte 0x000025EC
	.type sub_0800C730, %function
sub_0800C730:
_0800C730:
	push	{lr}
	adds	r0, #96
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _0800C740
	movs	r0, #1
	bl 0x08004ED8
_0800C740:
	pop	{r0}
	bx	r0
	.type sub_0800C744, %function
sub_0800C744:
_0800C744:
	push	{lr}
	adds	r2, r1, #0
	subs	r0, #1
	cmp	r0, #20
	bhi _0800C7EE
	lsls	r0, r0, #2
	ldr r1, _0800C758
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
_0800C758: .4byte 0x0800C75C
_0800C75C: .4byte 0x0800C7B0
_0800C760: .4byte 0x0800C7EE
_0800C764: .4byte 0x0800C7B8
_0800C768: .4byte 0x0800C7C0
_0800C76C: .4byte 0x0800C7EE
_0800C770: .4byte 0x0800C7EE
_0800C774: .4byte 0x0800C7EE
_0800C778: .4byte 0x0800C7C8
_0800C77C: .4byte 0x0800C7EE
_0800C780: .4byte 0x0800C7EE
_0800C784: .4byte 0x0800C7EE
_0800C788: .4byte 0x0800C7EE
_0800C78C: .4byte 0x0800C7D0
_0800C790: .4byte 0x0800C7DA
_0800C794: .4byte 0x0800C7EE
_0800C798: .4byte 0x0800C7EE
_0800C79C: .4byte 0x0800C7EE
_0800C7A0: .4byte 0x0800C7EE
_0800C7A4: .4byte 0x0800C7EE
_0800C7A8: .4byte 0x0800C7EE
_0800C7AC: .4byte 0x0800C7E4
_0800C7B0:
	adds	r0, r3, #0
	bl 0x0800C4D0
	b _0800C7EE
_0800C7B8:
	adds	r0, r3, #0
	bl 0x0800C604
	b _0800C7EE
_0800C7C0:
	adds	r0, r3, #0
	bl 0x0800C640
	b _0800C7EE
_0800C7C8:
	adds	r0, r3, #0
	bl 0x0800C658
	b _0800C7EE
_0800C7D0:
	adds	r0, r3, #0
	adds	r1, r2, #0
	bl sub_0800C668
	b _0800C7EE
_0800C7DA:
	adds	r0, r3, #0
	adds	r1, r2, #0
	bl sub_0800C6CC
	b _0800C7EE
_0800C7E4:
	lsls	r1, r2, #16
	lsrs	r1, r1, #16
	adds	r0, r3, #0
	bl sub_0800C730
_0800C7EE:
	pop	{r0}
	bx	r0
	.hword 0x0000
