@ GT Advance 3 - converted span
@ Region: file offset 0x002254-0x0022E4 (VMA 0x08002254-0x080022E4).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08002254, %function
sub_08002254:
_08002254:
	push	{lr}
	ldr r0, _08002268
	ldr	r1, [r0, #0]
	movs	r0, #0
	strb	r0, [r1, #0]
	bl 0x080016D0
	pop	{r0}
	bx	r0
	movs	r0, r0
_08002268: .4byte 0x030000F4
.type _0800226C, %function
_0800226C:
	push	{r4, r5, lr}
	adds	r4, r0, #0
	adds	r5, r1, #0
	ldr r2, _08002294
	ldr	r1, [r2, #0]
	movs	r0, #1
	strb	r0, [r1, #1]
	ldr	r0, [r2, #0]
	movs	r1, #8
	ldrsh	r0, [r0, r1]
	bl 0x08001F80
	adds	r0, r4, #0
	adds	r1, r5, #0
	bl 0x08001EC8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08002294: .4byte 0x030000F4
.type _08002298, %function
_08002298:
	push	{r4, lr}
	adds	r4, r0, #0
	ldr r2, _080022BC
	ldr	r1, [r2, #0]
	movs	r0, #1
	strb	r0, [r1, #1]
	ldr	r0, [r2, #0]
	movs	r1, #8
	ldrsh	r0, [r0, r1]
	bl 0x08001F80
	adds	r0, r4, #0
	bl 0x08001F08
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080022BC: .4byte 0x030000F4
.type _080022C0, %function
_080022C0:
	push	{lr}
	bl 0x08001F3C
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_080022CC, %function
sub_080022CC:
_080022CC:
	push	{lr}
	bl 0x08001CB4
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_080022D8, %function
sub_080022D8:
_080022D8:
	push	{lr}
	bl 0x08001E14
	pop	{r1}
	bx	r1
	.hword 0x0000
code_2254_end:
