@ GT Advance 3 - converted span
@ Region: file offset 0x0022E4-0x002430 (VMA 0x080022E4-0x08002430).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

_080022E4:
	lsls	r0, r0, #16
	asrs	r1, r0, #16
	ldr r2, _080022F8
	adds	r0, r0, r2
	lsrs	r0, r0, #16
	cmp	r0, #97
	bls _080022FC
	movs	r0, #1
	negs	r0, r0
	b _08002306
_080022F8: .4byte 0xFFFF0000
_080022FC:
	.hword 0x4802
	lsls	r1, r1, #1
	adds	r1, r1, r0
	movs	r2, #0
	ldrsh	r0, [r1, r2]
_08002306:
	bx	lr
_08002308: .4byte 0x080C43EC
	lsls	r0, r0, #16
	asrs	r2, r0, #16
	ldr r1, _08002338
	adds	r0, r0, r1
	lsrs	r0, r0, #16
	cmp	r0, #97
	bhi _08002334
	ldr r1, _0800233C
	lsls	r0, r2, #1
	adds	r0, r0, r1
	ldrh	r2, [r0, #0]
	movs	r3, #0
	ldrsh	r1, [r0, r3]
	movs	r0, #1
	negs	r0, r0
	cmp	r1, r0
	bne _08002330
	movs	r2, #23
_08002330:
	lsls	r0, r2, #16
	asrs	r0, r0, #16
_08002334:
	bx	lr
	movs	r0, r0
_08002338: .4byte 0xFFFF0000
_0800233C: .4byte 0x080C43EC
	.type _08002340, %function
_08002340:
	push	{r4, r5, r6, lr}
	movs	r5, #0
	lsls	r0, r0, #16
	asrs	r6, r0, #16
_08002348:
	lsls	r0, r5, #16
	asrs	r4, r0, #16
	adds	r0, r4, #0
	bl _080022E4
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, r6
	bne _0800235E
	adds	r0, r4, #0
	b _08002368
_0800235E:
	adds	r5, #1
	cmp	r5, #98
	ble _08002348
	movs	r0, #1
	negs	r0, r0
_08002368:
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_08002370, %function
sub_08002370:
_08002370:
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	lsls	r1, r0, #3
	subs	r1, r1, r0
	ldr r0, _08002380
	adds	r1, r1, r0
	adds	r0, r1, #0
	bx	lr
_08002380: .4byte 0x080C44B2
	.type sub_08002384, %function
sub_08002384:
_08002384:
	bx	lr
	movs	r0, r0
	.type sub_08002388, %function
sub_08002388:
_08002388:
	push	{lr}
	bl 0x08000A60
	ldr r3, _080023A4
	movs	r0, #0
	strh	r0, [r3, #0]
	ldr r2, _080023A8
	ldrh	r0, [r2, #0]
	movs	r1, #1
	orrs	r0, r1
	strh	r0, [r2, #0]
	strh	r1, [r3, #0]
	pop	{r0}
	bx	r0
_080023A4: .4byte 0x04000208
_080023A8: .4byte 0x03007FF8
	.type sub_080023AC, %function
sub_080023AC:
_080023AC:
	push	{lr}
	bl 0x08002A3C
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080023B8, %function
sub_080023B8:
_080023B8:
	push	{lr}
	bl 0x08002A80
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080023C4, %function
sub_080023C4:
_080023C4:
	push	{r4, lr}
	ldr r0, _08002408
	movs	r1, #0
	strh	r1, [r0, #0]
	ldr r0, _0800240C
	strh	r1, [r0, #0]
	ldr r0, _08002410
	strh	r1, [r0, #0]
	ldr r1, _08002414
	ldr r2, _08002418
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	movs	r4, #0
_080023DE:
	adds	r0, r4, #0
	movs	r1, #0
	bl sub_080023AC
	adds	r4, #1
	cmp	r4, #9
	ble _080023DE
	ldr r1, _0800241C
	movs	r0, #0
	bl sub_080023AC
	ldr r1, _08002420
	movs	r0, #1
	bl sub_080023AC
	bl sub_080023B8
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08002408: .4byte 0x04000208
_0800240C: .4byte 0x04000004
_08002410: .4byte 0x04000200
_08002414: .4byte 0x04000202
_08002418: .4byte 0x0000FFFF
_0800241C: .4byte 0x0203EE71
_08002420: .4byte 0x08002389
	.type sub_08002424, %function
sub_08002424:
_08002424:
	push	{lr}
	bl 0x08002AAC
	pop	{r0}
	bx	r0
	.hword 0x0000
code_22e4_end:
