@ GT Advance 3 - converted span
@ Region: file offset 0x023E0C-0x023E7C (VMA 0x08023E0C-0x08023E7C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080023E0C, %function
sub_080023E0C:
_080023E0C:
	push	{r4, r5, r6, r7, lr}
	adds	r7, r0, #0
	adds	r0, #136
	movs	r1, #15
	bl 0x0800D97C
	ldr r4, _080023E74
	adds	r5, r7, #0
	adds	r5, #140
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	lsls	r0, r0, #3
	adds	r6, r4, #4
	adds	r0, r0, r6
	ldr	r1, [r0, #0]
	adds	r0, r7, #0
	adds	r0, #168
	ldr	r2, [r0, #0]
	adds	r0, r7, #0
	bl 0x08023AE4
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	lsls	r0, r0, #3
	adds	r4, r0, r4
	ldr	r1, [r4, #0]
	adds	r0, r0, r6
	ldr	r2, [r0, #0]
	adds	r0, r7, #0
	bl 0x08023B60
	adds	r0, r7, #0
	adds	r0, #16
	bl 0x0800DBE8
	adds	r0, r7, #0
	adds	r0, #144
	ldrh	r0, [r0, #0]
	cmp	r0, #1
	bne _080023E68
	adds	r1, r7, #0
	adds	r1, #176
	adds	r0, r7, #0
	movs	r2, #64
	bl 0x08022D44
_080023E68:
	adds	r0, r7, #0
	bl sub_080023E78
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080023E74: .4byte 0x080CC178
	.type sub_080023E78, %function
sub_080023E78:
_080023E78:
	bx	lr
	.hword 0x0000

code_23e0c_end:
