@ GT Advance 3 - converted span
@ Region: file offset 0x024E54-0x024F34 (VMA 0x08024E54-0x08024F34).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080024E54, %function
sub_080024E54:
_080024E54:
	push	{r4, r5, lr}
	sub	sp, #28
	mov	r2, sp
	ldr r1, _080024E78
	ldmia	r1!, {r3, r4, r5}
	stmia	r2!, {r3, r4, r5}
	ldmia	r1!, {r3, r4, r5}
	stmia	r2!, {r3, r4, r5}
	ldr	r1, [r1, #0]
	str	r1, [r2, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #14
	add	r0, sp
	ldr	r0, [r0, #0]
	add	sp, #28
	pop	{r4, r5}
	pop	{r1}
	bx	r1
_080024E78: .4byte 0x0805FC90
	.type sub_080024E7C, %function
sub_080024E7C:
_080024E7C:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	sub	sp, #28
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	mov	ip, r0
	movs	r7, #0
	mov	r1, sp
	ldr r0, _080024ED0
	ldmia	r0!, {r2, r3, r4}
	stmia	r1!, {r2, r3, r4}
	ldmia	r0!, {r2, r3, r6}
	stmia	r1!, {r2, r3, r6}
	ldr	r0, [r0, #0]
	str	r0, [r1, #0]
	movs	r4, #1
	negs	r4, r4
	mov	r8, r4
	mov	r5, sp
_080024EA6:
	ldr	r1, [r5, #0]
	ldrh	r2, [r1, #0]
	movs	r6, #0
	ldrsh	r0, [r1, r6]
	cmp	r0, r8
	beq _080024EE0
	mov	r3, ip
	lsls	r0, r3, #16
	asrs	r4, r0, #16
	lsls	r0, r7, #16
	asrs	r3, r0, #16
	movs	r6, #1
	negs	r6, r6
	mov	r9, r6
_080024EC2:
	lsls	r0, r2, #16
	asrs	r0, r0, #16
	cmp	r0, r4
	bne _080024ED4
	adds	r0, r3, #0
	b _080024EEC
	movs	r0, r0
_080024ED0: .4byte 0x0805FC90
_080024ED4:
	adds	r1, #2
	ldrh	r2, [r1, #0]
	movs	r6, #0
	ldrsh	r0, [r1, r6]
	cmp	r0, r9
	bne _080024EC2
_080024EE0:
	adds	r5, #4
	adds	r7, #1
	cmp	r7, #6
	ble _080024EA6
	movs	r0, #1
	negs	r0, r0
_080024EEC:
	add	sp, #28
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_080024EFC, %function
sub_080024EFC:
_080024EFC:
	push	{lr}
	sub	sp, #4
	movs	r0, #0
	str	r0, [sp, #0]
	ldr r1, _080024F14
	ldr r2, _080024F18
	mov	r0, sp
	bl 0x0802D974
	add	sp, #4
	pop	{r0}
	bx	r0
_080024F14: .4byte 0x030015D8
_080024F18: .4byte 0x05000003
@ Entry label for the leaf at 0x08024F1C. `_080024F24` below is its POOL
@ word, not its address, which is why the body had no entry: the inventory
@ admits only `.type %function` or a `bl` target, so `sub_080024EFC`'s span ran
@ through both leaves and its 32-byte body could never score EXACT. Zero bytes.
	.type _08024F1C, %function
_08024F1C:
	ldr r2, _080024F24
	adds	r0, r0, r2
	strb	r1, [r0, #0]
	bx	lr
_080024F24: .4byte 0x030015D8
	.type _08024F28, %function
_08024F28:
	ldr r1, _080024F30
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	bx	lr
_080024F30: .4byte 0x030015D8
@ End-of-region anchor for the splicer. This file declares exactly one
@ `@ Region:` (0x08024E54-0x08024F34), has no `.include`, and ends at
@ 0x08024F34 -- the same address the body at 0x08024F28 ends on. The
@ boundary is unambiguous, so the EOF anchor is a real end marker rather than
@ the destructive guess `promotion_screen` refuses to invent. Zero bytes.
code_24e54_end:
