@ GT Advance 3 - converted span
@ Region: file offset 0x004CC4-0x004CD4 (VMA 0x08004CC4-0x08004CD4).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	ldr r0, _08004CD0
	adds	r0, #112
	movs	r1, #0
	strh	r1, [r0, #0]
	bx	lr
	movs	r0, r0
_08004CD0: .4byte 0x03000198
