@ GT Advance 3 - converted span
@ Region: file offset 0x026F30-0x026F50 (VMA 0x08026F30-0x08026F50).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080026F30, %function
sub_080026F30:
_080026F30:
	push	{r4, r5, r6, lr}
	adds	r4, r0, #0
	adds	r6, r1, #0
	movs	r0, #64
	bl 0x0800572C
	adds	r5, r0, #0
	adds	r1, r4, #0
	adds	r2, r6, #0
	bl 0x08026F50
	adds	r0, r5, #0
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	.hword 0x0000
code_26f30_end:
