@ GT Advance 3 - converted span
@ Region: file offset 0x0261D4-0x026230 (VMA 0x080261D4-0x08026230).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

@ Three of these leaves had NO entry label, so the inventory saw one 72-byte
@ span starting at _080261C4 (asm/ai_award_mid.s) instead of four functions.
@ Their bytes were then scored against a stranger's instructions, and each one
@ has a byte-exact C body in src/ai_award_leaves.c. Adding the labels is
@ byte-neutral: it changes only the census, not a single ROM byte. Each is a
@ real entry -- a prologue-less leaf ending in `bx lr` with its own pool word,
@ and `0x080261D4`/`0x080261E8`/`0x080261F8` are each 20/16/20 bytes.
.type _080261D4, %function
_080261D4:
sub_080261D4:
	ldr r1, _0800261E4
	lsls	r0, r0, #16
	asrs	r0, r0, #13
	adds	r0, r0, r1
	movs	r1, #2
	ldrsh	r0, [r0, r1]
	bx	lr
	movs	r0, r0
_0800261E4: .4byte 0x030015F0
.type _080261E8, %function
_080261E8:
sub_080261E8:
	ldr r2, _0800261F4
	lsls	r0, r0, #16
	asrs	r0, r0, #13
	adds	r0, r0, r2
	strh	r1, [r0, #4]
	bx	lr
_0800261F4: .4byte 0x030015F0
.type _080261F8, %function
_080261F8:
sub_080261F8:
	ldr r1, _080026208
	lsls	r0, r0, #16
	asrs	r0, r0, #13
	adds	r0, r0, r1
	movs	r1, #4
	ldrsh	r0, [r0, r1]
	bx	lr
	movs	r0, r0
_080026208: .4byte 0x030015F0
	.type _0802620C, %function
_0802620C:
	push	{lr}
	ldr r2, _08002621C
	str	r0, [r2, #0]
	str	r1, [r0, #0]
	bl _08026220
	pop	{r0}
	bx	r0
_08002621C: .4byte 0x03001670
_08026220:
	ldr r0, _08002622C
	ldr	r1, [r0, #0]
	ldr	r0, [r1, #0]
	str	r0, [r1, #4]
	bx	lr
	movs	r0, r0
_08002622C: .4byte 0x03001670

@ End of region 0x080261D4-0x08026230. _08026220's span ends exactly here,
@ so this anchor is the precise end marker, not a bounded-region guess.
code_261d4_end:
