@ GT Advance 3 - converted span
@ Region: file offset 0x002A3C-0x002A68 (VMA 0x08002A3C-0x08002A68).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	adds	r3, r0, #0
	adds	r2, r1, #0
	cmp	r2, #0
	beq _08002A54
	ldr r1, _08002A50
	lsls	r0, r3, #2
	adds	r0, r0, r1
	str	r2, [r0, #0]
	b _08002A5E
	movs	r0, r0
_08002A50: .4byte 0x0203F170
_08002A54:
	ldr r0, _08002A60
	lsls	r1, r3, #2
	adds	r1, r1, r0
	ldr r0, _08002A64
	str	r0, [r1, #0]
_08002A5E:
	bx	lr
_08002A60: .4byte 0x0203F170
_08002A64: .4byte 0x080029D5
