@ GT Advance 3 - converted span
@ Region: file offset 0x004CD4-0x004CF0 (VMA 0x08004CD4-0x08004CF0).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	ldr r1, _08004CEC
	adds	r2, r1, #0
	adds	r2, #112
	adds	r1, #116
	ldrh	r3, [r2, #0]
	adds	r1, r3, r1
	strb	r0, [r1, #0]
	ldrh	r0, [r2, #0]
	adds	r0, #1
	strh	r0, [r2, #0]
	bx	lr
	movs	r0, r0
_08004CEC: .4byte 0x03000198
