@ GT Advance 3 - converted span
@ Region: file offset 0x0057D0-0x00580C (VMA 0x080057D0-0x0800580C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080057D0, %function
sub_080057D0:
_080057D0:
	push	{lr}
	adds	r1, r0, #0
	ldr r0, _080057EC
	ldr r2, _080057F0
	str	r2, [r0, #0]
	str	r1, [r2, #4]
	movs	r0, #0
	str	r0, [r2, #0]
	cmp	r1, #1
	beq _080057F4
	cmp	r1, #2
	beq _080057FE
	b _08005806
	movs	r0, r0
_080057EC: .4byte 0x030003AC
_080057F0: .4byte 0x03000320
_080057F4:
	str	r0, [r2, #8]
	movs	r0, #4
	bl 0x0802D9B8
	b _08005806
_080057FE:
	str	r0, [r2, #8]
	movs	r0, #64
	bl 0x0802D9B8
_08005806:
	pop	{r0}
	bx	r0
	.hword 0x0000
@ Region-final synthetic end label (cf. boot_end:, idle_end:, code_2254_end:).
@ Byte-neutral: emits no instruction. The region header fixes the span at
@ 0x080057D0-0x0800580C, and this is the only.type in the file, so the body
@ needs a same-file end marker and the manifest has no cross-file precedent.
code_57d0_end:
