@ GT Advance 3 - converted span
@ Region: file offset 0x00295C-0x002A3C (VMA 0x0800295C-0x08002A3C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_0800295C, %function
sub_0800295C:
_0800295C:
	push	{r4, r5, lr}
	ldr r2, _080029B0
	str	r0, [r2, #0]
	str	r1, [r2, #4]
	ldr r4, _080029B4
	movs	r5, #0
	strh	r5, [r4, #0]
	ldr r3, _080029B8
	ldrh	r1, [r3, #0]
	ldr r0, _080029BC
	ands	r0, r1
	strh	r0, [r3, #0]
	ldr r2, _080029C0
	ldrh	r1, [r2, #0]
	ldr r0, _080029C4
	ands	r0, r1
	strh	r0, [r2, #0]
	movs	r0, #1
	strh	r0, [r4, #0]
	ldr r1, _080029C8
	ldr r0, _080029CC
	strh	r5, [r0, #0]
	movs	r0, #0
	str	r0, [r1, #0]
	str	r0, [r1, #4]
	str	r0, [r1, #8]
	ldr r1, _080029D0
	adds	r0, r1, #0
	strh	r0, [r3, #0]
	movs	r0, #8
	strh	r0, [r2, #0]
	bl 0x080028CC
_0800299E:
	bl 0x08002910
	bl 0x08002924
	bl 0x0802D9B0
	bl 0x08002950
	b _0800299E
_080029B0: .4byte 0x030035D0
_080029B4: .4byte 0x04000208
_080029B8: .4byte 0x04000200
_080029BC: .4byte 0x0000FFFC
_080029C0: .4byte 0x04000004
_080029C4: .4byte 0x0000FFE7
_080029C8: .4byte 0x040000D4
_080029CC: .4byte 0x040000DE
_080029D0: .4byte 0x00002001
	bx	lr
	movs	r0, r0
	.type sub_080029D8, %function
sub_080029D8:
_080029D8:
	push	{r4, lr}
	ldr r1, _080029FC
	ldr r4, _08002A00
	ldrh	r0, [r4, #0]
	movs	r3, #0
	strh	r0, [r1, #56]
	ldr r2, _08002A04
	ldrh	r0, [r2, #0]
	strh	r0, [r1, #58]
	strh	r3, [r4, #0]
	strh	r3, [r2, #0]
	ldr r0, _08002A08
	movs	r2, #28
	bl 0x0802D974
	pop	{r4}
	pop	{r0}
	bx	r0
_080029FC: .4byte 0x030000F8
_08002A00: .4byte 0x04000200
_08002A04: .4byte 0x04000004
_08002A08: .4byte 0x0203F170
.type _08002A0C, %function
_08002A0C:
	push	{r4, lr}
	ldr r4, _08002A2C
	ldr r1, _08002A30
	adds	r0, r4, #0
	movs	r2, #28
	bl 0x0802D974
	ldr r1, _08002A34
	ldrh	r0, [r4, #58]
	strh	r0, [r1, #0]
	ldr r1, _08002A38
	ldrh	r0, [r4, #56]
	strh	r0, [r1, #0]
	pop	{r4}
	pop	{r0}
	bx	r0
_08002A2C: .4byte 0x030000F8
_08002A30: .4byte 0x0203F170
_08002A34: .4byte 0x04000004
_08002A38: .4byte 0x04000200

@ End of region 0x08002A3C. The last function here ends exactly at 0x08002A3C, where
@ the next region file's prologue begins, so this anchor is the precise
@ end marker -- not a bounded-region guess. Without it the last body in
@ this file has no end marker to fall back on and the promotion screen
@ refuses it. Emits no bytes; the following file supplies the address.
code_295c_end:
