@ GT Advance 3 - converted span
@ Region: file offset 0x018ADC-0x01A008 (VMA 0x08018ADC-0x0801A008).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_080018ADC, %function
sub_080018ADC:
_080018ADC:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #32
	ldr r4, _080018B00
	movs	r5, #128
	lsls	r5, r5, #3
	adds	r0, r5, #0
	bl 0x08018ACC
	cmp	r0, #0
	beq _080018B04
	movs	r0, #1
	strb	r0, [r4, #31]
	adds	r0, r5, #0
	movs	r1, #0
	bl 0x08018AA8
	b _080018B06
	movs	r0, r0
_080018B00: .4byte 0x03004E80
_080018B04:
	strb	r0, [r4, #31]
_080018B06:
	movs	r1, #140
_080018B08: .4byte 0x18600049
	ldr	r0, [r0, #0]
	ldr r5, _080018B64
	ldr	r2, [r5, #0]
	ldr	r1, [r4, #8]
	ldr	r2, [r2, #8]
	subs	r1, r1, r2
_080018B18: .4byte 0xFCDEF00D
	adds	r2, r0, #0
	ldr	r3, [r5, #0]
	adds	r1, r3, #0
	adds	r1, #148
	ldr	r0, [r1, #0]
	cmp	r2, r0
	beq _080018B3A
	str	r2, [r1, #0]
	adds	r0, r3, #0
	adds	r0, #132
	movs	r3, #0
	ldrsh	r1, [r0, r3]
	adds	r0, r2, #0
	bl 0x080263E0
_080018B3A:
	ldrb	r0, [r4, #31]
_080018B3C: .4byte 0xD0142800
	ldrh	r0, [r4, #26]
	ldr	r2, [r5, #0]
	ldr	r1, [r4, #8]
	ldr	r2, [r2, #8]
	subs	r1, r1, r2
	bl 0x080267FC
	adds	r3, r0, #0
	cmp	r3, #0
	beq _080018B68
	ldr	r0, [r5, #0]
	adds	r0, #86
	movs	r2, #0
	ldrsh	r1, [r0, r2]
_080018B5C: .4byte 0xF00D1C18
	.hword 0xFE83
	b _080018B6A
_080018B64: .4byte 0x03004E20
_080018B68:
	strb	r3, [r4, #31]
_080018B6A:
	ldr r0, _080018C30
	mov	r1, sp
	movs	r2, #8
	bl 0x0802D970
	ldrb	r0, [r4, #30]
	cmp	r0, #0
	beq _080018B80
	mov	r1, sp
	movs	r0, #31
	strh	r0, [r1, #2]
_080018B80:
	ldr r1, _080018C34
	mov	r0, sp
	movs	r2, #8
	bl 0x0802D970
	movs	r5, #1
	ldr r2, _080018C38
	ldr	r0, [r2, #0]
	adds	r0, #70
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	cmp	r5, r0
	bge _080018C26
	ldr r0, _080018C3C
	ldr	r4, [r0, #0]
	cmp	r4, #0
	beq _080018C26
	adds	r6, r2, #0
	ldr r7, _080018C40
_080018BA6:
	movs	r1, #140
	lsls	r1, r1, #1
	adds	r0, r4, r1
	ldr	r0, [r0, #0]
	ldr	r2, [r6, #0]
	ldr	r1, [r4, #8]
	ldr	r2, [r2, #8]
	subs	r1, r1, r2
	bl 0x080264D8
	adds	r2, r0, #0
	ldr	r3, [r6, #0]
	lsls	r1, r5, #2
	adds	r0, r3, #0
	adds	r0, #148
	adds	r1, r0, r1
	ldr	r0, [r1, #0]
	cmp	r2, r0
	beq _080018BE0
	str	r2, [r1, #0]
	lsls	r0, r5, #1
	adds	r1, r3, #0
	adds	r1, #132
	adds	r1, r1, r0
	movs	r3, #0
	ldrsh	r1, [r1, r3]
	adds	r0, r2, #0
	bl 0x080263E0
_080018BE0:
	movs	r1, #12
	ldrsh	r0, [r4, r1]
	lsls	r0, r0, #5
	ldr r1, _080018C30
	adds	r0, r0, r1
	mov	r1, sp
	movs	r2, #8
	bl 0x0802D970
	ldrb	r0, [r4, #30]
	cmp	r0, #0
	beq _080018BFE
	mov	r1, sp
	movs	r0, #31
	strh	r0, [r1, #2]
_080018BFE:
	mov	r0, sp
	adds	r1, r7, #0
	movs	r2, #8
	bl 0x0802D970
	adds	r7, #32
	adds	r5, #1
	ldr	r0, [r6, #0]
	adds	r0, #70
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r5, r0
	bge _080018C26
	ldr r1, _080018C3C
	subs	r0, r5, #1
	lsls	r0, r0, #2
	adds	r0, r0, r1
	ldr	r4, [r0, #0]
	cmp	r4, #0
	bne _080018BA6
_080018C26:
	add	sp, #32
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080018C30: .4byte 0x03005780
_080018C34: .4byte 0x050002A0
_080018C38: .4byte 0x03004E20
_080018C3C: .4byte 0x03000598
_080018C40: .4byte 0x050002C0
	.type _080018C44, %function
_080018C44:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #20
	ldr r7, _080018CD4
	adds	r1, r7, #0
	adds	r1, #224
	ldr r5, _080018CD8
	ldr	r0, [r5, #0]
	adds	r0, #132
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	str	r0, [r1, #0]
	adds	r1, #4
	movs	r0, #160
	lsls	r0, r0, #7
	str	r0, [r1, #0]
	ldr r0, _080018CDC
_080018C6C: .4byte 0xFF2EF7FF
	cmp	r0, #0
	beq _080018CE0
	ldr	r0, [r7, #0]
	ldr	r1, [r7, #4]
	adds	r4, r7, #0
	adds	r4, #200
	adds	r2, r4, #0
	bl 0x080044C4
	cmp	r0, #0
	bne _080018C88
	b _080018DD8
_080018C88:
	adds	r0, r4, #0
	bl 0x08004508
	cmp	r0, #0
	bne _080018C94
	b _080018DD8
_080018C94:
	bl 0x08002BE8
	adds	r1, r7, #0
	adds	r1, #220
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	str	r0, [r1, #0]
	subs	r1, #4
	ldrh	r1, [r1, #0]
	bl 0x08002C48
	adds	r1, r7, #0
	adds	r1, #208
	ldr	r0, [r1, #0]
	cmp	r0, #0
	bge _080018CB6
	adds	r0, #15
_080018CB6:
	asrs	r0, r0, #4
	str	r0, [r1, #0]
	movs	r3, #140
	lsls	r3, r3, #1
	adds	r0, r7, r3
	ldr	r0, [r0, #0]
	ldr	r2, [r5, #0]
	ldr	r1, [r7, #8]
	ldr	r2, [r2, #8]
	subs	r1, r1, r2
	adds	r2, r4, #0
	bl 0x08026550
	b _080018DD8
	movs	r0, r0
_080018CD4: .4byte 0x03004E80
_080018CD8: .4byte 0x03004E20
_080018CDC: .4byte 0x04000020
_080018CE0:
	ldr	r5, [r5, #0]
	ldr	r0, [r5, #12]
	movs	r1, #72
	bl 0x0802DE04
	lsls	r0, r0, #16
	adds	r6, r7, #0
	adds	r6, #200
	lsrs	r4, r0, #16
	mov	sl, r4
	asrs	r0, r0, #16
	movs	r1, #120
	subs	r1, r1, r0
	str	r1, [r6, #0]
	adds	r4, r7, #0
	adds	r4, #204
	ldr	r0, [r5, #16]
	adds	r0, #88
	str	r0, [r4, #0]
	movs	r0, #128
	lsls	r0, r0, #1
	bl 0x08018ACC
	mov	r8, r4
	cmp	r0, #0
	beq _080018D2A
	bl 0x08008014
	lsrs	r1, r0, #31
	adds	r1, r0, r1
	asrs	r1, r1, #1
	lsls	r1, r1, #1
	subs	r0, r0, r1
	ldr	r1, [r4, #0]
	adds	r1, r1, r0
	str	r1, [r4, #0]
	b _080018D46
_080018D2A:
	movs	r0, #128
	lsls	r0, r0, #20
	bl 0x08018ACC
	cmp	r0, #0
	beq _080018D46
	bl 0x08008014
	movs	r1, #1
	ands	r1, r0
	mov	r2, r8
	ldr	r0, [r2, #0]
	adds	r0, r0, r1
	str	r0, [r2, #0]
_080018D46:
	bl 0x08002BE8
	adds	r6, r7, #0
	adds	r6, #220
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	str	r0, [r6, #0]
	movs	r1, #128
	lsls	r1, r1, #1
	bl 0x08002C48
	adds	r5, r7, #0
	adds	r5, #208
	movs	r0, #12
	str	r0, [r5, #0]
	movs	r3, #140
	lsls	r3, r3, #1
	adds	r0, r7, r3
	ldr	r0, [r0, #0]
	ldr r4, _080018E14
	mov	r9, r4
	ldr	r2, [r4, #0]
	ldr	r1, [r7, #8]
	ldr	r2, [r2, #8]
	subs	r1, r1, r2
	ldr r3, _080018E18
	ldr	r2, [r3, #0]
	mov	r4, r8
	ldr	r3, [r4, #0]
	adds	r4, r7, #0
	adds	r4, #224
	ldr	r4, [r4, #0]
	str	r4, [sp, #0]
	adds	r4, r7, #0
	adds	r4, #228
	ldr	r4, [r4, #0]
	str	r4, [sp, #4]
	ldr	r4, [r5, #0]
	str	r4, [sp, #8]
	adds	r4, r7, #0
	adds	r4, #236
	ldr	r4, [r4, #0]
	str	r4, [sp, #12]
	ldr	r4, [r6, #0]
	str	r4, [sp, #16]
	bl 0x08026674
	ldrb	r0, [r7, #31]
	cmp	r0, #0
	beq _080018DD8
	mov	r0, sl
	lsls	r1, r0, #16
	asrs	r1, r1, #16
	movs	r0, #88
	subs	r0, r0, r1
	mov	r2, r8
	ldr	r1, [r2, #0]
	adds	r1, #20
	mov	r3, r9
	ldr	r2, [r3, #0]
	adds	r2, #86
	movs	r4, #0
	ldrsh	r2, [r2, r4]
	movs	r3, #0
	str	r3, [sp, #0]
	movs	r3, #7
	str	r3, [sp, #4]
	movs	r3, #192
	str	r3, [sp, #8]
	str	r3, [sp, #12]
	movs	r3, #2
	bl 0x08003004
_080018DD8:
	movs	r0, #128
	lsls	r0, r0, #17
	bl 0x08018ACC
	cmp	r0, #0
	beq _080018E02
	ldr r0, _080018E1C
	ldr r1, _080018E20
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	movs	r1, #1
	ands	r0, r1
	cmp	r0, #0
	bne _080018E02
	ldr	r0, [r7, #0]
	ldr	r1, [r7, #4]
	movs	r3, #8
	ldrsh	r2, [r7, r3]
	ldr r3, _080018E24
	bl 0x08027234
_080018E02:
	add	sp, #20
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080018E14: .4byte 0x03004E20
_080018E18: .4byte 0x03004F48
_080018E1C: .4byte 0x03001780
_080018E20: .4byte 0x000010DC
_080018E24: .4byte 0x03005DF0
	.type _080018E28, %function
_080018E28:
	push	{r4, r5, r6, lr}
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	lsls	r1, r0, #3
	adds	r1, r1, r0
	lsls	r1, r1, #3
	subs	r1, r1, r0
	lsls	r1, r1, #2
	ldr r2, _080018EB8
	adds	r4, r1, r2
	adds	r2, r4, #0
	adds	r2, #224
	ldr r6, _080018EBC
	ldr	r1, [r6, #0]
	lsls	r0, r0, #1
	adds	r1, #132
	adds	r1, r1, r0
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	str	r0, [r2, #0]
	adds	r1, r4, #0
	adds	r1, #228
	movs	r0, #160
	lsls	r0, r0, #7
	str	r0, [r1, #0]
	ldr	r0, [r4, #0]
	ldr	r1, [r4, #4]
	adds	r5, r4, #0
	adds	r5, #200
	adds	r2, r5, #0
	bl 0x080044C4
	cmp	r0, #0
	beq _080018EB2
	adds	r0, r5, #0
	bl 0x08004508
	cmp	r0, #0
	beq _080018EB2
	bl 0x08002BE8
	adds	r1, r4, #0
	adds	r1, #220
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	str	r0, [r1, #0]
	subs	r1, #4
	ldrh	r1, [r1, #0]
	bl 0x08002C48
	adds	r1, r4, #0
	adds	r1, #208
	ldr	r0, [r1, #0]
	cmp	r0, #0
	bge _080018E98
	adds	r0, #15
_080018E98:
	asrs	r0, r0, #4
	str	r0, [r1, #0]
	movs	r1, #140
	lsls	r1, r1, #1
	adds	r0, r4, r1
	ldr	r0, [r0, #0]
	ldr	r2, [r6, #0]
	ldr	r1, [r4, #8]
	ldr	r2, [r2, #8]
	subs	r1, r1, r2
	adds	r2, r5, #0
	bl 0x08026550
_080018EB2:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
_080018EB8: .4byte 0x03004E80
_080018EBC: .4byte 0x03004E20
	.type sub_080018EC0, %function
sub_080018EC0:
_080018EC0:
	push	{r4, r5, r6, r7, lr}
	movs	r1, #0
	ldr r0, _080018EFC
	ldr r3, _080018F00
	adds	r2, r0, r3
	movs	r7, #0
	ldrsh	r0, [r2, r7]
	subs	r0, #1
	ldr r5, _080018F04
	ldr r6, _080018F08
	cmp	r1, r0
	bge _080018EEA
	movs	r4, #0
	ldr r3, _080018F0C
_080018EDC:
	stmia	r3!, {r4}
	adds	r1, #1
	movs	r7, #0
	ldrsh	r0, [r2, r7]
	subs	r0, #1
	cmp	r1, r0
	blt _080018EDC
_080018EEA:
	ldr r0, _080018F10
	str	r0, [r5, #0]
	ldr	r0, [r6, #0]
	adds	r0, #70
	movs	r1, #1
	strh	r1, [r0, #0]
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080018EFC: .4byte 0x03001780
_080018F00: .4byte 0x000010CA
_080018F04: .4byte 0x03005E48
_080018F08: .4byte 0x03004E20
_080018F0C: .4byte 0x03000598
_080018F10: .4byte 0x00FFFFFF
	.type sub_080018F14, %function
sub_080018F14:
_080018F14:
	push	{r4, r5, r6, r7, lr}
	adds	r5, r0, #0
	ldr r1, _080018F38
	adds	r0, #204
	ldr	r2, [r1, #0]
	ldr	r0, [r0, #0]
	adds	r7, r1, #0
	cmp	r2, r0
	ble _080018F8C
	movs	r4, #0
	ldr r0, _080018F3C
	ldr	r1, [r0, #0]
	adds	r6, r0, #0
	cmp	r1, #0
	bne _080018F40
	str	r5, [r6, #0]
	b _080018F80
	movs	r0, r0
_080018F38: .4byte 0x03005E48
_080018F3C: .4byte 0x03000598
_080018F40:
	adds	r1, r5, #0
	adds	r1, #204
	lsls	r2, r4, #2
	adds	r0, r2, r6
	ldr	r0, [r0, #0]
	adds	r0, #204
	ldr	r1, [r1, #0]
	ldr	r0, [r0, #0]
	cmp	r1, r0
	bge _080018F6E
	movs	r3, #1
	cmp	r3, r4
	blt _080018F68
	adds	r1, r6, #4
_080018F5C:
	ldr	r0, [r1, #0]
	str	r0, [r1, #4]
	subs	r1, #4
	subs	r3, #1
	cmp	r3, r4
	bge _080018F5C
_080018F68:
	adds	r0, r2, r6
	str	r5, [r0, #0]
	b _080018F80
_080018F6E:
	adds	r4, #1
	cmp	r4, #2
	bgt _080018F80
	lsls	r0, r4, #2
	adds	r1, r0, r6
	ldr	r0, [r1, #0]
	cmp	r0, #0
	bne _080018F40
	str	r5, [r1, #0]
_080018F80:
	ldr	r0, [r6, #8]
	cmp	r0, #0
	beq _080018F8C
	adds	r0, #204
	ldr	r0, [r0, #0]
	str	r0, [r7, #0]
_080018F8C:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080018F94, %function
sub_080018F94:
_080018F94:
	push	{r4, r5, r6, r7, lr}
	bl sub_080018EC0
	movs	r5, #1
	ldr r0, _080019000
	ldr r2, _080019004
	adds	r1, r0, r2
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r5, r0
	bge _080018FE6
	adds	r7, r1, #0
	movs	r6, #142
	lsls	r6, r6, #1
_080018FB0:
	ldr r0, _080019008
	adds	r4, r6, r0
	ldr	r0, [r4, #0]
	ldr	r1, [r4, #4]
	adds	r2, r4, #0
	adds	r2, #200
	bl 0x080044C4
	cmp	r0, #0
	beq _080018FD6
	adds	r0, r4, #0
	bl sub_080018F14
	ldr r0, _08001900C
	ldr	r0, [r0, #0]
	adds	r0, #70
	ldrh	r1, [r0, #0]
	adds	r1, #1
	strh	r1, [r0, #0]
_080018FD6:
	movs	r0, #142
	lsls	r0, r0, #1
	adds	r6, r6, r0
	adds	r5, #1
	movs	r1, #0
	ldrsh	r0, [r7, r1]
	cmp	r5, r0
	blt _080018FB0
_080018FE6:
	ldr r0, _08001900C
	ldr	r0, [r0, #0]
	adds	r1, r0, #0
	adds	r1, #70
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r0, #3
	ble _080018FFA
	movs	r0, #4
	strh	r0, [r1, #0]
_080018FFA:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080019000: .4byte 0x03001780
_080019004: .4byte 0x000010CA
_080019008: .4byte 0x03004E80
_08001900C: .4byte 0x03004E20
	.type _080019010, %function
_080019010:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #20
	movs	r0, #0
	str	r0, [sp, #8]
	ldr r1, _080019030
	mov	r0, sp
	movs	r2, #4
	bl 0x0802E0A4
	bl 0x08006B20
	b _080019182
_080019030: .4byte 0x0805FB84
_080019034:
	ldr	r1, [sp, #4]
	movs	r2, #4
	ldrsh	r4, [r1, r2]
	movs	r2, #6
	ldrsh	r0, [r1, r2]
	cmp	r4, r0
	ble _080019044
	b _080019182
_080019044:
	bl 0x08005F98
	lsls	r1, r4, #1
	adds	r1, r1, r4
	lsls	r1, r1, #2
	ldr	r0, [r0, #12]
	adds	r5, r0, r1
	ldrh	r0, [r5, #8]
	mov	r9, r0
	ldr r1, _0800191A0
	ldr	r0, [r1, #0]
	mov	r2, r9
	lsls	r1, r2, #1
	adds	r0, #140
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	mov	r8, r0
	mov	r2, sp
	adds	r0, r2, r1
	ldrh	r0, [r0, #0]
	str	r0, [sp, #12]
	bl 0x08002BD8
	cmp	r0, #0
	bne _080019078
	b _080019182
_080019078:
	ldr	r0, [sp, #8]
	cmp	r0, #47
	ble _080019080
	b _080019182
_080019080:
	ldr r6, _0800191A4
	ldr	r0, [r5, #0]
	str	r0, [r6, #4]
	ldr	r0, [r5, #4]
	str	r0, [r6, #8]
	adds	r0, r6, #0
	bl 0x08004330
	adds	r4, #1
	str	r4, [sp, #16]
	cmp	r0, #0
	beq _080019174
	ldr	r5, [r6, #60]
	bl 0x08002BFC
	adds	r4, r0, #0
	ldr	r0, [r6, #44]
	cmp	r0, #0
	bge _0800190A8
	adds	r0, #3
_0800190A8:
	asrs	r0, r0, #2
	adds	r1, r4, #0
	bl 0x08002C34
	ldr r1, _0800191A8
	mov	sl, r1
	ldr r0, _0800191AC
	add	r0, sl
	ldrb	r0, [r0, #0]
	movs	r7, #128
	lsls	r7, r7, #3
	cmp	r0, #0
	beq _0800190C6
	movs	r7, #128
	lsls	r7, r7, #4
_0800190C6:
	bl 0x08002BE8
	strh	r0, [r6, #52]
	movs	r2, #52
	ldrsh	r0, [r6, r2]
	ldrh	r1, [r5, #4]
	bl 0x08002C48
	movs	r1, #128
	lsls	r1, r1, #1
	adds	r0, r1, #0
	ldrh	r5, [r5, #6]
	orrs	r0, r5
	ldr	r1, [r6, #40]
	movs	r2, #255
	ands	r1, r2
	orrs	r0, r1
	strh	r0, [r4, #0]
	ldr	r0, [r6, #36]
	ldr r2, _0800191B0
	adds	r1, r2, #0
	ands	r0, r1
	ldr r2, _0800191B4
	adds	r1, r2, #0
	orrs	r0, r1
	ldrh	r6, [r6, #52]
	lsls	r1, r6, #9
	orrs	r0, r1
	strh	r0, [r4, #2]
	ldr	r1, [sp, #12]
	lsls	r0, r1, #12
	mov	r2, r8
	orrs	r2, r0
	orrs	r7, r2
	strh	r7, [r4, #4]
	movs	r0, #0
	strh	r0, [r4, #12]
	movs	r0, #128
	lsls	r0, r0, #18
	bl 0x08018ACC
	ldr	r6, [sp, #8]
	adds	r6, #1
	cmp	r0, #0
	beq _080019172
	ldr r1, _0800191A0
	ldr	r0, [r1, #0]
	mov	r2, r9
	lsls	r1, r2, #2
	movs	r2, #146
	lsls	r2, r2, #3
	adds	r0, r0, r2
	adds	r0, r0, r1
	ldr	r4, [r0, #0]
	movs	r5, #0
	movs	r1, #4
	ldrsh	r0, [r4, r1]
	cmp	r5, r0
	bge _080019172
	ldr r7, _0800191B8
	add	r7, sl
_080019140:
	ldr	r0, [r7, #0]
	adds	r0, r5, r0
	movs	r1, #1
	ands	r0, r1
	cmp	r0, #0
	beq _080019168
	lsls	r2, r5, #3
	adds	r0, r4, #0
	adds	r0, #8
	adds	r0, r0, r2
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	adds	r1, r4, #0
	adds	r1, #12
	adds	r1, r1, r2
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	ldr r2, _0800191A4
	bl 0x08027308
_080019168:
	adds	r5, #1
	movs	r1, #4
	ldrsh	r0, [r4, r1]
	cmp	r5, r0
	blt _080019140
_080019172:
	str	r6, [sp, #8]
_080019174:
	ldr	r4, [sp, #16]
	ldr	r2, [sp, #4]
	movs	r1, #6
	ldrsh	r0, [r2, r1]
	cmp	r4, r0
	bgt _080019182
	b _080019044
_080019182:
	bl 0x08006B30
	str	r0, [sp, #4]
	cmp	r0, #0
	beq _08001918E
	b _080019034
_08001918E:
	add	sp, #20
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800191A0: .4byte 0x03004E20
_0800191A4: .4byte 0x03005DF0
_0800191A8: .4byte 0x03001780
_0800191AC: .4byte 0x000010BC
_0800191B0: .4byte 0x000001FF
_0800191B4: .4byte 0xFFFFC000
_0800191B8: .4byte 0x000010DC
	.type sub_0800191BC, %function
sub_0800191BC:
_0800191BC:
	push	{r4, r5, lr}
	lsls	r0, r0, #16
	lsrs	r1, r0, #16
	adds	r4, r1, #0
	ldr r0, _0800191D8
	ldr	r0, [r0, #0]
	adds	r3, r0, #0
	adds	r3, #90
	movs	r2, #0
	ldrsh	r0, [r3, r2]
	cmp	r0, #0
	bge _0800191DC
	strh	r1, [r3, #0]
	b _0800191F6
_0800191D8: .4byte 0x03004E20
_0800191DC:
	ldr r2, _0800191FC
	lsls	r1, r4, #16
	asrs	r1, r1, #14
	adds	r1, r1, r2
	movs	r5, #0
	ldrsh	r0, [r3, r5]
	lsls	r0, r0, #2
	adds	r0, r0, r2
	ldr	r1, [r1, #0]
	ldr	r0, [r0, #0]
	cmp	r1, r0
	bge _0800191F6
	strh	r4, [r3, #0]
_0800191F6:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_0800191FC: .4byte 0x080CBB30
	.type sub_080019200, %function
sub_080019200:
_080019200:
	push	{r4, r5, r6, r7, lr}
	adds	r6, r0, #0
	adds	r7, r1, #0
	ldr	r0, [r6, #28]
	movs	r2, #18
	ldrsh	r1, [r0, r2]
	ldr	r2, [r7, #28]
	movs	r3, #18
	ldrsh	r0, [r2, r3]
	subs	r1, r1, r0
	cmp	r1, #0
	bgt _080019242
	cmp	r1, #0
	bne _080019246
	adds	r0, r2, #0
	movs	r1, #0
	bl 0x08006C10
	ldr	r2, [r6, #4]
	ldr	r1, [r7, #4]
	subs	r4, r2, r1
	ldr	r2, [r6, #8]
	ldr	r1, [r7, #8]
	subs	r5, r2, r1
	movs	r2, #20
	ldrsh	r1, [r0, r2]
	muls	r1, r5
	movs	r3, #22
	ldrsh	r0, [r0, r3]
	muls	r0, r4
	subs	r1, r1, r0
	cmp	r1, #0
	bgt _080019246
_080019242:
	movs	r0, #1
	b _080019248
_080019246:
	movs	r0, #0
_080019248:
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_080019250, %function
sub_080019250:
_080019250:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	adds	r7, r0, #0
	mov	r8, r1
	movs	r0, #22
	ldrsh	r1, [r7, r0]
	mov	r2, r8
	movs	r3, #22
	ldrsh	r0, [r2, r3]
	subs	r6, r1, r0
	ldr r0, _0800192A8
	ldr r1, _0800192AC
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq _080019292
	negs	r0, r6
	lsls	r1, r0, #3
	cmp	r1, #36
	ble _080019280
	movs	r1, #36
_080019280:
	cmp	r1, #0
	bge _080019286
	movs	r1, #0
_080019286:
	adds	r0, r7, #0
	adds	r0, #36
	lsls	r1, r1, #16
	asrs	r1, r1, #16
	bl sub_0802A8F0
_080019292:
	ldr r0, _0800192B0
	ldr	r2, [r0, #0]
	adds	r1, r2, #0
	adds	r1, #130
	ldrb	r0, [r1, #0]
	cmp	r0, #0
	beq _0800192B4
	movs	r0, #0
	strb	r0, [r1, #0]
	b _08001930E
	movs	r0, r0
_0800192A8: .4byte 0x03001780
_0800192AC: .4byte 0x00001111
_0800192B0: .4byte 0x03004E20
_0800192B4:
	cmp	r6, #0
	bgt _0800192F8
	cmp	r6, #0
	bne _08001930C
	ldr r3, _0800192FC
	adds	r0, r2, r3
	movs	r1, #0
	bl 0x08006C10
	ldr	r2, [r7, #0]
	mov	r3, r8
	ldr	r1, [r3, #0]
	subs	r4, r2, r1
	ldr	r2, [r7, #4]
	ldr	r1, [r3, #4]
	subs	r5, r2, r1
	movs	r2, #20
	ldrsh	r1, [r0, r2]
	muls	r1, r5
	movs	r3, #22
	ldrsh	r0, [r0, r3]
	muls	r0, r4
	subs	r1, r1, r0
	asrs	r1, r1, #16
	adds	r0, r1, #0
	adds	r0, #40
	cmp	r0, #79
	bhi _080019308
	ldr r0, _080019300
	ldr r1, _080019304
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	beq _08001930C
_0800192F8:
	movs	r0, #1
	b _08001930E
_0800192FC: .4byte 0x000004FC
_080019300: .4byte 0x03001780
_080019304: .4byte 0x000010C3
_080019308:
	cmp	r1, #0
	blt _0800192F8
_08001930C:
	movs	r0, #0
_08001930E:
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	.type sub_080019318, %function
sub_080019318:
_080019318:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	sub	sp, #68
	ldr r0, _0800193D0
	ldr r1, _0800193D4
	adds	r2, r0, r1
	movs	r3, #0
	ldrsh	r6, [r2, r3]
	adds	r1, #18
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	movs	r1, #1
	ands	r0, r1
	cmp	r0, #0
	bne _08001933C
	b _0800194F4
_08001933C:
	movs	r5, #1
	add	r3, sp, #52
	mov	r9, r3
	cmp	r5, r6
	bge _0800193B2
	mov	r8, r2
	movs	r7, #142
	lsls	r7, r7, #1
_08001934C:
	ldr r0, _0800193D8
	adds	r4, r7, r0
	ldr r1, _0800193DC
	adds	r0, r4, #0
	adds	r0, #36
	ldr	r2, [r1, #0]
	mov	r1, sp
	bl 0x0802DDD0
	ldr	r0, [sp, #4]
	str	r0, [r4, #0]
	ldr	r0, [sp, #8]
	str	r0, [r4, #4]
	movs	r0, #136
	lsls	r0, r0, #1
	adds	r2, r4, r0
	ldr	r0, [sp, #12]
	ldr	r1, [sp, #16]
	str	r0, [r2, #0]
	str	r1, [r2, #4]
	ldr	r0, [sp, #24]
	str	r0, [r4, #8]
	ldr	r0, [sp, #28]
	ldr	r0, [r0, #12]
	strh	r0, [r4, #20]
	mov	r0, sp
	ldrh	r0, [r0, #38]
	strh	r0, [r4, #24]
	ldr	r0, [sp, #32]
	lsrs	r0, r0, #6
	movs	r1, #1
	ands	r0, r1
	strb	r0, [r4, #30]
	ldr r0, _0800193E0
	ldr	r0, [r0, #0]
	movs	r1, #153
	lsls	r1, r1, #3
	adds	r0, r0, r1
	mov	r1, sp
	bl sub_080019200
	subs	r6, r6, r0
	movs	r2, #142
	lsls	r2, r2, #1
	adds	r7, r7, r2
	adds	r5, #1
	mov	r3, r8
	movs	r1, #0
	ldrsh	r0, [r3, r1]
	cmp	r5, r0
	blt _08001934C
_0800193B2:
	movs	r0, #1
	bl 0x08018ACC
	cmp	r0, #0
	bne _0800193C0
	ldr r0, _0800193D8
	strh	r6, [r0, #14]
_0800193C0:
	movs	r5, #0
	ldr r0, _0800193E0
	ldr	r0, [r0, #0]
	adds	r0, #70
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	b _08001945C
	movs	r0, r0
_0800193D0: .4byte 0x03001780
_0800193D4: .4byte 0x000010CA
_0800193D8: .4byte 0x03004E80
_0800193DC: .4byte 0x080CBB28
_0800193E0: .4byte 0x03004E20
_0800193E4:
	ldr r1, _0800194D8
	lsls	r0, r5, #2
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	cmp	r0, #0
	beq _080019450
	adds	r4, r0, #0
	ldrb	r0, [r4, #29]
	cmp	r0, #0
	beq _080019450
	bl 0x08002BE8
	adds	r1, r4, #0
	adds	r1, #220
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	str	r0, [r1, #0]
	subs	r1, #4
	ldrh	r1, [r1, #0]
	bl 0x08002C48
	movs	r3, #140
	lsls	r3, r3, #1
	adds	r0, r4, r3
	ldr	r0, [r0, #0]
	ldr r1, _0800194DC
	ldr	r2, [r1, #0]
	ldr	r1, [r4, #8]
	ldr	r2, [r2, #8]
	subs	r1, r1, r2
	adds	r2, r4, #0
	adds	r2, #200
	bl 0x08026550
	movs	r0, #0
	strb	r0, [r4, #29]
	movs	r0, #128
	lsls	r0, r0, #17
	bl 0x08018ACC
	cmp	r0, #0
	beq _080019450
	adds	r0, r4, #0
	adds	r0, #32
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _080019450
	ldr	r0, [r4, #0]
	ldr	r1, [r4, #4]
	movs	r3, #8
	ldrsh	r2, [r4, r3]
	ldr r3, _0800194E0
	bl 0x08027234
_080019450:
	adds	r5, #1
	ldr r0, _0800194DC
	ldr	r0, [r0, #0]
	adds	r0, #70
	movs	r1, #0
	ldrsh	r0, [r0, r1]
_08001945C:
	subs	r0, #1
	cmp	r5, r0
	blt _0800193E4
	ldr r2, _0800194E4
	ldr r0, _0800194E8
	ldr r3, _0800194EC
	adds	r4, r0, r3
	movs	r0, #0
	ldrsh	r1, [r4, r0]
	subs	r1, #1
	lsls	r0, r1, #3
	adds	r0, r0, r1
	lsls	r0, r0, #3
	subs	r0, r0, r1
	lsls	r0, r0, #2
	adds	r0, r0, r2
	ldrh	r6, [r0, #20]
	ldr r1, _0800194F0
	mov	r0, r9
	movs	r2, #16
	bl 0x0802E0A4
	movs	r5, #1
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	subs	r0, #1
	cmp	r5, r0
	blt _080019496
	b _0800195A4
_080019496:
	lsls	r0, r6, #16
	asrs	r7, r0, #16
	mov	r8, r4
	mov	r4, r9
	adds	r4, #2
	movs	r6, #142
	lsls	r6, r6, #1
_0800194A4:
	ldr r0, _0800194E4
	adds	r2, r6, r0
	movs	r3, #20
	ldrsh	r0, [r2, r3]
	subs	r0, r7, r0
	movs	r3, #0
	ldrsh	r1, [r4, r3]
	cmp	r0, r1
	ble _0800194C0
	adds	r0, r2, #0
	adds	r0, #36
	movs	r1, #1
	bl sub_0802A8F0
_0800194C0:
	adds	r4, #2
	movs	r0, #142
	lsls	r0, r0, #1
	adds	r6, r6, r0
	adds	r5, #1
	mov	r1, r8
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	subs	r0, #1
	cmp	r5, r0
	blt _0800194A4
	b _0800195A4
_0800194D8: .4byte 0x03000598
_0800194DC: .4byte 0x03004E20
_0800194E0: .4byte 0x03005DF0
_0800194E4: .4byte 0x03004E80
_0800194E8: .4byte 0x03001780
_0800194EC: .4byte 0x000010CA
_0800194F0: .4byte 0x0805FB88
_0800194F4:
	bl sub_080018F94
	movs	r5, #0
	b _080019594
_0800194FC:
	ldr r1, _080019588
	lsls	r0, r5, #2
	adds	r0, r0, r1
	ldr	r4, [r0, #0]
	adds	r7, r5, #1
	cmp	r4, #0
	beq _080019592
	adds	r1, r4, #0
	adds	r1, #252
	movs	r0, #0
	str	r0, [r1, #0]
	adds	r6, r4, #0
	adds	r6, #200
	adds	r0, r6, #0
	bl 0x08004508
	cmp	r0, #0
	beq _080019590
	bl 0x08002BE8
	adds	r1, r4, #0
	adds	r1, #220
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	str	r0, [r1, #0]
	subs	r1, #4
	ldrh	r1, [r1, #0]
	bl 0x08002C48
	adds	r2, r4, #0
	adds	r2, #224
	ldr r3, _08001958C
	ldr	r0, [r3, #0]
	lsls	r1, r7, #1
	adds	r0, #132
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	str	r0, [r2, #0]
	adds	r1, r4, #0
	adds	r1, #228
	adds	r0, r5, #6
	lsls	r0, r0, #12
	str	r0, [r1, #0]
	subs	r1, #20
	ldr	r0, [r1, #0]
	cmp	r0, #0
	bge _08001955E
	adds	r0, #15
_08001955E:
	asrs	r0, r0, #4
	str	r0, [r1, #0]
	movs	r0, #1
	strb	r0, [r4, #29]
	adds	r0, r4, #0
	adds	r0, #32
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _080019592
	movs	r2, #140
	lsls	r2, r2, #1
	adds	r0, r4, r2
	ldr	r0, [r0, #0]
	ldr	r2, [r3, #0]
	ldr	r1, [r4, #8]
	ldr	r2, [r2, #8]
	subs	r1, r1, r2
	adds	r2, r6, #0
	bl 0x08026550
	b _080019592
_080019588: .4byte 0x03000598
_08001958C: .4byte 0x03004E20
_080019590:
	strb	r0, [r4, #29]
_080019592:
	adds	r5, r7, #0
_080019594:
	ldr r0, _0800195B4
	ldr	r0, [r0, #0]
	adds	r0, #70
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	subs	r0, #1
	cmp	r5, r0
	blt _0800194FC
_0800195A4:
	add	sp, #68
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800195B4: .4byte 0x03004E20
	.type sub_0800195B8, %function
sub_0800195B8:
_0800195B8:
	push	{lr}
	movs	r0, #128
	lsls	r0, r0, #11
	bl 0x08018ACC
	adds	r1, r0, #0
	cmp	r1, #0
	beq _0800195E8
	ldr r0, _0800195E4
	ldr	r1, [r0, #0]
	adds	r1, #92
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #19
	ble _0800195F0
	movs	r0, #3
	bl 0x0801B498
	b _0800195F0
_0800195E4: .4byte 0x03004E20
_0800195E8:
	ldr r0, _0800195F4
	ldr	r0, [r0, #0]
	adds	r0, #92
	strh	r1, [r0, #0]
_0800195F0:
	pop	{r0}
	bx	r0
_0800195F4: .4byte 0x03004E20
	.type sub_0800195F8, %function
sub_0800195F8:
_0800195F8:
	push	{r4, r5, lr}
	movs	r0, #128
	lsls	r0, r0, #6
	bl 0x08018ACC
	cmp	r0, #0
	beq _080019624
	ldr r0, _080019620
	ldr	r0, [r0, #0]
	adds	r1, r0, #0
	adds	r1, #94
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #120
	ble _08001963A
	movs	r0, #120
	b _080019638
_080019620: .4byte 0x03004E20
_080019624:
	ldr r0, _0800196D8
	ldr	r0, [r0, #0]
	adds	r1, r0, #0
	adds	r1, #94
	ldrh	r2, [r1, #0]
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #0
	ble _08001963A
	subs	r0, r2, #3
_080019638:
	strh	r0, [r1, #0]
_08001963A:
	movs	r0, #128
	lsls	r0, r0, #11
	bl 0x08018ACC
	cmp	r0, #0
	beq _080019652
	ldr r0, _0800196D8
	ldr	r0, [r0, #0]
	adds	r0, #94
	ldrh	r1, [r0, #0]
	subs	r1, #3
	strh	r1, [r0, #0]
_080019652:
	ldr r5, _0800196D8
	ldr	r0, [r5, #0]
	adds	r1, r0, #0
	adds	r1, #94
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r0, #0
	bgt _08001967A
	movs	r0, #0
	strh	r0, [r1, #0]
	movs	r0, #128
	lsls	r0, r0, #22
	movs	r1, #1
	bl 0x08018AA8
	movs	r0, #128
	lsls	r0, r0, #7
	movs	r1, #0
	bl 0x08018AA8
_08001967A:
	movs	r4, #128
	lsls	r4, r4, #22
	adds	r0, r4, #0
	bl 0x08018ACC
	cmp	r0, #0
	beq _0800196A6
	adds	r0, r4, #0
	movs	r1, #0
	bl 0x08018AA8
	ldr	r1, [r5, #0]
	adds	r0, r1, #0
	adds	r0, #94
	movs	r2, #0
	strh	r2, [r0, #0]
	ldr	r0, [r1, #48]
	cmp	r0, #0
	ble _0800196A6
	str	r2, [r1, #48]
	bl 0x0800821C
_0800196A6:
	movs	r0, #128
	lsls	r0, r0, #9
	bl 0x08018ACC
	cmp	r0, #0
	beq _0800196DC
	movs	r0, #1
	bl 0x08018ACC
	cmp	r0, #0
	bne _0800196DC
	ldr r0, _0800196D8
	ldr	r0, [r0, #0]
	adds	r0, #94
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	lsls	r0, r0, #4
	movs	r1, #120
	bl 0x0802DE04
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	bl 0x08008284
	b _0800196E2
_0800196D8: .4byte 0x03004E20
_0800196DC:
	movs	r0, #0
	bl 0x08008284
_0800196E2:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_0800196E8, %function
sub_0800196E8:
_0800196E8:
	push	{r4, r5, r6, lr}
	ldr r0, _080019790
	ldr r1, _080019794
	movs	r2, #154
	lsls	r2, r2, #1
	adds	r1, r1, r2
	movs	r2, #250
	lsls	r2, r2, #2
	strh	r2, [r1, #0]
	ldr r3, _080019798
	adds	r0, r0, r3
	ldr	r4, [r0, #0]
	movs	r6, #1
	ands	r4, r6
	cmp	r4, #0
	beq _0800197D4
	ldr r0, _08001979C
	ldr	r0, [r0, #0]
	cmp	r0, #0
	beq _080019772
	adds	r4, r0, #0
	ldrb	r0, [r4, #29]
	cmp	r0, #0
	beq _080019772
	bl 0x08002BE8
	adds	r1, r4, #0
	adds	r1, #220
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	str	r0, [r1, #0]
	subs	r1, #4
	ldrh	r1, [r1, #0]
	bl 0x08002C48
	adds	r1, r4, #0
	adds	r1, #208
	ldr	r0, [r1, #0]
	cmp	r0, #0
	bge _08001973A
	adds	r0, #15
_08001973A:
	asrs	r0, r0, #4
	str	r0, [r1, #0]
	movs	r1, #140
	lsls	r1, r1, #1
	adds	r0, r4, r1
	ldr	r0, [r0, #0]
	ldr r1, _0800197A0
	ldr	r2, [r1, #0]
	ldr	r1, [r4, #8]
	ldr	r2, [r2, #8]
	subs	r1, r1, r2
	adds	r2, r4, #0
	adds	r2, #200
	bl 0x08026550
	movs	r0, #128
	lsls	r0, r0, #17
	bl 0x08018ACC
	cmp	r0, #0
	beq _080019772
	ldr	r0, [r4, #0]
	ldr	r1, [r4, #4]
	movs	r3, #8
	ldrsh	r2, [r4, r3]
	ldr r3, _0800197A4
	bl 0x08027234
_080019772:
	movs	r0, #128
	lsls	r0, r0, #9
	bl 0x08018ACC
	cmp	r0, #0
	beq _0800197A8
	ldr r0, _080019794
	movs	r2, #142
	lsls	r2, r2, #1
	adds	r1, r0, r2
	bl sub_080019250
	movs	r1, #2
	subs	r4, r1, r0
	b _0800197B8
_080019790: .4byte 0x03001780
_080019794: .4byte 0x03004E80
_080019798: .4byte 0x000010DC
_08001979C: .4byte 0x03000598
_0800197A0: .4byte 0x03004E20
_0800197A4: .4byte 0x03005DF0
_0800197A8:
	ldr r0, _0800197C8
	ldr r3, _0800197CC
	adds	r0, r0, r3
	ldrb	r0, [r0, #0]
	movs	r4, #2
	cmp	r0, #0
	beq _0800197B8
	movs	r4, #1
_0800197B8:
	movs	r0, #1
	bl 0x08018ACC
	cmp	r0, #0
	bne _080019858
	ldr r0, _0800197D0
	strh	r4, [r0, #14]
	b _080019858
_0800197C8: .4byte 0x03001780
_0800197CC: .4byte 0x000010C3
_0800197D0: .4byte 0x03004E80
_0800197D4:
	bl sub_080018F94
	ldr r0, _08001984C
	ldr	r5, [r0, #0]
	cmp	r5, #0
	beq _080019858
	adds	r0, r5, #0
	adds	r0, #252
	str	r4, [r0, #0]
	adds	r4, r5, #0
	adds	r4, #200
	adds	r0, r4, #0
	bl 0x08004508
	cmp	r0, #0
	beq _080019854
	bl 0x08002BE8
	adds	r1, r5, #0
	adds	r1, #220
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	str	r0, [r1, #0]
	subs	r1, #4
	ldrh	r1, [r1, #0]
	bl 0x08002C48
	adds	r1, r5, #0
	adds	r1, #224
	ldr r2, _080019850
	ldr	r0, [r2, #0]
	adds	r0, #134
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	str	r0, [r1, #0]
	adds	r1, #4
	movs	r0, #192
	lsls	r0, r0, #7
	str	r0, [r1, #0]
	subs	r1, #20
	ldr	r0, [r1, #0]
	cmp	r0, #0
	bge _08001982C
	adds	r0, #15
_08001982C:
	asrs	r0, r0, #4
	str	r0, [r1, #0]
	strb	r6, [r5, #29]
	movs	r1, #140
	lsls	r1, r1, #1
	adds	r0, r5, r1
	ldr	r0, [r0, #0]
	ldr	r2, [r2, #0]
	ldr	r1, [r5, #8]
	ldr	r2, [r2, #8]
	subs	r1, r1, r2
	adds	r2, r4, #0
	bl 0x08026550
	b _080019858
	movs	r0, r0
_08001984C: .4byte 0x03000598
_080019850: .4byte 0x03004E20
_080019854:
	movs	r0, #0
	strb	r0, [r5, #29]
_080019858:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080019860, %function
sub_080019860:
_080019860:
	push	{lr}
	bl 0x08027FCC
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08001986C, %function
sub_08001986C:
_08001986C:
	push	{r4, r5, r6, lr}
	ldr r2, _0800198C8
	ldr r1, _0800198CC
	adds	r0, r2, r1
	ldr	r0, [r0, #0]
	movs	r1, #1
	ands	r0, r1
	cmp	r0, #0
	beq _0800198AA
	movs	r5, #0
	ldr r0, _0800198D0
	adds	r1, r2, r0
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r5, r0
	bge _0800198AA
	adds	r6, r1, #0
	ldr r4, _0800198D4
_080019890:
	ldr	r0, [r4, #0]
	ldr	r1, [r4, #4]
	adds	r2, r5, #0
	bl 0x080270D8
	movs	r0, #142
	lsls	r0, r0, #1
	adds	r4, r4, r0
	adds	r5, #1
	movs	r1, #0
	ldrsh	r0, [r6, r1]
	cmp	r5, r0
	blt _080019890
_0800198AA:
	ldr r0, _0800198C8
	ldr r2, _0800198D8
	adds	r0, r0, r2
	ldrh	r0, [r0, #0]
	subs	r0, #1
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #9
	bhi _080019924
	lsls	r0, r0, #2
	ldr r1, _0800198DC
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_0800198C8: .4byte 0x03001780
_0800198CC: .4byte 0x000010DC
_0800198D0: .4byte 0x000010CA
_0800198D4: .4byte 0x03004E80
_0800198D8: .4byte 0x000010FC
_0800198DC: .4byte 0x080198E0
_0800198E0: .4byte 0x08019908
_0800198E4: .4byte 0x0801990E
_0800198E8: .4byte 0x08019908
_0800198EC: .4byte 0x08019908
_0800198F0: .4byte 0x08019914
_0800198F4: .4byte 0x08019924
_0800198F8: .4byte 0x08019924
_0800198FC: .4byte 0x0801991A
_080019900: .4byte 0x08019924
_080019904: .4byte 0x08019920
_080019908:
	bl sub_080019318
	b _080019924
_08001990E:
	bl sub_0800195B8
	b _080019924
_080019914:
	bl sub_0800195F8
	b _080019924
_08001991A:
	bl sub_0800196E8
	b _080019924
_080019920:
	bl sub_080019860
_080019924:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08001992C, %function
sub_08001992C:
_08001992C:
	push	{r4, lr}
	ldr r4, _080019974
	ldr	r1, [r4, #0]
	ldr	r0, [r1, #48]
	adds	r0, #1
	str	r0, [r1, #48]
	cmp	r0, #99
	ble _080019940
	movs	r0, #99
	str	r0, [r1, #48]
_080019940:
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #48]
	bl 0x08008164
	bl 0x08008208
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #48]
	movs	r1, #5
	bl 0x0802D97C
	cmp	r0, #0
	beq _080019978
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #48]
	subs	r0, #5
	movs	r1, #150
	adds	r2, r0, #0
	muls	r2, r1
	lsls	r2, r2, #16
	asrs	r2, r2, #16
	movs	r0, #22
	movs	r1, #255
	bl 0x0802B500
	b _080019990
_080019974: .4byte 0x03004E20
_080019978:
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #48]
	subs	r0, #5
	movs	r1, #150
	adds	r2, r0, #0
	muls	r2, r1
	lsls	r2, r2, #16
	asrs	r2, r2, #16
	movs	r0, #23
	movs	r1, #255
	bl 0x0802B500
_080019990:
	ldr r0, _0800199AC
	ldr	r1, [r0, #0]
	ldr	r2, [r1, #48]
	ldr	r0, [r1, #52]
	cmp	r2, r0
	ble _0800199A4
	str	r2, [r1, #52]
	adds	r0, r2, #0
	bl 0x080081F8
_0800199A4:
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800199AC: .4byte 0x03004E20
_0800199B0:
sub_0800199B0:
	push	{lr}
	movs	r0, #128
	lsls	r0, r0, #7
	movs	r1, #1
	bl 0x08018AA8
	movs	r0, #128
	lsls	r0, r0, #21
	movs	r1, #1
	bl 0x08018AA8
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800199CC, %function
sub_0800199CC:
_0800199CC:
	push	{lr}
	movs	r0, #128
	lsls	r0, r0, #7
	bl 0x08018ACC
	cmp	r0, #0
	beq _080019A0E
	ldr r0, _080019A24
	ldr	r1, [r0, #0]
	movs	r2, #158
	lsls	r2, r2, #3
	adds	r0, r1, r2
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r0, #79
	ble _080019A0E
	adds	r0, r1, #0
	adds	r0, #94
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r0, #0
	ble _080019A0E
	ldr r2, _080019A28
	adds	r0, r1, r2
	ldr	r0, [r0, #0]
	movs	r2, #18
	ldrsh	r1, [r0, r2]
	movs	r2, #22
	ldrsh	r0, [r0, r2]
	cmp	r1, r0
	blt _080019A0E
	bl sub_08001992C
_080019A0E:
	ldr r0, _080019A24
	ldr	r1, [r0, #0]
	movs	r0, #0
	str	r0, [r1, #56]
	movs	r0, #128
	lsls	r0, r0, #21
	movs	r1, #0
	bl 0x08018AA8
	pop	{r0}
	bx	r0
_080019A24: .4byte 0x03004E20
_080019A28: .4byte 0x000004E4
	.type sub_080019A2C, %function
sub_080019A2C:
_080019A2C:
	push	{r4, lr}
	adds	r4, r0, #0
	movs	r0, #64
	movs	r1, #1
	bl 0x08018AA8
	ldr r0, _080019A54
	ldr	r2, [r0, #0]
	adds	r0, r2, #0
	adds	r0, #72
	strh	r4, [r0, #0]
	ldr r1, _080019A58
	ldr r3, _080019A5C
	adds	r0, r3, #0
	strh	r0, [r1, #0]
	cmp	r4, #0
	beq _080019A60
	cmp	r4, #1
	beq _080019A6C
	b _080019A7A
_080019A54: .4byte 0x03004E20
_080019A58: .4byte 0x04000050
_080019A5C: .4byte 0x00000FDF
_080019A60:
	ldr r1, _080019A68
	movs	r0, #16
	b _080019A70
	movs	r0, r0
_080019A68: .4byte 0x04000054
_080019A6C:
	ldr r1, _080019A80
	movs	r0, #0
_080019A70:
	strh	r0, [r1, #0]
	adds	r1, r2, #0
	adds	r1, #74
	movs	r0, #32
	strh	r0, [r1, #0]
_080019A7A:
	pop	{r4}
	pop	{r0}
	bx	r0
_080019A80: .4byte 0x04000054
	.type _080019A84, %function
_080019A84:
	push	{r4, lr}
	ldr r0, _080019AB8
	ldr	r3, [r0, #0]
	adds	r1, r3, #0
	adds	r1, #74
	ldrh	r2, [r1, #0]
	movs	r4, #0
	ldrsh	r0, [r1, r4]
	cmp	r0, #0
	ble _080019ADC
	subs	r0, r2, #1
	strh	r0, [r1, #0]
	adds	r0, r3, #0
	adds	r0, #72
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r0, #0
	bne _080019AC0
	movs	r4, #0
	ldrsh	r0, [r1, r4]
	movs	r1, #2
	bl 0x0802D978
	ldr r1, _080019ABC
	strh	r0, [r1, #0]
	b _080019AE4
_080019AB8: .4byte 0x03004E20
_080019ABC: .4byte 0x04000054
_080019AC0:
	cmp	r0, #1
	bne _080019AE4
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	movs	r1, #2
	bl 0x0802D978
	ldr r2, _080019AD8
	movs	r1, #16
	subs	r1, r1, r0
	strh	r1, [r2, #0]
	b _080019AE4
_080019AD8: .4byte 0x04000054
_080019ADC:
	movs	r0, #64
	movs	r1, #0
	bl 0x08018AA8
_080019AE4:
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080019AEC, %function
sub_080019AEC:
_080019AEC:
	push	{r4, r5, r6, r7, lr}
	adds	r3, r0, #0
	ldr r1, _080019B34
	ldr	r2, [r1, #0]
	adds	r0, r2, #0
	adds	r0, #64
	ldrh	r0, [r0, #0]
	subs	r0, #1
	lsls	r0, r0, #16
	lsrs	r4, r0, #16
	ldr r0, _080019B38
	str	r0, [r2, #44]
	adds	r5, r1, #0
	cmp	r3, #0
	ble _080019B80
	ldr r1, _080019B3C
	ldr r0, _080019B40
	adds	r2, r1, r0
	movs	r0, #1
	strb	r0, [r2, #0]
	ldr r2, _080019B44
	adds	r0, r1, r2
	strb	r3, [r0, #0]
	adds	r2, #23
	adds	r0, r1, r2
	adds	r2, r1, #0
	ldrh	r0, [r0, #0]
	cmp	r0, #8
	bne _080019B4C
	cmp	r3, #2
	bne _080019B4C
	ldr r0, _080019B48
	adds	r1, r2, r0
	movs	r0, #0
	str	r0, [r1, #0]
	b _080019B56
_080019B34: .4byte 0x03004E20
_080019B38: .4byte 0x7FFFFFFF
_080019B3C: .4byte 0x03001780
_080019B40: .4byte 0x000010E4
_080019B44: .4byte 0x000010E5
_080019B48: .4byte 0x000010F4
_080019B4C:
	ldr r1, _080019B78
	adds	r0, r2, r1
	ldr	r1, [r5, #0]
	ldr	r1, [r1, #24]
	str	r1, [r0, #0]
_080019B56:
	ldr r1, _080019B7C
	adds	r0, r2, r1
	ldrh	r0, [r0, #0]
	cmp	r0, #5
	bne _080019B6A
	subs	r1, #4
	adds	r0, r2, r1
	ldr	r1, [r5, #0]
	ldr	r1, [r1, #52]
	str	r1, [r0, #0]
_080019B6A:
	lsls	r0, r4, #16
	movs	r2, #128
	lsls	r2, r2, #9
	adds	r0, r0, r2
	lsrs	r4, r0, #16
	b _080019B9C
	movs	r0, r0
_080019B78: .4byte 0x000010F4
_080019B7C: .4byte 0x000010FC
_080019B80:
	ldr r3, _080019BE0
	ldr r1, _080019BE4
	adds	r0, r3, r1
	movs	r1, #0
	strb	r1, [r0, #0]
	ldr r1, _080019BE8
	adds	r0, r3, r1
	ldrh	r0, [r0, #0]
	cmp	r0, #5
	bne _080019B9C
	ldr r0, _080019BEC
	adds	r1, r3, r0
	ldr	r0, [r2, #52]
	str	r0, [r1, #0]
_080019B9C:
	movs	r1, #0
	lsls	r0, r4, #16
	asrs	r0, r0, #16
	cmp	r1, r0
	bge _080019BD8
	ldr r2, _080019BF0
	mov	ip, r2
	adds	r6, r0, #0
	ldr r7, _080019BF4
_080019BAE:
	lsls	r2, r1, #2
	mov	r0, ip
	adds	r3, r2, r0
	ldr	r4, [r7, #0]
	adds	r5, r1, #1
	lsls	r1, r5, #2
	adds	r0, r4, #0
	adds	r0, #28
	adds	r1, r0, r1
	adds	r0, r0, r2
	ldr	r1, [r1, #0]
	ldr	r0, [r0, #0]
	subs	r1, r1, r0
	str	r1, [r3, #0]
	ldr	r0, [r4, #44]
	cmp	r1, r0
	bcs _080019BD2
	str	r1, [r4, #44]
_080019BD2:
	adds	r1, r5, #0
	cmp	r1, r6
	blt _080019BAE
_080019BD8:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080019BE0: .4byte 0x03001780
_080019BE4: .4byte 0x000010E4
_080019BE8: .4byte 0x000010FC
_080019BEC: .4byte 0x000010F8
_080019BF0: .4byte 0x03002868
_080019BF4: .4byte 0x03004E20
	.type _080019BF8, %function
_080019BF8:
	push	{lr}
	ldr r1, _080019C20
	ldr r2, _080019C24
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	adds	r1, #4
	ldr r2, _080019C28
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	subs	r1, #12
	ldr r2, _080019C2C
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	ldr r1, _080019C30
	movs	r0, #3
	bl 0x080023AC
	pop	{r0}
	bx	r0
	movs	r0, r0
_080019C20: .4byte 0x04000008
_080019C24: .4byte 0x00001C4B
_080019C28: .4byte 0x0000E8C2
_080019C2C: .4byte 0x00001741
_080019C30: .4byte 0x08019C35
	.type _080019C34, %function
_080019C34:
	push	{lr}
	ldr r0, _080019C7C
	ldrb	r0, [r0, #0]
	cmp	r0, #159
	bls _080019C76
	movs	r1, #128
	lsls	r1, r1, #19
	ldr r2, _080019C80
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	adds	r1, #10
	ldr r2, _080019C84
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	ldr r2, _080019C88
	ldr r0, _080019C8C
	ldr	r0, [r0, #0]
	ldr	r1, [r0, #8]
	lsrs	r0, r1, #2
	strh	r0, [r2, #0]
	adds	r2, #2
	movs	r0, #6
	strh	r0, [r2, #0]
	ldr r0, _080019C90
	lsrs	r1, r1, #3
	strh	r1, [r0, #0]
	ldr r1, _080019C94
	movs	r0, #0
	strh	r0, [r1, #0]
	ldr r1, _080019C98
	movs	r0, #3
	bl 0x080023AC
_080019C76:
	pop	{r0}
	bx	r0
	movs	r0, r0
_080019C7C: .4byte 0x04000006
_080019C80: .4byte 0x00001341
_080019C84: .4byte 0x00005E49
_080019C88: .4byte 0x04000014
_080019C8C: .4byte 0x03004E20
_080019C90: .4byte 0x04000010
_080019C94: .4byte 0x04000012
_080019C98: .4byte 0x08019C9D
	.type _080019C9C, %function
_080019C9C:
	push	{lr}
	ldr r0, _080019CB4
	ldrb	r0, [r0, #0]
	cmp	r0, #160
	bhi _080019CAE
	ldr r1, _080019CB8
	movs	r0, #3
	bl 0x080023AC
_080019CAE:
	pop	{r0}
	bx	r0
	movs	r0, r0
_080019CB4: .4byte 0x04000006
_080019CB8: .4byte 0x08019CBD
	.type _080019CBC, %function
_080019CBC:
	push	{lr}
	ldr r0, _080019CE4
	ldr r1, _080019CE8
	movs	r2, #10
	ldrsh	r1, [r1, r2]
	ldrb	r0, [r0, #0]
	cmp	r0, r1
	blt _080019CDE
	movs	r0, #128
	lsls	r0, r0, #19
	ldr r2, _080019CEC
	adds	r1, r2, #0
	strh	r1, [r0, #0]
	ldr r1, _080019CF0
	movs	r0, #3
	bl 0x080023AC
_080019CDE:
	pop	{r0}
	bx	r0
	movs	r0, r0
_080019CE4: .4byte 0x04000006
_080019CE8: .4byte 0x03005760
_080019CEC: .4byte 0x00001641
_080019CF0: .4byte 0x08019CF5
	.type _080019CF4, %function
_080019CF4:
	push	{lr}
	ldr r0, _080019D1C
	ldrb	r0, [r0, #0]
	cmp	r0, #79
	bls _080019D18
	ldr r1, _080019D20
	ldr r2, _080019D24
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	ldr r0, _080019D28
	movs	r1, #0
	strh	r1, [r0, #0]
	adds	r0, #2
	strh	r1, [r0, #0]
	ldr r1, _080019D2C
	movs	r0, #3
	bl 0x080023AC
_080019D18:
	pop	{r0}
	bx	r0
_080019D1C: .4byte 0x04000006
_080019D20: .4byte 0x0400000A
_080019D24: .4byte 0x00005E48
_080019D28: .4byte 0x04000014
_080019D2C: .4byte 0x08019C35
	.type _080019D30, %function
_080019D30:
	push	{lr}
	ldr r1, _080019D58
	movs	r0, #3
	bl 0x080023AC
	ldr r1, _080019D5C
	ldr r2, _080019D60
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	adds	r1, #4
	ldr r2, _080019D64
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	subs	r1, #12
	ldr r2, _080019D68
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	pop	{r0}
	bx	r0
	movs	r0, r0
_080019D58: .4byte 0x08019D6D
_080019D5C: .4byte 0x04000008
_080019D60: .4byte 0x00001C49
_080019D64: .4byte 0x0000E8C3
_080019D68: .4byte 0x00001741
	.type sub_080019D6C, %function
sub_080019D6C:
_080019D6C:
	push	{lr}
	ldr r0, _080019DA8
	ldrb	r0, [r0, #0]
	cmp	r0, #159
	bls _080019DA2
	movs	r1, #128
	lsls	r1, r1, #19
	ldr r2, _080019DAC
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	adds	r1, #10
	ldr r2, _080019DB0
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	adds	r1, #10
	ldr r0, _080019DB4
	ldr	r0, [r0, #0]
	ldr	r0, [r0, #8]
	lsrs	r0, r0, #2
	strh	r0, [r1, #0]
	adds	r1, #2
	movs	r0, #6
	strh	r0, [r1, #0]
	ldr r1, _080019DB8
	movs	r0, #3
	bl 0x080023AC
_080019DA2:
	pop	{r0}
	bx	r0
	movs	r0, r0
_080019DA8: .4byte 0x04000006
_080019DAC: .4byte 0x00001341
_080019DB0: .4byte 0x00005E4A
_080019DB4: .4byte 0x03004E20
_080019DB8: .4byte 0x08019DBD
	.type _080019DBC, %function
_080019DBC:
	push	{lr}
	ldr r0, _080019DD4
	ldrb	r0, [r0, #0]
	cmp	r0, #160
	bhi _080019DCE
	ldr r1, _080019DD8
	movs	r0, #3
	bl 0x080023AC
_080019DCE:
	pop	{r0}
	bx	r0
	movs	r0, r0
_080019DD4: .4byte 0x04000006
_080019DD8: .4byte 0x08019DDD
	.type _080019DDC, %function
_080019DDC:
	push	{lr}
	ldr r0, _080019E04
	ldr r1, _080019E08
	movs	r2, #10
	ldrsh	r1, [r1, r2]
	ldrb	r0, [r0, #0]
	cmp	r0, r1
	blt _080019DFE
	movs	r0, #128
	lsls	r0, r0, #19
	ldr r2, _080019E0C
	adds	r1, r2, #0
	strh	r1, [r0, #0]
	ldr r1, _080019E10
	movs	r0, #3
	bl 0x080023AC
_080019DFE:
	pop	{r0}
	bx	r0
	movs	r0, r0
_080019E04: .4byte 0x04000006
_080019E08: .4byte 0x03005760
_080019E0C: .4byte 0x00001741
_080019E10: .4byte 0x08019E15
	.type _080019E14, %function
_080019E14:
	push	{lr}
	ldr r0, _080019E60
	ldrb	r0, [r0, #0]
	cmp	r0, #79
	bls _080019E5C
	ldr r1, _080019E64
	ldr r2, _080019E68
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	ldr r0, _080019E6C
	movs	r1, #0
	strh	r1, [r0, #0]
	adds	r0, #2
	strh	r1, [r0, #0]
	ldr r3, _080019E70
	ldr r0, _080019E74
	ldr r1, _080019E78
	adds	r0, r0, r1
	ldr	r2, [r0, #0]
	movs	r1, #31
	ands	r1, r2
	movs	r0, #7
	ands	r0, r2
	muls	r0, r1
	strh	r0, [r3, #0]
	adds	r3, #2
	movs	r0, #63
	ands	r0, r2
	movs	r1, #15
	ands	r2, r1
	muls	r0, r2
	strh	r0, [r3, #0]
	ldr r1, _080019E7C
	movs	r0, #3
	bl 0x080023AC
_080019E5C:
	pop	{r0}
	bx	r0
_080019E60: .4byte 0x04000006
_080019E64: .4byte 0x0400000A
_080019E68: .4byte 0x00005E48
_080019E6C: .4byte 0x04000014
_080019E70: .4byte 0x04000010
_080019E74: .4byte 0x03001780
_080019E78: .4byte 0x000010DC
_080019E7C: .4byte 0x08019D6D
	.type _080019E80, %function
_080019E80:
	push	{lr}
	ldr r1, _080019EB0
	movs	r0, #3
	bl 0x080023AC
	ldr r1, _080019EB4
	ldr r2, _080019EB8
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	adds	r1, #2
	ldr r2, _080019EBC
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	adds	r1, #2
	ldr r2, _080019EC0
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	subs	r1, #12
	ldr r2, _080019EC4
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	pop	{r0}
	bx	r0
	movs	r0, r0
_080019EB0: .4byte 0x08019EC9
_080019EB4: .4byte 0x04000008
_080019EB8: .4byte 0x00001CC8
_080019EBC: .4byte 0x00001E49
_080019EC0: .4byte 0x0000E8C3
_080019EC4: .4byte 0x00000141
	.type sub_080019EC8, %function
sub_080019EC8:
_080019EC8:
	push	{lr}
	ldr r0, _080019F04
	ldrb	r0, [r0, #0]
	cmp	r0, #55
	bls _080019F00
	movs	r0, #128
	lsls	r0, r0, #23
	bl 0x08018ACC
	cmp	r0, #0
	beq _080019F00
	ldr r1, _080019F08
	ldr r2, _080019F0C
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	ldr r2, _080019F10
	ldr r0, _080019F14
	ldr	r0, [r0, #0]
	adds	r0, #114
	ldrh	r1, [r0, #0]
	adds	r0, r1, #2
	lsls	r0, r0, #8
	orrs	r0, r1
	strh	r0, [r2, #0]
	ldr r1, _080019F18
	movs	r0, #3
	bl 0x080023AC
_080019F00:
	pop	{r0}
	bx	r0
_080019F04: .4byte 0x04000006
_080019F08: .4byte 0x04000050
_080019F0C: .4byte 0x00001442
_080019F10: .4byte 0x04000052
_080019F14: .4byte 0x03004E20
_080019F18: .4byte 0x08019F1D
	.type _080019F1C, %function
_080019F1C:
	push	{lr}
	ldr r0, _080019F5C
	ldrb	r0, [r0, #0]
	cmp	r0, #56
	bhi _080019F58
	movs	r0, #128
	lsls	r0, r0, #23
	bl 0x08018ACC
	cmp	r0, #0
	beq _080019F58
	ldr r1, _080019F60
	movs	r2, #160
	lsls	r2, r2, #1
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	ldr r3, _080019F64
	ldr r0, _080019F68
	ldr	r0, [r0, #0]
	adds	r0, #116
	ldrh	r2, [r0, #0]
	lsls	r1, r2, #8
	movs	r0, #16
	subs	r0, r0, r2
	orrs	r1, r0
	strh	r1, [r3, #0]
	ldr r1, _080019F6C
	movs	r0, #3
	bl 0x080023AC
_080019F58:
	pop	{r0}
	bx	r0
_080019F5C: .4byte 0x04000006
_080019F60: .4byte 0x04000050
_080019F64: .4byte 0x04000052
_080019F68: .4byte 0x03004E20
_080019F6C: .4byte 0x08019EC9
	.type sub_08019F70, %function
sub_08019F70:
_08019F70:
	push	{r4, r5, r6, lr}
	mov	r6, r8
	push	{r6}
	bl 0x08005F98
	ldr	r0, [r0, #0]
	ldrb	r1, [r0, #14]
	ldrb	r3, [r0, #15]
	cmp	r1, #13
	ble _080019F86
	movs	r1, #0
_080019F86:
	cmp	r3, #13
	ble _080019F8C
	movs	r3, #0
_080019F8C:
	ldr r0, _080019FFC
	mov	r8, r0
	ldr	r0, [r0, #0]
	movs	r4, #146
	lsls	r4, r4, #3
	adds	r2, r0, r4
	lsls	r5, r1, #1
	adds	r5, r5, r1
	lsls	r5, r5, #3
	ldr r1, _08001A000
	adds	r5, r5, r1
	str	r5, [r2, #0]
	adds	r4, #4
	adds	r2, r0, r4
	lsls	r4, r3, #1
	adds	r4, r4, r3
	lsls	r4, r4, #3
	adds	r4, r4, r1
	str	r4, [r2, #0]
	ldr r6, _08001A004
	movs	r2, #0
	ldrsh	r1, [r5, r2]
	adds	r0, #140
	movs	r3, #0
	ldrsh	r2, [r0, r3]
	adds	r0, r6, #0
	bl 0x08007538
	movs	r0, #0
	ldrsh	r1, [r4, r0]
	mov	r2, r8
	ldr	r0, [r2, #0]
	adds	r0, #142
	movs	r3, #0
	ldrsh	r2, [r0, r3]
	adds	r0, r6, #0
	bl 0x08007538
	movs	r0, #2
	ldrsh	r1, [r5, r0]
	adds	r0, r6, #0
	movs	r2, #0
	bl 0x080075E8
	movs	r2, #2
	ldrsh	r1, [r4, r2]
	adds	r0, r6, #0
	movs	r2, #1
	bl 0x080075E8
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080019FFC: .4byte 0x03004E20
_08001A000: .4byte 0x080CB954
_08001A004: .4byte 0x0832F654
