@ GT Advance 3 - rec35 raw gap
@ Region: file offset 0x016002-0x0163B8 (VMA 0x08016002-0x080163B8).
@ Pure Thumb, ARMCC; closes the raw gap between rec35_stage.s (ends at
@ 0x16002) and rec35_driver.s (starts at 0x163B8). Generated by
@ tools/objdump2gas.py from an objdump listing of baserom.gba;
@ byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.
@
@ Function map (8 functions):
@   sub_080016004/sub_0800160C4 - twin event handlers on u16[rec+140]:
@     mode 2 (sound 4, rec+16=10, +20=0, +48=10, +44=0, clear
@     0x03001780+0x1084), mode 1 (sound 1 / writes rec+144/150/14A),
@     64/128 (rec+140 -/+1), clamp rec+140 to [0,1], sound 2 on change.
@   sub_080016164 - sound-driven record clear (u16 arg & 0xFFFF <= 1:
@     rec+144=0, 0x08002618(1,0), sound 1, rec+16/20/48/44 set).
@   sub_0800161A0 - twin of sub_080016164 with extra rec+26/24=1 and
@     0x03001780+0x1084 clear.
@   sub_0800161F0 - high-register (sl/r9/r8) loop: 30 iterations (r9=29
@     down) stepping r4 += 8, calling sub_08007B18 with {sp:4|5,1,1,0},
@     rec+52, mode 7 (course-record placement, cf. menu_dbe8.s 0xDD20).
@   sub_08001626C - dispatch on rec+152 {0,1,2,3} via u16 table
@     0x080CB89C: mode 5/4 sub_08007B18 calls with (rec, r4, r5).
@   sub_0800162E0 - record-49 tail driver: rec+136 clear (sub_0800D97C
@     id 15), rec+144 gate, sub_08007B18 mode 3/4 fills (rec, 4|5, 0,
@     32), table 0x080CB88C stride-8 lookups -> sub_0800161F0 +
@     sub_08001626C, then sub_08007C68 packet (rec+8..+164 cells, sp
@     {64,6,1,0,0}, mode 48) and sub_0800DBE8 + sub_0800163B4.
@   sub_0800163B4 - bx lr no-op stub (rec35_driver.s calls the next
@     function at 0x163B8).
@
@ Cross-references: only in-span BLs; external entries are the
@ runtime-registered rec35 scene driver at 0x163B8 (rec35_driver.s).
	movs	r0, r0
	.type sub_080016004, %function
sub_080016004:
_080016004:
	push	{r4, r5, r6, r7, lr}
	adds	r5, r0, #0
	lsls	r2, r2, #16
	lsrs	r6, r2, #16
	adds	r4, r5, #0
	adds	r4, #140
	ldrh	r7, [r4, #0]
	cmp	r6, #2
	bne _080016030
	movs	r0, #4
	bl 0x0802B368
	movs	r0, #10
	str	r0, [r5, #16]
	movs	r1, #0
	strh	r1, [r5, #20]
	str	r0, [r5, #48]
	str	r1, [r5, #44]
	ldr r0, _080016044
	ldr r2, _080016048
	adds	r0, r0, r2
	strh	r1, [r0, #0]
_080016030:
	cmp	r6, #1
	bne _080016078
	movs	r3, #0
	ldrsh	r4, [r4, r3]
	cmp	r4, #0
	beq _08001604C
	cmp	r4, #1
	beq _08001605E
	b _080016078
	movs	r0, r0
_080016044: .4byte 0x03001780
_080016048: .4byte 0x00001084
_08001604C:
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r5, #0
	adds	r0, #144
	strh	r4, [r0, #0]
	adds	r0, #6
	strh	r6, [r0, #0]
	b _080016078
_08001605E:
	movs	r0, #1
	bl 0x0802B368
	movs	r0, #10
	str	r0, [r5, #16]
	movs	r1, #0
	strh	r1, [r5, #20]
	str	r0, [r5, #48]
	str	r1, [r5, #44]
	ldr r0, _0800160BC
	ldr r2, _0800160C0
	adds	r0, r0, r2
	strh	r1, [r0, #0]
_080016078:
	adds	r2, r5, #0
	adds	r2, #140
	cmp	r6, #64
	bne _080016086
	ldrh	r0, [r2, #0]
	subs	r0, #1
	strh	r0, [r2, #0]
_080016086:
	cmp	r6, #128
	bne _080016090
	ldrh	r0, [r2, #0]
	adds	r0, #1
	strh	r0, [r2, #0]
_080016090:
	adds	r1, r2, #0
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #0
	bge _08001609E
	movs	r0, #0
	strh	r0, [r1, #0]
_08001609E:
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #1
	ble _0800160AA
	movs	r0, #1
	strh	r0, [r1, #0]
_0800160AA:
	ldrh	r2, [r2, #0]
	cmp	r7, r2
	beq _0800160B6
	movs	r0, #2
	bl 0x0802B368
_0800160B6:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_0800160BC: .4byte 0x03001780
_0800160C0: .4byte 0x00001084
	.type sub_0800160C4, %function
sub_0800160C4:
_0800160C4:
	push	{r4, r5, r6, r7, lr}
	adds	r5, r0, #0
	lsls	r2, r2, #16
	lsrs	r6, r2, #16
	adds	r4, r5, #0
	adds	r4, #140
	ldrh	r7, [r4, #0]
	cmp	r6, #2
	bne _0800160E8
	movs	r0, #4
	bl 0x0802B368
	movs	r1, #10
	str	r1, [r5, #16]
	movs	r0, #0
	strh	r0, [r5, #20]
	str	r1, [r5, #48]
	str	r0, [r5, #44]
_0800160E8:
	cmp	r6, #1
	bne _08001611E
	movs	r0, #0
	ldrsh	r4, [r4, r0]
	cmp	r4, #0
	beq _0800160FA
	cmp	r4, #1
	beq _08001610C
	b _08001611E
_0800160FA:
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r5, #0
	adds	r0, #144
	strh	r4, [r0, #0]
	adds	r0, #4
	strh	r6, [r0, #0]
	b _08001611E
_08001610C:
	movs	r0, #1
	bl 0x0802B368
	movs	r1, #10
	str	r1, [r5, #16]
	movs	r0, #0
	strh	r0, [r5, #20]
	str	r1, [r5, #48]
	str	r0, [r5, #44]
_08001611E:
	adds	r2, r5, #0
	adds	r2, #140
	cmp	r6, #64
	bne _08001612C
	ldrh	r0, [r2, #0]
	subs	r0, #1
	strh	r0, [r2, #0]
_08001612C:
	cmp	r6, #128
	bne _080016136
	ldrh	r0, [r2, #0]
	adds	r0, #1
	strh	r0, [r2, #0]
_080016136:
	adds	r1, r2, #0
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #0
	bge _080016144
	movs	r0, #0
	strh	r0, [r1, #0]
_080016144:
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #1
	ble _080016150
	movs	r0, #1
	strh	r0, [r1, #0]
_080016150:
	ldrh	r2, [r2, #0]
	cmp	r7, r2
	beq _08001615C
	movs	r0, #2
	bl 0x0802B368
_08001615C:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080016164, %function
sub_080016164:
_080016164:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	lsls	r2, r2, #16
	ldr r0, _08001619C
	adds	r2, r2, r0
	lsrs	r2, r2, #16
	cmp	r2, #1
	bhi _080016194
	adds	r0, r5, #0
	adds	r0, #144
	movs	r4, #0
	strh	r4, [r0, #0]
	movs	r0, #1
	movs	r1, #0
	bl 0x08002618
	movs	r0, #1
	bl 0x0802B368
	movs	r0, #10
	str	r0, [r5, #16]
	strh	r4, [r5, #20]
	str	r0, [r5, #48]
	str	r4, [r5, #44]
_080016194:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08001619C: .4byte 0xFFFF0000
	.type sub_0800161A0, %function
sub_0800161A0:
_0800161A0:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	lsls	r2, r2, #16
	ldr r0, _0800161E4
	adds	r2, r2, r0
	lsrs	r2, r2, #16
	cmp	r2, #1
	bhi _0800161DE
	adds	r0, r5, #0
	adds	r0, #144
	movs	r4, #0
	strh	r4, [r0, #0]
	movs	r0, #1
	movs	r1, #0
	bl 0x08002618
	movs	r0, #1
	bl 0x0802B368
	movs	r0, #10
	str	r0, [r5, #16]
	strh	r4, [r5, #20]
	str	r0, [r5, #48]
	str	r4, [r5, #44]
	movs	r1, #1
	strh	r1, [r5, #26]
	strh	r1, [r5, #24]
	ldr r0, _0800161E8
	ldr r2, _0800161EC
	adds	r0, r0, r2
	strh	r1, [r0, #0]
_0800161DE:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_0800161E4: .4byte 0xFFFF0000
_0800161E8: .4byte 0x03001780
_0800161EC: .4byte 0x00001084
	.type sub_0800161F0, %function
sub_0800161F0:
_0800161F0:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #16
	mov	r8, r0
	adds	r7, r1, #0
	adds	r6, r2, #0
	movs	r5, #1
	movs	r0, #0
	mov	sl, r0
	movs	r4, #0
	movs	r0, #29
	mov	r9, r0
_08001620E:
	cmp	r6, #2
	beq _080016218
	cmp	r6, #3
	beq _080016234
	b _08001624E
_080016218:
	movs	r0, #4
	str	r0, [sp, #0]
	str	r5, [sp, #4]
	str	r5, [sp, #8]
	mov	r0, sl
	str	r0, [sp, #12]
	mov	r0, r8
	adds	r0, #52
	movs	r1, #7
	adds	r2, r4, #0
	adds	r3, r7, #0
	bl sub_08007B18
	b _08001624E
_080016234:
	movs	r0, #5
	str	r0, [sp, #0]
	str	r5, [sp, #4]
	str	r5, [sp, #8]
	mov	r0, sl
	str	r0, [sp, #12]
	mov	r0, r8
	adds	r0, #52
	movs	r1, #7
	adds	r2, r4, #0
	adds	r3, r7, #0
	bl sub_08007B18
_08001624E:
	adds	r4, #8
	movs	r0, #1
	negs	r0, r0
	add	r9, r0
	mov	r0, r9
	cmp	r0, #0
	bge _08001620E
	add	sp, #16
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.type sub_08001626C, %function
sub_08001626C:
_08001626C:
	push	{r4, r5, lr}
	sub	sp, #16
	adds	r3, r0, #0
	adds	r4, r1, #0
	adds	r5, r2, #0
	ldr r1, _080016298
	adds	r0, #140
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldrh	r1, [r0, #0]
	adds	r0, r3, #0
	adds	r0, #152
	ldr	r0, [r0, #0]
	cmp	r0, #1
	beq _0800162A4
	cmp	r0, #1
	bgt _08001629C
	cmp	r0, #0
	beq _0800162BE
	b _0800162D6
_080016298: .4byte 0x080CB89C
_08001629C:
	cmp	r0, #2
	beq _0800162BE
	cmp	r0, #3
	bne _0800162D6
_0800162A4:
	movs	r0, #5
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	str	r0, [sp, #8]
	movs	r0, #0
	str	r0, [sp, #12]
	adds	r0, r3, #0
	adds	r2, r4, #0
	adds	r3, r5, #0
	bl sub_08007B18
	b _0800162D6
_0800162BE:
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	str	r0, [sp, #8]
	movs	r0, #0
	str	r0, [sp, #12]
	adds	r0, r3, #0
	adds	r2, r4, #0
	adds	r3, r5, #0
	bl sub_08007B18
_0800162D6:
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800162E0, %function
sub_0800162E0:
_0800162E0:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #20
	adds	r7, r0, #0
	adds	r0, #136
	movs	r1, #15
	bl sub_0800D97C
	adds	r0, r7, #0
	adds	r0, #144
	movs	r1, #0
	ldrsh	r2, [r0, r1]
	cmp	r2, #0
	bne _08001636A
	subs	r0, #2
	movs	r3, #0
	ldrsh	r1, [r0, r3]
	cmp	r1, #0
	beq _080016320
	cmp	r1, #1
	bne _080016338
	movs	r0, #3
	str	r0, [sp, #0]
	str	r1, [sp, #4]
	str	r1, [sp, #8]
	str	r2, [sp, #12]
	adds	r0, r7, #0
	movs	r1, #4
	movs	r2, #0
	movs	r3, #32
	bl sub_08007B18
	b _080016338
_080016320:
	movs	r0, #3
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	str	r0, [sp, #8]
	str	r1, [sp, #12]
	adds	r0, r7, #0
	movs	r1, #5
	movs	r2, #0
	movs	r3, #32
	bl sub_08007B18
_080016338:
	ldr r4, _0800163B0
	adds	r5, r7, #0
	adds	r5, #140
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	lsls	r0, r0, #3
	adds	r6, r4, #4
	adds	r0, r0, r6
	ldr	r1, [r0, #0]
	adds	r0, r7, #0
	adds	r0, #152
	ldr	r2, [r0, #0]
	adds	r0, r7, #0
	bl sub_0800161F0
	movs	r3, #0
	ldrsh	r0, [r5, r3]
	lsls	r0, r0, #3
	adds	r4, r0, r4
	ldr	r1, [r4, #0]
	adds	r0, r0, r6
	ldr	r2, [r0, #0]
	adds	r0, r7, #0
	bl sub_08001626C
_08001636A:
	adds	r0, r7, #0
	adds	r0, #144
	movs	r1, #0
	ldrsh	r4, [r0, r1]
	cmp	r4, #1
	bne _08001639A
	subs	r0, #136
	adds	r1, r7, #0
	adds	r1, #160
	ldr	r1, [r1, #0]
	adds	r2, r7, #0
	adds	r2, #164
	ldr	r2, [r2, #0]
	movs	r3, #64
	str	r3, [sp, #0]
	movs	r3, #6
	str	r3, [sp, #4]
	str	r4, [sp, #8]
	movs	r3, #0
	str	r3, [sp, #12]
	str	r3, [sp, #16]
	movs	r3, #48
	bl sub_08007C68
_08001639A:
	adds	r0, r7, #0
	adds	r0, #16
	bl sub_0800DBE8
	adds	r0, r7, #0
	bl sub_0800163B4
	add	sp, #20
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_0800163B0: .4byte 0x080CB88C
	.type sub_0800163B4, %function
sub_0800163B4:
_0800163B4:
	bx	lr
	.hword 0x0000


@ End-of-region anchor for the splicer: this file declares exactly one
@ `@ Region:` (0x016002-0x0163B8), and the promoted body at 0x080163b4 ends on
@ 0x080163b8, exactly that boundary. Without it the body is refused as
@ 'no end marker'.
rec35_gap_end:
