@ GT Advance 3 - rec35 runtime region 0x164D4-0x18A50
@ Region: file offset 0x0164D4-0x018A50 (VMA 0x080164D4-0x08018A50).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_0800164D4, %function
sub_0800164D4:
_0800164D4:
	push	{r4, lr}
	adds	r4, r1, #0
	bl 0x08004B68
	movs	r1, #2
	ldrsh	r0, [r0, r1]
	cmp	r0, #21
	beq _0800164F0
	cmp	r0, #21
	blt _0800164F8
	cmp	r0, #30
	bgt _0800164F8
	cmp	r0, #27
	blt _0800164F8
_0800164F0:
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #1
	b _0800164FE
_0800164F8:
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #6
_0800164FE:
	strh	r0, [r1, #0]
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080016508, %function
sub_080016508:
_080016508:
	bx	lr
	movs	r0, r0
	.type sub_08001650C, %function
sub_08001650C:
_08001650C:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #32
	adds	r7, r0, #0
	movs	r0, #65
	bl 0x0802B214
	ldr r0, _080016544
	ldr r1, _080016548
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	cmp	r0, #3
	bne _080016550
	ldr r1, _08001654C
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	movs	r2, #1
	movs	r3, #0
	bl sub_08007770
	b _080016564
	movs	r0, r0
_080016544: .4byte 0x03001780
_080016548: .4byte 0x00000FF8
_08001654C: .4byte 0x082FE118
_080016550:
	ldr r1, _0800166C0
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	movs	r2, #0
	movs	r3, #0
	bl sub_08007770
_080016564:
	movs	r0, #6
	str	r0, [r7, #80]
	movs	r0, #17
	str	r0, [r7, #92]
	movs	r0, #0
	str	r0, [r7, #104]
	movs	r2, #8
	adds	r2, r2, r7
	mov	r8, r2
	mov	r0, r8
	bl sub_0800DAB8
	ldr r5, _0800166C4
	adds	r0, r5, #0
	adds	r1, r7, #0
	bl sub_0800798C
	movs	r0, #200
	bl sub_0800572C
	adds	r2, r7, #0
	adds	r2, #144
	str	r0, [r2, #0]
	adds	r3, r7, #0
	adds	r3, #148
	ldr r1, _0800166C8
	ldr r6, _0800166CC
	mov	r9, r6
	ldr r4, _0800166D0
	add	r4, r9
	movs	r6, #0
	ldrsh	r0, [r4, r6]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	movs	r6, #0
	ldrsh	r1, [r0, r6]
	str	r1, [r3, #0]
	ldr	r0, [r7, #4]
	ldr	r2, [r2, #0]
	bl sub_08007ABC
	movs	r0, #0
	ldrsh	r2, [r4, r0]
	adds	r0, r5, #0
	movs	r1, #0
	movs	r3, #3
	bl sub_08007614
	movs	r1, #3
	str	r1, [sp, #28]
	movs	r3, #0
	movs	r5, #3
	mov	r2, r8
	str	r2, [sp, #8]
	movs	r6, #132
	adds	r6, r6, r7
	mov	r8, r6
	adds	r0, r7, #0
	adds	r0, #136
	str	r0, [sp, #20]
	adds	r1, r7, #0
	adds	r1, #28
	str	r1, [sp, #16]
	adds	r2, r7, #0
	adds	r2, #20
	str	r2, [sp, #12]
	mov	sl, r9
	mov	r9, r4
_0800165EC:
	ldr r4, _0800166D4
	add	r4, sl
	movs	r6, #0
	ldrsh	r0, [r4, r6]
	mov	r2, r9
	movs	r6, #0
	ldrsh	r1, [r2, r6]
	adds	r2, r5, #0
	str	r3, [sp, #24]
	bl 0x08025CF4
	adds	r1, r0, #0
	subs	r0, r1, #1
	ldr	r3, [sp, #24]
	cmp	r0, #2
	bhi _08001660E
	adds	r3, r1, #0
_08001660E:
	ldr	r0, [sp, #28]
	cmp	r3, r0
	bgt _080016616
	str	r3, [sp, #28]
_080016616:
	adds	r5, #1
	cmp	r5, #10
	ble _0800165EC
	movs	r5, #0
	mov	r1, sp
	ldrh	r2, [r1, #28]
	mov	r1, r8
	strh	r2, [r1, #0]
	movs	r3, #0
	ldrsh	r0, [r4, r3]
	movs	r6, #4
	ldrsh	r1, [r4, r6]
	ldr	r2, [sp, #28]
	bl sub_080026DC
	movs	r0, #64
	bl sub_08005758
	ldr r2, _0800166D8
	strh	r0, [r2, #2]
	strh	r5, [r2, #0]
	ldr r4, _0800166DC
	ldr r1, _0800166E0
	mov	r3, r8
	movs	r6, #0
	ldrsh	r0, [r3, r6]
	subs	r0, #1
	lsls	r0, r0, #1
	adds	r0, r0, r1
	movs	r3, #0
	ldrsh	r1, [r0, r3]
	movs	r6, #2
	ldrsh	r2, [r2, r6]
	movs	r0, #64
	str	r0, [sp, #0]
	adds	r0, r4, #0
	movs	r3, #64
	bl sub_08007570
	ldr r1, _0800166E4
	mov	r2, r8
	movs	r3, #0
	ldrsh	r0, [r2, r3]
	subs	r0, #1
	lsls	r0, r0, #1
	adds	r0, r0, r1
	movs	r6, #0
	ldrsh	r1, [r0, r6]
	adds	r0, r4, #0
	movs	r2, #4
	bl sub_080075E8
	ldr	r0, [sp, #20]
	str	r0, [r7, #120]
	ldr	r1, [sp, #8]
	str	r1, [r7, #124]
	str	r5, [r7, #8]
	movs	r0, #1
	strh	r0, [r7, #12]
	movs	r2, #32
	negs	r2, r2
	ldr	r0, [sp, #16]
	movs	r1, #0
	bl sub_0800D77C
	ldr	r0, [sp, #12]
	movs	r1, #0
	movs	r2, #160
	bl sub_0800D77C
	movs	r0, #6
	strh	r0, [r7, #16]
	movs	r0, #5
	strh	r0, [r7, #18]
	movs	r0, #2
	ldr	r2, [sp, #20]
	str	r0, [r2, #0]
	add	sp, #32
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_0800166C0: .4byte 0x082FE118
_0800166C4: .4byte 0x08300404
_0800166C8: .4byte 0x080CB8B8
_0800166CC: .4byte 0x03001780
_0800166D0: .4byte 0x00000FF8
_0800166D4: .4byte 0x00000FF4
_0800166D8: .4byte 0x0203F8E8
_0800166DC: .4byte 0x08306B54
_0800166E0: .4byte 0x080CB8AC
_0800166E4: .4byte 0x080CB8B2
	.type sub_0800166E8, %function
sub_0800166E8:
_0800166E8:
	push	{r4, lr}
	adds	r4, r0, #0
	lsls	r2, r2, #16
	ldr r0, _080016728
	adds	r2, r2, r0
	lsrs	r2, r2, #16
	cmp	r2, #1
	bhi _080016720
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r4, #0
	adds	r0, #136
	movs	r1, #1
	str	r1, [r0, #0]
	movs	r2, #0
	strh	r2, [r4, #12]
	subs	r0, #20
	strh	r1, [r0, #0]
	ldr r0, _08001672C
	ldr r1, _080016730
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #1
	bne _08001671E
	strh	r0, [r4, #16]
_08001671E:
	str	r2, [r4, #36]
_080016720:
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080016728: .4byte 0xFFFF0000
_08001672C: .4byte 0x03001780
_080016730: .4byte 0x00001074
	.type sub_080016734, %function
sub_080016734:
_080016734:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	sub	sp, #24
	adds	r6, r0, #0
	adds	r7, r1, #0
	adds	r1, r2, #0
	mov	r8, r3
	ldr r2, _0800167B4
	ldr	r0, [r2, #0]
	subs	r0, #1
	str	r0, [r2, #0]
	ldr r5, _0800167B8
	cmp	r0, #0
	bgt _08001675C
	ldrh	r0, [r5, #0]
	adds	r0, #1
	strh	r0, [r5, #0]
	movs	r0, #5
	str	r0, [r2, #0]
_08001675C:
	adds	r2, r5, #0
	movs	r3, #0
	ldrsh	r0, [r2, r3]
	cmp	r0, #15
	ble _08001676A
	movs	r0, #0
	strh	r0, [r2, #0]
_08001676A:
	ldr r0, _0800167BC
	ldr r2, _0800167C0
	lsls	r1, r1, #1
	adds	r1, r1, r2
	movs	r4, #0
	ldrsh	r1, [r1, r4]
	movs	r3, #2
	ldrsh	r2, [r5, r3]
	movs	r4, #0
	ldrsh	r3, [r5, r4]
	lsls	r3, r3, #6
_080016780:
	movs	r4, #64
	str	r4, [sp, #0]
	bl sub_08007570
	movs	r0, #2
	ldrsh	r2, [r5, r0]
	movs	r1, #1
	str	r1, [sp, #0]
	movs	r0, #3
	str	r0, [sp, #4]
	str	r1, [sp, #8]
	movs	r0, #0
	str	r0, [sp, #12]
	str	r0, [sp, #16]
	str	r1, [sp, #20]
	adds	r0, r6, #0
	adds	r1, r7, #0
	mov	r3, r8
	bl 0x08002ED0
	add	sp, #24
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_0800167B4: .4byte 0x0300058C
_0800167B8: .4byte 0x0203F8E8
_0800167BC: .4byte 0x08306B54
_0800167C0: .4byte 0x080CB8AC
	.type sub_0800167C4, %function
sub_0800167C4:
_0800167C4:
	push	{r4, lr}
	sub	sp, #20
	adds	r4, r0, #0
	adds	r0, #128
	movs	r1, #15
	bl sub_0800D97C
	adds	r0, r4, #0
	adds	r0, #144
	ldr	r1, [r0, #0]
	adds	r0, #4
	ldr	r2, [r0, #0]
	movs	r0, #64
	str	r0, [sp, #0]
	movs	r0, #3
	str	r0, [sp, #4]
	movs	r0, #1
	str	r0, [sp, #8]
	movs	r0, #0
	str	r0, [sp, #12]
	str	r0, [sp, #16]
	adds	r0, r4, #0
	movs	r3, #80
	bl sub_08007BFC
	adds	r0, r4, #0
	adds	r0, #132
	movs	r1, #0
	ldrsh	r2, [r0, r1]
	subs	r2, #1
	movs	r0, #8
	movs	r1, #72
	movs	r3, #4
	bl sub_080016734
	adds	r0, r4, #0
	adds	r0, #8
	bl sub_0800DBE8
	add	sp, #20
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08001681C, %function
sub_08001681C:
_08001681C:
	push	{r4, r5, lr}
	adds	r5, r1, #0
	adds	r4, r3, #0
	subs	r0, #1
	cmp	r0, #11
	bhi _0800168B0
	lsls	r0, r0, #2
	ldr r1, _080016834
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_080016834: .4byte 0x08016838
_080016838: .4byte 0x080168A2
_08001683C: .4byte 0x08016868
_080016840: .4byte 0x080168B0
_080016844: .4byte 0x080168B0
_080016848: .4byte 0x08016872
_08001684C: .4byte 0x0801688C
_080016850: .4byte 0x08016884
_080016854: .4byte 0x080168B0
_080016858: .4byte 0x080168B0
_08001685C: .4byte 0x080168B0
_080016860: .4byte 0x080168B0
_080016864: .4byte 0x080168AA
_080016868:
	adds	r0, r4, #0
	adds	r1, r5, #0
	bl sub_0800164D4
	b _0800168B0
_080016872:
	adds	r0, r4, #0
	adds	r0, #8
	bl sub_0800D854
	adds	r0, r4, #0
	adds	r0, #112
	bl sub_0800D8E4
	b _0800168B0
_080016884:
	adds	r0, r4, #0
	bl sub_0800167C4
	b _0800168B0
_08001688C:
	ldrh	r0, [r4, #12]
	cmp	r0, #0
	beq _0800168B0
	lsls	r1, r5, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r4, #0
	bl sub_0800166E8
	b _0800168B0
_0800168A2:
	adds	r0, r4, #0
	bl sub_08001650C
	b _0800168B0
_0800168AA:
	adds	r0, r4, #0
	bl sub_080016508
_0800168B0:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800168B8, %function
sub_0800168B8:
_0800168B8:
	push	{lr}
	lsls	r0, r0, #16
	lsrs	r1, r0, #16
	ldr r0, _0800168D4
	ldr r2, _0800168D8
	adds	r0, r0, r2
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne _0800168DC
	adds	r0, r1, #0
	bl 0x0802B368
	b _0800168E2
	movs	r0, r0
_0800168D4: .4byte 0x03001780
_0800168D8: .4byte 0x000010C3
_0800168DC:
	adds	r0, r1, #0
	bl 0x0802B368
_0800168E2:
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800168E8, %function
sub_0800168E8:
_0800168E8:
	push	{r4, r5, lr}
	adds	r4, r1, #0
	adds	r5, r0, #0
	adds	r5, #192
	movs	r0, #0
	strh	r0, [r5, #0]
_0800168F4:
	ldr r2, _080016934
	ldr r1, _080016938
	adds	r0, r2, r1
	ldrh	r0, [r0, #0]
	cmp	r0, #3
	bne _080016920
	adds	r1, r4, #0
	adds	r1, #88
	movs	r0, #0
	strb	r0, [r1, #0]
	ldr r1, _08001693C
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _080016920
	adds	r0, r4, #0
	movs	r1, #1
	movs	r2, #1
	bl 0x080056F4
	movs	r0, #1
	strh	r0, [r5, #0]
_080016920:
	bl 0x08004B68
	ldrh	r0, [r0, #2]
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #1
	strh	r0, [r1, #0]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_080016934: .4byte 0x03001780
_080016938: .4byte 0x00000FBC
_08001693C: .4byte 0x000010C3
	.type sub_080016940, %function
sub_080016940:
_080016940:
	bx	lr
	movs	r0, r0
	.type sub_080016944, %function
sub_080016944:
_080016944:
	push	{r4, r5, r6, lr}
	adds	r5, r0, #0
	movs	r0, #0
	bl 0x08024BFC
	adds	r4, r0, #0
	movs	r0, #1
	bl 0x08024BFC
	ldrh	r2, [r4, #0]
	adds	r1, r5, #0
	adds	r1, #204
	movs	r3, #0
	strh	r2, [r1, #0]
	ldrh	r0, [r0, #0]
	adds	r1, #2
	strh	r0, [r1, #0]
	adds	r0, r5, #0
	adds	r0, #182
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #2
	beq _080016992
	cmp	r0, #2
	bgt _08001697C
	cmp	r0, #1
	beq _08001698A
	b _080016980
_08001697C:
	cmp	r0, #3
	beq _0800169A6
_080016980:
	adds	r3, r5, #0
	adds	r3, #208
	adds	r6, r5, #0
	adds	r6, #210
	b _0800169B6
_08001698A:
	adds	r1, r5, #0
	adds	r1, #208
	strh	r0, [r1, #0]
	b _0800169AC
_080016992:
	adds	r2, r5, #0
	adds	r2, #208
	strh	r3, [r2, #0]
	adds	r1, r5, #0
	adds	r1, #210
	movs	r0, #1
	strh	r0, [r1, #0]
	adds	r3, r2, #0
	adds	r6, r1, #0
	b _0800169B6
_0800169A6:
	adds	r1, r5, #0
	adds	r1, #208
	strh	r3, [r1, #0]
_0800169AC:
	adds	r0, r5, #0
	adds	r0, #210
	strh	r3, [r0, #0]
	adds	r3, r1, #0
	adds	r6, r0, #0
_0800169B6:
	movs	r0, #230
	lsls	r0, r0, #1
	adds	r2, r5, r0
	ldr r4, _080016A1C
	movs	r0, #0
	ldrsh	r1, [r3, r0]
	lsls	r1, r1, #1
	adds	r0, r5, #0
	adds	r0, #204
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	lsls	r0, r0, #2
	adds	r1, r1, r0
	adds	r1, r1, r4
	movs	r0, #0
	ldrsh	r1, [r1, r0]
	str	r1, [r2, #0]
	ldr	r0, [r5, #12]
	movs	r3, #228
	lsls	r3, r3, #1
	adds	r2, r5, r3
	ldr	r2, [r2, #0]
	bl sub_08007ABC
	movs	r0, #236
	lsls	r0, r0, #1
	adds	r2, r5, r0
	movs	r3, #0
	ldrsh	r1, [r6, r3]
	lsls	r1, r1, #1
	adds	r0, r5, #0
	adds	r0, #206
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	lsls	r0, r0, #2
	adds	r1, r1, r0
	adds	r1, r1, r4
	movs	r0, #0
	ldrsh	r1, [r1, r0]
	str	r1, [r2, #0]
	ldr	r0, [r5, #12]
	movs	r3, #234
	lsls	r3, r3, #1
	adds	r2, r5, r3
	ldr	r2, [r2, #0]
	bl sub_08007ABC
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080016A1C: .4byte 0x080CB8CC
	.type sub_080016A20, %function
sub_080016A20:
_080016A20:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	sub	sp, #8
	adds	r6, r0, #0
	movs	r0, #0
	mov	r8, r0
	bl 0x08024BFC
	str	r0, [sp, #0]
	movs	r0, #1
	bl 0x08024BFC
	str	r0, [sp, #4]
	movs	r7, #0
_080016A3E:
	mov	r1, r8
	lsls	r5, r1, #2
	add	r5, sp
	ldr	r0, [r5, #0]
	movs	r2, #16
	ldrsh	r4, [r0, r2]
	adds	r0, r4, #0
	bl 0x080022E4
	adds	r0, r4, #0
	bl 0x08024D5C
	adds	r1, r0, #0
	movs	r3, #194
	lsls	r3, r3, #1
	adds	r0, r6, r3
	adds	r0, r0, r7
	str	r1, [r0, #0]
	ldr	r0, [r6, #20]
	subs	r3, #4
	adds	r2, r6, r3
	adds	r2, r2, r7
	ldr	r2, [r2, #0]
	bl sub_08007ABC
	adds	r0, r4, #0
	bl 0x08024C74
	adds	r1, r0, #0
	movs	r2, #206
	lsls	r2, r2, #1
	adds	r0, r6, r2
	adds	r0, r0, r7
	str	r1, [r0, #0]
	ldr	r0, [r6, #28]
	movs	r3, #204
	lsls	r3, r3, #1
	adds	r2, r6, r3
	adds	r2, r2, r7
	ldr	r2, [r2, #0]
	bl sub_08007ABC
	ldr	r0, [r5, #0]
	movs	r1, #2
	ldrsh	r0, [r0, r1]
	bl 0x080258A8
	adds	r1, r0, #0
	movs	r2, #218
	lsls	r2, r2, #1
	adds	r0, r6, r2
	adds	r0, r0, r7
	lsls	r1, r1, #16
	asrs	r1, r1, #16
	str	r1, [r0, #0]
	ldr	r0, [r6, #36]
	movs	r3, #216
	lsls	r3, r3, #1
	adds	r2, r6, r3
	adds	r2, r2, r7
	ldr	r2, [r2, #0]
	bl sub_08007ABC
	adds	r7, #12
	movs	r0, #1
	add	r8, r0
	mov	r1, r8
	cmp	r1, #1
	ble _080016A3E
	add	sp, #8
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.type sub_080016AD4, %function
sub_080016AD4:
_080016AD4:
	push	{r4, lr}
	adds	r4, r0, #0
	movs	r0, #0
	bl 0x08002060
	movs	r0, #173
	lsls	r0, r0, #1
	adds	r1, r4, r0
	movs	r0, #180
	strh	r0, [r1, #0]
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080016AF0, %function
sub_080016AF0:
_080016AF0:
	push	{r4, r5, r6, r7, lr}
	adds	r6, r0, #0
	adds	r0, #196
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #7
	bhi _080016BB0
	lsls	r0, r0, #2
	ldr r1, _080016B08
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
_080016B08: .4byte 0x08016B0C
_080016B0C: .4byte 0x08016BB0
_080016B10: .4byte 0x08016B2C
_080016B14: .4byte 0x08016B40
_080016B18: .4byte 0x08016B54
_080016B1C: .4byte 0x08016B66
_080016B20: .4byte 0x08016BB0
_080016B24: .4byte 0x08016BB0
_080016B28: .4byte 0x08016BB0
_080016B2C:
	adds	r0, r6, #0
	adds	r0, #212
	movs	r1, #64
	bl 0x0800226C
	adds	r1, r6, #0
	adds	r1, #196
	movs	r0, #3
	strh	r0, [r1, #0]
	b _080016BB0
_080016B40:
	movs	r1, #138
	lsls	r1, r1, #1
	adds	r0, r6, r1
	bl 0x08002298
	adds	r1, r6, #0
	adds	r1, #196
	movs	r0, #4
	strh	r0, [r1, #0]
	b _080016BB0
_080016B54:
	bl 0x080022C0
	adds	r1, r0, #0
	cmp	r1, #1
	bne _080016BB0
	adds	r0, r6, #0
	adds	r0, #194
	strh	r1, [r0, #0]
	b _080016BB0
_080016B66:
	bl 0x080022C0
	adds	r7, r0, #0
	cmp	r7, #1
	bne _080016BB0
	movs	r0, #138
	lsls	r0, r0, #1
	adds	r4, r6, r0
	movs	r0, #0
	bl 0x08024BFC
	adds	r1, r0, #0
	ldr r5, _080016BB8
	adds	r0, r4, #0
	adds	r2, r5, #0
	bl 0x0802D974
	movs	r1, #154
	lsls	r1, r1, #1
	adds	r4, r6, r1
	movs	r0, #1
	bl 0x08024BFC
	adds	r1, r0, #0
	adds	r0, r4, #0
	adds	r2, r5, #0
	bl 0x0802D974
	adds	r0, r6, #0
	bl sub_080016944
	adds	r0, r6, #0
	bl sub_080016A20
	adds	r0, r6, #0
	adds	r0, #194
	strh	r7, [r0, #0]
_080016BB0:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080016BB8: .4byte 0x04000008
	.type sub_080016BBC, %function
sub_080016BBC:
_080016BBC:
	push	{r4, r5, r6, lr}
	adds	r5, r0, #0
	adds	r0, #198
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #7
	bls _080016BCC
	b _080016DB8
_080016BCC:
	lsls	r0, r0, #2
	ldr r1, _080016BD8
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_080016BD8: .4byte 0x08016BDC
_080016BDC: .4byte 0x08016BFC
_080016BE0: .4byte 0x08016C48
_080016BE4: .4byte 0x08016C8C
_080016BE8: .4byte 0x08016CCC
_080016BEC: .4byte 0x08016D02
_080016BF0: .4byte 0x08016DB8
_080016BF4: .4byte 0x08016D90
_080016BF8: .4byte 0x08016DB8
_080016BFC:
	movs	r0, #1
	movs	r1, #2
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r4, r0, #16
	cmp	r4, #1
	beq _080016C0E
	b _080016DB8
_080016C0E:
	ldr r0, _080016C24
	ldr r2, _080016C28
	adds	r0, r0, r2
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne _080016C2C
	adds	r1, r5, #0
	adds	r1, #198
	movs	r0, #2
	b _080016DB6
	movs	r0, r0
_080016C24: .4byte 0x03001780
_080016C28: .4byte 0x000010C3
_080016C2C:
	adds	r0, r5, #0
	bl sub_080016AD4
	movs	r1, #170
	lsls	r1, r1, #1
	adds	r0, r5, r1
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	bl 0x08024C18
	adds	r0, r5, #0
	adds	r0, #198
	strh	r4, [r0, #0]
	b _080016DB8
_080016C48:
	movs	r1, #254
	lsls	r1, r1, #1
	adds	r0, r5, r1
	movs	r1, #0
	str	r1, [r0, #0]
	movs	r2, #128
	lsls	r2, r2, #2
	adds	r0, r5, r2
	str	r1, [r0, #0]
	bl 0x080240D0
	adds	r0, #32
	movs	r1, #158
	lsls	r1, r1, #4
	bl 0x0800226C
	adds	r1, r5, #0
	adds	r1, #198
	movs	r0, #3
	strh	r0, [r1, #0]
	movs	r0, #1
	movs	r1, #1
	bl 0x08002618
	adds	r1, r5, #0
	adds	r1, #192
	movs	r0, #1
	strh	r0, [r1, #0]
	movs	r0, #240
	lsls	r0, r0, #1
	adds	r4, r5, r0
	adds	r0, r4, #0
	movs	r1, #4
	b _080016CEC
_080016C8C:
	movs	r1, #254
	lsls	r1, r1, #1
	adds	r0, r5, r1
	movs	r1, #0
	str	r1, [r0, #0]
	movs	r2, #128
	lsls	r2, r2, #2
	adds	r0, r5, r2
	str	r1, [r0, #0]
	bl 0x080240D0
	adds	r0, #32
	bl 0x08002298
	adds	r1, r5, #0
	adds	r1, #198
	movs	r0, #4
	strh	r0, [r1, #0]
	movs	r0, #1
	movs	r1, #1
	bl 0x08002618
	adds	r1, r5, #0
	adds	r1, #192
	movs	r0, #1
	strh	r0, [r1, #0]
	movs	r0, #240
	lsls	r0, r0, #1
	adds	r4, r5, r0
	adds	r0, r4, #0
	movs	r1, #2
	b _080016CEC
_080016CCC:
	bl 0x080022C0
	cmp	r0, #1
	bne _080016DB8
	adds	r1, r5, #0
	adds	r1, #198
	movs	r0, #6
	strh	r0, [r1, #0]
	adds	r0, r5, #0
	bl sub_080016AD4
	movs	r0, #240
	lsls	r0, r0, #1
	adds	r4, r5, r0
	adds	r0, r4, #0
	movs	r1, #3
_080016CEC:
	bl sub_08025BF0
	ldr	r0, [r5, #44]
	movs	r2, #242
	lsls	r2, r2, #1
	adds	r1, r5, r2
	ldr	r1, [r1, #0]
	ldr	r2, [r4, #0]
	bl sub_08007ABC
	b _080016DB8
_080016D02:
	bl 0x080022C0
	cmp	r0, #1
	bne _080016DB8
	adds	r0, r5, #0
	bl sub_080016AD4
	movs	r0, #240
	lsls	r0, r0, #1
	adds	r4, r5, r0
	adds	r0, r4, #0
	movs	r1, #1
	bl sub_08025BF0
	ldr	r0, [r5, #44]
	movs	r2, #242
	lsls	r2, r2, #1
	adds	r1, r5, r2
	ldr	r1, [r1, #0]
	ldr	r2, [r4, #0]
	bl sub_08007ABC
	movs	r0, #171
	lsls	r0, r0, #1
	adds	r6, r5, r0
	movs	r1, #0
	ldrsh	r4, [r6, r1]
	bl 0x080240D0
	adds	r1, r0, #0
	adds	r1, #32
	adds	r0, r4, #0
	bl 0x08024C14
	movs	r2, #170
	lsls	r2, r2, #1
	adds	r0, r5, r2
	movs	r1, #0
	ldrsh	r4, [r0, r1]
	lsls	r4, r4, #5
	subs	r2, #64
	adds	r4, r4, r2
	adds	r4, r5, r4
	movs	r1, #0
	ldrsh	r0, [r6, r1]
	bl 0x08024BFC
	adds	r1, r0, #0
	ldr r2, _080016D8C
	adds	r0, r4, #0
	bl 0x0802D974
	movs	r0, #0
	bl 0x08024C10
	movs	r0, #1
	bl 0x08024C10
	bl 0x08024C1C
	adds	r0, r5, #0
	bl sub_080016944
	adds	r0, r5, #0
	bl sub_080016A20
	adds	r1, r5, #0
	adds	r1, #198
	b _080016DB4
_080016D8C: .4byte 0x04000008
_080016D90:
	movs	r2, #128
	lsls	r2, r2, #2
	adds	r1, r5, r2
	movs	r0, #1
	str	r0, [r1, #0]
	movs	r1, #6
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r1, r0, #16
	cmp	r1, #1
	bne _080016DB8
	movs	r2, #254
	lsls	r2, r2, #1
	adds	r0, r5, r2
	str	r1, [r0, #0]
	adds	r1, r5, #0
	adds	r1, #194
_080016DB4:
	movs	r0, #6
_080016DB6:
	strh	r0, [r1, #0]
_080016DB8:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080016DC0, %function
sub_080016DC0:
_080016DC0:
	push	{r4, lr}
	movs	r1, #173
	lsls	r1, r1, #1
	adds	r4, r0, r1
	ldrh	r0, [r4, #0]
	subs	r0, #1
	strh	r0, [r4, #0]
	lsls	r0, r0, #16
	cmp	r0, #0
	bge _080016DDE
	movs	r0, #1
	bl 0x08002060
	movs	r0, #0
	strh	r0, [r4, #0]
_080016DDE:
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_080016DE4, %function
sub_080016DE4:
_080016DE4:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	adds	r0, #194
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #8
	bls _080016DF4
	b _080016F20
_080016DF4:
	lsls	r0, r0, #2
	ldr r1, _080016E00
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_080016E00: .4byte 0x08016E04
_080016E04: .4byte 0x08016E28
_080016E08: .4byte 0x08016E44
_080016E0C: .4byte 0x08016F20
_080016E10: .4byte 0x08016EC4
_080016E14: .4byte 0x08016F20
_080016E18: .4byte 0x08016E30
_080016E1C: .4byte 0x08016F20
_080016E20: .4byte 0x08016E8C
_080016E24: .4byte 0x08016F20
_080016E28:
	adds	r0, r5, #0
	bl sub_080016AF0
	b _080016F20
_080016E30:
	movs	r0, #3
	bl 0x0802B3B8
	lsls	r0, r0, #24
	cmp	r0, #0
	bne _080016F20
	adds	r0, r5, #0
	bl sub_080016BBC
	b _080016F20
_080016E44:
	movs	r0, #0
	bl 0x08024BFC
	adds	r4, r0, #0
	movs	r0, #1
	bl 0x08024BFC
	adds	r1, r0, #0
	ldrh	r0, [r4, #0]
	cmp	r0, #0
	bne _080016E6A
	ldrh	r0, [r1, #0]
	cmp	r0, #0
	bne _080016E6A
	adds	r1, r5, #0
	adds	r1, #194
	movs	r0, #7
	strh	r0, [r1, #0]
	b _080016F20
_080016E6A:
	movs	r2, #248
	lsls	r2, r2, #1
	adds	r1, r5, r2
	movs	r0, #0
	str	r0, [r1, #0]
	ldr	r0, [r5, #52]
	subs	r2, #4
	adds	r1, r5, r2
	ldr	r2, [r1, #0]
	movs	r1, #0
	bl sub_08007ABC
	adds	r1, r5, #0
	adds	r1, #194
	movs	r0, #2
	strh	r0, [r1, #0]
	b _080016F20
_080016E8C:
	movs	r0, #1
	movs	r1, #1
	bl 0x08002618
	adds	r1, r5, #0
	adds	r1, #192
	movs	r0, #1
	strh	r0, [r1, #0]
	movs	r0, #240
	lsls	r0, r0, #1
	adds	r4, r5, r0
	adds	r0, r4, #0
	movs	r1, #0
	bl sub_08025BF0
	ldr	r0, [r5, #44]
	movs	r2, #242
	lsls	r2, r2, #1
	adds	r1, r5, r2
	ldr	r1, [r1, #0]
	ldr	r2, [r4, #0]
	bl sub_08007ABC
	adds	r1, r5, #0
	adds	r1, #194
	movs	r0, #8
	strh	r0, [r1, #0]
	b _080016F20
_080016EC4:
	movs	r0, #3
	bl 0x0802B3B8
	lsls	r0, r0, #24
	cmp	r0, #0
	bne _080016F1C
	movs	r4, #1
	strh	r4, [r5, #60]
	movs	r0, #248
	lsls	r0, r0, #1
	adds	r1, r5, r0
	movs	r0, #2
	str	r0, [r1, #0]
	ldr	r0, [r5, #52]
	movs	r2, #246
	lsls	r2, r2, #1
	adds	r1, r5, r2
	ldr	r2, [r1, #0]
	movs	r1, #2
	bl sub_08007ABC
	bl 0x08024C1C
	adds	r0, r5, #0
	bl sub_080016944
	adds	r0, r5, #0
	bl sub_080016A20
	adds	r1, r5, #0
	adds	r1, #194
	movs	r0, #4
	strh	r0, [r1, #0]
	adds	r0, r5, #0
	adds	r0, #184
	strh	r4, [r0, #0]
	subs	r0, #2
	strh	r4, [r0, #0]
	adds	r0, #4
	strh	r4, [r0, #0]
	adds	r0, r5, #0
	bl sub_080016944
	b _080016F20
_080016F1C:
	movs	r0, #0
	strh	r0, [r5, #60]
_080016F20:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080016F28, %function
sub_080016F28:
_080016F28:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	adds	r0, #200
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #4
	bhi _080016FC8
	lsls	r0, r0, #2
	ldr r1, _080016F40
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
_080016F40: .4byte 0x08016F44
_080016F44: .4byte 0x08016FC0
_080016F48: .4byte 0x08016F58
_080016F4C: .4byte 0x08016FC8
_080016F50: .4byte 0x08016FBA
_080016F54: .4byte 0x08016FB4
_080016F58:
	movs	r0, #3
	bl 0x0802B3B8
	lsls	r0, r0, #24
	cmp	r0, #0
	bne _080016FC8
	adds	r0, r5, #0
	adds	r0, #182
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r0, #1
	beq _080016F76
	cmp	r0, #2
	beq _080016F7A
	b _080016FC8
_080016F76:
	movs	r0, #0
	b _080016F7C
_080016F7A:
	movs	r0, #1
_080016F7C:
	bl 0x08024C0C
	adds	r0, r5, #0
	bl sub_080016944
	adds	r0, r5, #0
	bl sub_080016A20
	adds	r1, r5, #0
	adds	r1, #200
	movs	r0, #4
	strh	r0, [r1, #0]
	movs	r0, #240
	lsls	r0, r0, #1
	adds	r4, r5, r0
	adds	r0, r4, #0
	movs	r1, #10
	bl sub_08025BF0
	ldr	r0, [r5, #44]
	movs	r2, #242
	lsls	r2, r2, #1
	adds	r1, r5, r2
	ldr	r1, [r1, #0]
	ldr	r2, [r4, #0]
	bl sub_08007ABC
	b _080016FC8
_080016FB4:
	movs	r0, #1
	strh	r0, [r5, #60]
	b _080016FC8
_080016FBA:
	adds	r0, r5, #0
	bl sub_0800173E8
_080016FC0:
	adds	r1, r5, #0
	adds	r1, #200
	movs	r0, #2
	strh	r0, [r1, #0]
_080016FC8:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080016FD0, %function
sub_080016FD0:
_080016FD0:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #56
	adds	r6, r0, #0
	ldr r1, _08001702C
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r5, #1
	str	r5, [sp, #4]
	movs	r0, #0
	movs	r2, #2
	movs	r3, #0
	bl sub_08007770
	ldr r1, _080017030
	movs	r4, #0
	str	r4, [sp, #0]
	movs	r0, #3
	str	r0, [sp, #4]
	movs	r0, #1
	movs	r2, #1
	movs	r3, #0
	bl sub_08007770
	adds	r1, r6, #0
	adds	r1, #128
	movs	r0, #6
	str	r0, [r1, #0]
	ldr r0, _080017034
	ldr r1, _080017038
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r2, [r0, r1]
	cmp	r2, #3
	bne _08001703C
	adds	r0, r6, #0
	adds	r0, #140
	movs	r1, #19
	str	r1, [r0, #0]
	adds	r0, #40
	strh	r2, [r0, #0]
	b _08001706C
	movs	r0, r0
_08001702C: .4byte 0x0831F244
_080017030: .4byte 0x082B7410
_080017034: .4byte 0x03001780
_080017038: .4byte 0x00000FBC
_08001703C:
	bl 0x08004B68
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r0, #39
	beq _080017060
	movs	r1, #180
	adds	r1, r1, r6
	mov	r9, r1
	cmp	r0, #40
	bne _08001706E
	adds	r1, r6, #0
	adds	r1, #140
	movs	r0, #19
	str	r0, [r1, #0]
	mov	r2, r9
	strh	r5, [r2, #0]
	b _08001706E
_080017060:
	adds	r0, r6, #0
	adds	r0, #140
	movs	r1, #18
	str	r1, [r0, #0]
	adds	r0, #40
	strh	r4, [r0, #0]
_08001706C:
	mov	r9, r0
_08001706E:
	adds	r1, r6, #0
	adds	r1, #152
	movs	r0, #1
	str	r0, [r1, #0]
	adds	r5, r6, #0
	adds	r5, #56
	adds	r0, r5, #0
	bl sub_0800DAB8
	ldr r4, _0800172E0
	adds	r0, r4, #0
	adds	r1, r6, #0
	bl sub_0800798C
	adds	r0, r6, #0
	bl sub_08007A58
	adds	r0, r4, #0
	movs	r1, #0
	movs	r2, #3
	bl sub_080075E8
	adds	r0, r4, #0
	movs	r1, #1
	movs	r2, #6
	bl sub_080075E8
	ldr r4, _0800172E4
	adds	r1, r6, #0
	adds	r1, #8
	adds	r0, r4, #0
	bl sub_0800798C
	adds	r0, r4, #0
	movs	r1, #0
	movs	r2, #5
	bl sub_080075E8
	str	r5, [sp, #36]
	adds	r7, r6, #0
	adds	r7, #48
	movs	r0, #32
	adds	r0, r0, r6
	mov	r8, r0
	movs	r1, #16
	adds	r1, r1, r6
	mov	sl, r1
	adds	r2, r6, #0
	adds	r2, #24
	str	r2, [sp, #28]
	adds	r0, r6, #0
	adds	r0, #40
	str	r0, [sp, #32]
	adds	r1, r6, #0
	adds	r1, #168
	str	r1, [sp, #8]
	adds	r2, #148
	str	r2, [sp, #12]
	adds	r0, #36
	str	r0, [sp, #52]
	subs	r1, #100
	str	r1, [sp, #48]
	subs	r2, #108
	str	r2, [sp, #40]
	subs	r0, #10
	str	r0, [sp, #44]
	adds	r1, #114
	str	r1, [sp, #16]
	adds	r2, #124
	str	r2, [sp, #20]
	adds	r0, #124
	str	r0, [sp, #24]
	movs	r4, #0
	movs	r5, #1
_080017102:
	movs	r0, #150
	bl sub_0800572C
	movs	r1, #228
	lsls	r1, r1, #1
	adds	r2, r6, r1
	adds	r2, r2, r4
	str	r0, [r2, #0]
	adds	r1, #4
	adds	r0, r6, r1
	adds	r0, r0, r4
	movs	r1, #1
	str	r1, [r0, #0]
	ldr	r0, [r6, #12]
	ldr	r2, [r2, #0]
	bl sub_08007ABC
	adds	r4, #12
	subs	r5, #1
	cmp	r5, #0
	bge _080017102
	ldr r0, _0800172E8
	adds	r1, r7, #0
	bl sub_0800798C
	movs	r0, #30
	bl sub_0800572C
	movs	r1, #246
	lsls	r1, r1, #1
	adds	r2, r6, r1
	str	r0, [r2, #0]
	movs	r0, #248
	lsls	r0, r0, #1
	adds	r1, r6, r0
	movs	r0, #0
	str	r0, [r1, #0]
	ldr	r0, [r6, #52]
	ldr	r2, [r2, #0]
	movs	r1, #0
	bl sub_08007ABC
	ldr r4, _0800172EC
	adds	r0, r4, #0
	mov	r1, r8
	bl sub_0800798C
	adds	r0, r4, #0
	movs	r1, #0
	movs	r2, #7
	bl sub_080075E8
	ldr r1, _0800172F0
	mov	r8, r1
	movs	r5, #0
	movs	r7, #1
_080017172:
	movs	r0, #12
	bl sub_0800572C
	movs	r2, #216
	lsls	r2, r2, #1
	adds	r4, r6, r2
	adds	r4, r4, r5
	str	r0, [r4, #0]
	mov	r1, r8
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	bl 0x080258A8
	adds	r1, r0, #0
	movs	r2, #218
	lsls	r2, r2, #1
	adds	r0, r6, r2
	adds	r0, r0, r5
	lsls	r1, r1, #16
	asrs	r1, r1, #16
	str	r1, [r0, #0]
	ldr	r0, [r6, #36]
	ldr	r2, [r4, #0]
	bl sub_08007ABC
	adds	r5, #12
	subs	r7, #1
	cmp	r7, #0
	bge _080017172
	ldr r0, _0800172F4
	movs	r1, #0
	movs	r2, #4
	bl sub_080075E8
	ldr r0, _0800172F8
	mov	r1, sl
	bl sub_0800798C
	ldr r0, _0800172FC
	ldr	r1, [sp, #28]
	bl sub_0800798C
	movs	r4, #0
	movs	r7, #1
_0800171CA:
	movs	r0, #7
	bl sub_0800572C
	movs	r1, #192
	lsls	r1, r1, #1
	adds	r2, r6, r1
	adds	r2, r2, r4
	str	r0, [r2, #0]
	adds	r1, #4
	adds	r0, r6, r1
	adds	r0, r0, r4
	movs	r1, #4
	str	r1, [r0, #0]
	ldr	r0, [r6, #20]
	ldr	r2, [r2, #0]
	bl sub_08007ABC
	movs	r0, #7
	bl sub_0800572C
	movs	r1, #204
	lsls	r1, r1, #1
	adds	r2, r6, r1
	adds	r2, r2, r4
	str	r0, [r2, #0]
	adds	r1, #4
	adds	r0, r6, r1
	adds	r0, r0, r4
	movs	r1, #50
	str	r1, [r0, #0]
	ldr	r0, [r6, #28]
	ldr	r2, [r2, #0]
	bl sub_08007ABC
	adds	r4, #12
	subs	r7, #1
	cmp	r7, #0
	bge _0800171CA
	ldr r4, _080017300
	adds	r0, r4, #0
	ldr	r1, [sp, #32]
	bl sub_0800798C
	adds	r0, r4, #0
	movs	r1, #0
	movs	r2, #8
	bl sub_080075E8
	movs	r2, #240
	lsls	r2, r2, #1
	adds	r4, r6, r2
	adds	r0, r4, #0
	movs	r1, #5
	bl 0x08025BC8
	ldr	r0, [r6, #44]
	movs	r2, #242
	lsls	r2, r2, #1
	adds	r1, r6, r2
	ldr	r1, [r1, #0]
	ldr	r2, [r4, #0]
	bl sub_08007ABC
	movs	r0, #176
	lsls	r0, r0, #1
	adds	r4, r6, r0
	ldr	r1, [sp, #8]
	str	r4, [r1, #0]
	ldr	r2, [sp, #36]
	ldr	r0, [sp, #12]
	str	r2, [r0, #0]
	movs	r7, #0
	str	r7, [r6, #56]
	movs	r5, #1
	strh	r5, [r6, #60]
	movs	r2, #32
	negs	r2, r2
	ldr	r0, [sp, #52]
	movs	r1, #0
	bl sub_0800D77C
	ldr	r0, [sp, #48]
	movs	r1, #0
	movs	r2, #160
	bl sub_0800D77C
	ldr	r1, [sp, #40]
	strh	r5, [r1, #0]
	ldr	r2, [sp, #44]
	strh	r5, [r2, #0]
	ldr	r0, [sp, #16]
	strh	r5, [r0, #0]
	movs	r1, #2
	mov	r8, r1
	str	r1, [r4, #0]
	ldr	r2, [sp, #20]
	strh	r7, [r2, #0]
	ldr	r0, [sp, #24]
	strh	r7, [r0, #0]
	mov	r1, r9
	ldrh	r1, [r1, #0]
	cmp	r1, #3
	beq _08001729E
	adds	r0, r6, #0
	bl sub_080016944
_08001729E:
	adds	r0, r6, #0
	bl sub_080016A20
	ldr r4, _080017304
	ldr r2, _080017308
	adds	r0, r4, r2
	ldrh	r1, [r0, #0]
	movs	r2, #182
	lsls	r2, r2, #1
	adds	r0, r6, r2
	strh	r1, [r0, #0]
	ldr r1, _08001730C
	adds	r0, r4, r1
	ldrh	r0, [r0, #0]
	subs	r2, #2
	adds	r1, r6, r2
	strh	r0, [r1, #0]
	movs	r0, #174
	lsls	r0, r0, #1
	adds	r1, r6, r0
	movs	r0, #20
	strh	r0, [r1, #0]
	mov	r1, r9
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r0, #1
	beq _08001733C
	cmp	r0, #1
	bgt _080017310
	cmp	r0, #0
	beq _080017316
	b _0800173B8
	movs	r0, r0
_0800172E0: .4byte 0x0831F244
_0800172E4: .4byte 0x08320060
_0800172E8: .4byte 0x08324F00
_0800172EC: .4byte 0x082DFBDC
_0800172F0: .4byte 0x03001CF6
_0800172F4: .4byte 0x082C4228
_0800172F8: .4byte 0x082C4458
_0800172FC: .4byte 0x08325A7C
_080017300: .4byte 0x082B7410
_080017304: .4byte 0x03001780
_080017308: .4byte 0x00000FBE
_08001730C: .4byte 0x00000574
_080017310:
	cmp	r0, #3
	beq _080017356
	b _0800173B8
_080017316:
	bl 0x0802412C
	movs	r1, #248
	lsls	r1, r1, #1
	adds	r0, r6, r1
	mov	r2, r8
	str	r2, [r0, #0]
	ldr	r0, [r6, #52]
	movs	r2, #246
	lsls	r2, r2, #1
	adds	r1, r6, r2
	ldr	r2, [r1, #0]
	movs	r1, #2
	bl sub_08007ABC
	adds	r0, r6, #0
	adds	r0, #200
	strh	r7, [r0, #0]
	b _0800173B8
_08001733C:
	movs	r1, #248
	lsls	r1, r1, #1
	adds	r0, r6, r1
	str	r5, [r0, #0]
	ldr	r0, [r6, #52]
	movs	r2, #246
	lsls	r2, r2, #1
	adds	r1, r6, r2
	ldr	r2, [r1, #0]
	movs	r1, #1
	bl sub_08007ABC
	b _0800173B8
_080017356:
	adds	r0, r6, #0
	adds	r0, #194
	strh	r7, [r0, #0]
	ldr r0, _080017378
	bl 0x08002124
	ldr r1, _08001737C
	adds	r0, r4, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne _080017380
	adds	r0, r6, #0
	adds	r0, #196
	mov	r2, r8
	strh	r2, [r0, #0]
	b _0800173B8
	movs	r0, r0
_080017378: .4byte 0x00001390
_08001737C: .4byte 0x000010C3
_080017380:
	bl 0x08024C1C
	adds	r0, r6, #0
	bl sub_080016944
	adds	r0, r6, #0
	bl sub_080016A20
	adds	r0, r6, #0
	adds	r0, #196
	strh	r5, [r0, #0]
	movs	r0, #0
	bl 0x08024BFC
	adds	r1, r6, #0
	adds	r1, #212
	ldr r4, _0800173E4
	adds	r2, r4, #0
	bl 0x0802D974
	movs	r0, #1
	bl 0x08024BFC
	adds	r1, r6, #0
	adds	r1, #244
	adds	r2, r4, #0
	bl 0x0802D974
_0800173B8:
	movs	r0, #172
	lsls	r0, r0, #1
	adds	r1, r6, r0
	movs	r0, #0
	strh	r0, [r1, #0]
	movs	r1, #254
	lsls	r1, r1, #1
	adds	r0, r6, r1
	movs	r1, #1
	str	r1, [r0, #0]
	movs	r2, #128
	lsls	r2, r2, #2
	adds	r0, r6, r2
	str	r1, [r0, #0]
	add	sp, #56
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_0800173E4: .4byte 0x04000008
	.type sub_0800173E8, %function
sub_0800173E8:
_0800173E8:
	push	{r4, r5, lr}
	adds	r4, r0, #0
	movs	r0, #1
	movs	r1, #0
	bl 0x08002618
	adds	r0, r4, #0
	adds	r0, #192
	movs	r5, #0
	strh	r5, [r0, #0]
	movs	r0, #1
	bl 0x0802B368
	movs	r0, #10
	str	r0, [r4, #56]
	strh	r5, [r4, #60]
	str	r0, [r4, #88]
	movs	r0, #1
	str	r0, [r4, #84]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_080017414, %function
sub_080017414:
_080017414:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	movs	r0, #1
	movs	r1, #0
	bl 0x08002618
	adds	r0, r5, #0
	adds	r0, #192
	movs	r4, #0
	strh	r4, [r0, #0]
	movs	r0, #4
	bl 0x0802B368
	movs	r0, #10
	str	r0, [r5, #56]
	strh	r4, [r5, #60]
	str	r0, [r5, #88]
	str	r4, [r5, #84]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080017440, %function
sub_080017440:
_080017440:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	adds	r5, r0, #0
	lsls	r2, r2, #16
	lsrs	r6, r2, #16
	adds	r7, r5, #0
	adds	r7, #182
	ldrh	r0, [r7, #0]
	mov	r8, r0
	adds	r4, r5, #0
	adds	r4, #200
	ldrh	r1, [r4, #0]
	cmp	r1, #4
	beq _080017516
	cmp	r6, #2
	bne _080017474
	movs	r0, #4
	bl 0x0802B368
	movs	r1, #10
	str	r1, [r5, #56]
	movs	r0, #0
	strh	r0, [r5, #60]
	str	r1, [r5, #88]
	str	r0, [r5, #84]
_080017474:
	cmp	r6, #1
	bne _0800174D0
	movs	r2, #0
	ldrsh	r0, [r7, r2]
	cmp	r0, #2
	beq _080017490
	cmp	r0, #2
	bgt _08001748A
	cmp	r0, #1
	beq _080017490
	b _0800174D0
_08001748A:
	cmp	r0, #3
	beq _0800174CA
	b _0800174D0
_080017490:
	movs	r0, #1
	bl 0x0802B368
	movs	r0, #0
	strh	r6, [r4, #0]
	strh	r0, [r5, #60]
	movs	r3, #240
	lsls	r3, r3, #1
	adds	r4, r5, r3
	adds	r0, r4, #0
	movs	r1, #9
	bl sub_08025BF0
	ldr	r0, [r5, #44]
	movs	r2, #242
	lsls	r2, r2, #1
	adds	r1, r5, r2
	ldr	r1, [r1, #0]
	ldr	r2, [r4, #0]
	bl sub_08007ABC
	movs	r0, #1
	movs	r1, #1
	bl 0x08002618
	adds	r0, r5, #0
	adds	r0, #192
	strh	r6, [r0, #0]
	b _0800174D0
_0800174CA:
	adds	r0, r5, #0
	bl sub_080017414
_0800174D0:
	adds	r2, r5, #0
	adds	r2, #182
	cmp	r6, #64
	bne _0800174DE
	ldrh	r0, [r2, #0]
	subs	r0, #1
	strh	r0, [r2, #0]
_0800174DE:
	cmp	r6, #128
	bne _0800174E8
	ldrh	r0, [r2, #0]
	adds	r0, #1
	strh	r0, [r2, #0]
_0800174E8:
	adds	r1, r2, #0
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #0
	bgt _0800174F6
	movs	r0, #1
	strh	r0, [r1, #0]
_0800174F6:
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #3
	ble _080017502
	movs	r0, #3
	strh	r0, [r1, #0]
_080017502:
	ldrh	r2, [r2, #0]
	cmp	r8, r2
	beq _08001751E
	adds	r0, r5, #0
	bl sub_080016944
	movs	r0, #2
	bl 0x0802B368
	b _08001751E
_080017516:
	cmp	r6, #1
	bne _08001751E
	movs	r0, #3
	strh	r0, [r4, #0]
_08001751E:
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.type sub_080017528, %function
sub_080017528:
_080017528:
	push	{r4, r5, r6, r7, lr}
	adds	r4, r0, #0
	lsls	r2, r2, #16
	lsrs	r6, r2, #16
	adds	r5, r4, #0
	adds	r5, #182
	ldrh	r7, [r5, #0]
	cmp	r6, #2
	bne _08001753E
	bl sub_080017414
_08001753E:
	cmp	r6, #1
	bne _080017572
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	cmp	r0, #2
	beq _08001755E
	cmp	r0, #2
	bgt _080017554
	cmp	r0, #1
	beq _08001755A
	b _080017572
_080017554:
	cmp	r0, #3
	beq _08001756C
	b _080017572
_08001755A:
	movs	r0, #0
	b _080017560
_08001755E:
	movs	r0, #1
_080017560:
	bl 0x08024C08
	adds	r0, r4, #0
	bl sub_0800173E8
	b _080017572
_08001756C:
	adds	r0, r4, #0
	bl sub_0800173E8
_080017572:
	adds	r2, r4, #0
	adds	r2, #182
	cmp	r6, #64
	bne _080017580
	ldrh	r0, [r2, #0]
	subs	r0, #1
	strh	r0, [r2, #0]
_080017580:
	cmp	r6, #128
	bne _08001758A
	ldrh	r0, [r2, #0]
	adds	r0, #1
	strh	r0, [r2, #0]
_08001758A:
	adds	r1, r2, #0
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #0
	bgt _080017598
	movs	r0, #1
	strh	r0, [r1, #0]
_080017598:
	movs	r3, #0
	ldrsh	r0, [r1, r3]
	cmp	r0, #3
	ble _0800175A4
	movs	r0, #3
	strh	r0, [r1, #0]
_0800175A4:
	ldrh	r2, [r2, #0]
	cmp	r7, r2
	beq _0800175B6
	adds	r0, r4, #0
	bl sub_080016944
	movs	r0, #2
	bl 0x0802B368
_0800175B6:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.type sub_0800175BC, %function
sub_0800175BC:
_0800175BC:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	adds	r4, r0, #0
	movs	r0, #0
	bl 0x08024BFC
	adds	r5, r0, #0
	movs	r0, #1
	bl 0x08024BFC
	adds	r6, r0, #0
	adds	r0, r4, #0
	adds	r0, #188
	ldrh	r0, [r0, #0]
	cmp	r0, #2
	bne _08001760E
	movs	r0, #0
	movs	r1, #5
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #2
	bne _08001760E
	movs	r0, #1
	movs	r1, #5
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #2
	bne _08001760E
	adds	r1, r4, #0
	adds	r1, #190
	movs	r0, #0
	strh	r0, [r1, #0]
	adds	r0, r4, #0
	bl sub_080017414
_08001760E:
	adds	r0, r4, #0
	adds	r0, #188
	movs	r1, #0
	ldrsh	r7, [r0, r1]
	cmp	r7, #1
	beq _08001761C
	b _08001773E
_08001761C:
	adds	r0, #2
	movs	r2, #0
	mov	r9, r2
	mov	r1, r9
	strh	r1, [r0, #0]
	movs	r2, #194
	adds	r2, r2, r4
	mov	r8, r2
	movs	r1, #0
	ldrsh	r0, [r2, r1]
	cmp	r0, #2
	beq _08001763A
	cmp	r0, #4
	beq _0800176AE
	b _08001773E
_08001763A:
	movs	r0, #1
	movs	r1, #4
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #2
	bne _08001773E
	adds	r0, r4, #0
	adds	r0, #182
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r0, #2
	beq _080017680
	cmp	r0, #2
	bgt _080017660
	cmp	r0, #1
	beq _080017666
	b _08001773E
_080017660:
	cmp	r0, #3
	beq _0800176A6
	b _08001773E
_080017666:
	adds	r0, r5, #0
	ldrh	r0, [r0, #0]
	cmp	r0, #1
	bne _08001769E
	movs	r0, #1
	bl sub_0800168B8
	movs	r1, #170
	lsls	r1, r1, #1
	adds	r0, r4, r1
	mov	r2, r9
	strh	r2, [r0, #0]
	b _080017696
_080017680:
	adds	r0, r6, #0
	ldrh	r0, [r0, #0]
	cmp	r0, #1
	bne _08001769E
	movs	r0, #1
	bl sub_0800168B8
	movs	r2, #170
	lsls	r2, r2, #1
	adds	r0, r4, r2
	strh	r7, [r0, #0]
_080017696:
	movs	r0, #3
	mov	r1, r8
	strh	r0, [r1, #0]
	b _08001773E
_08001769E:
	movs	r0, #10
	bl sub_0800168B8
	b _08001773E
_0800176A6:
	adds	r0, r4, #0
	bl sub_080017414
	b _08001773E
_0800176AE:
	movs	r0, #1
	movs	r1, #4
	bl 0x08002178
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #4
	bne _08001773E
	adds	r0, r4, #0
	adds	r0, #182
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r0, #2
	beq _0800176EC
	cmp	r0, #2
	bgt _0800176D4
	cmp	r0, #1
	beq _0800176DA
	b _08001773E
_0800176D4:
	cmp	r0, #3
	beq _080017738
	b _08001773E
_0800176DA:
	movs	r0, #1
	bl sub_0800168B8
	movs	r1, #171
	lsls	r1, r1, #1
	adds	r0, r4, r1
	mov	r2, r9
	strh	r2, [r0, #0]
	b _0800176FA
_0800176EC:
	movs	r0, #1
	bl sub_0800168B8
	movs	r2, #171
	lsls	r2, r2, #1
	adds	r0, r4, r2
	strh	r7, [r0, #0]
_0800176FA:
	ldr r0, _080017730
	ldr r1, _080017734
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _080017716
	movs	r0, #1
	movs	r1, #3
	bl 0x08002178
	movs	r2, #170
	lsls	r2, r2, #1
	adds	r1, r4, r2
	strh	r0, [r1, #0]
_080017716:
	movs	r0, #5
	mov	r1, r8
	strh	r0, [r1, #0]
	adds	r0, r4, #0
	adds	r0, #198
	mov	r2, r9
	strh	r2, [r0, #0]
	movs	r1, #172
	lsls	r1, r1, #1
	adds	r0, r4, r1
	strh	r7, [r0, #0]
	b _08001773E
	movs	r0, r0
_080017730: .4byte 0x03001780
_080017734: .4byte 0x000010C3
_080017738:
	adds	r0, r4, #0
	bl sub_080017414
_08001773E:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08001774C, %function
sub_08001774C:
_08001774C:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	movs	r0, #0
	movs	r1, #4
	bl 0x08002178
	adds	r4, r0, #0
	movs	r0, #1
	movs	r1, #4
	bl 0x08002178
	lsls	r4, r4, #16
	lsls	r0, r0, #16
	cmp	r4, r0
	bne _080017780
	adds	r0, r5, #0
	adds	r0, #188
	ldrh	r0, [r0, #0]
	subs	r0, #1
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #1
	bhi _080017780
	adds	r0, r5, #0
	bl sub_080017414
_080017780:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080017788, %function
sub_080017788:
_080017788:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	adds	r7, r0, #0
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	mov	r9, r1
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	mov	r8, r2
	ldr r0, _080017804
	ldr r1, _080017808
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne _08001780C
	adds	r5, r7, #0
	adds	r5, #194
	ldrh	r1, [r5, #0]
	movs	r0, #4
	bl 0x08002158
	adds	r0, r7, #0
	adds	r0, #190
	ldrh	r1, [r0, #0]
	movs	r0, #5
	bl 0x08002158
	adds	r4, r7, #0
	adds	r4, #184
	ldrh	r1, [r4, #0]
	movs	r0, #1
	bl 0x08002158
	movs	r2, #170
	lsls	r2, r2, #1
	adds	r0, r7, r2
	ldrh	r1, [r0, #0]
	movs	r0, #3
	bl 0x08002158
	movs	r3, #172
	lsls	r3, r3, #1
	adds	r0, r7, r3
	ldrh	r1, [r0, #0]
	movs	r0, #2
	bl 0x08002158
	movs	r1, #128
	lsls	r1, r1, #2
	adds	r0, r7, r1
	ldrh	r1, [r0, #0]
	movs	r0, #6
	bl 0x08002158
	adds	r6, r5, #0
	adds	r1, r4, #0
	subs	r5, #6
	subs	r4, #2
	b _08001785E
	movs	r0, r0
_080017804: .4byte 0x03001780
_080017808: .4byte 0x000010C3
_08001780C:
	adds	r6, r7, #0
	adds	r6, #194
	ldrh	r1, [r6, #0]
	movs	r0, #4
	bl 0x08002158
	adds	r5, r7, #0
	adds	r5, #188
	ldrh	r1, [r5, #0]
	movs	r0, #5
	bl 0x08002158
	adds	r4, r7, #0
	adds	r4, #182
	ldrh	r1, [r4, #0]
	movs	r0, #1
	bl 0x08002158
	movs	r2, #170
	lsls	r2, r2, #1
	adds	r0, r7, r2
	ldrh	r1, [r0, #0]
	movs	r0, #3
	bl 0x08002158
	movs	r3, #172
	lsls	r3, r3, #1
	adds	r0, r7, r3
	ldrh	r1, [r0, #0]
	movs	r0, #2
	bl 0x08002158
	movs	r1, #128
	lsls	r1, r1, #2
	adds	r0, r7, r1
	ldrh	r1, [r0, #0]
	movs	r0, #6
	bl 0x08002158
	adds	r1, r7, #0
	adds	r1, #184
_08001785E:
	mov	r2, r8
	cmp	r2, #1
	bne _08001786A
	adds	r0, r7, #0
	adds	r0, #190
	strh	r2, [r0, #0]
_08001786A:
	mov	r3, r8
	cmp	r3, #2
	bne _080017876
	adds	r0, r7, #0
	adds	r0, #190
	strh	r3, [r0, #0]
_080017876:
	mov	r0, r8
	cmp	r0, #64
	bne _080017882
	ldrh	r0, [r1, #0]
	subs	r0, #1
	strh	r0, [r1, #0]
_080017882:
	mov	r2, r8
	cmp	r2, #128
	bne _08001788E
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
_08001788E:
	adds	r2, r1, #0
	movs	r3, #0
	ldrsh	r0, [r2, r3]
	cmp	r0, #0
	bgt _08001789C
	movs	r0, #1
	strh	r0, [r2, #0]
_08001789C:
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r0, #3
	ble _0800178A8
	movs	r0, #3
	strh	r0, [r1, #0]
_0800178A8:
	ldr r0, _0800178C4
	ldr r3, _0800178C8
	adds	r0, r0, r3
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne _0800178CC
	movs	r0, #1
	movs	r1, #1
	bl 0x08002178
	strh	r0, [r4, #0]
	movs	r0, #1
	b _0800178D8
	movs	r0, r0
_0800178C4: .4byte 0x03001780
_0800178C8: .4byte 0x000010C3
_0800178CC:
	movs	r0, #0
	movs	r1, #1
	bl 0x08002178
	strh	r0, [r4, #0]
	movs	r0, #0
_0800178D8:
	movs	r1, #5
	bl 0x08002178
	strh	r0, [r5, #0]
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	adds	r5, r7, #0
	adds	r5, #186
	cmp	r0, #0
	bne _0800178F0
	ldrh	r0, [r5, #0]
	strh	r0, [r4, #0]
_0800178F0:
	movs	r2, #0
	ldrsh	r0, [r6, r2]
	cmp	r0, #2
	beq _0800178FC
	cmp	r0, #4
	bne _080017910
_0800178FC:
	ldrh	r3, [r5, #0]
	ldrh	r0, [r4, #0]
	cmp	r3, r0
	beq _080017910
	adds	r0, r7, #0
	bl sub_080016944
	movs	r0, #2
	bl sub_0800168B8
_080017910:
	ldrh	r0, [r4, #0]
	strh	r0, [r5, #0]
	movs	r1, #0
	ldrsh	r5, [r6, r1]
	cmp	r5, #2
	blt _08001793E
	cmp	r5, #4
	bgt _08001792C
	adds	r0, r7, #0
	mov	r1, r9
	mov	r2, r8
	bl sub_0800175BC
	b _08001793E
_08001792C:
	cmp	r5, #8
	bgt _08001793E
	cmp	r5, #6
	blt _08001793E
	adds	r0, r7, #0
	mov	r1, r9
	mov	r2, r8
	bl sub_08001774C
_08001793E:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08001794C, %function
sub_08001794C:
_08001794C:
	push	{r4, r5, lr}
	movs	r0, #0
	bl 0x08024BFC
	adds	r4, r0, #0
	movs	r0, #1
	bl 0x08024BFC
	adds	r5, r0, #0
	ldrh	r0, [r4, #0]
	cmp	r0, #0
	beq _08001796E
	ldr	r2, [r4, #4]
	movs	r0, #152
	movs	r1, #68
	bl 0x08003BC0
_08001796E:
	ldrh	r0, [r5, #0]
	cmp	r0, #0
	beq _08001797E
	ldr	r2, [r5, #4]
	movs	r0, #152
	movs	r1, #108
	bl 0x08003BC0
_08001797E:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_080017984, %function
sub_080017984:
_080017984:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	sub	sp, #20
	adds	r7, r0, #0
	movs	r0, #8
	adds	r0, r0, r7
	mov	r8, r0
	movs	r1, #228
	lsls	r1, r1, #1
	adds	r0, r7, r1
	ldr	r1, [r0, #0]
	movs	r2, #230
	lsls	r2, r2, #1
	adds	r0, r7, r2
	ldr	r2, [r0, #0]
	movs	r0, #48
	str	r0, [sp, #0]
	movs	r6, #5
	str	r6, [sp, #4]
	movs	r4, #1
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	movs	r5, #0
	str	r5, [sp, #16]
	mov	r0, r8
	movs	r3, #0
	bl sub_08007BFC
	movs	r1, #234
	lsls	r1, r1, #1
	adds	r0, r7, r1
	ldr	r1, [r0, #0]
	movs	r2, #236
	lsls	r2, r2, #1
	adds	r0, r7, r2
	ldr	r2, [r0, #0]
	movs	r0, #88
	str	r0, [sp, #0]
	str	r6, [sp, #4]
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	str	r5, [sp, #16]
	mov	r0, r8
	movs	r3, #0
	bl sub_08007BFC
	add	sp, #20
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800179F0, %function
sub_0800179F0:
_0800179F0:
	push	{lr}
	sub	sp, #16
	adds	r1, r0, #0
	adds	r0, #182
	ldrh	r0, [r0, #0]
	cmp	r0, #3
	bne _080017A18
	movs	r0, #6
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	str	r0, [sp, #8]
	movs	r0, #0
	str	r0, [sp, #12]
	adds	r0, r1, #0
	movs	r1, #4
	movs	r2, #104
	movs	r3, #128
	bl sub_08007B18
_080017A18:
	add	sp, #16
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080017A20, %function
sub_080017A20:
_080017A20:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	sub	sp, #20
	adds	r7, r0, #0
	movs	r0, #0
	bl 0x08024BFC
	adds	r4, r0, #0
	movs	r0, #1
	bl 0x08024BFC
	mov	r9, r0
	ldrh	r0, [r4, #0]
	cmp	r0, #0
	beq _080017A96
	adds	r0, r7, #0
	adds	r0, #16
	movs	r2, #192
	lsls	r2, r2, #1
	adds	r1, r7, r2
	ldr	r1, [r1, #0]
	movs	r3, #194
	lsls	r3, r3, #1
	adds	r2, r7, r3
	ldr	r2, [r2, #0]
	movs	r3, #72
	mov	r8, r3
	str	r3, [sp, #0]
	movs	r6, #4
	str	r6, [sp, #4]
	movs	r4, #1
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	movs	r5, #0
	str	r5, [sp, #16]
	movs	r3, #9
	bl sub_08007BFC
	adds	r0, r7, #0
	adds	r0, #24
	movs	r2, #204
	lsls	r2, r2, #1
	adds	r1, r7, r2
	ldr	r1, [r1, #0]
	movs	r3, #206
	lsls	r3, r3, #1
	adds	r2, r7, r3
	ldr	r2, [r2, #0]
	mov	r3, r8
	str	r3, [sp, #0]
	str	r6, [sp, #4]
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	str	r5, [sp, #16]
	movs	r3, #76
	bl sub_08007BFC
_080017A96:
	mov	r1, r9
	ldrh	r0, [r1, #0]
	cmp	r0, #0
	beq _080017AF2
	adds	r0, r7, #0
	adds	r0, #16
	movs	r2, #198
	lsls	r2, r2, #1
	adds	r1, r7, r2
	ldr	r1, [r1, #0]
	movs	r3, #200
	lsls	r3, r3, #1
	adds	r2, r7, r3
	ldr	r2, [r2, #0]
	movs	r3, #112
	mov	r8, r3
	str	r3, [sp, #0]
	movs	r6, #4
	str	r6, [sp, #4]
	movs	r4, #1
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	movs	r5, #0
	str	r5, [sp, #16]
	movs	r3, #9
	bl sub_08007BFC
	adds	r0, r7, #0
	adds	r0, #24
	movs	r2, #210
	lsls	r2, r2, #1
	adds	r1, r7, r2
	ldr	r1, [r1, #0]
	movs	r3, #212
	lsls	r3, r3, #1
	adds	r2, r7, r3
	ldr	r2, [r2, #0]
	mov	r3, r8
	str	r3, [sp, #0]
	str	r6, [sp, #4]
	str	r4, [sp, #8]
	str	r4, [sp, #12]
	str	r5, [sp, #16]
	movs	r3, #76
	bl sub_08007BFC
_080017AF2:
	add	sp, #20
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.type sub_080017B00, %function
sub_080017B00:
_080017B00:
	push	{r4, r5, r6, lr}
	sub	sp, #20
	adds	r5, r0, #0
	movs	r0, #0
	bl 0x08024BFC
	adds	r4, r0, #0
	movs	r0, #1
	bl 0x08024BFC
	adds	r6, r0, #0
	ldrh	r0, [r4, #0]
	cmp	r0, #0
	beq _080017B48
	adds	r0, r5, #0
	adds	r0, #32
	movs	r2, #216
	lsls	r2, r2, #1
	adds	r1, r5, r2
	ldr	r1, [r1, #0]
	movs	r3, #218
	lsls	r3, r3, #1
	adds	r2, r5, r3
	ldr	r2, [r2, #0]
	movs	r3, #60
	str	r3, [sp, #0]
	movs	r3, #7
	str	r3, [sp, #4]
	movs	r3, #1
	str	r3, [sp, #8]
	str	r3, [sp, #12]
	movs	r3, #0
	str	r3, [sp, #16]
	movs	r3, #16
	bl sub_08007BFC
_080017B48:
	ldrh	r0, [r6, #0]
	cmp	r0, #0
	beq _080017B7A
	adds	r0, r5, #0
	adds	r0, #32
	movs	r2, #222
	lsls	r2, r2, #1
	adds	r1, r5, r2
	ldr	r1, [r1, #0]
	movs	r3, #224
	lsls	r3, r3, #1
	adds	r2, r5, r3
	ldr	r2, [r2, #0]
	movs	r3, #100
	str	r3, [sp, #0]
	movs	r3, #7
	str	r3, [sp, #4]
	movs	r3, #1
	str	r3, [sp, #8]
	str	r3, [sp, #12]
	movs	r3, #0
	str	r3, [sp, #16]
	movs	r3, #16
	bl sub_08007BFC
_080017B7A:
	add	sp, #20
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080017B84, %function
sub_080017B84:
_080017B84:
	push	{lr}
	sub	sp, #20
	adds	r2, r0, #0
	adds	r0, #48
	movs	r3, #246
	lsls	r3, r3, #1
	adds	r1, r2, r3
	ldr	r1, [r1, #0]
	adds	r3, #4
	adds	r2, r2, r3
	ldr	r2, [r2, #0]
	movs	r3, #32
	str	r3, [sp, #0]
	movs	r3, #3
	str	r3, [sp, #4]
	movs	r3, #1
	str	r3, [sp, #8]
	str	r3, [sp, #12]
	movs	r3, #0
	str	r3, [sp, #16]
	bl sub_08007BFC
	add	sp, #20
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080017BB8, %function
sub_080017BB8:
_080017BB8:
	push	{r4, r5, lr}
	sub	sp, #20
	adds	r4, r0, #0
	adds	r0, #176
	movs	r1, #15
	bl sub_0800D97C
	adds	r0, r4, #0
	bl sub_08001794C
	adds	r0, r4, #0
	bl sub_080017984
	adds	r0, r4, #0
	bl sub_0800179F0
	adds	r0, r4, #0
	bl sub_080017A20
	adds	r0, r4, #0
	bl sub_080017B00
	adds	r0, r4, #0
	bl sub_080017B84
	adds	r0, r4, #0
	adds	r0, #192
	movs	r1, #0
	ldrsh	r5, [r0, r1]
	cmp	r5, #1
	bne _080017C1E
	subs	r0, #152
	movs	r2, #240
	lsls	r2, r2, #1
	adds	r1, r4, r2
	ldr	r1, [r1, #0]
	movs	r3, #242
	lsls	r3, r3, #1
	adds	r2, r4, r3
	ldr	r2, [r2, #0]
	movs	r3, #64
	str	r3, [sp, #0]
	movs	r3, #8
	str	r3, [sp, #4]
	str	r5, [sp, #8]
	movs	r3, #0
	str	r3, [sp, #12]
	str	r3, [sp, #16]
	movs	r3, #56
	bl sub_08007C68
_080017C1E:
	adds	r0, r4, #0
	adds	r0, #56
	bl sub_0800DBE8
	adds	r0, r4, #0
	bl sub_080017D50
	add	sp, #20
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_080017C34, %function
sub_080017C34:
_080017C34:
	push	{r4, lr}
	adds	r4, r0, #0
	adds	r0, #176
	movs	r1, #15
	bl sub_0800D97C
	adds	r0, r4, #0
	bl sub_08001794C
	adds	r0, r4, #0
	bl sub_080017984
	adds	r0, r4, #0
	bl sub_0800179F0
	adds	r0, r4, #0
	bl sub_080017A20
	adds	r0, r4, #0
	bl sub_080017B00
	adds	r0, r4, #0
	bl sub_080017B84
	adds	r0, r4, #0
	adds	r0, #56
	bl sub_0800DBE8
	adds	r0, r4, #0
	bl sub_080017D50
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_080017C78, %function
sub_080017C78:
_080017C78:
	push	{r4, r5, lr}
	sub	sp, #20
	adds	r4, r0, #0
	adds	r0, #176
	movs	r1, #15
	bl sub_0800D97C
	ldr r0, _080017D44
	ldr r1, _080017D48
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne _080017CCE
	adds	r5, r4, #0
	adds	r5, #194
	movs	r2, #0
	ldrsh	r0, [r5, r2]
	cmp	r0, #0
	beq _080017CCE
	adds	r0, r4, #0
	bl sub_08001794C
	adds	r0, r4, #0
	bl sub_080017984
	ldrh	r0, [r5, #0]
	subs	r0, #6
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	cmp	r0, #2
	bls _080017CBC
	adds	r0, r4, #0
	bl sub_0800179F0
_080017CBC:
	adds	r0, r4, #0
	bl sub_080017A20
	adds	r0, r4, #0
	bl sub_080017B00
	adds	r0, r4, #0
	bl sub_080017B84
_080017CCE:
	adds	r0, r4, #0
	adds	r0, #192
	movs	r3, #0
	ldrsh	r5, [r0, r3]
	cmp	r5, #1
	bne _080017D02
	subs	r0, #152
	movs	r2, #240
	lsls	r2, r2, #1
	adds	r1, r4, r2
	ldr	r1, [r1, #0]
	movs	r3, #242
	lsls	r3, r3, #1
	adds	r2, r4, r3
	ldr	r2, [r2, #0]
	movs	r3, #72
	str	r3, [sp, #0]
	movs	r3, #8
	str	r3, [sp, #4]
	str	r5, [sp, #8]
	movs	r3, #0
	str	r3, [sp, #12]
	str	r3, [sp, #16]
	movs	r3, #20
	bl sub_08007C68
_080017D02:
	adds	r0, r4, #0
	adds	r0, #198
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #4
	bgt _080017D2E
	cmp	r0, #3
	blt _080017D2E
	bl 0x080022CC
	movs	r1, #100
	muls	r0, r1
	cmp	r0, #0
	bge _080017D22
	ldr r2, _080017D4C
	adds	r0, r0, r2
_080017D22:
	asrs	r2, r0, #12
	subs	r2, r1, r2
	movs	r0, #128
	movs	r1, #96
	bl 0x08003978
_080017D2E:
	adds	r0, r4, #0
	adds	r0, #56
	bl sub_0800DBE8
	adds	r0, r4, #0
	bl sub_080017D50
	add	sp, #20
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_080017D44: .4byte 0x03001780
_080017D48: .4byte 0x000010C3
_080017D4C: .4byte 0x00000FFF
	.type sub_080017D50, %function
sub_080017D50:
_080017D50:
	bx	lr
	movs	r0, r0
	.type sub_080017D54, %function
sub_080017D54:
_080017D54:
	push	{r4, lr}
	adds	r4, r0, #0
	ldr r0, _080017D94
	ldr r1, _080017D98
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	cmp	r0, #3
	bne _080017DA6
	movs	r1, #254
	lsls	r1, r1, #1
	adds	r0, r4, r1
	ldr	r0, [r0, #0]
	cmp	r0, #1
	bne _080017DA6
	bl 0x08002140
	cmp	r0, #2
	beq _080017D9C
	movs	r0, #252
	lsls	r0, r0, #1
	adds	r1, r4, r0
	ldr	r0, [r1, #0]
	adds	r0, #1
	str	r0, [r1, #0]
	cmp	r0, #180
	ble _080017DA6
	movs	r0, #21
	movs	r1, #0
	movs	r2, #0
	bl 0x08004D4C
	b _080017DA6
_080017D94: .4byte 0x03001780
_080017D98: .4byte 0x00000FBC
_080017D9C:
	movs	r0, #252
	lsls	r0, r0, #1
	adds	r1, r4, r0
	movs	r0, #0
	str	r0, [r1, #0]
_080017DA6:
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_080017DAC, %function
sub_080017DAC:
_080017DAC:
	push	{r4, r5, r6, lr}
	adds	r5, r1, #0
	adds	r6, r2, #0
	adds	r4, r3, #0
	subs	r0, #1
	cmp	r0, #11
	bls _080017DBC
	b _080017EC4
_080017DBC:
	lsls	r0, r0, #2
	ldr r1, _080017DC8
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_080017DC8: .4byte 0x08017DCC
_080017DCC: .4byte 0x08017EB6
_080017DD0: .4byte 0x08017DFC
_080017DD4: .4byte 0x08017EC4
_080017DD8: .4byte 0x08017EC4
_080017DDC: .4byte 0x08017E06
_080017DE0: .4byte 0x08017E5E
_080017DE4: .4byte 0x08017E2A
_080017DE8: .4byte 0x08017EC4
_080017DEC: .4byte 0x08017EC4
_080017DF0: .4byte 0x08017EC4
_080017DF4: .4byte 0x08017EC4
_080017DF8: .4byte 0x08017EBE
_080017DFC:
	adds	r0, r4, #0
	adds	r1, r5, #0
	bl sub_0800168E8
	b _080017EC4
_080017E06:
	adds	r0, r4, #0
	adds	r0, #56
	bl sub_0800D854
	adds	r0, r4, #0
	adds	r0, #160
	bl sub_0800D8E4
	adds	r0, r4, #0
	bl sub_080016DE4
	adds	r0, r4, #0
	bl sub_080016F28
	adds	r0, r4, #0
	bl sub_080016DC0
	b _080017EC4
_080017E2A:
	adds	r0, r4, #0
	adds	r0, #180
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #1
	beq _080017E4E
	cmp	r0, #1
	bgt _080017E40
	cmp	r0, #0
	beq _080017E46
	b _080017EC4
_080017E40:
	cmp	r0, #3
	beq _080017E56
	b _080017EC4
_080017E46:
	adds	r0, r4, #0
	bl sub_080017BB8
	b _080017EC4
_080017E4E:
	adds	r0, r4, #0
	bl sub_080017C34
	b _080017EC4
_080017E56:
	adds	r0, r4, #0
	bl sub_080017C78
	b _080017EC4
_080017E5E:
	adds	r0, r4, #0
	bl sub_080017D54
	ldrh	r0, [r4, #60]
	cmp	r0, #0
	beq _080017EC4
	adds	r0, r4, #0
	adds	r0, #180
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #1
	beq _080017E96
	cmp	r0, #1
	bgt _080017E80
	cmp	r0, #0
	beq _080017E86
	b _080017EC4
_080017E80:
	cmp	r0, #3
	beq _080017EA6
	b _080017EC4
_080017E86:
	lsls	r1, r5, #16
	lsrs	r1, r1, #16
	lsls	r2, r6, #16
	lsrs	r2, r2, #16
	adds	r0, r4, #0
	bl sub_080017440
	b _080017EC4
_080017E96:
	lsls	r1, r5, #16
	lsrs	r1, r1, #16
	lsls	r2, r6, #16
	lsrs	r2, r2, #16
	adds	r0, r4, #0
	bl sub_080017528
	b _080017EC4
_080017EA6:
	lsls	r1, r5, #16
	lsrs	r1, r1, #16
	lsls	r2, r6, #16
	lsrs	r2, r2, #16
	adds	r0, r4, #0
	bl sub_080017788
	b _080017EC4
_080017EB6:
	adds	r0, r4, #0
	bl sub_080016FD0
	b _080017EC4
_080017EBE:
	adds	r0, r4, #0
	bl sub_080016940
_080017EC4:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080017ECC, %function
sub_080017ECC:
_080017ECC:
	push	{r4, lr}
	adds	r4, r1, #0
	bl 0x08004B68
	movs	r1, #2
	ldrsh	r0, [r0, r1]
	cmp	r0, #21
	beq _080017EE8
	cmp	r0, #21
	blt _080017EF0
	cmp	r0, #30
	bgt _080017EF0
	cmp	r0, #27
	blt _080017EF0
_080017EE8:
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #1
	b _080017EF6
_080017EF0:
	adds	r1, r4, #0
	adds	r1, #84
	movs	r0, #6
_080017EF6:
	strh	r0, [r1, #0]
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080017F00, %function
sub_080017F00:
_080017F00:
	bx	lr
	movs	r0, r0
	.type sub_080017F04, %function
sub_080017F04:
_080017F04:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #12
	adds	r7, r0, #0
	movs	r0, #65
	bl 0x0802B214
	ldr r4, _080018044
	movs	r0, #4
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	adds	r1, r4, #0
	movs	r2, #1
	movs	r3, #0
	bl sub_08007770
	movs	r0, #6
	str	r0, [r7, #80]
	movs	r0, #23
	str	r0, [r7, #92]
	movs	r0, #0
	str	r0, [r7, #104]
	adds	r0, r7, #0
	adds	r0, #8
	bl sub_0800DAB8
	adds	r0, r4, #0
	adds	r1, r7, #0
	bl sub_0800798C
	adds	r0, r7, #0
	bl sub_08007A58
	adds	r0, r4, #0
	movs	r1, #0
	movs	r2, #3
	bl sub_080075E8
	movs	r0, #3
	mov	sl, r0
	movs	r5, #0
	movs	r4, #0
	ldr r1, _080018048
	mov	r8, r1
	ldr r2, _08001804C
	add	r2, r8
	mov	r9, r2
_080017F6C:
	ldr r3, _080018050
	add	r3, r8
	movs	r6, #0
	ldrsh	r0, [r3, r6]
	mov	r2, r9
	movs	r6, #0
	ldrsh	r1, [r2, r6]
	adds	r2, r4, #0
	str	r3, [sp, #8]
	bl 0x08025CF4
	adds	r1, r0, #0
	subs	r0, r1, #1
	ldr	r3, [sp, #8]
	cmp	r0, #2
	bhi _080017F8E
	adds	r5, r1, #0
_080017F8E:
	cmp	r5, sl
	bgt _080017F94
	mov	sl, r5
_080017F94:
	adds	r4, #1
	cmp	r4, #2
	ble _080017F6C
	adds	r4, r7, #0
	adds	r4, #132
	movs	r0, #0
	mov	r8, r0
	mov	r1, sl
	strh	r1, [r4, #0]
	movs	r2, #0
	ldrsh	r0, [r3, r2]
	movs	r6, #4
	ldrsh	r1, [r3, r6]
	mov	r2, sl
	bl sub_08002714
	movs	r0, #64
	bl sub_08005758
	ldr r2, _080018054
	strh	r0, [r2, #2]
	mov	r0, r8
	strh	r0, [r2, #0]
	ldr r5, _080018058
	ldr r1, _08001805C
	movs	r3, #0
	ldrsh	r0, [r4, r3]
	subs	r0, #1
	lsls	r0, r0, #1
	adds	r0, r0, r1
	movs	r6, #0
	ldrsh	r1, [r0, r6]
	movs	r0, #2
	ldrsh	r2, [r2, r0]
	movs	r0, #64
	str	r0, [sp, #0]
	adds	r0, r5, #0
	movs	r3, #64
	bl sub_08007570
	ldr r1, _080018060
	movs	r2, #0
	ldrsh	r0, [r4, r2]
	subs	r0, #1
	lsls	r0, r0, #1
	adds	r0, r0, r1
	movs	r3, #0
	ldrsh	r1, [r0, r3]
	adds	r0, r5, #0
	movs	r2, #4
	bl sub_080075E8
	adds	r4, #4
	str	r4, [r7, #120]
	adds	r0, r7, #0
	adds	r0, #8
	str	r0, [r7, #124]
	mov	r6, r8
	str	r6, [r7, #8]
	movs	r0, #1
	strh	r0, [r7, #12]
	adds	r0, r7, #0
	adds	r0, #28
	movs	r2, #32
	negs	r2, r2
	movs	r1, #0
	bl sub_0800D77C
	adds	r0, r7, #0
	adds	r0, #20
	movs	r1, #0
	movs	r2, #160
	bl sub_0800D77C
	movs	r0, #6
	strh	r0, [r7, #16]
	movs	r0, #5
	strh	r0, [r7, #18]
	movs	r0, #2
	str	r0, [r4, #0]
	add	sp, #12
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080018044: .4byte 0x0832C31C
_080018048: .4byte 0x03001780
_08001804C: .4byte 0x00000FF8
_080018050: .4byte 0x00000FF4
_080018054: .4byte 0x0203F8E8
_080018058: .4byte 0x08306B54
_08001805C: .4byte 0x080CB8E0
_080018060: .4byte 0x080CB8E6
	.type sub_080018064, %function
sub_080018064:
_080018064:
	push	{r4, lr}
	adds	r4, r0, #0
	lsls	r2, r2, #16
	ldr r0, _080018094
	adds	r2, r2, r0
	lsrs	r2, r2, #16
	cmp	r2, #1
	bhi _08001808E
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r4, #0
	adds	r0, #136
	movs	r1, #1
	str	r1, [r0, #0]
	movs	r0, #0
	strh	r0, [r4, #12]
	adds	r0, r4, #0
	adds	r0, #116
	strh	r1, [r0, #0]
	str	r1, [r4, #36]
_08001808E:
	pop	{r4}
	pop	{r0}
	bx	r0
_080018094: .4byte 0xFFFF0000
	.type sub_080018098, %function
sub_080018098:
_080018098:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	sub	sp, #24
	adds	r6, r0, #0
	adds	r7, r1, #0
	adds	r1, r2, #0
	mov	r8, r3
	ldr r2, _080018118
	ldr	r0, [r2, #0]
	subs	r0, #1
	str	r0, [r2, #0]
	ldr r5, _08001811C
	cmp	r0, #0
	bgt _0800180C0
	ldrh	r0, [r5, #0]
	adds	r0, #1
	strh	r0, [r5, #0]
	movs	r0, #5
	str	r0, [r2, #0]
_0800180C0:
	adds	r2, r5, #0
	movs	r3, #0
	ldrsh	r0, [r2, r3]
	cmp	r0, #15
	ble _0800180CE
	movs	r0, #0
	strh	r0, [r2, #0]
_0800180CE:
	ldr r0, _080018120
	ldr r2, _080018124
	lsls	r1, r1, #1
	adds	r1, r1, r2
	movs	r4, #0
	ldrsh	r1, [r1, r4]
	movs	r3, #2
	ldrsh	r2, [r5, r3]
	movs	r4, #0
	ldrsh	r3, [r5, r4]
	lsls	r3, r3, #6
	movs	r4, #64
	str	r4, [sp, #0]
	bl sub_08007570
	movs	r0, #2
	ldrsh	r2, [r5, r0]
	movs	r1, #1
	str	r1, [sp, #0]
	movs	r0, #3
	str	r0, [sp, #4]
	str	r1, [sp, #8]
	movs	r0, #0
	str	r0, [sp, #12]
	str	r0, [sp, #16]
	str	r1, [sp, #20]
	adds	r0, r6, #0
	adds	r1, r7, #0
	mov	r3, r8
	bl 0x08002ED0
	add	sp, #24
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080018118: .4byte 0x03000590
_08001811C: .4byte 0x0203F8E8
_080018120: .4byte 0x08306B54
_080018124: .4byte 0x080CB8E0
	.type sub_080018128, %function
sub_080018128:
_080018128:
	push	{r4, lr}
	sub	sp, #16
	adds	r4, r0, #0
	adds	r0, #128
	movs	r1, #15
	bl sub_0800D97C
	movs	r0, #3
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	str	r0, [sp, #8]
	str	r0, [sp, #12]
	adds	r0, r4, #0
	movs	r1, #2
	movs	r2, #64
	movs	r3, #64
	bl sub_08007B18
	adds	r0, r4, #0
	adds	r0, #132
	movs	r1, #0
	ldrsh	r2, [r0, r1]
	subs	r2, #1
	movs	r0, #0
	movs	r1, #72
	movs	r3, #4
	bl sub_080018098
	adds	r4, #8
	adds	r0, r4, #0
	bl sub_0800DBE8
	add	sp, #16
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_080018174, %function
sub_080018174:
_080018174:
	push	{r4, r5, lr}
	adds	r5, r1, #0
	adds	r4, r3, #0
	subs	r0, #1
	cmp	r0, #11
	bhi _080018208
	lsls	r0, r0, #2
	ldr r1, _08001818C
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
_08001818C: .4byte 0x08018190
_080018190: .4byte 0x080181FA
_080018194: .4byte 0x080181C0
_080018198: .4byte 0x08018208
_08001819C: .4byte 0x08018208
_0800181A0: .4byte 0x080181CA
_0800181A4: .4byte 0x080181E4
_0800181A8: .4byte 0x080181DC
_0800181AC: .4byte 0x08018208
_0800181B0: .4byte 0x08018208
_0800181B4: .4byte 0x08018208
_0800181B8: .4byte 0x08018208
_0800181BC: .4byte 0x08018202
_0800181C0:
	adds	r0, r4, #0
	adds	r1, r5, #0
	bl sub_080017ECC
	b _080018208
_0800181CA:
	adds	r0, r4, #0
	adds	r0, #8
	bl sub_0800D854
	adds	r0, r4, #0
	adds	r0, #112
	bl sub_0800D8E4
	b _080018208
_0800181DC:
	adds	r0, r4, #0
	bl sub_080018128
	b _080018208
_0800181E4:
	ldrh	r0, [r4, #12]
	cmp	r0, #0
	beq _080018208
	lsls	r1, r5, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r4, #0
	bl sub_080018064
	b _080018208
_0800181FA:
	adds	r0, r4, #0
	bl sub_080017F04
	b _080018208
_080018202:
	adds	r0, r4, #0
	bl sub_080017F00
_080018208:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080018210, %function
sub_080018210:
_080018210:
	push	{r4, r5, lr}
	adds	r5, r0, #0
	adds	r4, r1, #0
	adds	r1, r2, #0
	adds	r0, r4, #0
	bl 0x08025C60
	ldr	r0, [r5, #4]
	ldr	r1, [r4, #24]
	ldr	r2, [r4, #20]
	bl sub_08007ABC
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080018230, %function
sub_080018230:
_080018230:
	push	{r4, r5, lr}
	sub	sp, #20
	ldr	r4, [r1, #20]
	ldr	r5, [r1, #24]
	ldr	r3, [r1, #4]
	ldr	r1, [r1, #8]
	adds	r2, r2, r1
	str	r2, [sp, #0]
	movs	r1, #3
	str	r1, [sp, #4]
	movs	r1, #1
	str	r1, [sp, #8]
	movs	r1, #0
	str	r1, [sp, #12]
	str	r1, [sp, #16]
	adds	r1, r4, #0
	adds	r2, r5, #0
	bl sub_08007C68
	add	sp, #20
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080018260, %function
sub_080018260:
_080018260:
	push	{lr}
	adds	r0, r1, #0
	adds	r2, r0, #0
	adds	r2, #89
	movs	r1, #1
	strb	r1, [r2, #0]
	movs	r2, #1
	bl 0x080056F4
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080018278, %function
sub_080018278:
_080018278:
	push	{r4, r5, lr}
	sub	sp, #8
	adds	r4, r0, #0
	ldr r1, _0800182D0
	movs	r0, #0
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	movs	r2, #0
	movs	r3, #0
	bl sub_08007770
	ldr r5, _0800182D4
	adds	r0, r5, #0
	adds	r1, r4, #0
	bl sub_0800798C
	adds	r0, r5, #0
	movs	r1, #0
	movs	r2, #3
	bl sub_080075E8
	adds	r0, r4, #0
	adds	r0, #44
	movs	r1, #19
	bl 0x08025BC8
	ldr	r0, [r4, #4]
	ldr	r1, [r4, #48]
	ldr	r2, [r4, #44]
	bl sub_08007ABC
	adds	r1, r4, #0
	adds	r1, #24
	adds	r0, r4, #0
	movs	r2, #19
	bl sub_080018210
	add	sp, #8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800182D0: .4byte 0x0832EBF0
_0800182D4: .4byte 0x082B7410
	.type sub_0800182D8, %function
sub_0800182D8:
_0800182D8:
	push	{lr}
	lsls	r2, r2, #16
	ldr r0, _0800182F8
	adds	r2, r2, r0
	lsrs	r2, r2, #16
	cmp	r2, #1
	bhi _0800182F2
	movs	r0, #1
	bl 0x0802B368
	movs	r0, #1
	bl 0x08004EA8
_0800182F2:
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800182F8: .4byte 0xFFFF0000
_0800182FC:
	.hword 0x4770
	movs	r0, r0
	.type sub_080018300, %function
sub_080018300:
_080018300:
	push	{lr}
	cmp	r0, #2
	beq _08001831A
	cmp	r0, #2
	bhi _080018310
	cmp	r0, #1
	beq _080018322
	b _080018340
_080018310:
	cmp	r0, #6
	beq _08001832A
	cmp	r0, #7
	beq _08001833A
	b _080018340
_08001831A:
	adds	r0, r3, #0
	bl sub_080018260
	b _080018340
_080018322:
	adds	r0, r3, #0
	bl sub_080018278
	b _080018340
_08001832A:
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r3, #0
	bl sub_0800182D8
	b _080018340
_08001833A:
	adds	r0, r3, #0
	bl _0800182FC
_080018340:
	pop	{r0}
	bx	r0
	.type sub_080018344, %function
sub_080018344:
_080018344:
	push	{r4, lr}
	adds	r4, r0, #0
	ldr r1, _080018360
	movs	r0, #0
	movs	r2, #9
	bl sub_08007664
	movs	r0, #150
	str	r0, [r4, #0]
	movs	r0, #0
	str	r0, [r4, #4]
	pop	{r4}
	pop	{r0}
	bx	r0
_080018360: .4byte 0x08292B40
	.type sub_080018364, %function
sub_080018364:
_080018364:
	push	{lr}
	adds	r1, r0, #0
	ldr	r0, [r1, #0]
	cmp	r0, #0
	ble _080018374
	subs	r0, #1
	str	r0, [r1, #0]
	b _080018382
_080018374:
	ldr	r0, [r1, #4]
	cmp	r0, #0
	bne _080018382
	movs	r0, #1
	str	r0, [r1, #4]
	bl 0x08004EC0
_080018382:
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080018388, %function
sub_080018388:
_080018388:
	bx	lr
	movs	r0, r0
_08001838C:
	adds	r1, #84
	movs	r0, #1
	strh	r0, [r1, #0]
	bx	lr
	.type sub_080018394, %function
sub_080018394:
_080018394:
	push	{lr}
	cmp	r0, #2
	beq _0800183AE
	cmp	r0, #2
	bhi _0800183A4
	cmp	r0, #1
	beq _0800183B6
	b _0800183D4
_0800183A4:
	cmp	r0, #5
	beq _0800183BE
	cmp	r0, #6
	beq _0800183C6
	b _0800183D4
_0800183AE:
	adds	r0, r3, #0
	bl _08001838C
	b _0800183D4
_0800183B6:
	adds	r0, r3, #0
	bl sub_080018344
	b _0800183D4
_0800183BE:
	adds	r0, r3, #0
	bl sub_080018364
	b _0800183D4
_0800183C6:
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r3, #0
	bl sub_080018388
_0800183D4:
	pop	{r0}
	bx	r0
	.type sub_0800183D8, %function
sub_0800183D8:
_0800183D8:
	push	{r4, r5, lr}
	adds	r4, r0, #0
	movs	r0, #0
	strh	r0, [r4, #8]
	movs	r0, #48
	bl 0x0802B214
	ldr r5, _080018414
	movs	r0, #0
	adds	r1, r5, #0
	movs	r2, #2
	bl sub_08007664
	adds	r4, #28
	adds	r0, r5, #0
	adds	r1, r4, #0
	bl sub_0800798C
	adds	r0, r4, #0
	bl sub_08007A58
	adds	r0, r5, #0
	movs	r1, #1
	movs	r2, #0
	bl sub_080075E8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080018414: .4byte 0x08292B40
	.type sub_080018418, %function
sub_080018418:
_080018418:
	bx	lr
	movs	r0, r0
	.type sub_08001841C, %function
sub_08001841C:
_08001841C:
	bx	lr
	movs	r0, r0
	.type sub_080018420, %function
sub_080018420:
_080018420:
	push	{r4, lr}
	adds	r4, r0, #0
	bl 0x08004B68
	adds	r1, r4, #0
	bl sub_08001841C
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_080018434, %function
sub_080018434:
_080018434:
	push	{r4, lr}
	movs	r4, #1
_080018438:
	cmp	r4, #54
	beq _08001844E
	cmp	r4, #94
	beq _08001844E
	cmp	r4, #95
	beq _08001844E
	cmp	r4, #96
	beq _08001844E
	adds	r0, r4, #0
	bl 0x08025F78
_08001844E:
	adds	r4, #1
	cmp	r4, #98
	ble _080018438
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08001845C, %function
sub_08001845C:
_08001845C:
	push	{r4, r5, r6, r7, lr}
	movs	r7, #1
	movs	r5, #0
_080018462:
	movs	r4, #0
	adds	r6, r5, #1
_080018466:
	movs	r0, #0
	adds	r1, r5, #0
	adds	r2, r4, #0
	adds	r3, r7, #0
	bl 0x08025C84
	adds	r4, #1
	cmp	r4, #10
	ble _080018466
	adds	r5, r6, #0
	cmp	r5, #3
	ble _080018462
	movs	r0, #0
	bl 0x08025FF0
	movs	r0, #1
	bl 0x08025FF0
	movs	r0, #2
	bl 0x08025FF0
	movs	r4, #0
_080018492:
	adds	r0, r4, #0
	adds	r1, r7, #0
	bl 0x08025DBC
	adds	r4, #1
	cmp	r4, #31
	ble _080018492
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800184A8, %function
sub_0800184A8:
_0800184A8:
	push	{lr}
	movs	r0, #0
	movs	r1, #3
	bl 0x08025EC0
	movs	r0, #1
	movs	r1, #3
	bl 0x08025EC0
	movs	r0, #2
	movs	r1, #3
	bl 0x08025EC0
	movs	r0, #3
	movs	r1, #1
	bl 0x08025EC0
	movs	r0, #4
	movs	r1, #1
	bl 0x08025EC0
	movs	r0, #5
	movs	r1, #1
	bl 0x08025EC0
	movs	r0, #6
	movs	r1, #1
	bl 0x08025EC0
	movs	r0, #7
	movs	r1, #1
	bl 0x08025EC0
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800184F0, %function
sub_0800184F0:
_0800184F0:
	push	{lr}
	movs	r0, #0
	bl 0x08026020
	movs	r0, #1
	bl 0x08026020
	movs	r0, #2
	bl 0x08026020
	pop	{r0}
	bx	r0
	.type sub_080018508, %function
sub_080018508:
_080018508:
	push	{r4, r5, r6, lr}
	movs	r5, #0
_08001850C:
	movs	r4, #0
	adds	r6, r5, #1
_080018510:
	movs	r0, #0
	adds	r1, r5, #0
	adds	r2, r4, #0
	movs	r3, #3
	bl 0x08025C84
	adds	r4, #1
	cmp	r4, #10
	ble _080018510
	adds	r5, r6, #0
	cmp	r5, #3
	ble _08001850C
	ldr r0, _08001853C
	movs	r1, #255
	lsls	r1, r1, #4
	adds	r0, r0, r1
	movs	r1, #1
	strh	r1, [r0, #0]
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08001853C: .4byte 0x03001780
	.type sub_080018540, %function
sub_080018540:
_080018540:
	push	{r4, r5, r6, lr}
	adds	r6, r0, #0
	lsls	r1, r1, #16
	lsrs	r4, r1, #16
	lsls	r2, r2, #16
	lsrs	r5, r2, #16
	bl 0x08004B68
	ldr r0, _08001859C
	ands	r4, r0
	cmp	r5, #0
	beq _08001855C
	movs	r0, #0
	strh	r0, [r6, #16]
_08001855C:
	ldrh	r0, [r6, #16]
	adds	r0, #1
	strh	r0, [r6, #16]
	lsls	r0, r0, #16
	movs	r1, #150
	lsls	r1, r1, #19
	cmp	r0, r1
	ble _080018578
	movs	r0, #1
	bl 0x08004BFC
	movs	r0, #1
	bl 0x08004EC0
_080018578:
	ldr r0, _0800185A0
	cmp	r4, r0
	bne _0800185A4
	movs	r0, #32
	ands	r0, r5
	cmp	r0, #0
	beq _0800185A4
	movs	r0, #1
	bl 0x0800274C
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r6, #0
	bl sub_080018434
	b _0800186A2
	movs	r0, r0
_08001859C: .4byte 0x000003FF
_0800185A0: .4byte 0x00000222
_0800185A4:
	ldr r0, _0800185CC
	cmp	r4, r0
	bne _0800185D0
	movs	r0, #16
	ands	r0, r5
	cmp	r0, #0
	beq _0800185D0
	movs	r0, #1
	bl 0x0800274C
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r6, #0
	bl sub_08001845C
	bl 0x080241C8
	b _0800186A2
	movs	r0, r0
_0800185CC: .4byte 0x00000212
_0800185D0:
	ldr r0, _0800185F4
	cmp	r4, r0
	bne _0800185F8
	movs	r0, #64
	ands	r0, r5
	cmp	r0, #0
	beq _0800185F8
	movs	r0, #1
	bl 0x0800274C
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r6, #0
	bl sub_0800184A8
	b _0800186A2
	movs	r0, r0
_0800185F4: .4byte 0x00000242
_0800185F8:
	ldr r0, _08001861C
	cmp	r4, r0
	bne _080018620
	movs	r0, #128
	ands	r0, r5
	cmp	r0, #0
	beq _080018620
	movs	r0, #1
	bl 0x0800274C
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r6, #0
	bl sub_0800184F0
	b _0800186A2
	movs	r0, r0
_08001861C: .4byte 0x00000282
_080018620:
	movs	r0, #145
	lsls	r0, r0, #2
	cmp	r4, r0
	bne _080018648
	movs	r0, #4
	ands	r0, r5
	cmp	r0, #0
	beq _080018648
	movs	r0, #1
	bl 0x0800274C
	movs	r0, #1
	bl 0x0802B368
	adds	r0, r6, #0
	bl sub_080018508
	bl 0x080241C8
	b _0800186A2
_080018648:
	movs	r0, #161
	lsls	r0, r0, #2
	cmp	r4, r0
	bne _080018688
	movs	r0, #4
	ands	r0, r5
	cmp	r0, #0
	beq _080018688
	movs	r0, #1
	bl 0x0800274C
	movs	r0, #1
	bl 0x0802B368
	ldr r0, _080018680
	ldr r1, _080018684
	adds	r0, r0, r1
	movs	r1, #1
	strh	r1, [r0, #0]
	bl sub_0800B0BC
	movs	r0, #0
	bl 0x08004BFC
	movs	r0, #1
	bl 0x08004EC0
	b _0800186A2
_080018680: .4byte 0x03001780
_080018684: .4byte 0x00001086
_080018688:
	movs	r0, #8
	ands	r0, r5
	cmp	r0, #0
	beq _0800186A2
	movs	r0, #1
	bl 0x0802B368
	movs	r0, #0
	bl 0x08004BFC
	movs	r0, #1
	bl 0x08004EC0
_0800186A2:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	.type sub_0800186A8, %function
sub_0800186A8:
_0800186A8:
	push	{r4, lr}
	sub	sp, #16
	adds	r4, r0, #0
	ldr r0, _0800186E8
	ldr r1, _0800186EC
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	movs	r1, #48
	bl 0x0802D97C
	movs	r1, #24
	bl 0x0802D978
	cmp	r0, #0
	beq _0800186DE
	adds	r0, r4, #0
	adds	r0, #28
	movs	r1, #0
	str	r1, [sp, #0]
	str	r1, [sp, #4]
	str	r1, [sp, #8]
	str	r1, [sp, #12]
	movs	r1, #13
	movs	r2, #88
	movs	r3, #112
	bl sub_08007B18
_0800186DE:
	add	sp, #16
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800186E8: .4byte 0x03001780
_0800186EC: .4byte 0x000010D8
	.type sub_0800186F0, %function
sub_0800186F0:
_0800186F0:
	push	{r4, lr}
	adds	r4, r1, #0
	subs	r0, #1
	cmp	r0, #11
	bhi _080018766
	lsls	r0, r0, #2
	ldr r1, _080018704
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
_080018704: .4byte 0x08018708
_080018708: .4byte 0x08018738
_08001870C: .4byte 0x08018766
_080018710: .4byte 0x08018766
_080018714: .4byte 0x08018766
_080018718: .4byte 0x08018740
_08001871C: .4byte 0x08018750
_080018720: .4byte 0x08018748
_080018724: .4byte 0x08018766
_080018728: .4byte 0x08018766
_08001872C: .4byte 0x08018766
_080018730: .4byte 0x08018766
_080018734: .4byte 0x08018760
_080018738:
	adds	r0, r3, #0
	bl sub_0800183D8
	b _080018766
_080018740:
	adds	r0, r3, #0
	bl sub_080018420
	b _080018766
_080018748:
	adds	r0, r3, #0
	bl sub_0800186A8
	b _080018766
_080018750:
	lsls	r1, r4, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r3, #0
	bl sub_080018540
	b _080018766
_080018760:
	adds	r0, r3, #0
	bl sub_080018418
_080018766:
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_08001876C, %function
sub_08001876C:
_08001876C:
	push	{r4, lr}
	adds	r4, r0, #0
	ldr r1, _080018788
	movs	r0, #0
	movs	r2, #7
	bl sub_08007664
	movs	r0, #150
	str	r0, [r4, #0]
	movs	r0, #0
	str	r0, [r4, #4]
	pop	{r4}
	pop	{r0}
	bx	r0
_080018788: .4byte 0x08292B40
	.type sub_08001878C, %function
sub_08001878C:
_08001878C:
	push	{lr}
	adds	r1, r0, #0
	ldr	r0, [r1, #0]
	cmp	r0, #0
	ble _08001879C
	subs	r0, #1
	str	r0, [r1, #0]
	b _0800187AA
_08001879C:
	ldr	r0, [r1, #4]
	cmp	r0, #0
	bne _0800187AA
	movs	r0, #1
	str	r0, [r1, #4]
	bl 0x08004EC0
_0800187AA:
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800187B0, %function
sub_0800187B0:
_0800187B0:
	bx	lr
	movs	r0, r0
_0800187B4:
	ldr r0, _0800187CC
	movs	r3, #134
	lsls	r3, r3, #5
	adds	r2, r0, r3
	ldrb	r0, [r2, #0]
	cmp	r0, #0
	beq _0800187D0
	movs	r0, #0
	strb	r0, [r2, #0]
	adds	r1, #84
	movs	r0, #1
	b _0800187D4
_0800187CC: .4byte 0x03001780
_0800187D0:
	adds	r1, #84
	movs	r0, #2
_0800187D4:
	strh	r0, [r1, #0]
	bx	lr
	.type sub_0800187D8, %function
sub_0800187D8:
_0800187D8:
	push	{lr}
	cmp	r0, #2
	beq _0800187F2
	cmp	r0, #2
	bhi _0800187E8
	cmp	r0, #1
	beq _0800187FA
	b _080018818
_0800187E8:
	cmp	r0, #5
	beq _080018802
	cmp	r0, #6
	beq _08001880A
	b _080018818
_0800187F2:
	adds	r0, r3, #0
	bl _0800187B4
	b _080018818
_0800187FA:
	adds	r0, r3, #0
	bl sub_08001876C
	b _080018818
_080018802:
	adds	r0, r3, #0
	bl sub_08001878C
	b _080018818
_08001880A:
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r3, #0
	bl sub_0800187B0
_080018818:
	pop	{r0}
	bx	r0
	.type sub_08001881C, %function
sub_08001881C:
_08001881C:
	push	{r4, lr}
	adds	r4, r0, #0
	ldr r1, _080018838
	movs	r0, #0
	movs	r2, #10
	bl sub_08007664
	movs	r0, #150
	str	r0, [r4, #0]
	movs	r0, #0
	str	r0, [r4, #4]
	pop	{r4}
	pop	{r0}
	bx	r0
_080018838: .4byte 0x08292B40
	.type sub_08001883C, %function
sub_08001883C:
_08001883C:
	push	{lr}
	adds	r1, r0, #0
	ldr	r0, [r1, #0]
	cmp	r0, #0
	ble _08001884C
	subs	r0, #1
	str	r0, [r1, #0]
	b _08001885A
_08001884C:
	ldr	r0, [r1, #4]
	cmp	r0, #0
	bne _08001885A
	movs	r0, #1
	str	r0, [r1, #4]
	bl 0x08004EC0
_08001885A:
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080018860, %function
sub_080018860:
_080018860:
	bx	lr
	movs	r0, r0
_080018864:
	adds	r1, #84
	movs	r0, #1
	strh	r0, [r1, #0]
	bx	lr
	.type sub_08001886C, %function
sub_08001886C:
_08001886C:
	push	{lr}
	cmp	r0, #2
	beq _080018886
	cmp	r0, #2
	bhi _08001887C
	cmp	r0, #1
	beq _08001888E
	b _0800188AC
_08001887C:
	cmp	r0, #5
	beq _080018896
	cmp	r0, #6
	beq _08001889E
	b _0800188AC
_080018886:
	adds	r0, r3, #0
	bl _080018864
	b _0800188AC
_08001888E:
	adds	r0, r3, #0
	bl sub_08001881C
	b _0800188AC
_080018896:
	adds	r0, r3, #0
	bl sub_08001883C
	b _0800188AC
_08001889E:
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	adds	r0, r3, #0
	bl sub_080018860
_0800188AC:
	pop	{r0}
	bx	r0
	.type sub_0800188B0, %function
sub_0800188B0:
_0800188B0:
	push	{r4, r5, lr}
	sub	sp, #32
	adds	r5, r0, #0
	movs	r0, #0
	ldrsh	r1, [r5, r0]
	movs	r0, #1
	negs	r0, r0
	cmp	r1, r0
	bne _080018908
	ldr r1, _0800188DC
	mov	r0, sp
	movs	r2, #30
	bl 0x0802E0A4
	movs	r1, #2
	ldrsh	r0, [r5, r1]
	cmp	r0, #14
	ble _0800188E0
	mov	r0, sp
	ldrh	r0, [r0, #28]
	b _0800188EA
	movs	r0, r0
_0800188DC: .4byte 0x0805FB66
_0800188E0:
	movs	r2, #2
	ldrsh	r0, [r5, r2]
	lsls	r0, r0, #1
	add	r0, sp
	ldrh	r0, [r0, #0]
_0800188EA:
	strh	r0, [r5, #0]
	ldr r0, _0800188FC
	str	r0, [r5, #12]
	ldr r0, _080018900
	ldr r1, _080018904
	adds	r0, r0, r1
	movs	r1, #1
	strb	r1, [r0, #0]
	b _08001891A
_0800188FC: .4byte 0x00002328
_080018900: .4byte 0x03001780
_080018904: .4byte 0x000010C1
_080018908:
	ldr r1, _080018928
	ldr r0, _08001892C
	adds	r2, r1, r0
	movs	r0, #0
	strb	r0, [r2, #0]
	ldrh	r0, [r5, #6]
	ldr r2, _080018930
	adds	r1, r1, r2
	strh	r0, [r1, #0]
_08001891A:
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	cmp	r0, #4
	bne _080018934
	movs	r2, #24
	ldrsh	r0, [r5, r2]
	b _080018A0E
_080018928: .4byte 0x03001780
_08001892C: .4byte 0x000010C1
_080018930: .4byte 0x000010C6
_080018934:
	cmp	r0, #0
	bne _08001893E
	strh	r0, [r5, #2]
	strh	r0, [r5, #8]
	b _080018A14
_08001893E:
	cmp	r0, #9
	bne _0800189D8
	bl sub_08008014
	bl 0x08005B5C
	movs	r1, #31
	ands	r0, r1
	adds	r0, #16
	strh	r0, [r5, #2]
	movs	r1, #2
	ldrsh	r0, [r5, r1]
	bl 0x080258B8
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #1
	bne _080018966
	movs	r0, #2
	strh	r0, [r5, #8]
_080018966:
	movs	r4, #1
	negs	r4, r4
_08001896A:
	bl sub_08008014
	bl 0x08005B5C
	movs	r1, #98
	bl 0x0802D97C
	strh	r0, [r5, #24]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #86
	beq _08001896A
	cmp	r0, #56
	beq _08001896A
	cmp	r0, #55
	beq _08001896A
	cmp	r0, #31
	beq _08001896A
	cmp	r0, #14
	beq _08001896A
	cmp	r0, #98
	beq _08001896A
	cmp	r0, #54
	beq _08001896A
	cmp	r0, #94
	beq _08001896A
	cmp	r0, #95
	beq _08001896A
	cmp	r0, #96
	beq _08001896A
	movs	r2, #24
	ldrsh	r0, [r5, r2]
	bl 0x080022E4
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, r4
	beq _08001896A
	bl sub_08008014
	bl 0x08005B5C
	adds	r4, r0, #0
	movs	r1, #24
	ldrsh	r0, [r5, r1]
	bl 0x080254E8
	adds	r1, r0, #0
	lsls	r1, r1, #24
	asrs	r1, r1, #24
	adds	r0, r4, #0
	bl 0x0802D97C
	strb	r0, [r5, #29]
	b _080018A14
_0800189D8:
	cmp	r0, #10
	bne _0800189F8
	ldr r0, _0800189F0
	ldr r2, _0800189F4
	adds	r0, r0, r2
	movs	r1, #0
	strb	r1, [r0, #0]
	strh	r1, [r5, #8]
	movs	r0, #48
	strh	r0, [r5, #2]
	strh	r1, [r5, #26]
	b _080018A14
_0800189F0: .4byte 0x03001780
_0800189F4: .4byte 0x000010C1
_0800189F8:
	cmp	r0, #6
	bne _080018A02
	movs	r0, #3
	strh	r0, [r5, #0]
	b _080018A14
_080018A02:
	cmp	r0, #7
	bne _080018A14
	movs	r0, #4
	strh	r0, [r5, #0]
	movs	r1, #24
	ldrsh	r0, [r5, r1]
_080018A0E:
	bl 0x08024E7C
	strh	r0, [r5, #4]
_080018A14:
	movs	r2, #24
	ldrsh	r0, [r5, r2]
	bl 0x080022E4
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	movs	r1, #1
	negs	r1, r1
	cmp	r0, r1
	bne _080018A30
	movs	r1, #0
	movs	r0, #10
	strh	r0, [r5, #24]
	strb	r1, [r5, #29]
_080018A30:
	ldr r0, _080018A48
	ldr r1, _080018A4C
	adds	r0, r0, r1
	adds	r1, r5, #0
	movs	r2, #56
	bl 0x0802E0A4
	add	sp, #32
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080018A48: .4byte 0x03001780
_080018A4C: .4byte 0x000010FC
