@ GT Advance 3 - main-loop runtime region 0x2AAC-0x4A2C
@ Region: file offset 0x002AAC-0x004A2C (VMA 0x08002AAC-0x08004A2C).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

	.type sub_08002AAC, %function
sub_08002AAC:
	ldr r3, _08002ADC
	movs	r0, #5
	strh	r0, [r3, #0]
	ldr r0, _08002AE0
	ldrb	r0, [r0, #0]
	cmp	r0, #150
	bne _08002AD2
	ldr r0, _08002AE4
	ldr r1, _08002AE8
	ldr	r2, [r0, #0]
	ldr	r0, [r1, #0]
	cmp	r2, r0
	bne _08002AD2
	ldrh	r0, [r3, #0]
	movs	r2, #128
	lsls	r2, r2, #6
	adds	r1, r2, #0
	orrs	r0, r1
	strh	r0, [r3, #0]
_08002AD2:
	ldr r1, _08002AEC
	ldr r2, _08002AF0
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	bx	lr
_08002ADC: .4byte 0x04000200
_08002AE0: .4byte 0x080000B2
_08002AE4: .4byte 0x080000AC
_08002AE8: .4byte 0x0802E1FC
_08002AEC: .4byte 0x04000004
_08002AF0: .4byte 0x00003828
	.type sub_08002AF4, %function
sub_08002AF4:
	lsls	r0, r0, #2
	ldr r1, _08002AFC
	adds	r0, r0, r1
	bx	lr
_08002AFC: .4byte 0x0203F170
_08002B00:
	ldr r2, _08002B10
	str	r0, [r2, #0]
	ldr r2, _08002B14
	str	r1, [r2, #0]
	ldr r1, _08002B18
	str	r0, [r1, #0]
	bx	lr
	movs	r0, r0
_08002B10: .4byte 0x03000134
_08002B14: .4byte 0x0300013C
_08002B18: .4byte 0x03000138
_08002B1C:
	ldr r2, _08002B28
	str	r0, [r2, #0]
	ldr r0, _08002B2C
	str	r1, [r0, #0]
	bx	lr
	movs	r0, r0
_08002B28: .4byte 0x03000140
_08002B2C: .4byte 0x03000144
_08002B30:
	ldr r2, _08002B3C
	str	r0, [r2, #0]
	ldr r0, _08002B40
	str	r1, [r0, #0]
	bx	lr
	movs	r0, r0
_08002B3C: .4byte 0x03000148
_08002B40: .4byte 0x0300014C
	.type sub_08002B44, %function
sub_08002B44:
	ldr r1, _08002B4C
	movs	r0, #0
	strh	r0, [r1, #0]
	bx	lr
_08002B4C: .4byte 0x03000158
	.type sub_08002B50, %function
sub_08002B50:
	push	{r4, r5, lr}
	sub	sp, #8
	movs	r4, #0
	str	r4, [sp, #0]
	ldr r0, _08002B9C
	ldr	r1, [r0, #0]
	ldr r0, _08002BA0
	ldr	r2, [r0, #0]
	ldr r0, _08002BA4
	ands	r2, r0
	movs	r0, #160
	lsls	r0, r0, #19
	orrs	r2, r0
	mov	r0, sp
	bl 0x0802D974
	str	r4, [sp, #4]
	add	r0, sp, #4
	ldr r4, _08002BA8
	ldr	r1, [r4, #0]
	ldr r2, _08002BAC
	bl 0x0802D974
	movs	r2, #0
	ldr r5, _08002BB0
	movs	r3, #160
_08002B84:
	ldr	r1, [r4, #0]
	lsls	r0, r2, #1
	adds	r0, r0, r1
	strh	r3, [r0, #0]
	adds	r2, #4
	cmp	r2, r5
	ble _08002B84
	add	sp, #8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08002B9C: .4byte 0x03000140
_08002BA0: .4byte 0x03000144
_08002BA4: .4byte 0x001FFFFF
_08002BA8: .4byte 0x03000134
_08002BAC: .4byte 0x05000100
_08002BB0: .4byte 0x000001FF
	.type sub_08002BB4, %function
sub_08002BB4:
	ldr r1, _08002BC8
	ldr r0, _08002BCC
	ldr	r0, [r0, #0]
	str	r0, [r1, #0]
	ldr r1, _08002BD0
	ldr r0, _08002BD4
	ldr	r0, [r0, #0]
	str	r0, [r1, #0]
	bx	lr
	movs	r0, r0
_08002BC8: .4byte 0x03000154
_08002BCC: .4byte 0x03000148
_08002BD0: .4byte 0x03000150
_08002BD4: .4byte 0x0300014C
	.type sub_08002BD8, %function
sub_08002BD8:
	ldr r0, _08002BE4
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	movs	r0, #32
	subs	r0, r0, r1
	bx	lr
_08002BE4: .4byte 0x03000158
_08002BE8:
	ldr r1, _08002BF8
	ldrh	r0, [r1, #0]
	adds	r2, r0, #1
	strh	r2, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	bx	lr
	movs	r0, r0
_08002BF8: .4byte 0x03000158
	.type sub_08002BFC, %function
sub_08002BFC:
_08002BFC:
	push	{r4, lr}
	ldr r2, _08002C18
	ldr	r4, [r2, #0]
	ldr r1, _08002C1C
	ldr	r0, [r1, #0]
	cmp	r0, #0
	ble _08002C20
	subs	r0, #1
	str	r0, [r1, #0]
	adds	r0, r4, #0
	adds	r0, #16
	str	r0, [r2, #0]
	b _08002C28
	movs	r0, r0
_08002C18: .4byte 0x03000154
_08002C1C: .4byte 0x03000150
_08002C20:
	ldr r0, _08002C30
	movs	r1, #0
	bl 0x0800295C
_08002C28:
	adds	r0, r4, #0
	pop	{r4}
	pop	{r1}
	bx	r1
_08002C30: .4byte 0x0802E204
_08002C34:
	ldr r2, _08002C44
	ldr	r2, [r2, #0]
	lsls	r0, r0, #2
	adds	r2, r2, r0
	ldr	r0, [r2, #0]
	str	r0, [r1, #8]
	str	r1, [r2, #0]
	bx	lr
_08002C44: .4byte 0x03000140
	.type sub_08002C48, %function
sub_08002C48:
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	ldr r2, _08002C5C
	ldr	r2, [r2, #0]
	lsls	r0, r0, #5
	adds	r0, r0, r2
	strh	r1, [r0, #6]
	strh	r1, [r0, #30]
	bx	lr
	movs	r0, r0
_08002C5C: .4byte 0x03000134
_08002C60:
	ldr r3, _08002C70
	ldr	r3, [r3, #0]
	lsls	r0, r0, #5
	adds	r0, r0, r3
	strh	r1, [r0, #6]
	strh	r2, [r0, #30]
	bx	lr
	movs	r0, r0
_08002C70: .4byte 0x03000134
.type sub_08002C74, %function
sub_08002C74:
	ldr r2, _08002C80
	ldr	r2, [r2, #0]
	lsls	r0, r0, #5
	adds	r0, r0, r2
	strh	r1, [r0, #22]
	bx	lr
_08002C80: .4byte 0x03000134
	.type sub_08002C84, %function
sub_08002C84:
	ldr r1, _08002C94
	ldr	r1, [r1, #0]
	lsls	r0, r0, #5
	adds	r0, r0, r1
	ldrh	r2, [r0, #6]
	negs	r1, r2
	strh	r1, [r0, #6]
	bx	lr
_08002C94: .4byte 0x03000134
	.type sub_08002C98, %function
sub_08002C98:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #4
	ldr r0, _08002D28
	ldr	r5, [r0, #0]
	ldr r2, _08002D2C
	ldr	r6, [r2, #0]
	movs	r4, #0
	ldr r0, _08002D30
	ldr	r1, [r0, #0]
	mov	sl, r2
	mov	r9, r0
	cmp	r4, r1
	bge _08002D08
	ldr r0, _08002D34
	mov	r8, r0
_08002CBE:
	ldmia	r5!, {r3}
	adds	r4, #1
	str	r4, [sp, #0]
	mov	ip, r5
	cmp	r3, #0
	beq _08002CFC
	ldr r4, _08002D38
	mov	r5, r8
_08002CCE:
	ldrh	r1, [r3, #12]
	cmp	r1, #1
	bne _08002CEC
	ldrh	r2, [r3, #2]
	adds	r1, r4, #0
	ands	r1, r2
	ldrh	r7, [r5, #12]
	lsls	r0, r7, #16
	asrs	r0, r0, #19
	subs	r1, r1, r0
	lsrs	r2, r2, #9
	lsls	r2, r2, #9
	ands	r1, r4
	orrs	r2, r1
	strh	r2, [r3, #2]
_08002CEC:
	ldr	r0, [r3, #0]
	str	r0, [r6, #0]
	ldrh	r0, [r3, #4]
	strh	r0, [r6, #4]
	adds	r6, #8
	ldr	r3, [r3, #8]
	cmp	r3, #0
	bne _08002CCE
_08002CFC:
	ldr	r4, [sp, #0]
	mov	r5, ip
	mov	r1, r9
	ldr	r0, [r1, #0]
	cmp	r4, r0
	blt _08002CBE
_08002D08:
	mov	r7, sl
	ldr	r0, [r7, #0]
	movs	r1, #224
	lsls	r1, r1, #19
	movs	r2, #128
	lsls	r2, r2, #1
	bl 0x0802D970
	add	sp, #4
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08002D28: .4byte 0x03000140
_08002D2C: .4byte 0x03000134
_08002D30: .4byte 0x03000144
_08002D34: .4byte 0x030035C0
_08002D38: .4byte 0x000001FF
	.type sub_08002D3C, %function
sub_08002D3C:
_08002D3C:
	push	{r4, r5, r6, lr}
	ldr r0, _08002D88
	ldr	r4, [r0, #0]
	ldr r0, _08002D8C
	ldr	r2, [r0, #0]
	movs	r3, #0
	ldr r1, _08002D90
	ldr	r0, [r1, #0]
	ldr r6, _08002D94
	cmp	r3, r0
	bge _08002D72
	adds	r5, r1, #0
_08002D54:
	ldmia	r4!, {r1}
	adds	r3, #1
	cmp	r1, #0
	beq _08002D6C
_08002D5C:
	ldr	r0, [r1, #0]
	str	r0, [r2, #0]
	ldrh	r0, [r1, #4]
	strh	r0, [r2, #4]
	adds	r2, #8
	ldr	r1, [r1, #8]
	cmp	r1, #0
	bne _08002D5C
_08002D6C:
	ldr	r0, [r5, #0]
	cmp	r3, r0
	blt _08002D54
_08002D72:
	ldr	r0, [r6, #0]
	movs	r1, #224
	lsls	r1, r1, #19
	movs	r2, #128
	lsls	r2, r2, #1
	bl 0x0802D970
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08002D88: .4byte 0x03000140
_08002D8C: .4byte 0x03000138
_08002D90: .4byte 0x03000144
_08002D94: .4byte 0x03000134
@ Entry label. The four lines above are literal POOL words, not code -- the
@ function they precede begins here at 0x08002D98 and had no label at all, so
@ it was invisible and inflated _08002D3C's span. Note the trap: a
@ `.type` on `_08002D94` (a pool word) would have created an entry four bytes
@ before the real function and split it. Zero bytes emitted.
	.type _08002D98, %function
_08002D98:
	push	{r4, r5, lr}
	ldr	r5, [sp, #12]
	ldr r4, _08002DB4
	ldr	r4, [r4, #0]
	lsls	r0, r0, #5
	.type sub_08002D98, %function
sub_08002D98:
	adds	r0, r0, r4
	strh	r1, [r0, #6]
	strh	r2, [r0, #14]
	strh	r3, [r0, #22]
	strh	r5, [r0, #30]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08002DB4: .4byte 0x03000134
	.type sub_08002DB8, %function
sub_08002DB8:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	adds	r7, r0, #0
	mov	ip, r1
	adds	r6, r2, #0
	mov	sl, r3
	ldr	r0, [sp, #36]
	ldr	r5, [sp, #40]
	lsls	r0, r0, #3
	ldr r1, _08002E34
	adds	r4, r0, r1
	ldrh	r1, [r4, #4]
	cmp	r5, #0
	beq _08002E24
	movs	r0, #255
	mov	r2, ip
	ands	r2, r0
	mov	r9, r2
	lsls	r0, r1, #16
	asrs	r0, r0, #16
	mov	r8, r0
_08002DE8:
	bl sub_08002BFC
	adds	r1, r0, #0
	mov	r0, r9
	ldrh	r2, [r4, #0]
	orrs	r0, r2
	strh	r0, [r1, #0]
	ldr r0, _08002E38
	adds	r2, r0, #0
	adds	r0, r7, #0
	ands	r0, r2
	ldrh	r2, [r4, #2]
	orrs	r0, r2
	strh	r0, [r1, #2]
	mov	r2, sl
	lsls	r0, r2, #12
	orrs	r0, r6
	strh	r0, [r1, #4]
	movs	r0, #0
	strh	r0, [r1, #12]
	ldr	r0, [sp, #32]
	bl _08002C34
	movs	r0, #6
	ldrsb	r0, [r4, r0]
	adds	r7, r7, r0
	add	r6, r8
	subs	r5, #1
	cmp	r5, #0
	bne _08002DE8
_08002E24:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08002E34: .4byte 0x080C4940
_08002E38: .4byte 0x000001FF
	.type sub_08002E3C, %function
sub_08002E3C:
_08002E3C:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #4
	adds	r7, r0, #0
	mov	ip, r1
	adds	r6, r2, #0
	str	r3, [sp, #0]
	ldr	r0, [sp, #40]
	ldr	r5, [sp, #44]
	ldr	r1, [sp, #48]
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	mov	sl, r1
	lsls	r0, r0, #3
	ldr r1, _08002EC8
	adds	r4, r0, r1
	ldrh	r1, [r4, #4]
	cmp	r5, #0
	beq _08002EB8
	movs	r0, #255
	mov	r2, ip
	ands	r2, r0
	mov	r9, r2
	lsls	r0, r1, #16
	asrs	r0, r0, #16
	mov	r8, r0
_08002E76:
	bl sub_08002BFC
	adds	r1, r0, #0
	mov	r0, r9
	ldrh	r3, [r4, #0]
	orrs	r0, r3
	strh	r0, [r1, #0]
	ldr r0, _08002ECC
	adds	r2, r0, #0
	adds	r0, r7, #0
	ands	r0, r2
	ldrh	r2, [r4, #2]
	orrs	r0, r2
	strh	r0, [r1, #2]
	ldr	r3, [sp, #0]
	lsls	r0, r3, #12
	orrs	r0, r6
	mov	r3, sl
	lsls	r2, r3, #10
	orrs	r0, r2
	strh	r0, [r1, #4]
	movs	r0, #0
	strh	r0, [r1, #12]
	ldr	r0, [sp, #36]
	bl _08002C34
	movs	r0, #6
	ldrsb	r0, [r4, r0]
	adds	r7, r7, r0
	add	r6, r8
	subs	r5, #1
	cmp	r5, #0
	bne _08002E76
_08002EB8:
	add	sp, #4
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08002EC8: .4byte 0x080C4940
_08002ECC: .4byte 0x000001FF
	.type sub_08002ED0, %function
sub_08002ED0:
_08002ED0:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #4
	adds	r7, r0, #0
	mov	ip, r1
	adds	r6, r2, #0
	str	r3, [sp, #0]
_08002EE4:
	ldr	r0, [sp, #40]
	ldr	r5, [sp, #44]
	ldr	r2, [sp, #52]
	lsls	r0, r0, #3
	ldr r1, _08002F60
	adds	r4, r0, r1
	lsls	r2, r2, #10
	mov	sl, r2
	ldrh	r1, [r4, #4]
	cmp	r5, #0
	beq _08002F50
	movs	r0, #255
	mov	r2, ip
	ands	r2, r0
	mov	r9, r2
	lsls	r0, r1, #16
	asrs	r0, r0, #16
	mov	r8, r0
_08002F08:
	bl sub_08002BFC
	adds	r1, r0, #0
	mov	r0, sl
	ldrh	r3, [r4, #0]
	orrs	r0, r3
	mov	r2, r9
	orrs	r0, r2
	strh	r0, [r1, #0]
	ldr r3, _08002F64
	adds	r2, r3, #0
	adds	r0, r7, #0
	ands	r0, r2
	ldrh	r2, [r4, #2]
	orrs	r0, r2
	strh	r0, [r1, #2]
	ldr	r3, [sp, #0]
	lsls	r0, r3, #12
	orrs	r0, r6
	ldr	r3, [sp, #48]
	lsls	r2, r3, #10
	orrs	r0, r2
	strh	r0, [r1, #4]
	mov	r0, sp
	ldrh	r0, [r0, #56]
	strh	r0, [r1, #12]
	ldr	r0, [sp, #36]
	bl _08002C34
	movs	r0, #6
	ldrsb	r0, [r4, r0]
	adds	r7, r7, r0
	add	r6, r8
	subs	r5, #1
	cmp	r5, #0
	bne _08002F08
_08002F50:
	add	sp, #4
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08002F60: .4byte 0x080C4940
_08002F64: .4byte 0x000001FF
	.type sub_08002F68, %function
sub_08002F68:
_08002F68:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #8
	mov	r8, r0
	adds	r6, r1, #0
	adds	r7, r2, #0
	str	r3, [sp, #0]
	ldr	r0, [sp, #44]
	ldr	r4, [sp, #48]
	lsls	r0, r0, #3
	ldr r1, _08002FFC
	adds	r0, r0, r1
	ldrh	r2, [r0, #0]
	ldrh	r1, [r0, #2]
	str	r1, [sp, #4]
	movs	r1, #6
	ldrsb	r1, [r0, r1]
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	mov	sl, r1
	ldrh	r0, [r0, #4]
	mov	r9, r0
	cmp	r4, #0
	beq _08002FEC
	movs	r1, #128
	lsls	r1, r1, #3
	adds	r0, r1, #0
	adds	r5, r2, #0
	orrs	r5, r0
	movs	r0, #255
	ands	r6, r0
	orrs	r5, r6
_08002FAE:
	bl sub_08002BFC
	adds	r1, r0, #0
	strh	r5, [r1, #0]
	ldr r0, _08003000
	adds	r2, r0, #0
	mov	r0, r8
	ands	r0, r2
	ldr	r2, [sp, #4]
	orrs	r0, r2
	strh	r0, [r1, #2]
	ldr	r2, [sp, #0]
	lsls	r0, r2, #12
	orrs	r0, r7
	strh	r0, [r1, #4]
	movs	r0, #0
	strh	r0, [r1, #12]
	ldr	r0, [sp, #40]
	bl _08002C34
	mov	r1, sl
	lsls	r0, r1, #16
	asrs	r0, r0, #16
	add	r8, r0
	mov	r2, r9
	lsls	r0, r2, #16
	asrs	r0, r0, #16
	adds	r7, r7, r0
	subs	r4, #1
	cmp	r4, #0
	bne _08002FAE
_08002FEC:
	add	sp, #8
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08002FFC: .4byte 0x080C4940
_08003000: .4byte 0x000001FF
	.type sub_08003004, %function
sub_08003004:
_08003004:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #4
	mov	r8, r0
	adds	r6, r1, #0
	str	r2, [sp, #0]
	mov	sl, r3
	ldr	r1, [sp, #40]
	lsls	r1, r1, #3
	ldr r0, _0800307C
	adds	r7, r1, r0
	bl _08002BE8
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	mov	r9, r0
	ldrh	r5, [r7, #0]
	ldrh	r4, [r7, #2]
	ldr	r0, [sp, #44]
	lsls	r1, r0, #16
	lsrs	r1, r1, #16
	ldr	r3, [sp, #48]
	lsls	r2, r3, #16
	lsrs	r2, r2, #16
	mov	r0, r9
_0800303C:
	bl _08002C60
	bl sub_08002BFC
	adds	r2, r0, #0
	ldr	r0, [sp, #44]
	cmp	r0, #255
	ble _08003052
	ldr	r1, [sp, #48]
	cmp	r1, #255
	bgt _08003080
_08003052:
	movs	r0, #6
	ldrsb	r0, [r7, r0]
	lsrs	r1, r0, #31
	adds	r0, r0, r1
	asrs	r0, r0, #1
	mov	r3, r8
	subs	r3, r3, r0
	mov	r8, r3
	movs	r0, #7
	ldrsb	r0, [r7, r0]
	lsrs	r1, r0, #31
	adds	r0, r0, r1
	asrs	r0, r0, #1
	subs	r6, r6, r0
	movs	r0, #255
	ands	r6, r0
	orrs	r5, r6
	movs	r1, #192
	lsls	r1, r1, #2
	adds	r0, r1, #0
	b _0800308C
_0800307C: .4byte 0x080C4940
_08003080:
	movs	r0, #255
	ands	r6, r0
	orrs	r5, r6
	movs	r3, #128
	lsls	r3, r3, #1
	adds	r0, r3, #0
_0800308C:
	orrs	r5, r0
	strh	r5, [r2, #0]
	ldr r1, _080030C8
	adds	r0, r1, #0
	mov	r3, r8
	ands	r3, r0
	orrs	r4, r3
	mov	r1, r9
	lsls	r0, r1, #9
	orrs	r4, r0
	movs	r1, #0
	strh	r4, [r2, #2]
	mov	r3, sl
	lsls	r0, r3, #12
	ldr	r3, [sp, #0]
	orrs	r0, r3
	strh	r0, [r2, #4]
	strh	r1, [r2, #12]
	ldr	r0, [sp, #36]
	adds	r1, r2, #0
	bl _08002C34
	add	sp, #4
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080030C8: .4byte 0x000001FF
	.type sub_080030CC, %function
sub_080030CC:
_080030CC:
	push	{r4, r5, lr}
	sub	sp, #8
	mov	r2, sp
	movs	r1, #0
	movs	r0, #160
	strh	r0, [r2, #0]
	mov	r0, sp
	strh	r1, [r0, #2]
	strh	r1, [r0, #4]
	strh	r1, [r0, #6]
	movs	r5, #224
	lsls	r5, r5, #19
	movs	r4, #31
_080030E6:
	mov	r0, sp
	adds	r1, r5, #0
	ldr r2, _08003100
	bl 0x0802D974
	adds	r5, #8
	subs	r4, #1
	cmp	r4, #0
	bge _080030E6
	add	sp, #8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_08003100: .4byte 0x04000002
	.type sub_08003104, %function
sub_08003104:
	push	{r4, lr}
	adds	r4, r0, #0
	movs	r1, #128
	lsls	r1, r1, #2
	bl _08002B00
	movs	r1, #128
	lsls	r1, r1, #3
	adds	r0, r4, r1
	movs	r1, #32
	bl _08002B1C
	movs	r0, #144
	lsls	r0, r0, #3
	adds	r4, r4, r0
	adds	r0, r4, #0
	movs	r1, #128
	bl _08002B30
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_08003130, %function
sub_08003130:
_08003130:
	ldr r0, _08003138
	ldr	r0, [r0, #0]
	bx	lr
	movs	r0, r0
_08003138: .4byte 0x03000134
	.type sub_0800313C, %function
sub_0800313C:
_0800313C:
	ldr r1, _08003144
	str	r0, [r1, #0]
	bx	lr
	movs	r0, r0
_08003144: .4byte 0x03000138
_08003148:
	adds	r1, r0, #0
	movs	r2, #0
	b _08003152
_0800314E:
	adds	r2, #1
	adds	r1, #1
_08003152:
	ldrb	r0, [r1, #0]
	cmp	r0, #0
	bne _0800314E
	adds	r0, r2, #0
	bx	lr
	.type sub_0800315C, %function
sub_0800315C:
_0800315C:
	push	{r4, r5, lr}
	adds	r3, r0, #0
	ldr	r4, [r3, #0]
	ldr	r1, [r3, #12]
	cmp	r1, #0
	blt _0800318C
	ldr	r2, [r3, #16]
	movs	r5, #128
	lsls	r5, r5, #8
	adds	r0, r5, #0
	ldrh	r5, [r3, #8]
	orrs	r0, r5
	strh	r0, [r4, #0]
	ldr	r0, [r3, #4]
	strh	r0, [r4, #2]
	lsls	r1, r1, #1
	ldrh	r0, [r2, #2]
	adds	r1, r0, r1
	ldr	r0, [r3, #20]
	ldrh	r2, [r2, #0]
	adds	r0, r2, r0
	lsls	r0, r0, #12
	orrs	r1, r0
	strh	r1, [r4, #4]
_0800318C:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003194, %function
sub_08003194:
_08003194:
	push	{r4, r5, lr}
	adds	r3, r0, #0
	ldr	r4, [r3, #0]
	ldr	r1, [r3, #12]
	cmp	r1, #0
	blt _080031CC
	ldr	r2, [r3, #16]
	movs	r5, #128
	lsls	r5, r5, #8
	adds	r0, r5, #0
	ldrh	r5, [r3, #8]
	orrs	r0, r5
	strh	r0, [r4, #0]
	ldr	r0, [r3, #4]
	strh	r0, [r4, #2]
	lsls	r1, r1, #1
	ldrh	r0, [r2, #2]
	adds	r1, r0, r1
	ldr	r0, [r3, #20]
	ldrh	r2, [r2, #0]
	adds	r0, r2, r0
	lsls	r0, r0, #12
	orrs	r1, r0
	movs	r2, #128
	lsls	r2, r2, #3
	adds	r0, r2, #0
	orrs	r1, r0
	strh	r1, [r4, #4]
_080031CC:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080031D4, %function
sub_080031D4:
_080031D4:
	push	{r4, r5, lr}
	adds	r3, r0, #0
	ldr	r4, [r3, #0]
	ldr	r1, [r3, #12]
	cmp	r1, #0
	blt _0800320A
	ldr	r2, [r3, #16]
	movs	r5, #128
	lsls	r5, r5, #8
	adds	r0, r5, #0
	ldrh	r5, [r3, #8]
	orrs	r0, r5
	strh	r0, [r4, #0]
	ldr	r0, [r3, #4]
	strh	r0, [r4, #2]
	lsls	r1, r1, #1
	ldrh	r2, [r2, #2]
	adds	r1, r2, r1
	ldr	r0, [r3, #20]
	adds	r0, #12
	lsls	r0, r0, #12
	orrs	r1, r0
	movs	r2, #128
	lsls	r2, r2, #3
	adds	r0, r2, #0
	orrs	r1, r0
	strh	r1, [r4, #4]
_0800320A:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_08003210, %function
sub_08003210:
_08003210:
	push	{r4, r5, lr}
	adds	r3, r0, #0
	ldr	r4, [r3, #0]
	ldr	r1, [r3, #12]
	cmp	r1, #0
	blt _08003240
	ldr	r2, [r3, #16]
	movs	r5, #132
	lsls	r5, r5, #8
	adds	r0, r5, #0
	ldrh	r5, [r3, #8]
	orrs	r0, r5
	strh	r0, [r4, #0]
	ldr	r0, [r3, #4]
	strh	r0, [r4, #2]
	lsls	r1, r1, #1
	ldrh	r0, [r2, #2]
	adds	r1, r0, r1
	ldr	r0, [r3, #20]
	ldrh	r2, [r2, #0]
	adds	r0, r2, r0
	lsls	r0, r0, #12
	orrs	r1, r0
	strh	r1, [r4, #4]
_08003240:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003248, %function
sub_08003248:
_08003248:
	push	{r4, r5, lr}
	adds	r2, r0, #0
	adds	r5, r1, #0
	ldr r4, _0800326C
	adds	r0, r4, #0
	movs	r1, #0
	bl sub_08007538
	adds	r0, r4, #0
	movs	r1, #3
	movs	r2, #0
	adds	r3, r5, #0
	bl sub_08007614
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800326C: .4byte 0x087ACF70
	.type sub_08003270, %function
sub_08003270:
_08003270:
	push	{r4, r5, lr}
	adds	r2, r0, #0
	adds	r5, r1, #0
	ldr r4, _08003294
	adds	r0, r4, #0
	movs	r1, #1
	bl sub_08007538
	adds	r0, r4, #0
	movs	r1, #4
	movs	r2, #0
	adds	r3, r5, #0
	bl sub_08007614
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08003294: .4byte 0x087ACF70
	.type sub_08003298, %function
sub_08003298:
_08003298:
	push	{r4, r5, lr}
	adds	r2, r0, #0
	adds	r5, r1, #0
	ldr r4, _080032BC
	adds	r0, r4, #0
	movs	r1, #2
	bl sub_08007538
	adds	r0, r4, #0
	movs	r1, #5
	movs	r2, #0
	adds	r3, r5, #0
	bl sub_08007614
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080032BC: .4byte 0x087ACF70
	.type sub_080032C0, %function
sub_080032C0:
_080032C0:
	push	{lr}
	adds	r3, r0, #0
	adds	r2, r1, #0
	ldr r0, _080032D8
	ldr r1, _080032DC
	ldrh	r1, [r1, #0]
	adds	r3, r1, r3
	movs	r1, #3
	bl sub_08007614
	pop	{r0}
	bx	r0
_080032D8: .4byte 0x087ACF70
_080032DC: .4byte 0x03000160
	.type sub_080032E0, %function
sub_080032E0:
	push	{r4, r5, r6, lr}
	movs	r5, #0
	adds	r6, r0, #0
_080032E6:
	lsls	r1, r5, #2
	ldr r0, _08003314
	adds	r4, r1, r0
	ldrb	r0, [r6, #0]
	cmp	r0, #0
	beq _08003342
	ldr r0, _08003318
	adds	r0, r1, r0
	ldr	r0, [r0, #0]
	bl sub_08005758
	strh	r0, [r4, #2]
	ldrb	r0, [r6, #1]
	bl sub_08005790
	strh	r0, [r4, #0]
	cmp	r5, #1
	beq _08003342
	cmp	r5, #1
	bgt _0800331C
	cmp	r5, #0
	beq _08003326
	b _08003342
_08003314: .4byte 0x03000160
_08003318: .4byte 0x080C4BB0
_0800331C:
	cmp	r5, #2
	beq _08003330
	cmp	r5, #3
	beq _0800333A
	b _08003342
_08003326:
	ldrh	r0, [r4, #2]
	ldrh	r1, [r4, #0]
	bl sub_08003248
	b _08003342
_08003330:
	ldrh	r0, [r4, #2]
	ldrh	r1, [r4, #0]
	bl sub_08003270
	b _08003342
_0800333A:
	ldrh	r0, [r4, #2]
	ldrh	r1, [r4, #0]
	bl sub_08003298
_08003342:
	adds	r6, #4
	adds	r5, #1
	cmp	r5, #3
	ble _080032E6
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	.type sub_08003350, %function
sub_08003350:
_08003350:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #40
	adds	r6, r1, #0
	mov	r8, r2
	mov	ip, r3
	ldr	r5, [sp, #72]
	mov	r4, sp
	ldr r1, _080033EC
	ldmia	r1!, {r2, r3, r7}
	stmia	r4!, {r2, r3, r7}
	ldr	r1, [r1, #0]
	str	r1, [r4, #0]
	ldr r1, _080033F0
	lsls	r0, r0, #2
	adds	r1, r0, r1
	ldr	r1, [r1, #0]
	mov	sl, r1
	mov	r2, sp
	adds	r1, r2, r0
	ldr	r1, [r1, #0]
	mov	r9, r1
	add	r4, sp, #16
	ldr r1, _080033F4
	adds	r0, r0, r1
	str	r0, [r4, #16]
	mov	r3, r8
	str	r3, [r4, #8]
	mov	r7, ip
	str	r7, [r4, #20]
	ldrb	r0, [r5, #0]
	mov	r8, r4
	cmp	r0, #0
	beq _080033DC
	mov	r7, r8
_0800339C:
	ldrb	r1, [r5, #0]
	lsls	r0, r1, #1
	ldr r2, _080033F8
	adds	r0, r0, r2
	movs	r3, #0
	ldrsh	r1, [r0, r3]
	subs	r1, #1
	ldr r0, _080033FC
	ands	r0, r6
	str	r0, [r7, #4]
	str	r1, [r7, #12]
	cmp	r1, #0
	blt _080033D2
	bl sub_08002BFC
	adds	r4, r0, #0
	add	r0, sp, #76
	ldrh	r0, [r0, #0]
	strh	r0, [r4, #12]
	str	r4, [sp, #16]
	mov	r0, r8
	bl 0x0802DDEC
	movs	r0, #0
	adds	r1, r4, #0
	bl _08002C34
_080033D2:
	adds	r5, #1
	add	r6, sl
	ldrb	r0, [r5, #0]
	cmp	r0, #0
	bne _0800339C
_080033DC:
	add	sp, #40
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080033EC: .4byte 0x0802E210
_080033F0: .4byte 0x080C4BA0
_080033F4: .4byte 0x03000160
_080033F8: .4byte 0x080C49A0
_080033FC: .4byte 0x000001FF
	.type sub_08003400, %function
sub_08003400:
_08003400:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #40
	adds	r6, r1, #0
	mov	r8, r2
	mov	ip, r3
	ldr	r5, [sp, #72]
	mov	r4, sp
	ldr r1, _0800349C
	ldmia	r1!, {r2, r3, r7}
	stmia	r4!, {r2, r3, r7}
	ldr	r1, [r1, #0]
	str	r1, [r4, #0]
	ldr r1, _080034A0
	lsls	r0, r0, #2
	adds	r1, r0, r1
	ldr	r1, [r1, #0]
	mov	sl, r1
	mov	r2, sp
	adds	r1, r2, r0
	ldr	r1, [r1, #0]
	mov	r9, r1
	add	r4, sp, #16
	ldr r1, _080034A4
	adds	r0, r0, r1
	str	r0, [r4, #16]
	mov	r3, r8
	str	r3, [r4, #8]
	mov	r7, ip
	str	r7, [r4, #20]
	ldrb	r0, [r5, #0]
	mov	r8, r4
	cmp	r0, #0
	beq _0800348C
	mov	r7, r8
_0800344C:
	ldrb	r1, [r5, #0]
	lsls	r0, r1, #1
	ldr r2, _080034A8
	adds	r0, r0, r2
	movs	r3, #0
	ldrsh	r1, [r0, r3]
	subs	r1, #1
	ldr r0, _080034AC
	ands	r0, r6
	str	r0, [r7, #4]
	str	r1, [r7, #12]
	cmp	r1, #0
	blt _08003482
	bl sub_08002BFC
	adds	r4, r0, #0
	add	r0, sp, #80
	ldrh	r0, [r0, #0]
	strh	r0, [r4, #12]
	str	r4, [sp, #16]
	mov	r0, r8
	bl 0x0802DDEC
	movs	r0, #0
	adds	r1, r4, #0
	bl _08002C34
_08003482:
	adds	r5, #1
	add	r6, sl
	ldrb	r0, [r5, #0]
	cmp	r0, #0
	bne _0800344C
_0800348C:
	add	sp, #40
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_0800349C: .4byte 0x0802E220
_080034A0: .4byte 0x080C4BA0
_080034A4: .4byte 0x03000160
_080034A8: .4byte 0x080C49A0
_080034AC: .4byte 0x000001FF
	.type sub_080034B0, %function
sub_080034B0:
_080034B0:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #40
	adds	r6, r1, #0
	mov	r8, r2
	mov	ip, r3
	ldr	r5, [sp, #72]
	mov	r4, sp
	ldr r1, _0800354C
	ldmia	r1!, {r2, r3, r7}
	stmia	r4!, {r2, r3, r7}
	ldr	r1, [r1, #0]
	str	r1, [r4, #0]
	ldr r1, _08003550
	lsls	r0, r0, #2
	adds	r1, r0, r1
	ldr	r1, [r1, #0]
	mov	sl, r1
	mov	r2, sp
	adds	r1, r2, r0
	ldr	r1, [r1, #0]
	mov	r9, r1
	add	r4, sp, #16
	ldr r1, _08003554
	adds	r0, r0, r1
	str	r0, [r4, #16]
	mov	r3, r8
	str	r3, [r4, #8]
	mov	r7, ip
	str	r7, [r4, #20]
	ldrb	r0, [r5, #0]
	mov	r8, r4
	cmp	r0, #0
	beq _0800353C
	mov	r7, r8
_080034FC:
	ldrb	r1, [r5, #0]
	lsls	r0, r1, #1
	ldr r2, _08003558
	adds	r0, r0, r2
	movs	r3, #0
	ldrsh	r1, [r0, r3]
	subs	r1, #1
	ldr r0, _0800355C
	ands	r0, r6
	str	r0, [r7, #4]
	str	r1, [r7, #12]
	cmp	r1, #0
	blt _08003532
	bl sub_08002BFC
	adds	r4, r0, #0
	add	r0, sp, #76
	ldrh	r0, [r0, #0]
	strh	r0, [r4, #12]
	str	r4, [sp, #16]
	mov	r0, r8
	bl 0x0802DDEC
	movs	r0, #0
	adds	r1, r4, #0
	bl _08002C34
_08003532:
	adds	r5, #1
	add	r6, sl
	ldrb	r0, [r5, #0]
	cmp	r0, #0
	bne _080034FC
_0800353C:
	add	sp, #40
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_0800354C: .4byte 0x0802E230
_08003550: .4byte 0x080C4BA0
_08003554: .4byte 0x03000160
_08003558: .4byte 0x080C49A0
_0800355C: .4byte 0x000001FF
	.type sub_08003560, %function
sub_08003560:
_08003560:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #40
	adds	r6, r1, #0
	mov	r8, r2
	mov	ip, r3
	ldr	r5, [sp, #72]
	mov	r4, sp
	ldr r1, _080035F4
	ldmia	r1!, {r2, r3, r7}
	stmia	r4!, {r2, r3, r7}
	ldr	r1, [r1, #0]
	str	r1, [r4, #0]
	ldr r1, _080035F8
	lsls	r0, r0, #2
	adds	r1, r0, r1
	ldr	r1, [r1, #0]
	mov	sl, r1
	mov	r2, sp
	adds	r1, r2, r0
	ldr	r1, [r1, #0]
	mov	r9, r1
	add	r4, sp, #16
	ldr r1, _080035FC
	adds	r0, r0, r1
	str	r0, [r4, #16]
	mov	r3, r8
	str	r3, [r4, #8]
	mov	r7, ip
	str	r7, [r4, #20]
	ldrb	r0, [r5, #0]
	mov	r8, r4
	cmp	r0, #0
	beq _080035E2
	mov	r7, r8
_080035AC:
	ldrb	r1, [r5, #0]
	lsls	r0, r1, #1
	ldr r2, _08003600
	adds	r0, r0, r2
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	subs	r0, #1
	str	r6, [r7, #4]
	str	r0, [r7, #12]
	cmp	r0, #0
	blt _080035D8
	bl sub_08002BFC
	adds	r4, r0, #0
	str	r4, [sp, #16]
	mov	r0, r8
	bl 0x0802DDEC
	movs	r0, #0
	adds	r1, r4, #0
	bl _08002C34
_080035D8:
	adds	r5, #1
	add	r6, sl
	ldrb	r0, [r5, #0]
	cmp	r0, #0
	bne _080035AC
_080035E2:
	add	sp, #40
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080035F4: .4byte 0x0802E240
_080035F8: .4byte 0x080C4BA0
_080035FC: .4byte 0x03000160
_08003600: .4byte 0x080C49A0
	.type sub_08003604, %function
sub_08003604:
_08003604:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #8
	adds	r5, r0, #0
	adds	r6, r1, #0
	adds	r7, r2, #0
	ldr r1, _08003648
	lsls	r0, r5, #2
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	lsrs	r1, r0, #31
	adds	r0, r0, r1
	asrs	r4, r0, #1
	adds	r2, r3, #0
	movs	r1, #120
	ldrb	r0, [r3, #0]
	cmp	r0, #0
	beq _08003630
_08003626:
	adds	r2, #1
	subs	r1, r1, r4
	ldrb	r0, [r2, #0]
	cmp	r0, #0
	bne _08003626
_08003630:
	str	r3, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	adds	r0, r5, #0
	adds	r2, r6, #0
	adds	r3, r7, #0
	bl sub_08003350
	add	sp, #8
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08003648: .4byte 0x080C4BA0
	.type sub_0800364C, %function
sub_0800364C:
_0800364C:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #8
	adds	r5, r0, #0
	adds	r4, r1, #0
	adds	r6, r2, #0
	adds	r7, r3, #0
	ldr	r3, [sp, #28]
	adds	r2, r3, #0
	ldr r1, _08003694
	lsls	r0, r5, #2
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	lsrs	r1, r0, #31
	adds	r0, r0, r1
	asrs	r1, r0, #1
	ldrb	r0, [r3, #0]
	cmp	r0, #0
	beq _0800367A
_08003670:
	adds	r2, #1
	subs	r4, r4, r1
	ldrb	r0, [r2, #0]
	cmp	r0, #0
	bne _08003670
_0800367A:
	str	r3, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	adds	r0, r5, #0
	adds	r1, r4, #0
	adds	r2, r6, #0
	adds	r3, r7, #0
	bl sub_08003350
	add	sp, #8
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08003694: .4byte 0x080C4BA0
	.type sub_08003698, %function
sub_08003698:
_08003698:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #4
	adds	r5, r0, #0
	adds	r4, r1, #0
	adds	r6, r2, #0
	adds	r7, r3, #0
	ldr	r3, [sp, #24]
	adds	r2, r3, #0
	ldr r1, _080036DC
	lsls	r0, r5, #2
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	lsrs	r1, r0, #31
	adds	r0, r0, r1
	asrs	r1, r0, #1
	ldrb	r0, [r3, #0]
	cmp	r0, #0
	beq _080036C6
_080036BC:
	adds	r2, #1
	subs	r4, r4, r1
	ldrb	r0, [r2, #0]
	cmp	r0, #0
	bne _080036BC
_080036C6:
	str	r3, [sp, #0]
	adds	r0, r5, #0
	adds	r1, r4, #0
	adds	r2, r6, #0
	adds	r3, r7, #0
	bl sub_08003560
	add	sp, #4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_080036DC: .4byte 0x080C4BA0
	.type sub_080036E0, %function
sub_080036E0:
_080036E0:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #8
	adds	r5, r0, #0
	adds	r4, r1, #0
	adds	r6, r2, #0
	adds	r7, r3, #0
	ldr	r3, [sp, #28]
	adds	r2, r3, #0
	ldr r0, _08003724
	lsls	r1, r5, #2
	adds	r1, r1, r0
	ldr	r1, [r1, #0]
	ldrb	r0, [r3, #0]
	cmp	r0, #0
	beq _08003708
_080036FE:
	adds	r2, #1
	subs	r4, r4, r1
	ldrb	r0, [r2, #0]
	cmp	r0, #0
	bne _080036FE
_08003708:
	str	r3, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	adds	r0, r5, #0
	adds	r1, r4, #0
	adds	r2, r6, #0
	adds	r3, r7, #0
	bl sub_08003350
	add	sp, #8
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08003724: .4byte 0x080C4BA0
	.type sub_08003728, %function
sub_08003728:
_08003728:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #4
	adds	r5, r0, #0
	adds	r4, r1, #0
	adds	r6, r2, #0
	adds	r7, r3, #0
	ldr	r3, [sp, #24]
	adds	r2, r3, #0
	ldr r0, _08003768
	lsls	r1, r5, #2
	adds	r1, r1, r0
	ldr	r1, [r1, #0]
	ldrb	r0, [r3, #0]
	cmp	r0, #0
	beq _08003750
_08003746:
	adds	r2, #1
	subs	r4, r4, r1
	ldrb	r0, [r2, #0]
	cmp	r0, #0
	bne _08003746
_08003750:
	str	r3, [sp, #0]
	adds	r0, r5, #0
	adds	r1, r4, #0
	adds	r2, r6, #0
	adds	r3, r7, #0
	bl sub_08003560
	add	sp, #4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08003768: .4byte 0x080C4BA0
	.type sub_0800376C, %function
sub_0800376C:
_0800376C:
	push	{r4, r5, r6, lr}
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6}
	sub	sp, #24
	adds	r5, r0, #0
	adds	r4, r1, #0
	mov	r8, r2
	mov	r9, r3
	ldr	r0, [sp, #48]
	ldr	r6, [sp, #52]
	add	r1, sp, #8
	movs	r2, #16
	bl sub_08003CB4
	ldr r2, _080037B8
	lsls	r1, r5, #2
	adds	r1, r1, r2
	ldr	r1, [r1, #0]
	muls	r0, r1
	subs	r4, r4, r0
	add	r0, sp, #8
	str	r0, [sp, #0]
	str	r6, [sp, #4]
	adds	r0, r5, #0
	adds	r1, r4, #0
	mov	r2, r8
	mov	r3, r9
	bl sub_08003350
	add	sp, #24
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080037B8: .4byte 0x080C4BA0
	.type sub_080037BC, %function
sub_080037BC:
_080037BC:
	push	{r4, r5, r6, lr}
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6}
	sub	sp, #28
	adds	r5, r0, #0
	adds	r4, r1, #0
	mov	r8, r2
	mov	r9, r3
	ldr	r0, [sp, #52]
	ldr	r6, [sp, #56]
	add	r1, sp, #12
	movs	r2, #16
	bl sub_08003CB4
	ldr r2, _0800380C
	lsls	r1, r5, #2
	adds	r1, r1, r2
	ldr	r1, [r1, #0]
	muls	r0, r1
	subs	r4, r4, r0
	add	r0, sp, #12
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	str	r6, [sp, #8]
	adds	r0, r5, #0
	adds	r1, r4, #0
	mov	r2, r8
	mov	r3, r9
	bl sub_08003400
	add	sp, #28
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800380C: .4byte 0x080C4BA0
	.type sub_08003810, %function
sub_08003810:
_08003810:
	push	{r4, r5, r6, lr}
	sub	sp, #16
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r6, r2, #0
	adds	r0, r3, #0
	mov	r1, sp
	movs	r2, #16
	bl sub_08003CB4
	adds	r0, r4, #0
	adds	r1, r5, #0
	adds	r2, r6, #0
	mov	r3, sp
	bl sub_08003604
	add	sp, #16
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	.type sub_08003838, %function
sub_08003838:
_08003838:
	push	{r4, lr}
	sub	sp, #8
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_08003350
	add	sp, #8
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800385C, %function
sub_0800385C:
_0800385C:
	push	{r4, lr}
	sub	sp, #12
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	str	r0, [sp, #8]
	movs	r0, #0
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_08003400
	add	sp, #12
	pop	{r4}
	pop	{r0}
	bx	r0
	.type sub_08003880, %function
sub_08003880:
_08003880:
	push	{r4, r5, lr}
	sub	sp, #12
	adds	r4, r0, #0
	adds	r5, r1, #0
	str	r2, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	str	r3, [sp, #8]
	movs	r0, #0
	adds	r1, r4, #0
	adds	r2, r5, #0
	movs	r3, #0
	bl sub_080034B0
	add	sp, #12
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_080038A4, %function
sub_080038A4:
_080038A4:
	push	{r4, lr}
	sub	sp, #8
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #2
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_08003350
	add	sp, #8
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080038C8, %function
sub_080038C8:
_080038C8:
	push	{r4, lr}
	sub	sp, #8
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #3
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_08003350
	add	sp, #8
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080038EC, %function
sub_080038EC:
_080038EC:
	push	{r4, lr}
	sub	sp, #4
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #2
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_08003560
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800390C, %function
sub_0800390C:
_0800390C:
	push	{r4, lr}
	sub	sp, #4
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #3
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_08003560
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800392C, %function
sub_0800392C:
_0800392C:
	push	{lr}
	adds	r2, r0, #0
	adds	r3, r1, #0
	movs	r0, #0
	adds	r1, r2, #0
	movs	r2, #0
	bl sub_08003604
	pop	{r0}
	bx	r0
	.type sub_08003940, %function
sub_08003940:
_08003940:
	push	{lr}
	adds	r2, r0, #0
	adds	r3, r1, #0
	movs	r0, #2
	adds	r1, r2, #0
	movs	r2, #0
	bl sub_08003604
	pop	{r0}
	bx	r0
	.type sub_08003954, %function
sub_08003954:
_08003954:
	push	{r4, lr}
	sub	sp, #8
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #0
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_0800376C
	add	sp, #8
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003978, %function
sub_08003978:
_08003978:
	push	{r4, lr}
	sub	sp, #8
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #2
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_0800376C
	add	sp, #8
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0800399C, %function
sub_0800399C:
_0800399C:
	push	{r4, lr}
	sub	sp, #8
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #2
	adds	r1, r3, #0
	adds	r2, r4, #0
_080039B0:
	movs	r3, #0
	bl sub_080037BC
	add	sp, #8
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080039C0, %function
sub_080039C0:
_080039C0:
	push	{r4, lr}
	sub	sp, #8
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #3
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_0800376C
	add	sp, #8
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_080039E4, %function
sub_080039E4:
_080039E4:
	push	{r4, lr}
	sub	sp, #8
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #0
	str	r0, [sp, #4]
	movs	r0, #2
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_0800376C
	add	sp, #8
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003A08, %function
sub_08003A08:
_08003A08:
	push	{r4, lr}
	sub	sp, #4
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #0
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_0800364C
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003A28, %function
sub_08003A28:
_08003A28:
	push	{r4, lr}
	sub	sp, #4
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #2
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_0800364C
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003A48, %function
sub_08003A48:
_08003A48:
	push	{r4, lr}
	sub	sp, #4
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #3
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_0800364C
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003A68, %function
sub_08003A68:
_08003A68:
	push	{r4, lr}
	sub	sp, #4
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #3
	adds	r1, r3, #0
	adds	r2, r4, #0
_08003A78:
	movs	r3, #0
	bl sub_08003698
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003A88, %function
sub_08003A88:
_08003A88:
	push	{r4, lr}
	sub	sp, #4
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #3
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_080036E0
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003AA8, %function
sub_08003AA8:
_08003AA8:
	push	{r4, lr}
	sub	sp, #4
	adds	r3, r0, #0
	adds	r4, r1, #0
	str	r2, [sp, #0]
	movs	r0, #3
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_08003728
	add	sp, #4
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003AC8, %function
sub_08003AC8:
_08003AC8:
	push	{lr}
	adds	r2, r0, #0
	adds	r3, r1, #0
	movs	r0, #0
	adds	r1, r2, #0
	movs	r2, #0
	bl sub_08003810
	pop	{r0}
	bx	r0
	.type sub_08003ADC, %function
sub_08003ADC:
_08003ADC:
	push	{lr}
	adds	r2, r0, #0
	adds	r3, r1, #0
	movs	r0, #2
	adds	r1, r2, #0
	movs	r2, #0
	bl sub_08003810
	pop	{r0}
	bx	r0
	.type sub_08003AF0, %function
sub_08003AF0:
_08003AF0:
	push	{r4, lr}
	sub	sp, #8
	ldrb	r4, [r0, #8]
	movs	r2, #12
	ldrsh	r1, [r0, r2]
	movs	r3, #14
	ldrsh	r2, [r0, r3]
	ldrb	r3, [r0, #10]
	ldr	r0, [r0, #0]
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	adds	r0, r4, #0
	bl sub_08003350
	add	sp, #8
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
@ GlyphAdvance_03B18 — span boundary: this label ends the sub_08003AF0 body.
	.type _08003B18, %function
_08003B18:
sub_08003B18:
	ldr r1, _08003B28
	lsls	r0, r0, #1
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	subs	r0, #1
	bx	lr
	movs	r0, r0
_08003B28: .4byte 0x080C49A0
.type _08003B2C, %function
_08003B2C:
	push	{r4, lr}
	movs	r1, #0
	adds	r3, r0, #1
	ldr r2, _08003B40
_08003B34:
	movs	r4, #0
	ldrsh	r0, [r2, r4]
	cmp	r0, r3
	bne _08003B44
	adds	r0, r1, #0
	b _08003B4E
_08003B40: .4byte 0x080C49A0
_08003B44:
	adds	r2, #2
	adds	r1, #1
	cmp	r1, #255
	ble _08003B34
	movs	r0, #0
_08003B4E:
	pop	{r4}
	pop	{r1}
	bx	r1
	.type sub_08003B54, %function
sub_08003B54:
_08003B54:
	push	{r4, r5, lr}
	sub	sp, #16
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r0, r2, #0
	mov	r1, sp
	bl sub_08003D4C
	adds	r0, r4, #0
	adds	r1, r5, #0
	mov	r2, sp
	bl sub_080038A4
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003B78, %function
sub_08003B78:
_08003B78:
	push	{r4, r5, lr}
	sub	sp, #16
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r0, r2, #0
	mov	r1, sp
	bl sub_08003D4C
	adds	r0, r4, #0
	adds	r1, r5, #0
	mov	r2, sp
	bl sub_08003838
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003B9C, %function
sub_08003B9C:
_08003B9C:
	push	{r4, r5, lr}
	sub	sp, #16
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r0, r2, #0
	mov	r1, sp
	bl sub_08003E34
	adds	r0, r4, #0
	adds	r1, r5, #0
	mov	r2, sp
	bl sub_08003838
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003BC0, %function
sub_08003BC0:
_08003BC0:
	push	{r4, r5, lr}
	sub	sp, #16
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r0, r2, #0
	mov	r1, sp
	bl sub_08003D4C
	adds	r0, r4, #0
	adds	r1, r5, #0
	mov	r2, sp
	bl sub_0800385C
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003BE4, %function
sub_08003BE4:
_08003BE4:
	push	{r4, r5, r6, lr}
	sub	sp, #16
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r0, r2, #0
	adds	r6, r3, #0
	mov	r1, sp
	bl sub_08003E34
	adds	r0, r4, #0
	adds	r1, r5, #0
	mov	r2, sp
	adds	r3, r6, #0
	bl sub_08003880
	add	sp, #16
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003C0C, %function
sub_08003C0C:
_08003C0C:
	push	{r4, r5, lr}
	sub	sp, #24
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r0, r2, #0
	add	r1, sp, #8
	bl sub_08003D18
	ldr r1, _08003C44
	ldr	r1, [r1, #8]
	muls	r1, r0
	subs	r4, r4, r1
	subs	r0, #15
	add	r1, sp, #8
	subs	r0, r1, r0
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #2
	adds	r1, r4, #0
	adds	r2, r5, #0
	movs	r3, #0
	bl sub_08003350
	add	sp, #24
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_08003C44: .4byte 0x080C4BA0
.type _08003C48, %function
_08003C48:
	push	{r4, lr}
	sub	sp, #24
	adds	r3, r0, #0
	adds	r4, r1, #0
	add	r0, sp, #8
	adds	r2, #48
	movs	r1, #0
	strb	r2, [r0, #0]
	strb	r1, [r0, #1]
	ldr r0, _08003C7C
	ldr	r0, [r0, #8]
	subs	r3, r3, r0
	add	r0, sp, #8
	str	r0, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	movs	r0, #2
	adds	r1, r3, #0
	adds	r2, r4, #0
	movs	r3, #0
	bl sub_08003350
	add	sp, #24
	pop	{r4}
	pop	{r0}
	bx	r0
_08003C7C: .4byte 0x080C4BA0
	.type sub_08003C80, %function
sub_08003C80:
_08003C80:
	push	{r4, lr}
	adds	r4, r0, #0
	adds	r3, r2, #0
	adds	r1, r1, r2
	movs	r0, #0
	strb	r0, [r1, #0]
	cmp	r3, #0
	beq _08003CAC
	movs	r2, #15
_08003C92:
	subs	r1, #1
	adds	r0, r4, #0
	ands	r0, r2
	cmp	r0, #9
	bgt _08003CA0
	adds	r0, #48
	b _08003CA2
_08003CA0:
	adds	r0, #65
_08003CA2:
	strb	r0, [r1, #0]
	lsrs	r4, r4, #4
	subs	r3, #1
	cmp	r3, #0
	bne _08003C92
_08003CAC:
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003CB4, %function
sub_08003CB4:
_08003CB4:
	push	{r4, r5, r6, r7, lr}
	adds	r3, r0, #0
	adds	r6, r2, #0
	movs	r7, #0
	adds	r4, r1, #0
	cmp	r3, #0
	bge _08003CCC
	movs	r0, #45
	strb	r0, [r4, #0]
	adds	r4, #1
	negs	r3, r3
	subs	r6, #1
_08003CCC:
	adds	r5, r3, #0
	cmp	r5, #9
	ble _08003CE4
_08003CD2:
	adds	r4, #1
	adds	r0, r3, #0
	movs	r1, #10
	bl 0x0802D978
	adds	r3, r0, #0
	subs	r6, #1
	cmp	r3, #9
	bgt _08003CD2
_08003CE4:
	cmp	r6, #0
	bgt _08003CEC
	movs	r0, #0
	b _08003D10
_08003CEC:
	movs	r0, #0
	strb	r0, [r4, #1]
_08003CF0:
	adds	r0, r5, #0
	movs	r1, #10
	bl 0x0802D97C
	adds	r0, #48
	strb	r0, [r4, #0]
	subs	r4, #1
	adds	r0, r5, #0
	movs	r1, #10
	bl 0x0802D978
	adds	r5, r0, #0
	adds	r7, #1
	cmp	r5, #0
	bgt _08003CF0
	adds	r0, r7, #0
_08003D10:
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_08003D18, %function
sub_08003D18:
_08003D18:
	push	{r4, r5, r6, lr}
	movs	r6, #0
	adds	r5, r1, #0
	adds	r5, #14
	strb	r6, [r1, #15]
	adds	r4, r0, #0
_08003D24:
	adds	r0, r4, #0
	movs	r1, #10
	bl 0x0802D97C
	adds	r0, #48
	strb	r0, [r5, #0]
	subs	r5, #1
	adds	r0, r4, #0
	movs	r1, #10
	bl 0x0802D978
	adds	r4, r0, #0
	adds	r6, #1
	cmp	r4, #0
	bgt _08003D24
	adds	r0, r6, #0
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_08003D4C, %function
sub_08003D4C:
_08003D4C:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	adds	r6, r0, #0
	adds	r7, r1, #0
	movs	r0, #128
	lsls	r0, r0, #24
	mov	r8, r0
	ands	r0, r6
	mov	r8, r0
	cmp	r0, #0
	beq _08003D90
	movs	r1, #45
	strb	r1, [r7, #0]
	adds	r7, #1
	strb	r1, [r7, #0]
	adds	r7, #1
	movs	r0, #39
	strb	r0, [r7, #0]
	adds	r7, #1
	strb	r1, [r7, #0]
	adds	r7, #1
	strb	r1, [r7, #0]
	adds	r7, #1
	movs	r0, #34
	strb	r0, [r7, #0]
	adds	r7, #1
	strb	r1, [r7, #0]
	adds	r7, #1
	strb	r1, [r7, #0]
	movs	r0, #0
	strb	r0, [r7, #1]
	b _08003E22
_08003D90:
	movs	r5, #150
	lsls	r5, r5, #1
	adds	r0, r6, #0
	adds	r1, r5, #0
	bl 0x0802D97C
	movs	r1, #3
	bl 0x0802D978
	mov	r9, r0
	ldr r4, _08003E30
	adds	r0, r6, #0
	adds	r1, r4, #0
	bl 0x0802D97C
	adds	r1, r5, #0
	bl 0x0802D978
	adds	r5, r0, #0
	adds	r0, r6, #0
	adds	r1, r4, #0
	bl 0x0802D978
	adds	r4, r0, #0
	movs	r1, #10
	bl 0x0802D978
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	adds	r0, r4, #0
	movs	r1, #10
	bl 0x0802D97C
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	movs	r0, #39
	strb	r0, [r7, #0]
	adds	r7, #1
	adds	r0, r5, #0
	movs	r1, #10
	bl 0x0802D978
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	adds	r0, r5, #0
	movs	r1, #10
	bl 0x0802D97C
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	movs	r0, #34
	strb	r0, [r7, #0]
	adds	r7, #1
	mov	r0, r9
	movs	r1, #10
	bl 0x0802D978
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	mov	r0, r9
	movs	r1, #10
	bl 0x0802D97C
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	mov	r0, r8
	strb	r0, [r7, #0]
_08003E22:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_08003E30: .4byte 0x00004650
	.type sub_08003E34, %function
sub_08003E34:
_08003E34:
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	adds	r6, r0, #0
	adds	r7, r1, #0
	movs	r0, #128
	lsls	r0, r0, #24
	mov	r8, r0
	ands	r0, r6
	mov	r8, r0
	cmp	r0, #0
	beq _08003E78
	movs	r1, #45
	strb	r1, [r7, #0]
	adds	r7, #1
	strb	r1, [r7, #0]
	adds	r7, #1
	movs	r0, #39
	strb	r0, [r7, #0]
	adds	r7, #1
	strb	r1, [r7, #0]
	adds	r7, #1
	strb	r1, [r7, #0]
	adds	r7, #1
	movs	r0, #34
	strb	r0, [r7, #0]
	adds	r7, #1
	strb	r1, [r7, #0]
	adds	r7, #1
	strb	r1, [r7, #0]
	movs	r0, #0
	strb	r0, [r7, #1]
	b _08003F08
_08003E78:
	movs	r5, #150
	lsls	r5, r5, #1
	adds	r0, r6, #0
	adds	r1, r5, #0
	bl 0x0802D97C
	movs	r1, #3
	bl 0x0802D978
	mov	r9, r0
	ldr r4, _08003F14
	adds	r0, r6, #0
	adds	r1, r4, #0
	bl 0x0802D97C
	adds	r1, r5, #0
	bl 0x0802D978
	adds	r5, r0, #0
	adds	r0, r6, #0
	adds	r1, r4, #0
	bl 0x0802D978
	adds	r4, r0, #0
	movs	r1, #10
	bl 0x0802D978
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	adds	r0, r4, #0
	movs	r1, #10
	bl 0x0802D97C
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	movs	r4, #36
	strb	r4, [r7, #0]
	adds	r7, #1
	adds	r0, r5, #0
	movs	r1, #10
	bl 0x0802D978
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	adds	r0, r5, #0
	movs	r1, #10
	bl 0x0802D97C
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	strb	r4, [r7, #0]
	adds	r7, #1
	mov	r0, r9
	movs	r1, #10
	bl 0x0802D978
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	mov	r0, r9
	movs	r1, #10
	bl 0x0802D97C
	adds	r0, #48
	strb	r0, [r7, #0]
	adds	r7, #1
	mov	r0, r8
	strb	r0, [r7, #0]
_08003F08:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_08003F14: .4byte 0x00004650
	.type sub_08003F18, %function
sub_08003F18:
_08003F18:
	push	{r4, r5, r6, lr}
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6}
	sub	sp, #16
	adds	r5, r0, #0
	mov	r9, r1
	mov	r8, r2
	adds	r6, r3, #0
	mov	r0, r8
	bl _08003148
	adds	r4, r0, #0
	adds	r0, r6, #0
	mov	r1, sp
	movs	r2, #16
	bl sub_08003CB4
	adds	r0, r5, #0
	mov	r1, r9
	mov	r2, r8
	bl sub_080038A4
	lsls	r4, r4, #3
	adds	r5, r5, r4
	adds	r0, r5, #0
	mov	r1, r9
	mov	r2, sp
	bl sub_080038A4
	add	sp, #16
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003F64, %function
sub_08003F64:
_08003F64:
	push	{r4, r5, lr}
	sub	sp, #16
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r0, r2, #0
	adds	r2, r3, #0
	mov	r1, sp
	bl sub_08003C80
	adds	r0, r4, #0
	adds	r1, r5, #0
	mov	r2, sp
	bl sub_080038A4
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.type sub_08003F88, %function
sub_08003F88:
_08003F88:
	push	{r4, r5, r6, lr}
	adds	r3, r0, #0
	adds	r5, r1, #0
	lsls	r2, r2, #24
	lsrs	r0, r2, #24
	ldr	r2, [r3, #0]
	ldr	r1, [r3, #12]
	cmp	r1, #0
	blt _08003FCC
	ldr	r4, [r3, #16]
	cmp	r0, #0
	beq _08003FA6
	movs	r6, #135
	lsls	r6, r6, #8
	b _08003FAA
_08003FA6:
	movs	r6, #131
	lsls	r6, r6, #8
_08003FAA:
	adds	r0, r6, #0
	ldrh	r6, [r3, #8]
	orrs	r0, r6
	strh	r0, [r2, #0]
	lsls	r0, r5, #9
	ldrh	r5, [r3, #4]
	orrs	r0, r5
	strh	r0, [r2, #2]
	lsls	r1, r1, #1
	ldrh	r6, [r4, #2]
	adds	r1, r6, r1
	ldr	r0, [r3, #20]
	ldrh	r4, [r4, #0]
	adds	r0, r4, r0
	lsls	r0, r0, #12
	orrs	r1, r0
	strh	r1, [r2, #4]
_08003FCC:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_08003FD4, %function
sub_08003FD4:
_08003FD4:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #44
	adds	r6, r1, #0
	mov	r8, r2
	mov	ip, r3
	ldr	r5, [sp, #76]
	ldr	r1, [sp, #88]
	lsls	r1, r1, #24
	lsrs	r1, r1, #24
	str	r1, [sp, #40]
	mov	r4, sp
	ldr r1, _0800407C
	ldmia	r1!, {r2, r3, r7}
	stmia	r4!, {r2, r3, r7}
	ldr	r1, [r1, #0]
	str	r1, [r4, #0]
	ldr r1, _08004080
	lsls	r0, r0, #2
	adds	r1, r0, r1
	ldr	r1, [r1, #0]
	mov	sl, r1
	mov	r2, sp
	adds	r1, r2, r0
	ldr	r1, [r1, #0]
	mov	r9, r1
	add	r4, sp, #16
	ldr r1, _08004084
	adds	r0, r0, r1
	str	r0, [r4, #16]
	mov	r3, r8
	str	r3, [r4, #8]
	mov	r7, ip
	str	r7, [r4, #20]
	ldrb	r0, [r5, #0]
	mov	r8, r4
	cmp	r0, #0
	beq _0800406C
	mov	r7, r8
_08004028:
	ldrb	r1, [r5, #0]
	lsls	r0, r1, #1
	ldr r2, _08004088
	adds	r0, r0, r2
	movs	r3, #0
	ldrsh	r1, [r0, r3]
	subs	r1, #1
	ldr r0, _0800408C
	ands	r0, r6
	str	r0, [r7, #4]
	str	r1, [r7, #12]
	cmp	r1, #0
	blt _08004062
	bl sub_08002BFC
	adds	r4, r0, #0
	add	r0, sp, #80
	ldrh	r0, [r0, #0]
	strh	r0, [r4, #12]
	str	r4, [sp, #16]
	mov	r0, r8
	ldr	r1, [sp, #84]
	ldr	r2, [sp, #40]
	bl 0x0802DDEC
	movs	r0, #0
	adds	r1, r4, #0
	bl _08002C34
_08004062:
	adds	r5, #1
	add	r6, sl
	ldrb	r0, [r5, #0]
	cmp	r0, #0
	bne _08004028
_0800406C:
	add	sp, #44
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
_0800407C: .4byte 0x0802E250
_08004080: .4byte 0x080C4BA0
_08004084: .4byte 0x03000160
_08004088: .4byte 0x080C49A0
_0800408C: .4byte 0x000001FF
	.type sub_08004090, %function
sub_08004090:
_08004090:
	push	{r4, r5, lr}
	sub	sp, #16
	adds	r4, r0, #0
	adds	r5, r1, #0
	ldr	r1, [sp, #28]
	lsls	r1, r1, #24
	lsrs	r1, r1, #24
	str	r2, [sp, #0]
	movs	r0, #1
	str	r0, [sp, #4]
	str	r3, [sp, #8]
	str	r1, [sp, #12]
	movs	r0, #3
	adds	r1, r4, #0
	adds	r2, r5, #0
	movs	r3, #0
	bl sub_08003FD4
	add	sp, #16
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_080040BC:
	ldr r0, _080040D4
	ldr	r1, [r0, #0]
	movs	r2, #0
	ldr	r0, [r0, #4]
	cmp	r2, r0
	bge _080040E0
	adds	r3, r0, #0
_080040CA:
	ldrh	r0, [r1, #2]
	cmp	r0, #0
	bne _080040D8
	adds	r0, r1, #0
	b _080040E2
_080040D4: .4byte 0x03000178
_080040D8:
	adds	r2, #1
	adds	r1, #16
	cmp	r2, r3
	blt _080040CA
_080040E0:
	movs	r0, #0
_080040E2:
	bx	lr
	.type sub_080040E4, %function
sub_080040E4:
_080040E4:
	push	{lr}
	ldr r2, _080040F4
	str	r0, [r2, #0]
	str	r1, [r2, #4]
	bl sub_080040F8
	pop	{r0}
	bx	r0
_080040F4: .4byte 0x03000178
	.type sub_080040F8, %function
sub_080040F8:
_080040F8:
	push	{lr}
	sub	sp, #4
	movs	r0, #0
	str	r0, [sp, #0]
	ldr r0, _08004120
	ldr	r1, [r0, #0]
	ldr	r2, [r0, #4]
	lsls	r2, r2, #2
	ldr r0, _08004124
	ands	r2, r0
	movs	r0, #160
	lsls	r0, r0, #19
	orrs	r2, r0
	mov	r0, sp
	bl 0x0802D974
	add	sp, #4
	pop	{r0}
	bx	r0
	movs	r0, r0
_08004120: .4byte 0x03000178
_08004124: .4byte 0x001FFFFF
.type _08004128, %function
_08004128:
	push	{r4, r5, r6, lr}
	lsls	r0, r0, #16
	lsrs	r4, r0, #16
	ldr r3, _0800415C
	ldr	r1, [r3, #0]
	movs	r2, #0
	ldr	r0, [r3, #4]
	cmp	r2, r0
	bge _08004154
	lsls	r0, r4, #16
	asrs	r4, r0, #16
	movs	r5, #0
_08004140:
	movs	r6, #0
	ldrsh	r0, [r1, r6]
	cmp	r0, r4
	bne _0800414A
	strh	r5, [r1, #2]
_0800414A:
	adds	r2, #1
	adds	r1, #16
	ldr	r0, [r3, #4]
	cmp	r2, r0
	blt _08004140
_08004154:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_0800415C: .4byte 0x03000178
.type _08004160, %function
_08004160:
	push	{r4, r5, r6, lr}
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r6, r2, #0
	lsls	r4, r4, #16
	lsrs	r4, r4, #16
	bl _080040BC
	movs	r1, #1
	strh	r1, [r0, #2]
	strh	r4, [r0, #0]
	str	r5, [r0, #4]
	str	r6, [r0, #8]
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	.type sub_08004180, %function
sub_08004180:
_08004180:
	push	{r4, r5, r6, lr}
	lsls	r0, r0, #16
	lsrs	r1, r0, #16
	ldr r0, _080041C0
	ldr	r4, [r0, #0]
	movs	r5, #0
	ldr	r0, [r0, #4]
	cmp	r5, r0
	bge _080041B8
	lsls	r0, r1, #16
	asrs	r6, r0, #16
_08004196:
	ldrh	r0, [r4, #2]
	cmp	r0, #0
	beq _080041AC
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	cmp	r0, r6
	bne _080041AC
	ldr	r0, [r4, #8]
	ldr	r1, [r4, #4]
	bl 0x0802DDCC
_080041AC:
	adds	r5, #1
	adds	r4, #16
	ldr r0, _080041C0
	ldr	r0, [r0, #4]
	cmp	r5, r0
	blt _08004196
_080041B8:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080041C0: .4byte 0x03000178
	ldr r2, _080041D0
	ldr	r1, [r2, #0]
	str	r1, [r0, #0]
	ldr	r1, [r2, #4]
	str	r1, [r0, #4]
	bx	lr
_080041D0: .4byte 0x0203F6B0
	ldr r0, _080041DC
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bx	lr
_080041DC: .4byte 0x0203F728
	.type sub_080041E0, %function
sub_080041E0:
_080041E0:
	push	{lr}
	movs	r2, #200
	muls	r0, r2
	bl 0x0802DE04
	adds	r1, r0, #0
	movs	r0, #120
	subs	r0, r0, r1
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	pop	{r1}
	bx	r1
	.type sub_080041F8, %function
sub_080041F8:
_080041F8:
	push	{r4, r5, lr}
	sub	sp, #8
	adds	r5, r2, #0
	ldr r3, _08004238
	ldr	r2, [r3, #0]
	subs	r0, r0, r2
	str	r0, [sp, #0]
	ldr	r0, [r3, #4]
	subs	r1, r1, r0
	str	r1, [sp, #4]
	ldr r0, _0800423C
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	mov	r0, sp
	bl 0x08005BA8
	ldr	r4, [sp, #4]
	cmp	r4, #0
	beq _08004240
	ldr	r1, [sp, #0]
	movs	r0, #200
	muls	r0, r1
	adds	r1, r4, #0
	bl 0x0802DE04
	movs	r1, #120
	subs	r1, r1, r0
	str	r1, [r5, #0]
	str	r4, [r5, #4]
	movs	r0, #1
	b _08004242
	movs	r0, r0
_08004238: .4byte 0x0203F6B0
_0800423C: .4byte 0x0203F728
_08004240:
	movs	r0, #0
_08004242:
	add	sp, #8
	pop	{r4, r5}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_0800424C, %function
sub_0800424C:
_0800424C:
	push	{lr}
	movs	r2, #200
	muls	r0, r2
	bl 0x0802DE04
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_08004260, %function
sub_08004260:
_08004260:
	push	{r4, r5, r6, lr}
	mov	r6, r8
	push	{r6}
	adds	r6, r0, #0
	mov	r8, r1
	ldr r4, _080042B4
	movs	r0, #20
	str	r0, [r4, #0]
	movs	r1, #32
	str	r1, [r4, #4]
	subs	r0, #40
	str	r0, [r4, #8]
	str	r1, [r4, #12]
	lsls	r5, r2, #16
	asrs	r5, r5, #16
	adds	r0, r4, #0
	adds	r1, r5, #0
	bl 0x08005BA8
	adds	r4, #8
	adds	r0, r4, #0
	adds	r1, r5, #0
	bl 0x08005BA8
	ldr r0, _080042B8
	str	r6, [r0, #0]
	mov	r1, r8
	str	r1, [r0, #4]
	ldr r2, _080042BC
	movs	r3, #128
	lsls	r3, r3, #4
	adds	r0, r3, #0
	subs	r0, r0, r5
	ldr r3, _080042C0
	adds	r1, r3, #0
	ands	r0, r1
	strh	r0, [r2, #0]
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
_080042B4: .4byte 0x0203F6C0
_080042B8: .4byte 0x0203F6B0
_080042BC: .4byte 0x0203F728
_080042C0: .4byte 0x00000FFF
	.type sub_080042C4, %function
sub_080042C4:
_080042C4:
	push	{r4, r5, r6, r7, lr}
	adds	r6, r1, #0
	adds	r4, r2, #0
	ldr r7, _08004314
	ldr	r1, [r7, #0]
	subs	r0, r0, r1
	str	r0, [r4, #0]
	bl 0x08005B5C
	movs	r5, #128
	lsls	r5, r5, #10
	cmp	r0, r5
	bgt _0800431C
_080042DE:
	ldr	r0, [r7, #4]
	subs	r0, r6, r0
	str	r0, [r4, #4]
	bl 0x08005B5C
	cmp	r0, r5
	bgt _0800431C
	ldr r3, _08004318
	ldr	r0, [r3, #0]
	ldr	r5, [r4, #4]
	adds	r1, r0, #0
	muls	r1, r5
	ldr	r0, [r3, #4]
	ldr	r2, [r4, #0]
	muls	r0, r2
	subs	r1, r1, r0
	cmp	r1, #0
	bgt _0800431C
	ldr	r0, [r3, #8]
	muls	r0, r5
	ldr	r1, [r3, #12]
	muls	r1, r2
	subs	r0, r0, r1
	cmp	r0, #0
	blt _0800431C
	movs	r0, #1
	b _0800431E
_08004314: .4byte 0x0203F6B0
_08004318: .4byte 0x0203F6C0
_0800431C:
	movs	r0, #0
_0800431E:
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	.type sub_08004324, %function
sub_08004324:
_08004324:
	ldr r1, _0800432C
	str	r0, [r1, #0]
	bx	lr
	movs	r0, r0
_0800432C: .4byte 0x03000180
	.type sub_08004330, %function
sub_08004330:
_08004330:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #8
	adds	r7, r0, #0
	ldr	r0, [r7, #4]
	ldr	r1, [r7, #8]
	mov	r2, sp
	bl sub_080042C4
	lsls	r0, r0, #24
	cmp	r0, #0
	beq _080043AC
	ldr r0, _08004398
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	mov	r0, sp
	bl 0x08005BA8
	ldr	r6, [sp, #4]
	ldr r0, _0800439C
	adds	r1, r6, r0
	ldr r0, _080043A0
	cmp	r1, r0
	bhi _080043AC
	asrs	r5, r6, #8
	str	r5, [r7, #44]
	lsls	r5, r5, #3
	ldr r0, _080043A4
_08004366:
	adds	r5, r5, r0
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	movs	r4, #120
	subs	r4, r4, r0
	ldr	r1, [sp, #0]
	movs	r0, #200
	muls	r0, r1
	adds	r1, r6, #0
	bl 0x0802DE04
	subs	r4, r4, r0
	str	r4, [r7, #36]
	ldr r0, _080043A8
	adds	r1, r6, #0
	bl 0x0802DE04
	movs	r2, #2
	ldrsh	r1, [r5, r2]
	subs	r1, #48
	subs	r0, r0, r1
	str	r0, [r7, #40]
	str	r5, [r7, #60]
	movs	r0, #1
	b _080043AE
_08004398: .4byte 0x0203F728
_0800439C: .4byte 0xFFFFDD9F
_080043A0: .4byte 0x0001549E
_080043A4: .4byte 0x08032260
_080043A8: .4byte 0x000ED800
_080043AC:
	movs	r0, #0
_080043AE:
	add	sp, #8
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_080043B8, %function
sub_080043B8:
_080043B8:
	push	{r4, r5, r6, lr}
	sub	sp, #8
	adds	r6, r0, #0
	ldr	r0, [r6, #4]
	ldr	r1, [r6, #8]
	mov	r2, sp
	bl sub_080042C4
	lsls	r0, r0, #24
	cmp	r0, #0
	beq _08004434
	ldr r0, _08004420
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	mov	r0, sp
	bl 0x08005BA8
	ldr	r5, [sp, #4]
	ldr r0, _08004424
	adds	r1, r5, r0
	ldr r0, _08004428
	cmp	r1, r0
	bhi _08004434
	asrs	r0, r5, #6
	str	r0, [r6, #44]
_080043EA:
	asrs	r0, r5, #8
	lsls	r4, r0, #1
	adds	r4, r4, r0
	lsls	r4, r4, #2
	ldr r0, _0800442C
	adds	r4, r4, r0
	ldr	r1, [sp, #0]
	movs	r0, #200
	muls	r0, r1
	adds	r1, r5, #0
	bl 0x0802DE04
	movs	r1, #120
	subs	r1, r1, r0
	str	r1, [r6, #36]
	ldr r0, _08004430
	adds	r1, r5, #0
	bl 0x0802DE04
	movs	r2, #4
	ldrsh	r1, [r4, r2]
	subs	r1, #48
	subs	r0, r0, r1
	str	r0, [r6, #40]
	str	r4, [r6, #60]
	movs	r0, #1
	b _08004436
_08004420: .4byte 0x0203F728
_08004424: .4byte 0xFFFFDD9F
_08004428: .4byte 0x0001549E
_0800442C: .4byte 0x0802E260
_08004430: .4byte 0x000ED800
_08004434:
	movs	r0, #0
_08004436:
	add	sp, #8
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_08004440, %function
sub_08004440:
_08004440:
	push	{r4, r5, r6, lr}
	sub	sp, #8
	adds	r6, r0, #0
	ldr	r0, [r6, #4]
	ldr	r1, [r6, #8]
	mov	r2, sp
	bl sub_080042C4
	@ 0x08004450 is an interior continuation, distinct from the 4-byte leaf
	@ at 0x08004324 called by race_scene_a2.c. Preserve their separate labels.
	@
	@ This address is NOT typed as a function: the `lsls r0, r0, #24` below
	@ follows `bl sub_080042C4` inside a larger body, so 0x08004450 is a
	@ continuation point rather than an entry. Typing it would make it a false
	@ start, truncate the enclosing function's span, and then demand a C candidate
	@ from the self-test. A plain label names the address without claiming a
	@ boundary.
_08004450:
	lsls	r0, r0, #24
	cmp	r0, #0
	beq _080044B8
	ldr r0, _080044A4
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	mov	r0, sp
	bl 0x08005BA8
	ldr	r5, [sp, #4]
	ldr r0, _080044A8
	adds	r1, r5, r0
	ldr r0, _080044AC
	cmp	r1, r0
	bhi _080044B8
	asrs	r0, r5, #6
	str	r0, [r6, #44]
	asrs	r4, r5, #8
	lsls	r4, r4, #3
	ldr r0, _080044B0
	adds	r4, r4, r0
	ldr	r1, [sp, #0]
	movs	r0, #200
	muls	r0, r1
	adds	r1, r5, #0
	bl 0x0802DE04
	movs	r1, #120
	subs	r1, r1, r0
	str	r1, [r6, #36]
	ldr r0, _080044B4
	adds	r1, r5, #0
	bl 0x0802DE04
	movs	r2, #2
	ldrsh	r1, [r4, r2]
	subs	r1, #48
	subs	r0, r0, r1
	str	r0, [r6, #40]
	str	r4, [r6, #60]
	movs	r0, #1
	b _080044BA
_080044A4: .4byte 0x0203F728
_080044A8: .4byte 0xFFFFDD9F
_080044AC: .4byte 0x0001549E
_080044B0: .4byte 0x0802FA60
_080044B4: .4byte 0x000ED800
_080044B8:
	movs	r0, #0
_080044BA:
	add	sp, #8
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_080044C4, %function
sub_080044C4:
_080044C4:
	push	{r4, lr}
	adds	r4, r2, #0
	bl sub_080042C4
	lsls	r0, r0, #24
	lsrs	r0, r0, #24
	cmp	r0, #0
	beq _080044FC
	ldr r0, _080044F0
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	adds	r0, r4, #0
	bl 0x08005BA8
	ldr	r0, [r4, #4]
	ldr r1, _080044F4
	adds	r0, r0, r1
	ldr r1, _080044F8
	cmp	r0, r1
	bhi _08004500
	movs	r0, #1
	b _08004502
_080044F0: .4byte 0x0203F728
_080044F4: .4byte 0xFFFFEBAF
_080044F8: .4byte 0x0001EBAE
_080044FC:
	str	r0, [r4, #0]
	str	r0, [r4, #4]
_08004500:
	movs	r0, #0
_08004502:
	pop	{r4}
	pop	{r1}
	bx	r1
	.type sub_08004508, %function
sub_08004508:
_08004508:
	push	{r4, r5, r6, lr}
	adds	r5, r0, #0
	ldr	r6, [r5, #4]
	asrs	r0, r6, #8
	lsls	r4, r0, #1
	adds	r4, r4, r0
	lsls	r4, r4, #2
	ldr r0, _08004558
	adds	r4, r4, r0
	movs	r1, #6
	ldrsh	r0, [r4, r1]
	str	r0, [r5, #16]
_08004520:
	movs	r0, #32
	str	r0, [r5, #12]
	asrs	r0, r6, #6
	str	r0, [r5, #8]
	ldr	r1, [r5, #0]
	movs	r0, #200
	muls	r0, r1
	adds	r1, r6, #0
	bl 0x0802DE04
	movs	r1, #120
	subs	r1, r1, r0
	str	r1, [r5, #0]
	ldr r0, _0800455C
	adds	r1, r6, #0
	bl 0x0802DE04
	movs	r2, #4
	ldrsh	r1, [r4, r2]
	subs	r1, #48
	subs	r0, r0, r1
	str	r0, [r5, #4]
	str	r4, [r5, #44]
	movs	r0, #1
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
_08004558: .4byte 0x08030A60
_0800455C: .4byte 0x000ED800
	.type _08004560, %function
_08004560:
	bx	lr
	movs	r0, r0
	.type sub_08004564, %function
sub_08004564:
_08004564:
	push	{r4, r5, lr}
	ldr r0, _080045B0
	ldr	r0, [r0, #0]
	ldr	r5, [r0, #0]
	ldr	r4, [r0, #4]
	ldrh	r2, [r0, #8]
	lsls	r1, r2, #20
	lsrs	r1, r1, #23
	ldr	r0, [r0, #12]
	movs	r3, #208
	lsls	r3, r3, #2
	adds	r2, r0, r3
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #4
	adds	r0, r0, r1
	lsls	r0, r0, #4
	ldr r1, _080045B4
	adds	r1, r0, r1
	movs	r3, #107
_0800458C:
	ldr	r0, [r1, #0]
	adds	r0, r5, r0
	str	r0, [r2, #8]
	ldr	r0, [r1, #4]
	subs	r0, r4, r0
	str	r0, [r2, #12]
	ldrh	r0, [r1, #8]
	strh	r0, [r2, #0]
	ldrh	r0, [r1, #10]
	strh	r0, [r2, #4]
	adds	r2, #16
	adds	r1, #12
	subs	r3, #1
	cmp	r3, #0
	bge _0800458C
	pop	{r4, r5}
	pop	{r0}
	bx	r0
_080045B0: .4byte 0x03000180
_080045B4: .4byte 0x08033260
	.type sub_080045B8, %function
sub_080045B8:
_080045B8:
	push	{r4, r5, r6, lr}
	ldr r0, _08004608
	ldr	r0, [r0, #0]
	ldr	r5, [r0, #0]
	ldr	r4, [r0, #4]
	ldrh	r2, [r0, #8]
	lsls	r1, r2, #20
	lsrs	r1, r1, #23
	subs	r1, #128
	ldr	r0, [r0, #12]
	movs	r3, #208
	lsls	r3, r3, #2
	adds	r2, r0, r3
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #4
	adds	r0, r0, r1
	lsls	r0, r0, #4
	ldr r1, _0800460C
	adds	r1, r0, r1
	movs	r3, #107
_080045E2:
	ldr	r0, [r1, #4]
	adds	r0, r5, r0
	str	r0, [r2, #8]
	ldr	r0, [r1, #0]
	adds	r0, r4, r0
	str	r0, [r2, #12]
	ldrh	r6, [r1, #10]
	negs	r0, r6
	strh	r0, [r2, #0]
	ldrh	r0, [r1, #8]
	strh	r0, [r2, #4]
	adds	r2, #16
	adds	r1, #12
	subs	r3, #1
	cmp	r3, #0
	bge _080045E2
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
_08004608: .4byte 0x03000180
_0800460C: .4byte 0x08033260
	.type sub_08004610, %function
sub_08004610:
_08004610:
	push	{r4, r5, r6, lr}
	ldr r0, _08004664
	ldr	r0, [r0, #0]
	ldr	r5, [r0, #0]
	ldr	r4, [r0, #4]
	ldrh	r2, [r0, #8]
	lsls	r1, r2, #20
	lsrs	r1, r1, #23
	ldr r3, _08004668
	adds	r1, r1, r3
	ldr	r0, [r0, #12]
	movs	r6, #208
	lsls	r6, r6, #2
	adds	r2, r0, r6
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #4
	adds	r0, r0, r1
	lsls	r0, r0, #4
	ldr r1, _0800466C
	adds	r1, r0, r1
	movs	r3, #107
_0800463C:
	ldr	r0, [r1, #0]
	subs	r0, r5, r0
	str	r0, [r2, #8]
	ldr	r0, [r1, #4]
	adds	r0, r4, r0
	str	r0, [r2, #12]
	ldrh	r6, [r1, #8]
	negs	r0, r6
	strh	r0, [r2, #0]
	ldrh	r6, [r1, #10]
	negs	r0, r6
	strh	r0, [r2, #4]
	adds	r2, #16
	adds	r1, #12
	subs	r3, #1
	cmp	r3, #0
	bge _0800463C
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
_08004664: .4byte 0x03000180
_08004668: .4byte 0xFFFFFF00
_0800466C: .4byte 0x08033260
	.type sub_08004670, %function
sub_08004670:
_08004670:
	push	{r4, r5, r6, lr}
	ldr r0, _080046C4
	ldr	r0, [r0, #0]
	ldr	r5, [r0, #0]
	ldr	r4, [r0, #4]
	ldrh	r2, [r0, #8]
	lsls	r1, r2, #20
	lsrs	r1, r1, #23
	ldr r3, _080046C8
	adds	r1, r1, r3
	ldr	r0, [r0, #12]
	movs	r6, #208
	lsls	r6, r6, #2
	adds	r2, r0, r6
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #4
	adds	r0, r0, r1
	lsls	r0, r0, #4
	ldr r1, _080046CC
	adds	r1, r0, r1
	movs	r3, #107
_0800469C:
	ldr	r0, [r1, #4]
	subs	r0, r5, r0
	str	r0, [r2, #8]
	ldr	r0, [r1, #0]
	subs	r0, r4, r0
	str	r0, [r2, #12]
	ldrh	r0, [r1, #10]
	strh	r0, [r2, #0]
	ldrh	r6, [r1, #8]
	negs	r0, r6
	strh	r0, [r2, #4]
	adds	r2, #16
	adds	r1, #12
	subs	r3, #1
	cmp	r3, #0
	bge _0800469C
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080046C4: .4byte 0x03000180
_080046C8: .4byte 0xFFFFFE80
_080046CC: .4byte 0x08033260
.type sub_080046D0, %function
sub_080046D0:
_080046D0:
	push	{lr}
	ldr r0, _080046F4
	ldr	r1, [r0, #0]
	movs	r0, #52
	strh	r0, [r1, #10]
	ldrh	r1, [r1, #8]
	lsls	r0, r1, #16
	asrs	r1, r0, #26
	movs	r0, #3
	ands	r1, r0
	cmp	r1, #1
	beq _08004708
	cmp	r1, #1
	bgt _080046F8
	cmp	r1, #0
	beq _08004702
	b _08004718
	movs	r0, r0
_080046F4: .4byte 0x03000180
_080046F8:
	cmp	r1, #2
	beq _0800470E
	cmp	r1, #3
	beq _08004714
	b _08004718
_08004702:
	bl sub_08004564
	b _08004718
_08004708:
	bl sub_080045B8
	b _08004718
_0800470E:
	bl sub_08004610
	b _08004718
_08004714:
	bl sub_08004670
_08004718:
	ldr r3, _08004734
	ldr r1, _08004738
	movs	r2, #0
	adds	r0, r1, #0
	adds	r0, #34
_08004722:
	strh	r2, [r0, #0]
	subs	r0, #2
	cmp	r0, r1
	bge _08004722
	movs	r0, #0
	strh	r0, [r3, #0]
	pop	{r0}
	bx	r0
	movs	r0, r0
_08004734: .4byte 0x0203F724
_08004738: .4byte 0x0203F700
	.type sub_0800473C, %function
sub_0800473C:
_0800473C:
	ldr r1, _08004744
	str	r0, [r1, #12]
	bx	lr
	movs	r0, r0
_08004744: .4byte 0x03000188
	.type sub_08004748, %function
sub_08004748:
_08004748:
	ldr r3, _08004754
	str	r0, [r3, #0]
	str	r1, [r3, #4]
	strh	r2, [r3, #8]
	bx	lr
	movs	r0, r0
_08004754: .4byte 0x03000188
.type _08004758, %function
_08004758:
	push	{r4, r5, r6, lr}
	sub	sp, #8
	adds	r5, r0, #0
	ldr r4, _080047F8
	ldr	r0, [r5, #4]
	ldr	r1, [r4, #0]
	subs	r0, r0, r1
	str	r0, [sp, #0]
	bl 0x08005B5C
	movs	r6, #192
	lsls	r6, r6, #9
	cmp	r0, r6
	bgt _0800480C
	ldr	r0, [r5, #8]
	ldr	r1, [r4, #4]
	subs	r0, r0, r1
	str	r0, [sp, #4]
	bl 0x08005B5C
	cmp	r0, r6
	bgt _0800480C
	movs	r0, #128
	lsls	r0, r0, #4
	adds	r1, r0, #0
	ldrh	r4, [r4, #8]
	subs	r1, r1, r4
	ldr r2, _080047FC
	adds	r0, r2, #0
	ands	r1, r0
	mov	r0, sp
	bl 0x08005BA8
	ldr	r6, [sp, #4]
	ldr r3, _08004800
	adds	r1, r6, r3
	ldr r0, _08004804
	cmp	r1, r0
	bhi _0800480C
	lsls	r3, r6, #3
	ldr	r2, [sp, #0]
	lsls	r0, r2, #3
	subs	r1, r0, r2
	subs	r0, r3, r1
	cmp	r0, #0
	blt _0800480C
	negs	r0, r3
	subs	r0, r0, r1
	cmp	r0, #0
	bgt _0800480C
	asrs	r1, r6, #8
	lsls	r4, r1, #1
	adds	r4, r4, r1
	lsls	r4, r4, #1
	ldr r0, _08004808
	adds	r4, r4, r0
	ldrh	r0, [r4, #0]
	strh	r0, [r5, #54]
	adds	r4, #2
	movs	r3, #0
	ldrsh	r0, [r4, r3]
	str	r0, [r5, #48]
	adds	r4, #2
	str	r1, [r5, #44]
	lsls	r1, r2, #1
	adds	r1, r1, r2
	lsls	r0, r1, #4
	subs	r0, r0, r1
	lsls	r0, r0, #2
	negs	r0, r0
	adds	r1, r6, #0
	bl 0x0802DE04
	adds	r0, #120
	str	r0, [r5, #36]
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	str	r0, [r5, #40]
	movs	r0, #1
	b _0800480E
_080047F8: .4byte 0x03000188
_080047FC: .4byte 0x00000FFF
_08004800: .4byte 0xFFFFE890
_08004804: .4byte 0x00015BA8
_08004808: .4byte 0x080C53E4
_0800480C:
	movs	r0, #0
_0800480E:
	add	sp, #8
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_08004818, %function
sub_08004818:
_08004818:
	push	{r4, r5, r6, lr}
	sub	sp, #8
	adds	r5, r0, #0
	ldr r4, _080048B8
	ldr	r0, [r5, #0]
	ldr	r1, [r4, #0]
	subs	r0, r0, r1
	str	r0, [sp, #0]
	bl 0x08005B5C
	movs	r6, #192
	lsls	r6, r6, #9
	cmp	r0, r6
	bgt _080048CC
	ldr	r0, [r5, #4]
	ldr	r1, [r4, #4]
	subs	r0, r0, r1
	str	r0, [sp, #4]
	bl 0x08005B5C
	cmp	r0, r6
	bgt _080048CC
	movs	r0, #128
	lsls	r0, r0, #4
	adds	r1, r0, #0
	ldrh	r4, [r4, #8]
	subs	r1, r1, r4
	ldr r2, _080048BC
	adds	r0, r2, #0
	ands	r1, r0
	mov	r0, sp
	bl 0x08005BA8
	ldr	r2, [sp, #4]
	ldr r3, _080048C0
	adds	r1, r2, r3
	ldr r0, _080048C4
	cmp	r1, r0
	bhi _080048CC
	ldr	r1, [sp, #0]
	subs	r0, r2, r1
	cmp	r0, #0
	blt _080048CC
	negs	r0, r2
	subs	r0, r0, r1
	cmp	r0, #0
	bgt _080048CC
	asrs	r1, r2, #6
	lsls	r4, r1, #1
	adds	r4, r4, r1
	lsls	r4, r4, #1
	ldr r0, _080048C8
	adds	r4, r4, r0
	ldr	r5, [r5, #8]
	movs	r3, #0
	ldrsh	r0, [r4, r3]
	str	r0, [r5, #16]
	adds	r4, #2
	movs	r3, #0
	ldrsh	r0, [r4, r3]
	str	r0, [r5, #12]
	adds	r4, #2
	str	r1, [r5, #8]
	ldr	r0, [sp, #0]
	lsls	r1, r0, #1
	adds	r1, r1, r0
	lsls	r0, r1, #4
	subs	r0, r0, r1
	lsls	r0, r0, #2
	negs	r0, r0
	adds	r1, r2, #0
	bl 0x0802DE04
	adds	r0, #120
	str	r0, [r5, #0]
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	str	r0, [r5, #4]
	movs	r0, #1
	b _080048CE
_080048B8: .4byte 0x03000188
_080048BC: .4byte 0x00000FFF
_080048C0: .4byte 0xFFFFF448
_080048C4: .4byte 0x0000DEA8
_080048C8: .4byte 0x080C5FE4
_080048CC:
	movs	r0, #0
_080048CE:
	add	sp, #8
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_080048D8, %function
sub_080048D8:
_080048D8:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #8
	ldr r4, _080049A0
	movs	r1, #8
	ldrsh	r0, [r4, r1]
	bl sub_08005F44
	adds	r7, r0, #0
_080048F0:
	movs	r1, #8
	ldrsh	r0, [r4, r1]
	bl sub_08005F2C
	adds	r6, r0, #0
	ldr r0, _080049A4
	mov	ip, r0
	ldr	r0, [r4, #12]
	movs	r1, #128
	lsls	r1, r1, #3
	adds	r5, r0, r1
	ldr	r0, [r4, #0]
	mov	r9, r0
	ldr	r4, [r4, #4]
	mov	r8, r4
	add	r1, sp, #4
	mov	sl, r1
	movs	r4, #95
_08004914:
	mov	r0, ip
	ldmia	r0!, {r3}
	adds	r0, #4
	mov	ip, r0
	subs	r0, #4
	ldmia	r0!, {r2}
	adds	r0, r2, #0
	muls	r0, r6
	adds	r1, r3, #0
	muls	r1, r7
	subs	r0, r0, r1
	asrs	r0, r0, #12
	add	r0, r9
	str	r0, [r5, #8]
	adds	r0, r3, #0
	muls	r0, r6
	adds	r1, r2, #0
	muls	r1, r7
	adds	r0, r0, r1
	asrs	r0, r0, #12
	mov	r1, r8
	subs	r0, r1, r0
	str	r0, [r5, #12]
	mov	r0, ip
	adds	r0, #4
	mov	ip, r0
	subs	r0, #4
	ldmia	r0!, {r3}
	adds	r0, r3, #0
	muls	r0, r7
	asrs	r0, r0, #19
	strh	r0, [r5, #0]
	adds	r0, r3, #0
	muls	r0, r6
	asrs	r0, r0, #19
	strh	r0, [r5, #4]
	subs	r4, #1
	adds	r5, #16
	cmp	r4, #0
	bge _08004914
	movs	r5, #0
	str	r5, [sp, #0]
	ldr r4, _080049A0
	ldr	r1, [r4, #12]
	movs	r0, #159
	lsls	r0, r0, #4
	adds	r1, r1, r0
	ldr r6, _080049A8
	mov	r0, sp
	adds	r2, r6, #0
	bl 0x0802D974
	str	r5, [sp, #4]
	ldr	r1, [r4, #12]
	movs	r0, #128
	lsls	r0, r0, #3
	adds	r1, r1, r0
	mov	r0, sl
	adds	r2, r6, #0
	bl 0x0802D974
	add	sp, #8
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
_080049A0: .4byte 0x03000188
_080049A4: .4byte 0x080C4F64
_080049A8: .4byte 0x05000004
.type _080049AC, %function
_080049AC:
	push	{r4, r5, r6, r7, lr}
	sub	sp, #4
	adds	r4, r0, #0
	ldr r0, _080049F8
	adds	r6, r0, #0
	adds	r6, #136
	ldr	r7, [r6, #0]
	cmp	r4, #0
	beq _08004A00
	adds	r5, r0, #0
	adds	r5, #144
	ldr	r1, [r5, #0]
	cmp	r4, r1
	bls _080049D0
	ldr r0, _080049FC
	subs	r1, r4, r1
	bl 0x0800295C
_080049D0:
	ldr	r0, [r6, #0]
	adds	r0, r0, r4
	str	r0, [r6, #0]
	ldr	r0, [r5, #0]
	subs	r0, r0, r4
	str	r0, [r5, #0]
	movs	r0, #0
	str	r0, [sp, #0]
	lsls	r2, r4, #9
	lsrs	r2, r2, #11
	movs	r0, #160
	lsls	r0, r0, #19
	orrs	r2, r0
	mov	r0, sp
	adds	r1, r7, #0
	bl 0x0802D974
	adds	r0, r7, #0
	b _08004A02
	movs	r0, r0
_080049F8: .4byte 0x03000198
_080049FC: .4byte 0x0805BA60
_08004A00:
	movs	r0, #0
_08004A02:
	add	sp, #4
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.type sub_08004A0C, %function
sub_08004A0C:
_08004A0C:
	ldr r2, _08004A28
	adds	r1, r2, #0
	adds	r1, #136
	adds	r0, r2, #0
	adds	r0, #132
	ldr	r0, [r0, #0]
	str	r0, [r1, #0]
	adds	r1, #8
	adds	r0, r2, #0
	adds	r0, #140
	ldr	r0, [r0, #0]
	str	r0, [r1, #0]
	bx	lr
	movs	r0, r0
_08004A28: .4byte 0x03000198

@ Unique end marker so the body owned by this file can be C-owned.
@ Emits no bytes.
runtime_2aac_end:
