@ GT Advance 3 - Unsigned divmod core 0x0802DFE4–0x0802E0A4 (EABI-style, quotient r2 / remainder r0)
@ Region: file offset 0x02DFE4-0x02E0A4 (VMA 0x0802DFE4-0x0802E0A4).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

@ sub_0802DFE4: unsigned divmod core — 6 callers (idle 0x080019F0,
@ menu 0x0800BF20/0xBF32, garage 0x08027BBE/0x7C50/0x7CB2). No push
@ prologue; div-by-zero -> bl sub_0802DE98 (zero-divisor leaf) -> r0=0.
	.type sub_0802DFE4, %function
sub_0802DFE4:
_0802DFE4:
	cmp	r1, #0
	beq _08002E09A
	movs	r3, #1
	cmp	r0, r1
	bcs _08002DFF0
	mov	pc, lr
_08002DFF0:
	push	{r4}
	movs	r4, #1
	lsls	r4, r4, #28
_08002DFF6:
	cmp	r1, r4
	bcs _08002E004
	cmp	r1, r0
	bcs _08002E004
	lsls	r1, r1, #4
	lsls	r3, r3, #4
	b _08002DFF6
_08002E004:
	lsls	r4, r4, #3
_08002E006:
	cmp	r1, r4
	bcs _08002E014
	cmp	r1, r0
	bcs _08002E014
	lsls	r1, r1, #1
	lsls	r3, r3, #1
	b _08002E006
_08002E014:
	movs	r2, #0
	cmp	r0, r1
	bcc _08002E01C
	subs	r0, r0, r1
_08002E01C:
	lsrs	r4, r1, #1
	cmp	r0, r4
	bcc _08002E02E
	subs	r0, r0, r4
	mov	ip, r3
	movs	r4, #1
	rors	r3, r4
	orrs	r2, r3
	mov	r3, ip
_08002E02E:
	lsrs	r4, r1, #2
	cmp	r0, r4
	bcc _08002E040
	subs	r0, r0, r4
	mov	ip, r3
	movs	r4, #2
	rors	r3, r4
	orrs	r2, r3
	mov	r3, ip
_08002E040:
	lsrs	r4, r1, #3
	cmp	r0, r4
	bcc _08002E052
	subs	r0, r0, r4
	mov	ip, r3
	movs	r4, #3
	rors	r3, r4
	orrs	r2, r3
	mov	r3, ip
_08002E052:
	mov	ip, r3
	cmp	r0, #0
	beq _08002E060
	lsrs	r3, r3, #4
	beq _08002E060
	lsrs	r1, r1, #4
	b _08002E014
_08002E060:
	movs	r4, #14
	lsls	r4, r4, #28
	ands	r2, r4
	bne _08002E06C
	pop	{r4}
	mov	pc, lr
_08002E06C:
	mov	r3, ip
	movs	r4, #3
	rors	r3, r4
	tst	r2, r3
	beq _08002E07A
	lsrs	r4, r1, #3
	adds	r0, r0, r4
_08002E07A:
	mov	r3, ip
	movs	r4, #2
	rors	r3, r4
	tst	r2, r3
	beq _08002E088
	lsrs	r4, r1, #2
	adds	r0, r0, r4
_08002E088:
	mov	r3, ip
	movs	r4, #1
	rors	r3, r4
	tst	r2, r3
	beq _08002E096
	lsrs	r4, r1, #1
	adds	r0, r0, r4
_08002E096:
	pop	{r4}
	mov	pc, lr
_08002E09A:
	push	{lr}
	bl sub_0802DE98
	movs	r0, #0
	pop	{pc}
