@ GT Advance 3 - Pre-mixer sound leaves 0x0802B7B4–0x0802B888 (before the mixed-ISA mixer veneer)
@ Region: file offset 0x02B7B4-0x02B888 (VMA 0x0802B7B4-0x0802B888).
@ Pure Thumb, ARMCC. Generated by tools/objdump2gas.py from an objdump listing of
@ baserom.gba; byte-exact (make SHA gate). Unconverted targets keep numeric
@ `bl 0x0800XXXX` form. Pools at original offsets.

@ sub_08002B7B4: accessor returning u32 [*(r0)+8] (4 callers inside the
@ 0x26F50 garage span: 0x08028EC2/0x8F66/0x9002/0x9066).
	.type sub_08002B7B4, %function
sub_08002B7B4:
_08002B7B4:
	ldr	r0, [r0, #8]
	bx	lr
	.type sub_08002B7B8, %function
sub_08002B7B8:
_08002B7B8:
	push	{r4, lr}
	ldr	r3, [r0, #8]
	ldr	r2, [r1, #0]
	lsls	r2, r2, #13
	movs	r4, #128
	lsls	r4, r4, #10
	adds	r2, r2, r4
	str	r2, [r3, #0]
	movs	r2, #192
	lsls	r2, r2, #9
	str	r2, [r3, #4]
	ldr	r1, [r1, #0]
	str	r1, [r3, #12]
	pop	{r4}
	pop	{r1}
	bx	r1
	.type sub_08002B7D8, %function
sub_08002B7D8:
_08002B7D8:
	bx	lr
	movs	r0, r0
	.type sub_08002B7DC, %function
sub_08002B7DC:
_08002B7DC:
	bx	lr
	movs	r0, r0
	.type sub_08002B7E0, %function
sub_08002B7E0:
_08002B7E0:
	push	{r4, lr}
	adds	r4, r2, #0
	adds	r2, r3, #0
	cmp	r0, #5
	beq _08002B7F0
	cmp	r0, #6
	beq _08002B7F8
	b _08002B804
_08002B7F0:
	adds	r0, r2, #0
	bl sub_08002B7D8
	b _08002B804
_08002B7F8:
	lsls	r0, r1, #16
	lsrs	r0, r0, #16
	lsls	r1, r4, #16
	lsrs	r1, r1, #16
	bl sub_08002B7DC
_08002B804:
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.type sub_0802B80C, %function
sub_0802B80C:
_0802B80C:
	ldr	r0, [r0, #8]
	str	r1, [r0, #0]
	str	r2, [r0, #4]
	str	r3, [r0, #8]
	bx	lr
	movs	r0, r0
	.type sub_08002B818, %function
sub_08002B818:
_08002B818:
	push	{r4, lr}
	sub	sp, #8
	lsls	r1, r1, #16
	lsrs	r2, r1, #16
	ldr	r4, [r0, #8]
	movs	r0, #1
	ands	r0, r2
	cmp	r0, #0
	beq _08002B83C
	ldr	r0, [r4, #16]
	adds	r0, #16
	str	r0, [r4, #16]
	movs	r1, #200
	lsls	r1, r1, #3
	cmp	r0, r1
	ble _08002B846
	str	r1, [r4, #16]
	b _08002B846
_08002B83C:
	ldr	r0, [r4, #16]
	lsrs	r1, r0, #31
	adds	r0, r0, r1
	asrs	r0, r0, #1
	str	r0, [r4, #16]
_08002B846:
	movs	r0, #32
	ands	r0, r2
	cmp	r0, #0
	beq _08002B854
	ldr	r0, [r4, #8]
	subs	r0, #32
	str	r0, [r4, #8]
_08002B854:
	movs	r0, #16
	ands	r0, r2
	cmp	r0, #0
	beq _08002B862
	ldr	r0, [r4, #8]
	adds	r0, #32
	str	r0, [r4, #8]
_08002B862:
	ldr	r1, [r4, #16]
	movs	r0, #8
	ldrsh	r2, [r4, r0]
	mov	r0, sp
	bl 0x08005D74
	ldr	r0, [r4, #0]
	ldr	r1, [sp, #0]
	adds	r0, r0, r1
	str	r0, [r4, #0]
	ldr	r0, [r4, #4]
	ldr	r1, [sp, #4]
	adds	r0, r0, r1
	str	r0, [r4, #4]
	add	sp, #8
	pop	{r4}
	pop	{r0}
	bx	r0
	.hword 0x0000
sound_premix_end:
