#!/usr/bin/env python3
"""Generate the .incbin passthrough block for unconverted ROM regions.

Emits alternating .incbin slices and Thumb marker labels for every call
target that converted code references but whose body is not yet
disassembled. Byte layout is preserved exactly: markers emit nothing,
.incbin lengths are computed between consecutive targets.

Converted regions ("holes") are spliced in as .include directives at
their exact offsets; symbols falling inside holes are skipped (they are
defined by the included file itself).

Usage:
  python3 tools/mk_passthrough.py START SYM_FILE OUT_INC \
      [--converted START:END:FILE]...

  START      hex file offset where passthrough begins (end of converted code)
  SYM_FILE   text file, one VMA per line ("0x080016EC sub_080016EC" or bare)
  OUT_INC    path of .inc file to write
  --converted RANGE:FILE (repeatable); RANGE = hexfileoff:hexfileoff.
             Holes must not overlap each other or sit before START.

The ROM size is fixed at 8 MiB (standard GBA image); the final slice runs
to 0x800000.
"""
import sys
from pathlib import Path

ROM = Path(__file__).resolve().parents[1] / "baserom.gba"

ROM_END = 0x800000
# End of the independent code slice, i.e. one past the last assembled code
# byte. `make independent-slice` reports "code 0x000000-0x02E158 (188760
# bytes)"; a marker at or beyond this is in the data/asset tail, not in code.
CODE_END = 0x02E158


def parse_syms(path):
    syms = []
    with open(path) as f:
        for ln in f:
            ln = ln.split("#", 1)[0].strip()
            if not ln:
                continue
            parts = ln.split()
            vma = int(parts[0], 16)
            name = parts[1] if len(parts) > 1 else f"sub_{vma + 0x08000000:08X}"
            syms.append((vma, name))
    return sorted(set(syms))


def parse_holes(args):
    holes = []
    it = iter(range(len(args)))
    i = 0
    while i < len(args):
        if args[i] == "--converted":
            rng, _, path = args[i + 1].rpartition(":")
            s, e = (int(x, 16) for x in rng.split(":"))
            holes.append((s, e, path))
            i += 2
        else:
            raise SystemExit(f"unexpected arg {args[i]!r}")
    holes.sort()
    for a, b in zip(holes, holes[1:]):
        assert a[1] <= b[0], f"overlapping holes {a} {b}"
    return holes


def main():
    start = int(sys.argv[1], 16)
    sym_file, out_path = sys.argv[2], sys.argv[3]
    syms = parse_syms(sym_file)
    holes = parse_holes(sys.argv[4:])
    assert all(e > s for s, e, _ in holes)
    assert all(s >= start for s, _, _ in holes)

    def in_hole(v):
        return any(s <= v < e for s, e, _ in holes)

    syms = [(v, n) for v, n in syms if not in_hole(v)]

    # A marker whose first ROM halfword is `00 00` is not a function entry: in
    # Thumb that decodes to `movs r0, r0` (a NOP), which is what 4-byte inter-
    # function alignment padding looks like. Emitting `.type`/label for one
    # puts a phantom start in the coverage inventory, and because a span runs
    # to the next *known* start the phantom silently shortens its real
    # neighbour -- `0x080263C4` was pinned to 26 bytes by a marker that sat on
    # the pad word at `0x080263DE`. Five such markers were deleted by hand from
    # the committed `passthrough.inc`; this filter is what keeps a regeneration
    # from putting them back and silently undoing that census. Verified by
    # reading the ROM at the marker address, not by whether anything calls it:
    # `_0802D970` (the CpuFastSet wrapper) and `_0802DE9C` (a real callee) have
    # no `bl` anywhere in the closure, so a caller test would misjudge them.
    rom = Path(ROM).read_bytes()
    dropped = [(v, n) for v, n in syms
               if v >= CODE_END
               or (0 <= v < len(rom) - 1 and rom[v:v + 2] == b"\x00\x00")]
    if dropped:
        syms = [(v, n) for v, n in syms if (v, n) not in set(dropped)]
        for v, n in dropped:
            print(f"  dropped pad-word marker {n} @ 0x{v:06X}", file=sys.stderr)
    assert all(b[0] > a[0] for a, b in zip(syms, syms[1:])), "dup markers"

    out = [
        "@ -------------------------------------------------------------",
        "@ PASSTHROUGH REGION - GENERATED by tools/mk_passthrough.py.",
        "@ Do not edit by hand; regenerate instead.",
        f"@ Start: 0x{start:06X} ({len(syms)} call-target markers,"
        f" {len(holes)} converted regions)",
        "@ -------------------------------------------------------------",
        "",
    ]
    cur = start
    for vma, name in syms:
        # emit any hole that begins before this marker
        while holes and holes[0][0] < vma:
            hs, he, hf = holes.pop(0)
            if hs > cur:
                out.append(f'\t.incbin "baserom.gba", 0x{cur:06X}, 0x{hs - cur:06X}'
                           f'\t@ -> 0x{hs + 0x08000000:08X}')
            out.append(f'@@ converted region 0x{hs:06X}-0x{he:06X}:')
            out.append(f'\t.include "{hf}"')
            cur = max(cur, he)
        if vma == cur:
            pass  # marker sits exactly at slice start
        else:
            assert vma > cur, f"marker 0x{vma:06X} inside converted region"
            out.append(f'\t.incbin "baserom.gba", 0x{cur:06X}, 0x{vma - cur:06X}'
                       f'\t@ -> 0x{vma + 0x08000000:08X}')
        out.append("\t.thumb")
        out.append(f"\t.type {name}, %function")
        out.append(f"{name}:")
        cur = vma
    # trailing holes after last marker
    while holes:
        hs, he, hf = holes.pop(0)
        assert hs >= cur
        if hs > cur:
            out.append(f'\t.incbin "baserom.gba", 0x{cur:06X}, 0x{hs - cur:06X}'
                       f'\t@ -> 0x{hs + 0x08000000:08X}')
        out.append(f'@@ converted region 0x{hs:06X}-0x{he:06X}:')
        out.append(f'\t.include "{hf}"')
        cur = he
    out.append(f'\t.incbin "baserom.gba", 0x{cur:06X}, 0x{ROM_END - cur:06X}'
               f'\t@ -> end of ROM')
    out.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {out_path}: {len(syms)} markers, "
          f"{len(out) and sum(1 for l in out if '.include' in l)} includes, "
          f"0x{start:06X}-0x{ROM_END:06X}")


if __name__ == "__main__":
    main()
