#!/usr/bin/env python3
"""mGBA RAM-watch harness generator, TCP collector, and headless driver.

Locked-in verification oracle (docs/decompilation-roadmap.md): rebuilds must behave
identically to baserom.gba. This tool drives two emulator runs (original
vs rebuilt ROM) with identical inputs and snapshots IWRAM + EWRAM + VRAM
(+ palette + OAM) every N frames; `ramdiff.py` then compares the captures.

Subcommands:
  gen   INPUTS.csv OUT.lua --port 46001 --interval 30 [--frames 3600]
        Emit a Lua script for mGBA GUI scripting (Tools > Scripting >
        Load). INPUTS.csv lines: `frame,keymask` (blank mask = no keys).
        Keys use mGBA/KEYINPUT bit order:
        A=1 B=2 SELECT=4 START=8 RIGHT=16 LEFT=32 UP=64 DOWN=128 R=256 L=512
        The mask holds until the next row CHANGES it (including rows that
        set it back to 0 — fixed : earlier sparse tables dropped
        zero rows so keys never released).
  run   ROM INPUTS.csv --outdir DIR --interval 30 [--frames 3600]
        Headless equivalent of gen+GUI: drives libmgba directly through
        its Python bindings (see tools/build_mgba_python.sh), applying
        the same input semantics and writing the same snapshot files.
        Requires PYTHONPATH to point at a built mgba python package.
  listen OUTDIR --port 46001
        TCP collector for the Lua path: accept ONE connection, write each
        snapshot payload to OUTDIR/snap_XXXXXXXX.bin (frame in name),
        stop on EOF.

Snapshot files (body only, header stripped by collector/driver):
  v1 (legacy): IWRAM (32 KiB) then EWRAM (256 KiB)          = 294912 B
  v2 (live):   IWRAM, EWRAM, VRAM (96 KiB), PAL (1 KiB @
               0x05000000), OAM (1 KiB @ 0x07000000)        = 395264 B

Workflow (headless):
  python3 tools/ramwatch.py run baserom.gba inputs.csv \
      --outdir build/caps/orig --port 46001 --interval 30
  python3 tools/ramwatch.py run build/gtadv3.gba inputs.csv \
      --outdir build/caps/rebuilt --port 46002 --interval 30
  python3 tools/ramdiff.py build/caps/orig build/caps/rebuilt

Keys are applied at frame END (i.e. effective on f+1) exactly like the
Lua watcher; both runs share the skew so comparisons stay valid.
"""
import argparse
import socketserver
import struct
import sys
import threading
from pathlib import Path

MAGIC = 0x47544133  # 'GTA3'
DEFAULT_PORT = 46001
DEFAULT_INTERVAL = 30

# Snapshot body layout, v2 live format (name, size, bus base address).
REGIONS_V2 = [
    ("IWRAM", 0x8000, 0x03000000),
    ("EWRAM", 0x40000, 0x02000000),
    ("VRAM", 0x18000, 0x06000000),
    ("PAL", 0x400, 0x05000000),
    ("OAM", 0x400, 0x07000000),
]
LEGACY_TOTAL = 0x8000 + 0x40000  # v1 body size

LUA_TEMPLATE = r"""-- GENERATED by tools/ramwatch.py -- do not edit
-- GT Advance 3 RAM-watch: play embedded inputs, stream RAM snapshots.
local PORT   = %(port)d
local EVERY  = %(every)d
local STOPAT = %(stopat)d
local INPUTS = %(inputs)s

local sock = socket.connect("127.0.0.1", PORT)
if not sock then
    console:error("ramwatch: cannot reach collector on 127.0.0.1:" .. PORT)
    return
end
console:log("ramwatch: connected to collector")

local function send_snapshot(frame)
    local iw = emu.memory.iwram:readRange(0, 0x8000)
    local ew = emu.memory.wram:readRange(0, 0x40000)
    -- header: magic u32, frame u32, total u32, niw u32, new u32 (LE)
    local function le32(v)
        v = v %% 4294967296
        return string.char(v %% 256,
            math.floor(v / 256) %% 256,
            math.floor(v / 65536) %% 256,
            math.floor(v / 16777216) %% 256)
    end
    sock:send(le32(%(magic)d) .. le32(frame) ..
              le32(#iw + #ew + 8) .. le32(#iw) .. le32(#ew))
    sock:send(iw)
    sock:send(ew)
end

callbacks:add("frame", function()
    local f = emu:currentFrame()
    if f >= STOPAT then return end
    local mask = INPUTS[f]
    if mask then emu:setKeys(mask) end
    if EVERY > 0 and f %% EVERY == 0 then
        send_snapshot(f)
    end
end)
console:log("ramwatch: armed (every=" .. EVERY .. ", stopat=" .. STOPAT .. ")")
"""


def load_inputs(path):
    """Parse `frame,keymask` CSV -> {frame: mask} for explicit rows."""
    inputs = {}
    with open(path) as f:
        for ln in f:
            ln = ln.split("#")[0].strip()
            if not ln:
                continue
            parts = [x for x in ln.split(",")[:2]]
            try:
                fr, mask = (int(x, 0) for x in parts)
            except ValueError:
                continue  # header line like "frame,keymask"
            inputs[fr] = mask
    return inputs


def held_changes(inputs, stop):
    """Expand explicit rows into change-driven {frame: mask} up to stop.

    Semantics: the mask from row f holds until the next row CHANGES it;
    a row setting 0 is a real release and must be kept (bug fix
    : the previous sparse table dropped zero rows, so keys
    never released).
    """
    changes = {}
    cur = None
    for f in range(stop):
        if f in inputs:
            m = inputs[f]
            if m != cur:
                changes[f] = m
                cur = m
    return cur, changes


def cmd_gen(argv):
    ap = argparse.ArgumentParser(prog="ramwatch.py gen")
    ap.add_argument("inputs")
    ap.add_argument("out")
    ap.add_argument("--port", type=int, default=DEFAULT_PORT)
    ap.add_argument("--interval", type=int, default=DEFAULT_INTERVAL)
    ap.add_argument("--frames", type=int, default=3600,
                    help="stop scheduling after this many frames")
    args = ap.parse_args(argv)

    inputs = load_inputs(args.inputs)
    last = max(inputs) if inputs else 0
    _, changes = held_changes(inputs, max(args.frames, last + 1))
    lit = "{" + ",".join(f"[{k}]={v}" for k, v in sorted(changes.items())) + "}"
    lua = LUA_TEMPLATE % dict(port=args.port, every=args.interval,
                              stopat=args.frames, inputs=lit,
                              magic=MAGIC)
    Path(args.out).write_text(lua)
    print(f"wrote {args.out} ({len(changes)} key-change frames, "
          f"interval={args.interval}, port={args.port})")


def cmd_run(argv):
    ap = argparse.ArgumentParser(prog="ramwatch.py run")
    ap.add_argument("rom")
    ap.add_argument("inputs")
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--interval", type=int, default=DEFAULT_INTERVAL)
    ap.add_argument("--frames", type=int, default=3600,
                    help="stop after this many completed frames")
    args = ap.parse_args(argv)

    try:
        import mgba.core
        import mgba.image
        import mgba.log
        from mgba._pylib import ffi
        mgba.log.silence()
    except ImportError as e:
        sys.exit(f"mgba python bindings unavailable ({e}); build them "
                 f"with tools/build_mgba_python.sh and export PYTHONPATH")

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    core = mgba.core.load_path(args.rom)
    if core is None:
        sys.exit(f"cannot load ROM: {args.rom}")
    cfg = mgba.core.Config()
    core.load_config(cfg)
    w, h = core.desired_video_dimensions()
    core.set_video_buffer(mgba.image.Image(w, h))
    core.reset()

    inputs = load_inputs(args.inputs)
    last = max(inputs) if inputs else 0
    _, changes = held_changes(inputs, max(args.frames, last + 1))
    pending = dict(changes)

    def snapshot(frame):
        parts = []
        for name, size, base in REGIONS_V2:
            # mCoreGetMemoryBlock returns a direct pointer into the
            # emulated region (fast bulk copy; no per-byte bus reads).
            n = ffi.new("size_t *")
            raw = mgba.lib.mCoreGetMemoryBlock(core._core, base, n)
            if raw == ffi.NULL or n[0] < size:
                sys.exit(f"core cannot map {name} at 0x{base:08X} "
                         f"(got {n[0]} B)")
            parts.append(bytes(ffi.buffer(ffi.cast("uint8_t *", raw), size)))
        tmp = outdir / f".tmp_{frame:08d}"
        tmp.write_bytes(b"".join(parts))
        tmp.rename(outdir / f"snap_{frame:08d}.bin")

    print(f"driving {args.rom} for {args.frames} frames "
          f"(interval={args.interval}) -> {outdir}")
    nsnap = 0
    while True:
        core.run_frame()
        f = core.frame_counter
        if f >= args.frames:
            break
        if f in pending:
            core._core.setKeys(core._core, pending[f])
        if args.interval > 0 and f % args.interval == 0:
            snapshot(f)
            nsnap += 1
            if nsnap % 20 == 0:
                print(f"  frame {f}: {nsnap} snapshots")
    snapshot(args.frames - 1)  # terminal snapshot even if off-cadence
    nsnap += 1
    print(f"done: {args.frames} frames, {nsnap} snapshots -> {outdir}")


class _Handler(socketserver.BaseRequestHandler):
    def handle(self):
        outdir = self.server.outdir
        buf = b""
        expect = None
        while True:
            try:
                chunk = self.request.recv(1 << 16)
            except OSError:
                break
            if not chunk:
                break
            buf += chunk
            while True:
                if expect is None:
                    if len(buf) < 20:
                        break
                    magic, frame, total, niw, new = struct.unpack_from(
                        "<5I", buf, 0)
                    if magic != MAGIC:
                        print("bad magic, resync", file=sys.stderr)
                        buf = buf[1:]
                        continue
                    expect = (frame, total, niw, new)
                    buf = buf[20:]
                else:
                    frame, total, niw, new = expect
                    if len(buf) < total - 8:
                        break
                    payload, buf = buf[:total - 8], buf[total - 8:]
                    p = outdir / f"snap_{frame:08d}.bin"
                    tmp = outdir / f".tmp_{frame:08d}"
                    tmp.write_bytes(payload)
                    tmp.rename(p)
                    expect = None


class _Server(socketserver.TCPServer):
    allow_reuse_address = True

    def __init__(self, addr, handler, outdir):
        super().__init__(addr, handler)
        self.outdir = outdir


def cmd_listen(argv):
    ap = argparse.ArgumentParser(prog="ramwatch.py listen")
    ap.add_argument("outdir")
    ap.add_argument("--port", type=int, default=DEFAULT_PORT)
    args = ap.parse_args(argv)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    srv = _Server(("127.0.0.1", args.port), _Handler, outdir)
    print(f"collector on 127.0.0.1:{args.port} -> {outdir}")
    threading.Thread(target=srv.serve_forever, daemon=True).start()

    def shutdown_check():
        n = len(list(outdir.glob("snap_*.bin")))
        print(f"{n} snapshots captured", file=sys.stderr)

    try:
        while True:  # run until Ctrl-C; prints progress every 10 s
            import time
            time.sleep(10)
            shutdown_check()
    except KeyboardInterrupt:
        shutdown_check()


def main():
    if len(sys.argv) < 2 or sys.argv[1] not in ("gen", "listen", "run"):
        print(__doc__)
        sys.exit(2)
    {"gen": cmd_gen, "listen": cmd_listen, "run": cmd_run}[sys.argv[1]](
        sys.argv[2:])


if __name__ == "__main__":
    main()
